<?php

/**
 * @var Site\ViewModel\VehicleTestingStation\VtsFormViewModel
 * @var Site\Form\VtsCreateForm                               $form
 */
use DvsaCommon\Utility\AddressUtils;

$model = $this->model;
$form = $model->getForm();

$contact = $form->getContactModel();

echo $this->partial(
    'partial/gds/table/table',
    [
        'head' => 'Name and type',
        'body' => [
            ['Name', $form->getName()],
            ['Type', $form->getSiteTypes()[$form->getType()]],
        ],
    ]
);

echo $this->partial(
    'partial/gds/table/table',
    [
        'head' => 'Location and contacts',
        'body' => [
            ['Address', AddressUtils::stringify($contact->getAddressModel()->toDto())],
            ['Country', $form->getCountries()[$form->getCountry()]],
            ['Email', $contact->getEmailModel()->getEmail()],
            ['Telephone', $contact->getPhoneModel()->getNumber()],
        ],
    ]
);

echo $this->partial(
    'partial/gds/table/table',
    [
        'head' => 'Testing facilities',
        'body' => [
            ['OPTL test lanes', $form->getTestingFacilityOptl()],
            ['TPTL test lanes', $form->getTestingFacilityTptl()],
            ['Classes of vehicles tested at site', implode(', ', $form->getClasses())],
        ],
    ]
);
?>

<!--Hidden information of the AE for save purpose-->
<form method="POST" action="<?php echo $form->getFormUrl(); ?>">
    <?php
    echo $this->csrfToken();

    // Navigation
    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id' => 'submitSiteConfirmation',
            'name' => 'submitSiteConfirmation',
            'value' => 'Create site',
            'navigation' => [
                'Back' => $model->getCancelUrl(),
            ],
        ]
    );
    ?>
</form>
