<?php
/**
 * @var Site\ViewModel\VehicleTestingStation\VtsFormViewModel $model
 * @var \Site\Form\VtsCreateForm                              $form
 * @var \Zend\Mvc\Controller\Plugin\FlashMessenger            $flashMessenger
 */

use DvsaCommon\Enum\VehicleClassCode;
use Site\Form\VtsCreateForm;
use DvsaCommon\Enum\SiteContactTypeCode;
use DvsaClient\ViewModel\PhoneFormModel;

$model = $this->model;
$form = $model->getForm();

//  show api errors
$flashMessenger = $this->layout()->flashMessenger;
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'failure']
);
?>

<form method="POST" action="<?php echo $form->getFormUrl(); ?>">
    <?php echo $this->csrfToken() ?>

    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendSiteDetails', 'text' => 'Site name & type']
        );
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'           => VtsCreateForm::FIELD_NAME,
                'label'        => 'Site name',
                'title'        => 'Enter Site name',
                'value'        => $form->getName(),
                'errorMessage' => $form->getError(VtsCreateForm::FIELD_NAME),
                'maxLength'    => 100,
                'autofocus'    => true,
            ]
        );
        echo $this->partial(
            'partial/gds/form/control-select-group',
            [
                'id'           => VtsCreateForm::FIELD_SITE_TYPE,
                'label'        => 'Site type',
                'inputModifier'=> '1-4',
                'errorMessage' => $form->getError(VtsCreateForm::FIELD_SITE_TYPE),
                'value'        => $form->getType(),
                'options'      => $form->getSiteTypes(),
            ]
        );
        ?>
    </fieldset>

    <fieldset>
        <?php
        //  list of countries
        $countryOptions = [];
        foreach ($form->getCountries() as $code => $name) {
            $countryOptions[] = [
                'inputName' => VtsCreateForm::FIELD_COUNTRY,
                'key'       => $name,
                'value'     => $code,
                'checked'   => ($form->getCountry() === $code),
            ];
        }

        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendSiteContactDetails', 'text' => 'Site location']
        );

        echo $this->partial(
            'partial/gds/form/control-address-group',
            [
                'id'            => 'address',
                'group'         => SiteContactTypeCode::BUSINESS,
                'form'          => $form->getContactModel()->getAddressModel(),
                'countryRadio'  => $countryOptions,
            ],
            'Core'
        );
        ?>
    </fieldset>

    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendSiteEmail', 'text' => 'Email']
        );
        ?>
        <p>Please enter an email address if provided by the applicant</p>
        <?php
        echo $this->partial(
            'partial/gds/form/control-email-conf-group',
            [
                'id'    => 'email',
                'key'   => 'Email address not provided',
                'group' => SiteContactTypeCode::BUSINESS,
                'form'  => $form->getContactModel()->getEmailModel(),
                'maxLength' => 255,
            ],
            'Core'
        );
        ?>
    </fieldset>
    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendSiteTelephone', 'text' => 'Telephone']
        );
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => SiteContactTypeCode::BUSINESS . PhoneFormModel::FIELD_NUMBER,
                'name'          => SiteContactTypeCode::BUSINESS . '[' . PhoneFormModel::FIELD_NUMBER . ']',
                'errorMessage'  => $form->getContactModel()->getPhoneModel()->getError(SiteContactTypeCode::BUSINESS . '[' . PhoneFormModel::FIELD_NUMBER . ']'),
                'inputModifier' => '1-4',
                'label'         => 'Telephone number',
                'value'         => $form->getContactModel()->getPhoneModel()->getNumber(),
                'maxLength'     => 24,
            ]
        );
        ?>
    </fieldset>

    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendSiteTestingFacilities', 'text' => 'Testing facilities']
        );
        echo $this->partial(
            'partial/gds/form/control-select-group',
            [
                'id'           => VtsCreateForm::FIELD_TESTING_FACILITY_TPTL,
                'label'        => 'How many two-person test lanes (TPTL) does the site have?',
                'errorMessage' => $form->getError(VtsCreateForm::FIELD_TESTING_FACILITY_TPTL),
                'value'        => $form->getTestingFacilityTptl(),
                'options'      => $form->getTestingFacilities(),
                'inputModifier'=> '1-4',
            ]
        );
        echo $this->partial(
            'partial/gds/form/control-select-group',
            [
                'id'           => VtsCreateForm::FIELD_TESTING_FACILITY_OPTL,
                'label'        => 'How many one-person test lanes (OPTL) does the site have?',
                'errorMessage' => $form->getError(VtsCreateForm::FIELD_TESTING_FACILITY_OPTL),
                'value'        => $form->getTestingFacilityOptl(),
                'options'      => $form->getTestingFacilities(),
                'inputModifier'=> '1-4',
            ]
        );

        //  vehicle class options
        $classesOptions = [];
        foreach (VehicleClassCode::getAll() as $class) {
            $classesOptions[] = [
                'value'     => $class,
                'inputName' => VtsCreateForm::FIELD_VEHICLE_CLASS . '[]',
                'key'       => 'Class ' . $class,
                'checked'   => $form->isClassChecked($class),
            ];
        }

        echo $this->partial(
            'partial/gds/form/control-checkbox-group',
            [
                'label'        => 'Classes of vehicles tested at site',
                'errorMessage' => $form->getError(VtsCreateForm::FIELD_VEHICLE_CLASS),
                'options'      => $classesOptions,
            ]
        );
        ?>
    </fieldset>

    <?php
    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'         => 'submitSiteCreate',
            'name'       => 'submitSiteCreate',
            'value'      => 'Continue to summary',
            'navigation' => [
                'Cancel and return home' => $model->getCancelUrl(),
            ],
        ]
    );
    ?>
</form>
