<?php

use Core\Catalog\BusinessRole\BusinessRoleCatalog;
use Core\Formatting\AddressFormatter;
use DvsaCommon\Enum\BusinessRoleStatusCode;
use DvsaCommon\UrlBuilder\AuthorisedExaminerUrlBuilderWeb;
use DvsaCommon\UrlBuilder\PersonUrlBuilderWeb;
use DvsaCommon\UrlBuilder\VehicleTestingStationUrlBuilderWeb;
use DvsaCommon\Utility\ArrayUtils;
use DvsaMotTest\Controller\MotTestController;
use Site\ViewModel\MotTest\MotTestInProgressViewModel;
use Site\Service\RiskAssessmentScoreRagClassifier;

/**
 * @var \Site\ViewModel\SiteViewModel $viewModel
 * @var string $searchString
 * @var string $escRefPage
 * @var \DvsaCommon\Dto\Site\SiteDto $site
 * @var RiskAssessmentScoreRagClassifier $ragClassifier
 * @var string $isVtsRiskEnabled
 * @var BusinessRoleCatalog $businessRoleCatalog
 */
?>

<?php
//  --  errors  --
$errorMessages = $this->layout()->flashMessenger->getErrorMessages();
$successMessages = $this->layout()->flashMessenger->getSuccessMessages();

echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);
?>
<?php

$permission = $viewModel->getPermissions();
$site = $viewModel->getSite();
$organisation = $site->getOrganisation();
$contact = $site->getContactByType(\DvsaCommon\Enum\SiteContactTypeCode::BUSINESS);
?>

<h3 class="summary-heading">Site details
<?php if ($permission->canChangeSiteDetails()): ?>
    <span class="summary-heading__action">
        <a href="<?php echo VehicleTestingStationUrlBuilderWeb::siteDetails($site->getId()) ?>" >Change site details</a>
    </span>
<?php endif ?>
</h3>

<?php


$organisationDisplay = '';
if (isset($organisation)) {
    if ($permission->canViewAuthorisedExaminer()) {
        $organisationDisplay = '<a id="authorised-examiner-link" href="' . AuthorisedExaminerUrlBuilderWeb::of($organisation->getId()) . '">' . $organisation->getName() . '</a>';
    } else {
        $organisationDisplay = $organisation->getName();
    }
}

$body = [
    ['Name', $site->getName(), 'id' => 'site-name'],
    [
        'VTS ID',
        $site->getSiteNumber(),
        'id' => 'site-number',
    ],
    ['Classes', !empty($site->getTestClasses()) ? implode(',', $site->getTestClasses()) : 'None', 'id' => 'test-classes'],
];

if($permission->canViewVtsType()){
    $body[] = ['Type', $viewModel->getSiteTypes()[$site->getType()], 'id' => 'site-type'];
}

$body[] = [
    'Authorised Examiner',
    $organisationDisplay,
    'id' => 'authorisedExaminer',
    'escape' => !$permission->canViewAuthorisedExaminer(),
];

echo $this->partial(
    'partial/gds/gds-table/table',
    [
        'body' => $body,
    ]
);
?>

<h3 class="summary-heading">Contact details
    <?php if ($permission->canChangeDetails()): ?>
        <span class="summary-heading__action"><a id="change-contact-details"
           href="<?php echo VehicleTestingStationUrlBuilderWeb::contactDetails($site->getId()) ?>"
            >Change contact details</a>
        </span>
    <?php endif ?>
</h3>

<?php
$contactDetails[] = ['Address', (new AddressFormatter())->escapedDtoToMultiLine($contact->getAddress()), 'id' => 'site-address', 'escape' => false];
if ($permission->canViewCountry()) {
    $contactDetails[] = ['Country', $viewModel->getCountryToggle(), 'id' => 'site-country'];
}
$contactDetails[] = ['Email', $contact->getPrimaryEmailAddress(), 'id' => 'email'];
$contactDetails[] = ['Telephone', $contact->getPrimaryPhoneNumber(), 'id' => 'phone-number'];

echo $this->partial(
    'partial/gds/gds-table/table',
    [
        'body' => $contactDetails,
    ]
);
?>

<h3 class="summary-heading">Roles
    <?php if ($permission->canNominateRole()): ?>
        <span class="summary-heading__action">
        <a id="assign-a-role"
           href="<?php echo $this->url('vehicle-testing-station-search-for-person', ['vehicleTestingStationId' => $site->getId()]) ?>">
            Assign a role
        </a>
    </span>
    <?php endif; ?>
</h3>
<table class="table-summary">
    <tbody>
    <?php foreach ($site->getPositions() as $position): ?>
        <tr id="role-assignment-<?php echo $position->getPerson()->getId() . "-" . $position->getRole()->getCode(); ?>">
            <th class="table-summary__key">
                <?php if ($permission->canViewProfile($position->getPerson())): ?>

                    <a href="<?php echo PersonUrlBuilderWeb::profile($position->getPerson()->getId()); ?>">
                        <?php echo $this->escapeHtml($position->getPerson()->getFullName());
                        if ($permission->canViewUsername()):
                            echo "(" . $this->escapeHtml($position->getPerson()->getUsername()) . ")";
                        endif;
                        ?>
                    </a>
                <?php else: ?>
                    <?php echo $this->escapeHtml($position->getPerson()->getFullName());
                    if ($permission->canViewUsername()):
                        echo "(" . $this->escapeHtml($position->getPerson()->getUsername()) . ")";
                    endif;
                    ?>
                <?php endif; ?>
            </th>
            <td class="table-summary__value">
                <?php echo $this->escapeHtml($businessRoleCatalog->getByCode($position->getRole()->getCode())->getName()); ?>
                <?php if ($position->getRoleStatus()->getCode() !== BusinessRoleStatusCode::ACTIVE): ?>
                    <br/>
                    <span class="table-summary__meta">Pending</span>
                <?php endif; ?>
                <?php if ($permission->canRemovePositionAtSite($position->getRole()->getCode())): ?>
                    <a id="remove-role" class="table-summary__action" href="<?php echo $this->url(
                        \Site\Controller\RoleController::ROUTE_REMOVE_ROLE,
                        [
                            'siteId' => $site->getId(),
                            'positionId' => $position->getId(),
                        ]
                    ); ?>">Remove</a>
                    <span class="visuallyhidden"><?php echo $this->escapeHtml($position->getPerson()->getFullName()) ?></span>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php if ($permission->canViewTestsInProgress()): ?>
    <h3 class="summary-heading">Active MOT tests</h3>
    <table class="table-summary">
        <tbody>
        <?php if ($motTests = $viewModel->getTestsInProgress()):
            /** @var MotTestInProgressViewModel $motTest */
            foreach ($motTests as $motTest): ?>
                <tr id="site-active-mot-test-link-<?php echo $this->escapeHtmlAttr($motTest->getNumber()); ?>">
                    <th class="table-summary__key">
                        <?php echo $this->escapeHtml($motTest->getTesterName()); ?>
                    </th>
                    <td class="table-summary__value">
                        <a href="<?php echo $this->url(MotTestController::ROUTE_MOT_TEST_SHORT_SUMMARY, ['motTestNumber' => $motTest->getNumber()]) ?>">
                            <?php echo $this->escapeHtml($motTest->getVrmOrItsAbsentReason()); ?>
                        </a>
                        <br>
                    <span class="table-summary__meta">
                        <?php echo $this->escapeHtml(ArrayUtils::joinNonEmpty(', ', [
                                $motTest->getVehicleMake(),
                                $motTest->getVehicleModel()
                            ]));
                        ?>
                    </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <th class="table-summary__key">No active MOT tests</th>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
<?php endif ?>

<h3 class="summary-heading">Testing facilities
<?php if ($permission->canChangeTestingFacilities()): ?>
    <span class="summary-heading__action"><a id="change-testing-facilities"
       href="<?php echo VehicleTestingStationUrlBuilderWeb::testingFacilities($site->getId()) ?>"
        >Change testing facilities</a>
    </span>
<?php endif ?>
</h3>

<?php
$facilities = [];
foreach ($site->getFacilities() as $type => $items) {
    /** @var \DvsaCommon\Dto\Site\FacilityTypeDto $itemType */
    $itemType = current($items)->getType();

    $facilities[$type] = [
        $itemType->getName() . ' (' . $itemType->getCode() . ')',
        count($items),
        'id' => 'testing-facility-'.strtolower($type),
        'class' => 'testing-facility-'.strtolower($type),
    ];
}

krsort($facilities);

echo $this->partial(
    'partial/gds/gds-table/table',
    [
        'body' => $facilities,
    ]
);
?>


<h3 class="summary-heading">Default test settings
<?php if ($permission->canChangeDefaultBrakeTests()): ?>
    <span class="summary-heading__action">
    <a id="configure-brake-test-defaults-link"
       href="<?php echo $this->url(\Site\Controller\SiteController::ROUTE_CONFIGURE_BRAKE_TEST_DEFAULTS, ['id' => $site->getId()]); ?>">
        Change default test settings
    </a>
    </span>
<?php endif ?>
</h3>

<?php if ($permission->canTestClass1And2() && !empty($site->getDefaultBrakeTestClass1And2())): ?>
    <?php
    echo $this->partial(
        'partial/gds/gds-table/table',
        [
            'head' => 'Class 1 and 2',
            'body' => [
                [
                    'Brake test',
                    ucfirst($site->getDefaultBrakeTestClass1And2()->getName()),
                    'id' => 'default-brake-test-class-1-and-2',
                ],
            ],
        ]
    );
    ?>
<?php endif; ?>

<?php if ($permission->canTestAnyOfClass3AndAbove() && !empty($site->getDefaultServiceBrakeTestClass3AndAbove()) && !empty($site->getDefaultParkingBrakeTestClass3AndAbove())): ?>
    <?php
    echo $this->partial(
        'partial/gds/gds-table/table',
        [
            'head' => 'Class 3, 4, 5 and 7',
            'body' => [
                [
                    'Service brake',
                    ucfirst($site->getDefaultServiceBrakeTestClass3AndAbove()->getName()),
                    'id' => 'default-service-brake-test-class-3-and-above',
                ],
                [
                    'Parking brake',
                    ucfirst($site->getDefaultParkingBrakeTestClass3AndAbove()->getName()),
                    'id' => 'default-parking-brake-test-class-3-and-above',
                ],
            ],
        ]
    );
    ?>
<?php endif; ?>

<div id="opening-hours">
    <h3 class="summary-heading">Testing hours
    <?php if ($permission->canUpdateTestingSchedule()): ?>
        <span class="summary-heading__action">
        <a id="change-testing-hours"
           href="<?php echo $this->url('site/edit-opening-hours', ['siteId' => $site->getId()]) ?>">
            Change testing hours
        </a>
        </span>
    <?php endif ?>
    </h3>
    <table class="table-summary">
        <tbody>
        <?php foreach ($site->getSiteTestingSchedule() as $day):
            $dayName = $viewModel->displayWeekday($day);
            ?>
            <tr>
                <th class="table-summary__key">
                    <?php echo $this->escapeHtml($dayName); ?>
                </th>
                <td id="<?php echo $this->escapeHtmlAttr(strtolower($dayName)); ?>-hours"
                    class="table-summary__value--tabular">
                    <?php echo $this->escapeHtml($viewModel->displayOpeningHours($day)); ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
        <tfoot>
        <tr>
            <td class="text-secondary" colspan="2">These times do not include bank holidays</td>
        </tr>
        </tfoot>
    </table>
</div>


<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <?php if ($permission->canSearchVts()) : ?>
            <li>
                <?php
                if (!empty($searchString)) {
                    $escUrl = $this->url('vehicle-testing-station-results', ['search' => $searchString]);
                } else {
                    $escUrl = $this->url('vehicle-testing-station-search');
                }
                ?>
                <a id="search-again" class="btn-link" href="<?php echo $escUrl; ?>">Return to search</a>

                <?php if (!empty($escRefPage)) : ?>
                    <a href="<?php echo $escRefPage; ?>" class="btn-link">Return to results</a>
                <?php endif; ?>
            </li>
        <?php endif; ?>
        <li>
            <a id="return-to-home" href="<?php echo $this->url('user-home') ?>">Return home</a>
        </li>
    </ul>
</nav>
