<?php

use Site\Form\VtsSiteDetailsForm;
use DvsaCommon\Date\DateTimeDisplayFormat;
use DvsaCommon\Date\DateTimeApiFormat;

/**
 * @var VtsSiteDetailsForm $form;
 * @var string $cancelUrl
 * @var bool $hasStatusChanged
 * @var array $siteStatusMap
 */
?>

<!--Display of the information enter-->
<h3 class="key-value-list__header">Confirm changes below</h3>

<?php

$dateString = ($hasStatusChanged == true) ?
    DateTimeDisplayFormat::textDate((new \DateTime())->format(DateTimeApiFormat::FORMAT_ISO_8601_UTC_TZ)) :
    DateTimeDisplayFormat::textDate($site->getStatusChangedOn())
;

$statusField = sprintf(
    '%s<span class="key-value-list__meta">%s</span>',
    $this->escapeHtml($siteStatusMap[$form->getStatus()]),
    $this->escapeHtml($dateString)
);

echo $this->partial(
    'partial/gds/table/table',
    [
        'body' => [
            ['Trading name', $form->getName()],
            ['Status', $statusField,  'id' => 'site-status', 'escape' => false],
            ['Vehicle test classes', implode(', ',$form->getClasses())],
        ],
    ]
);
?>

<form method="POST" action="<?php echo $form->getFormUrl(); ?>">
    <?php
    echo $this->csrfToken();

    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'         => 'submitSiteDetailsUpdate',
            'name'       => 'submitSiteDetailsUpdate',
            'value'      => 'Save site changes',
            'navigation' => [
                'Back to change site details' => $cancelUrl,
            ],
        ]
    );
    ?>
</form>