<?php
/**
 * @var Site\ViewModel\VehicleTestingStation\VtsFormViewModel $model
 * @var \Site\Form\VtsSiteDetailsForm                         $form
 * @var \Zend\Mvc\Controller\Plugin\FlashMessenger            $flashMessenger
 */

use DvsaCommon\Enum\VehicleClassCode;
use Site\Form\VtsSiteDetailsForm;
use Site\Form\VtsCreateForm;

$model = $this->model;
$form = $model->getForm();

//  show api errors
$flashMessenger = $this->layout()->flashMessenger;
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'failure']
);
?>

<form method="POST" action="<?php echo $form->getFormUrl(); ?>">
    <?php echo $this->csrfToken() ?>

    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendSiteDetails', 'text' => 'Site name, status, classes and area office']
        );
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'           => VtsCreateForm::FIELD_NAME,
                'label'        => 'Trading name',
                'title'        => 'Enter Site name',
                'value'        => $form->getName(),
                'errorMessage' => $form->getError(VtsCreateForm::FIELD_NAME),
                'maxLength'    => 100,
                'autofocus'    => true,
            ]
        );
        ?>
    </fieldset>

    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-select-group',
            [
                'id'           => VtsSiteDetailsForm::FIELD_STATUS,
                'label'        => 'Status of this site',
                'errorMessage' => $form->getError(VtsSiteDetailsForm::FIELD_STATUS),
                'value'        => (string) $form->getStatus(),
                'options'      => $form->getStatuses(),
                'inputModifier'=> '1-4',
            ]
        );
        ?>
    </fieldset>


    <fieldset>
        <?php
        //  vehicle class options
        $classesOptions = [];
        foreach (VehicleClassCode::getAll() as $class) {
        $classesOptions[] = [
        'value'     => $class,
        'inputName' => VtsCreateForm::FIELD_VEHICLE_CLASS . '[]',
        'key'       => 'Class ' . $class,
        'checked'   => $form->isClassChecked($class),
        ];
        }

        echo $this->partial(
        'partial/gds/form/control-checkbox-group',
        [
        'label'        => 'Classes of vehicles tested at site',
        'errorMessage' => $form->getError(VtsCreateForm::FIELD_VEHICLE_CLASS),
        'options'      => $classesOptions,
        ]
        );
        ?>
    </fieldset>

    <?php
    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'         => 'submitSiteDetailsUpdate',
            'name'       => 'submitSiteDetailsUpdate',
            'value'      => 'Continue to summary',
            'navigation' => [
                'Cancel and return to site details' => $model->getCancelUrl(),
            ],
        ]
    );
    ?>

</form>
