<?php

use \Site\Form\VtsUpdateTestingFacilitiesForm;

/**
 * @var VtsUpdateTestingFacilitiesForm $form;
 */
?>

<!--Display of the information enter-->
<h3 class="key-value-list__header">Confirm testing facility changes below</h3>

<?php
echo $this->partial(
    'partial/gds/table/table',
    [
        'body' => [
            ['TPTL test lanes', $form->getTestingFacilityTptl()],
            ['OPTL test lanes', $form->getTestingFacilityOptl()],
        ],
    ]
);
?>

<form method="POST" action="<?php echo $form->getFormUrl(); ?>">
    <?php
    echo $this->csrfToken();

    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'         => 'submitTestingFacilitiesUpdate',
            'name'       => 'submitTestingFacilitiesUpdate',
            'value'      => 'Save testing facilities changes',
            'navigation' => [
                'Back to change testing facilities' => $cancelUrl,
            ],
        ]
    );
    ?>
</form>