<?php

use \Site\Form\VtsUpdateTestingFacilitiesForm;

/**
 * @var VtsUpdateTestingFacilitiesForm $form;
 */

echo $this->partial(
    'partial/gds/table/table',
    [
        'body' => [
            ['TPTL test lanes', $form->getTestingFacilityTptl()],
            ['OPTL test lanes', $form->getTestingFacilityOptl()],
        ],
    ]
);
?>

<form method="POST" action="<?php echo $form->getFormUrl(); ?>">
    <?php
    echo $this->csrfToken();

    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'         => 'submitTestingFacilitiesUpdate',
            'name'       => 'submitTestingFacilitiesUpdate',
            'value'      => 'Change testing facilities',
            'navigation' => [
                'Back' => $cancelUrl,
            ],
        ]
    );
    ?>
</form>