<?php
/**
 * @var \Site\Form\VtsUpdateTestingFacilitiesForm   $form
 * @var string                                      $cancelUrl
 */

use DvsaCommon\Enum\VehicleClassCode;
use Site\Form\VtsCreateForm;
use DvsaCommon\Enum\SiteContactTypeCode;
use DvsaClient\ViewModel\PhoneFormModel;


//  show api errors
$flashMessenger = $this->layout()->flashMessenger;
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'failure']
);
?>

<form method="POST" action="<?php echo $form->getFormUrl(); ?>">
    <?php echo $this->csrfToken() ?>

    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendSiteTestingFacilities', 'text' => 'Testing lanes']
        );
        echo $this->partial(
            'partial/gds/form/control-select-group',
            [
                'id'           => VtsCreateForm::FIELD_TESTING_FACILITY_TPTL,
                'label'        => 'How many two-person test lanes (TPTL) does the site have?',
                'errorMessage' => $form->getError(VtsCreateForm::FIELD_TESTING_FACILITY_TPTL),
                'value'        => (string) $form->getTestingFacilityTptl(),
                'options'      => $form->getTestingFacilities(),
                'inputModifier'=> '1-4',
            ]
        );
        echo $this->partial(
            'partial/gds/form/control-select-group',
            [
                'id'           => VtsCreateForm::FIELD_TESTING_FACILITY_OPTL,
                'label'        => 'How many one-person test lanes (OPTL) does the site have?',
                'errorMessage' => $form->getError(VtsCreateForm::FIELD_TESTING_FACILITY_OPTL),
                'value'        => (string) $form->getTestingFacilityOptl(),
                'options'      => $form->getTestingFacilities(),
                'inputModifier'=> '1-4',
            ]
        );
        ?>
    </fieldset>

    <?php
    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'         => 'submitTestingFacilitiesUpdate',
            'name'       => 'submitTestingFacilitiesUpdate',
            'value'      => 'Continue',
            'navigation' => [
                'Cancel and return to Vehicle Testing Station' => $cancelUrl,
            ],
        ]
    );
    ?>
</form>
