<?php
use DvsaCommon\UrlBuilder\AccountUrlBuilderWeb;

/**
 * @var \Account\ViewModel\SecurityQuestionViewModel
 * @var string                                       $numberOfAttemptMessage
 * @var \Application\Helper\PrgHelper                $prgHelper
 */
$question = $viewModel->getQuestion();
$questionNumber = $viewModel->getQuestionNumber();
$personId = $viewModel->getUserId();

$formAction = AccountUrlBuilderWeb::forgottenPasswordSecurityQuestion($personId, $questionNumber);
$legendTitle = ($questionNumber == 1 ? 'First ' : 'Second ').' security question ';
$labelText = $question->getText();
$inputId = 'question'.$questionNumber;

$errorMessages = $this->layout()->flashMessenger->getErrorMessages();
$successMessages = $this->layout()->flashMessenger->getSuccessMessages();

echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);

$this->layout()->setVariable('pageSubTitle', 'Forgotten your password');

if ($questionNumber == 1):
    $this->layout()->setVariable('pageTitle', 'First security question');
    $this->headTitle('First security question');
elseif ($questionNumber == 2):
    $this->layout()->setVariable('pageTitle', 'Second security question');
    $this->headTitle('Second security question');
else:
    $this->layout()->setVariable('pageTitle', 'Security question');
endif;

?>

<?php if ($questionNumber == 1): ?>
    <div class="lede">
        <p>Before your password can be changed - you need to answer your two security questions correctly.</p>
    </div>
<?php else: ?>
    <p>Here is the second question to be answered correctly before you may <strong>change your password</strong>...</p>
<?php endif; ?>

<form id="securityQuestionForm" action="<?php echo $this->escapeHtmlAttr($formAction); ?>" method="POST">
    <?php echo $this->csrfToken(); ?>
    <?php echo $prgHelper->getHtml(); ?>
    <fieldset>
        <?php
        echo $this->partial('partial/gds/form/control-legend', ['id' => 'legendQuestion', 'text' => $legendTitle, 'altLegendClass' => 'visuallyhidden']);

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id' => $inputId,
                'errorMessage' => $numberOfAttemptMessage,
                'label' => $labelText,
                'value' => '',
                'autoCompleteOff' => true,
            ]
        );
        ?>
    </fieldset>

    <a href="<?php echo $this->escapeHtmlAttr(AccountUrlBuilderWeb::forgottenPasswordNotAuthenticated()); ?>" class="key-value-list__action">Forgotten the answer to your security question?</a>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id' => 'submitSecurityQuestion',
            'value' => 'Continue',
        ]
    ); ?>
    <?php echo $this->partial(
        'partial/gds/general/message',
        [
            'message' => [
                ['type' => 'normal', 'm' => 'You must answer both of your security questions correctly before you can reset your password'],
            ],
        ]
    ); ?>
</form>

<script>
    document.onreadystatechange = function () {
        $('#securityQuestionForm').submit(function() {
            $('#submitSecurityQuestion').attr('disabled','disabled');
        });
    };
</script>
