<?php
use DvsaCommon\UrlBuilder\AccountUrlBuilderWeb;

/**
 * @var \Account\ViewModel\SecurityQuestionViewModel  $viewModel
 * @var string $numberOfAttemptMessage
 * @var \Application\Helper\PrgHelper $prgHelper
 */

$question = $viewModel->getQuestion();
$questionNumber = $viewModel->getQuestionNumber();
$personId = $viewModel->getUserId();

$formAction         = AccountUrlBuilderWeb::forgottenPasswordSecurityQuestion($personId, $questionNumber);
$legendTitle        = 'Security question ' . ($questionNumber == 1 ? 'one' : 'two');
$labelText          = $question->getText();
$inputId            = 'question' . $questionNumber;

$errorMessages      = $this->layout()->flashMessenger->getErrorMessages();
$successMessages    = $this->layout()->flashMessenger->getSuccessMessages();

echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);
?>

<?php if ($questionNumber == 1): ?>
    <div class="lede">
        <p>Before your password can be changed - you need to answer your two security questions correctly.</p>
    </div>
<?php else: ?>
    <p>Here is the second question to be answered correctly before you may <strong>change your password</strong>...</p>
<?php endif; ?>

<form id="securityQuestionForm" action="<?php echo $this->escapeHtmlAttr($formAction); ?>" method="POST">
    <?php echo $this->csrfToken(); ?>
    <?php echo $prgHelper->getHtml(); ?>
    <fieldset>
        <?php
        echo $this->partial('partial/gds/form/control-legend', ['id' => 'legendQuestion', 'text' => $legendTitle]);

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => $inputId,
                'errorMessage'  => $numberOfAttemptMessage,
                'label'         => $labelText,
                'value'         => '',
            ]
        );
        ?>
    </fieldset>

    <a href="<?php echo $this->escapeHtmlAttr(AccountUrlBuilderWeb::forgottenPasswordNotAuthenticated()); ?>" class="key-value-list__action">Forgotten security question</a>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'            => 'submitSecurityQuestion',
            'value'         => 'Submit answer',
        ]
    ); ?>
    <?php echo $this->partial(
        'partial/gds/general/message',
        [
            'message'       => [
                ['type' => 'normal', 'm' => 'Both security questions must be '],
                ['type' => 'bold', 'm' => 'answered correctly '],
                ['type' => 'normal', 'm' => 'before your password can be changed'],
            ]
        ]
    ); ?>
</form>

<script>
    document.onreadystatechange = function () {
        $('#securityQuestionForm').submit(function() {
            $('#submitSecurityQuestion').attr('disabled','disabled');
        });
    };
</script>
