<?php
/**
 * @var string
 * @var string $backButtonUrl
 * @var string $firstLine
 * @var string $secondLine
 * @var string $thirdLine
 * @var string $townOrCity
 * @var string $country
 * @var string $postcode
 */
?>

<div class="lede">
    <p>Check that the address is correct.</p>
</div>

<table class="key-value-list">
    <caption class="visuallyhidden">Summary of your details</caption>
    <tbody>
        <tr>
            <th scope="col" class="key-value-list__key">User profile</th>
            <td class="key-value-list__value"><?php echo $personName?></td>
        </tr>
        <tr>
            <th scope="col" class="key-value-list__key">Address</th>
            <td class="key-value-list__value">
                <?php
                echo $this->escapeHtml($firstLine).'<br>';
                echo ($secondLine != '') ? $this->escapeHtml($secondLine).'<br>' : '';
                echo ($thirdLine != '') ? $this->escapeHtml($thirdLine).'<br>' : '';
                echo ($townOrCity != '') ? $this->escapeHtml($townOrCity).'<br>' : '';
                echo ($country != '') ? $this->escapeHtml($country).'<br>' : '';
                echo ($postcode != '') ? $this->escapeHtml($postcode).'<br>' : '';
                ?>
            </td>
        </tr>
    </tbody>
</table>

<nav class="content-navigation">
    <form method="POST">
        <?php echo $this->csrfToken(); ?>
        <?php echo $this->partial(
            'partial/gds/form/control-navigation',
            [
                'id' => 'submitAddress',
                'value' => 'Change address',
            ]
        ); ?>
    </form>
    <ul class="content-navigation__secondary">
        <li>
            <a id="backtochangepage" href="<?php echo $backButtonUrl; ?>">Back</a>
        </li>
    </ul>
</nav>

