/* Recreate the Indexes */

ALTER TABLE TESTRESULT 
	ADD PRIMARY KEY (TESTID)
	,ADD INDEX IDX1 (TESTDATE, TESTTYPE, TESTRESULT, TESTCLASSID) 
;


ALTER TABLE TESTITEM 
	ADD INDEX IDX1 (TESTID)
	,ADD INDEX IDX2 (RFRID)
;


ALTER TABLE TESTITEM_DETAIL 
	ADD PRIMARY KEY (RFRID, TESTCLASSID)
	,ADD INDEX IDX1 (TSTITMID, TESTCLASSID)
	,ADD INDEX IDX2 (TSTITMSETSECID, TESTCLASSID)
;


ALTER TABLE TESTITEM_GROUP 
	ADD PRIMARY KEY (TSTITMID, TESTCLASSID)
	,ADD INDEX IDX1 (PARENTID, TESTCLASSID)
	,ADD INDEX IDX2(TSTITMSETSECID, TESTCLASSID)
;


ALTER TABLE FAILURE_LOCATION 
	ADD PRIMARY KEY (FAILURELOCATIONID)
;


ALTER TABLE FUEL_TYPE 
	ADD PRIMARY KEY (FUEL_TYPE)
;


ALTER TABLE TESTITEM_MARKER 
	ADD PRIMARY KEY (MARKER_CODE)
;


ALTER TABLE TEST_OUTCOME 
	ADD PRIMARY KEY (OUTCOME_CODE)
;


ALTER TABLE TEST_TYPE 
   ADD PRIMARY KEY (TEST_TYPE)
;


ALTER TABLE MOT_VTS_SITE 
   ADD PRIMARY KEY (SITE_NUMBER)
;


ALTER TABLE MAKE_MODEL 
	ADD PRIMARY KEY (MAKE, MODEL)
;


ALTER TABLE VEHICLE_VTS 
   ADD PRIMARY KEY (VEHICLEID)
   ,ADD KEY IDX_REGISTRATION (REGISTRATION)
   ,ADD KEY IDX_VIN (VIN)
   ,ADD KEY IDX_POSTCODE (POSTCODEREGION)
   ,ADD KEY IDX_SORT (SORT_ORDER)
;

ALTER TABLE VTS_INFO 
   ADD PRIMARY KEY (SITE_NUMBER)
   ,ADD KEY IDX_POSTCODE (POSTCODEREGION)
   ,ADD KEY IDX_SORT (SORT_ORDER)
;

ALTER TABLE USERS 
   ADD PRIMARY KEY (ID)
;


ALTER TABLE VTS_USER 
   ADD PRIMARY KEY (SITE_NUMBER, USERNAME)
   ,ADD KEY IDX_SORT (SORT_ORDER)
;

