/********************************************************
*
*  Tables for importing of test data from gov websites
*
*  http://data.gov.uk/dataset/anonymised_mot_test
*  http://data.gov.uk/dataset/mot-active-vts
*
\*******************************************************/

CREATE DATABASE IF NOT EXISTS `mot_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT COLLATE utf8_general_ci;

USE `mot_test`;

CREATE TABLE TESTRESULT (
	TESTID INT UNSIGNED
	,VEHICLEID INT UNSIGNED
	,TESTDATE DATE
	,TESTCLASSID CHAR(2)
	,TESTTYPE CHAR(2)
	,TESTRESULT CHAR(3)
	,TESTMILEAGE INT UNSIGNED
	,POSTCODEREGION CHAR(2)
	,MAKE CHAR(30)
	,MODEL CHAR(30)
	,COLOUR CHAR(16)
	,FUELTYPE CHAR(1)
	,CYLCPCTY INT UNSIGNED
	,FIRSTUSEDATE DATE
	,PRIMARY KEY (TESTID)
	,INDEX IDX1 (TESTDATE, TESTTYPE, TESTRESULT, TESTCLASSID) 
	)
;


CREATE TABLE TESTITEM (
	TESTID INT UNSIGNED
	,RFRID SMALLINT UNSIGNED
	,RFRTYPE CHAR(1)
	,LATLOCATIONID CHAR(1)
	,LONGLOCATIONID CHAR(1)
	,VERTLOCATIONID CHAR(1)
	,DMARK CHAR(1)
	,INDEX IDX1 (TESTID)
	,INDEX IDX2 (RFRID)
	)
;


CREATE TABLE TESTITEM_DETAIL (
	RFRID SMALLINT UNSIGNED
	,TESTCLASSID CHAR(2)
	,TSTITMID SMALLINT UNSIGNED
	,MINORITEM CHAR(1)
	,RFRDESC CHAR(250)
	,RFRLOCMARKER CHAR(1)
	,RFRINSPMANDESC MEDIUMTEXT -- CHAR(500)
	,RFRADVISORYTEXT CHAR(250)
	,TSTITMSETSECID SMALLINT UNSIGNED
	,PRIMARY KEY (RFRID, TESTCLASSID)
	,INDEX IDX1 (TSTITMID, TESTCLASSID)
	,INDEX IDX2 (TSTITMSETSECID, TESTCLASSID)
	)
;


CREATE TABLE TESTITEM_GROUP (
	TSTITMID SMALLINT UNSIGNED
	,TESTCLASSID CHAR(2)
	,PARENTID SMALLINT UNSIGNED
	,TSTITMSETSECID SMALLINT UNSIGNED
	,ITEMNAME CHAR(100)
	,PRIMARY KEY (TSTITMID, TESTCLASSID)
	,INDEX IDX1 (PARENTID, TESTCLASSID)
	,INDEX IDX2(TSTITMSETSECID, TESTCLASSID)
	)
;


CREATE TABLE FAILURE_LOCATION (
	FAILURELOCATIONID CHAR(1)
	,FAILURELOCATIONTXT CHAR(20)
	,PRIMARY KEY (FAILURELOCATIONID)
	)
;


CREATE TABLE FUEL_TYPE (
	FUEL_TYPE CHAR(1)
	,FUEL_TYPE_TXT CHAR(255)
	,PRIMARY KEY (FUEL_TYPE)
	)
;

CREATE TABLE TESTITEM_MARKER (
	MARKER_CODE CHAR(1)
	,MARKER_TYPE CHAR(20)
	,MARKER_TXT CHAR(255)
	,PRIMARY KEY (MARKER_CODE)
	)
;

CREATE TABLE TEST_OUTCOME (
	OUTCOME_CODE CHAR(3)
	,OUTCOME_TXT CHAR(255)
	,PRIMARY KEY (OUTCOME_CODE)
	)
;

CREATE TABLE TEST_TYPE (
    TEST_TYPE CHAR(2)
   ,TEST_TYPE_TXT CHAR(255)
   ,PRIMARY KEY (TEST_TYPE)
	)
;



CREATE TABLE MOT_VTS_SITE (
	 SITE_NUMBER CHAR(10)
	,TRADING_NAME CHAR(40)
	,ADDRESS_LINE_1 CHAR(40)
	,ADDRESS_LINE_2 CHAR(40)
	,ADDRESS_LINE_3 CHAR(40)
	,ADDRESS_LINE_4 CHAR(40)
	,POSTCODE CHAR(8)
	,TELEPHONE_NUMBER CHAR(20)
	,FAX_NUMBER CHAR(20)
	,CLASS_1 CHAR(1)
	,CLASS_2 CHAR(1)
	,CLASS_3 CHAR(1)
	,CLASS_4 CHAR(1)
	,CLASS_4A CHAR(1)
	,CLASS_5 CHAR(1)
	,CLASS_5A CHAR(1)
	,CLASS_7 CHAR(1)
   ,PRIMARY KEY (SITE_NUMBER)
	)
;


CREATE TABLE IF NOT EXISTS MAKE_MODEL (
	 MAKE CHAR(30)
	,MODEL CHAR(30)
	,PRIMARY KEY (MAKE, MODEL)
	)
;


CREATE TABLE VEHICLE_VTS (
    VEHICLEID INT(11) NOT NULL
   ,REGISTRATION VARCHAR(20) DEFAULT NULL
   ,VIN VARCHAR(30) NOT NULL
	,POSTCODEREGION CHAR(2)
   ,SORT_ORDER FLOAT NOT NULL
   ,VTS_SITE_NUMBER CHAR(10) DEFAULT NULL
   ,NOMINATED_TESTER VARCHAR(10) DEFAULT NULL
   ,PRIMARY KEY (VEHICLEID)
   ,KEY IDX_REGISTRATION (REGISTRATION)
   ,KEY IDX_VIN (VIN)
   ,KEY IDX_POSTCODE (POSTCODEREGION)
   ,KEY IDX_SORT (SORT_ORDER)
) ENGINE=INNODB DEFAULT CHARSET=UTF8
;

CREATE TABLE VTS_INFO (
	 SITE_NUMBER CHAR(10) NOT NULL
	,POSTCODEREGION CHAR(2)
   ,SORT_ORDER FLOAT NOT NULL
   ,PRIMARY KEY (SITE_NUMBER)
   ,KEY IDX_POSTCODE (POSTCODEREGION)
   ,KEY IDX_SORT (SORT_ORDER)
	)
;

CREATE TABLE USERS (
    ID INT(11) NOT NULL	
	,FIRSTNAME CHAR(30) NOT NULL
	,SURNAME CHAR(30) NOT NULL
	,USERNAME CHAR(10)
   ,PRIMARY KEY (ID)
);


CREATE TABLE VTS_USER (
	 SITE_NUMBER CHAR(10) NOT NULL
	,USERNAME VARCHAR(10) NOT NULL
   ,SORT_ORDER FLOAT NOT NULL
   ,PRIMARY KEY (SITE_NUMBER, USERNAME)
   ,KEY IDX_SORT (SORT_ORDER)
	)
;

