<p> Dear MOT testing service user, </p>

<p>
    You contacted the DVSA recently as you weren’t able to sign in to your MOT testing service account. We have reset your password and security questions.
</p>

<p> What to do now:
<br> Sign in to the service with your user ID and this temporary password: <?php echo $this->escapeHtml($this->newPassword); ?>
<br> When prompted, create a new password
<br> When prompted, choose new security questions and answers
</p>

<p> Don’t share your password or security answers with anyone else as they’re used to prove who you are to the DVSA and increase the security of the service. </p>
<p> If you did not contact the DVSA about your account then call the helpdesk on <?php echo $this->escapeHtml($this->contactNumber); ?> </p>
