Dear MOT Testing Service User,

You recently contacted DVSA and weren’t able to remember the answers to your security questions for the MOT testing service.

It’s important that you have security questions set up for the new service so we can confirm who you are when you want to do things like reset your password.
 To reset your security questions please follow these 3 steps:

Log in to the new service using the following one time password - <?php echo $this->escapeHtml($this->newPassword); ?>

When prompted, choose a new password to replace your one time password
Reset your security questions and answers

If you’re a tester, once you’ve completed these steps you’ll be given a new 6 digit PIN. This will replace your existing PIN which you use to enter test results into the new service.
Please DO NOT contact your Area Office, Customer Service Centre or the Atos Helpdesk as they will not be able to set up your security questions for you.
Please do not share your security questions, answers or PIN with anyone else as they’re used to reset your password and prove who you are to DVSA.
 If you did not request this reminder then please call <?php echo $this->escapeHtml($this->contactNumber); ?> quoting your username.