<p>Your temporary password is:</p>

<p><?php echo $this->escapeHtml($this->newPassword); ?></p>

<p>Sign in to the service with your user ID and temporary password to reset your account security.</p>

<p>Go to the sign in page: <?php echo $this->escapeHtml($this->motTestingServiceUrl); ?></p>

<p>You'll then choose a new password and security questions.</p>

<p>If you didn't ask to recover your account, contact the <?php echo $this->escapeHtml($this->contactLabel); ?> on <?php echo $this->escapeHtml($this->contactNumber); ?>.</p>

<p>DVSA (Driver and Vehicle Standards Agency)</p>