<?php

/** @var \DvsaCommon\Dto\Vehicle\History\VehicleHistoryDto $vehicleHistory */

//  --  draw siteName   --
if (!$this->isManySites) {
    echo '<h3>' . $this->escapeHtml($this->siteName) . '</h3>';
}
?>

<div class="results-entry col-sm-8">
    <?php
    //  --  draw certificates   --
    if ($vehicleHistory->hasHistory()) :
        $prevSiteId = 0;

        foreach($vehicleHistory->getIterator() as $item) :
            /** @var DvsaCommon\Dto\Vehicle\History\VehicleHistoryItemDto $item */
            $motTestNumber = $item->getMotTestNumber();

            //  --  draw site name  --
            if ($this->isManySites) :
                if ($prevSiteId !== 0 || $item->getSiteId() !== $prevSiteId) :
                    $prevSiteId = $item->getSiteId();
                    ?>
                    <br>
                    <h3><?php echo $this->escapeHtml($item->getSiteName() . ' ' . $item->getSiteAddress()); ?></h3>
                <?php
                endif;
            endif;
            ?>

            <div id="certificate-history" class="row">
                <div class="results-entry-item clearfix">
                    <?php echo $this->partial('vehicle/history-item', ['vehicleHistoryItem' => $item]); ?>

                    <div class="col-sm-3">
                        <dl>
                            <dt>Number:</dt>
                            <dd id="number-<?php echo $this->escapeHtmlAttr($motTestNumber); ?>"><?php echo $this->escapeHtml($motTestNumber); ?></dd>
                        </dl>
                    </div>

                    <div class="col-sm-4">
                        <a href="<?php echo $this->url('mot-test-certificate', ['motTestNumber' => $motTestNumber]); ?>"
                           id="view-<?php echo $this->escapeHtmlAttr($motTestNumber) ?>" class="btn btn-primary">View</a>
                        
                        <?php if($item->isAllowEdit()) : ?>
                            <form method="POST" style="display:inline-block"
                                  action="<?php echo $this->url('mot-test/replacement-certificate', ['motTestNumber' => $motTestNumber]); ?>">
                                <?php echo $this->csrfToken() ?>
                                <input type="hidden" name="action" value="edit-certificate"/>
                                <input type="hidden" name="motTestNumber" value="<?php echo $this->escapeHtmlAttr($motTestNumber); ?>"/>
                                <button type="submit" id="edit-<?php echo $this->escapeHtmlAttr($motTestNumber); ?>" class="btn btn-danger">Edit</button>
                            </form>
                        <?php endif ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <span class="divider"></span>
            </div>

            <?php endforeach; ?>
    <?php else : ?>
        <div class="row">
            No certificates found
        </div>
    <?php endif; ?>
</div>
