<?php

/** @var $vehicleHistoryItem DvsaCommon\Dto\Vehicle\History\VehicleHistoryItemDto */

$cssClass = $vehicleHistoryItem->hasPassed() ? 'pass' : 'fail';

?>

<div class="col-sm-2">
    <h4 class="result-summary-info <?php echo $this->escapeHtmlAttr($cssClass) ?>" id="status-<?php echo $this->escapeHtmlAttr($vehicleHistoryItem->getId()); ?>" >
        <?php echo $this->escapeHtml($vehicleHistoryItem->getDisplayStatus()); ?>
    </h4>
</div>
<div class="col-sm-3">
    <dl>
        <dt>Date</dt>
        <dd><?php echo $this->escapeHtml($vehicleHistoryItem->getDisplayIssuedDate()); ?></dd>
    </dl>
</div>
