<?php

use Organisation\ViewModel\TestQualityInformation\TestQualityInformationViewModel;

/**
 * @var TestQualityInformationViewModel $viewModel
 */
?>

<?php
    if($viewModel->aeHasAssociatedSites()){
        echo $viewModel->getTable()->renderTable($this);
        echo $viewModel->getTable()->renderFooter($this);
    } else {
        echo "There are currently no sites associated to this authorised examiner";
    }
?>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a id="return-link" href="<?php echo $viewModel->getReturnLink()?>">
                Return to authorised examiner
            </a>
        </li>
    </ul>
</nav>