/*
Create new table for MOT test certificate data. Used by Jasper workers to generate
new MOT PDF documents
*/
CREATE TABLE `mot_test_recent_certificate` (
  `id` BIGINT NULL AUTO_INCREMENT,
  `tester_person_id` INT NOT NULL COMMENT 'id of tester who carried out test',
  `site_id` INT NOT NULL COMMENT 'id of site where test was carried out',
  `mot_test_id` BIGINT(20) NOT NULL COMMENT 'FK to mot test table',
  `prs_mot_test_id` BIGINT(20) NULL COMMENT 'Used to link related PRS rows. Null if not PRS',
  `vin` VARCHAR(30) NULL COMMENT 'Plain text description for displaying in FE',
  `registration` VARCHAR(20) NULL COMMENT 'registration of vehicle',
  `make_id` INT(10) NULL COMMENT 'FK to make table',
  `model_id` INT(10) NULL COMMENT 'FK to model table',
  `model_detail_id` INT(10) NULL COMMENT 'FK to model table',
  `make_name` VARCHAR(50) NULL,
  `model_name` VARCHAR(50) NULL,
  `model_detail_name` VARCHAR(50) NULL,
  `mot_test_status_id` SMALLINT(5) NULL COMMENT 'FK to mot test status table',
  `generation_worker_id` INT NULL  COMMENT 'identifies the worker process',
  `document_id` BIGINT(20) NOT NULL COMMENT 'FK to jasper_document table',
  `recipient_first_name` VARCHAR(45) NULL COMMENT 'First name of recipient of emailed certificate. Used if certificate is being emailed to personalise it',
  `recipient_family_name` VARCHAR(45) NULL COMMENT 'Family name of recipient of emailed certificate. Used if certificate is being emailed to personalise it',
  `recipient_email` VARCHAR(255) NULL COMMENT 'Email of recipient of certificate. Used if certificate is being emailed',
  `certificate_status` VARCHAR(20) NOT NULL  COMMENT 'the current status of the certificate generation',
  `generation_started_on` DATETIME NULL COMMENT 'time worker picked up row',
  `generation_completed_on` DATETIME NULL COMMENT 'time worker completed certificate generation',
  `certificate_storage_key` VARCHAR(50) NULL COMMENT 'unique key used to store certificate in Amazon S3 store',
  `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time certificate generation was requested',
  `last_modified_on` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'time row was last modified',
  PRIMARY KEY (`id`),
  KEY `site_id_created_on` (`site_id`,`created_on`),
  KEY `generation_completed_on` (`generation_completed_on`));

DELIMITER $$

DROP TRIGGER IF EXISTS tr_mot_test_au$$

CREATE TRIGGER `tr_mot_test_au` AFTER UPDATE
ON `mot_test` FOR EACH ROW
  BEGIN
    DECLARE mot_status varchar(5);
    INSERT INTO  `mot_test_hist` (`hist_transaction_type`, `hist_batch_number`, `id`,
                                  `person_id`,
                                  `vehicle_id`,
                                  `vehicle_version`,
                                  `document_id`,
                                  `site_id`,
                                  `primary_colour_id`,
                                  `secondary_colour_id`,
                                  `vehicle_class_id`,
                                  `tested_as_fuel_type_id`,
                                  `vin`,
                                  `empty_vin_reason_id`,
                                  `registration`,
                                  `empty_vrm_reason_id`,
                                  `make_id`,
                                  `model_id`,
                                  `model_detail_id`,
                                  `country_of_registration_id`,
                                  `has_registration`,
                                  `mot_test_type_id`,
                                  `started_date`,
                                  `completed_date`,
                                  `status_id`,
                                  `issued_date`,
                                  `expiry_date`,
                                  `mot_test_id_original`,
                                  `prs_mot_test_id`,
                                  `mot_test_reason_for_cancel_id`,
                                  `reason_for_cancel_comment_id`,
                                  `reason_for_termination_comment`,
                                  `full_partial_retest_id`,
                                  `partial_reinspection_comment_id`,
                                  `items_not_tested_comment_id`,
                                  `one_person_test`,
                                  `one_person_reinspection`,
                                  `complaint_ref`,
                                  `number`,
                                  `odometer_reading_id`,
                                  `private`,
                                  `emergency_log_id`,
                                  `emergency_reason_lookup_id`,
                                  `emergency_reason_comment_id`,
                                  `vehicle_weight_source_lookup_id`,
                                  `vehicle_weight`,
                                  `incognito_vehicle_id`,
                                  `address_comment_id`,
                                  `mot1_legacy_id`,
                                  `created_by`,
                                  `created_on`,
                                  `last_updated_by`,
                                  `last_updated_on`,
                                  `version`,
                                  `batch_number`,
                                  `make_name`,
                                  `model_name`,
                                  `model_detail_name`,
                                  `client_ip`)
    VALUES ('U', COALESCE(@batch_number, CASE WHEN NEW.BATCH_NUMBER<> OLD.BATCH_NUMBER THEN NEW.BATCH_NUMBER ELSE 0 END), OLD.`id`,
            OLD.`person_id`,
            OLD.`vehicle_id`,
            OLD.`vehicle_version`,
            OLD.`document_id`,
            OLD.`site_id`,
            OLD.`primary_colour_id`,
            OLD.`secondary_colour_id`,
            OLD.`vehicle_class_id`,
            OLD.`tested_as_fuel_type_id`,
            OLD.`vin`,
            OLD.`empty_vin_reason_id`,
            OLD.`registration`,
            OLD.`empty_vrm_reason_id`,
            OLD.`make_id`,
            OLD.`model_id`,
            OLD.`model_detail_id`,
            OLD.`country_of_registration_id`,
            OLD.`has_registration`,
            OLD.`mot_test_type_id`,
            OLD.`started_date`,
            OLD.`completed_date`,
            OLD.`status_id`,
            OLD.`issued_date`,
            OLD.`expiry_date`,
            OLD.`mot_test_id_original`,
            OLD.`prs_mot_test_id`,
            OLD.`mot_test_reason_for_cancel_id`,
            OLD.`reason_for_cancel_comment_id`,
            OLD.`reason_for_termination_comment`,
            OLD.`full_partial_retest_id`,
            OLD.`partial_reinspection_comment_id`,
            OLD.`items_not_tested_comment_id`,
            OLD.`one_person_test`,
            OLD.`one_person_reinspection`,
            OLD.`complaint_ref`,
            OLD.`number`,
            OLD.`odometer_reading_id`,
            OLD.`private`,
            OLD.`emergency_log_id`,
            OLD.`emergency_reason_lookup_id`,
            OLD.`emergency_reason_comment_id`,
            OLD.`vehicle_weight_source_lookup_id`,
            OLD.`vehicle_weight`,
            OLD.`incognito_vehicle_id`,
            OLD.`address_comment_id`,
            OLD.`mot1_legacy_id`,
            OLD.`created_by`,
            OLD.`created_on`,
            OLD.`last_updated_by`,
            OLD.`last_updated_on`,
            OLD.`version`,
            OLD.`batch_number`,
            OLD.`make_name`,
            OLD.`model_name`,
            OLD.`model_detail_name`,
            OLD.`client_ip`);
    IF (OLD.document_id IS NULL && NEW.document_id IS NOT NULL) THEN
      SET mot_status = (SELECT mot_test_status.code FROM mot_test_status WHERE mot_test_status.id = NEW.status_id);
      IF(mot_status = 'P' || mot_status = 'F') THEN
        INSERT INTO mot_test_recent_certificate(
          `tester_person_id`, `site_id`, `mot_test_id`, `prs_mot_test_id`, `vin`, `registration`, `make_id`, `model_id`, `model_detail_id`, `make_name`, `model_name`, `model_detail_name`,
          `mot_test_status_id`, `document_id`, `certificate_status`)
        VALUES(
          NEW.person_id, NEW.site_id, NEW.id, NEW.prs_mot_test_id, NEW.VIN, NEW.registration, NEW.make_id, NEW.model_id, NEW.model_detail_id, NEW.make_name, NEW.model_name, NEW.model_detail_name,
          NEW.status_id, NEW.document_id, 'NEW');
      END IF;
    END IF;
  END$$
DELIMITER ;

