delimiter //

CREATE PROCEDURE generate_mot_tests_for_survey ()
BEGIN
  SET @tester = (SELECT `id` FROM `person` WHERE `username` = 'tester1');
  SET @vehicle = (SELECT `id` FROM `vehicle` WHERE `registration` = 'FNZ6110' AND `vin` = '1M8GDM9AXKP042788');

  # Jasper Document information
  SET @template_type = (SELECT `id` FROM `jasper_template` WHERE `jasper_report_name` = 'MOT/VT20.pdf');
  SET @document_content = '{"TestNumber":"999999999014","VRM":"FNZ6110","VIN":"1M8GDM9AXKP042788","Make":"RENAULT","Model":"CLIO","CountryOfRegistration":"Great Britain","TestClass":"4","Colour":"Grey","TestStation":"V1234","InspectionAuthority":"Popular Garages\n67 Main Road\nBristol\nBS8 2NT\t\t+768-45-4433630\n","Odometer":"12345 mi","IssuedDate":"19 Apr 2016","IssuersName":"B. T. Arctor Tester1","OdometerHistory":"19 4 2016: 12345 mi","AdvisoryInformation":"","ExpiryDate":"18 April 2017 (SEVENTEEN)","AdditionalInformation":"To preserve the anniversary of the expiry date, the earliest you can present your vehicle for test is 19 March 2017."}';

  INSERT INTO `jasper_document`(`template_id`, `document_content`, `created_by`, `created_on`)
    VALUES (@template_type, @document_content, @tester, CURRENT_TIMESTAMP(6));
  SET @document_id = LAST_INSERT_ID();

  # Vehicle information
  SET @vehicle_primary_colour = (SELECT `primary_colour_id` FROM `vehicle` WHERE `id` = @vehicle);
  SET @vehicle_secondary_colour = (SELECT `secondary_colour_id` FROM `vehicle` WHERE `id` = @vehicle);
  SET @vehicle_class = (SELECT `vehicle_class_id` FROM `vehicle` WHERE `id` = @vehicle);
  SET @vehicle_fuel_type = (SELECT `fuel_type_id` FROM `vehicle` WHERE `id` = @vehicle);
  SET @vehicle_vin = (SELECT `vin` FROM `vehicle` WHERE `id` = @vehicle);
  SET @vehicle_vrm = (SELECT `registration` FROM `vehicle` WHERE `id` = @vehicle);
  SET @vehicle_make = (SELECT `make_id` FROM `vehicle` WHERE `id` = @vehicle);
  SET @vehicle_model = (SELECT `model_id` FROM `vehicle` WHERE `id` = @vehicle);
  SET @vehicle_country = (SELECT `country_of_registration_id` FROM `vehicle` WHERE `id` = @vehicle);

  # Odometer reading information
  INSERT INTO `odometer_reading`(`value`, `unit`, `result_type`, `is_deleted`, `created_by`, `created_on`)
    VALUES ('12345', 'mi', 'OK', 0, @tester, CURRENT_TIMESTAMP(6));
  SET @odometer_reading = LAST_INSERT_ID();

  # MOT information
  SET @site = (SELECT `id` FROM `site` WHERE `name` = 'Popular Garages');
  SET @mot_test_type = (SELECT `id` FROM `mot_test_type` WHERE `code` = 'NT');
  SET @mot_test_start_date = CURRENT_TIMESTAMP(6);
  SET @mot_test_status = (SELECT `id` FROM `mot_test_status` WHERE `code` = 'P');
  SET @mot_test_completed_date = CURRENT_TIMESTAMP(6);
  SET @mot_test_expiry_date = CURRENT_DATE();
  SET @mot_test_full_retest_id = (SELECT `id` FROm `enforcement_full_partial_retest_lookup` WHERE `name` = 'Full');

  # MOT inserts with comments to break into 10 rows
  INSERT INTO `mot_test`(`person_id`, `vehicle_id`, `document_id`, `site_id`, `primary_colour_id`, `secondary_colour_id`,
                         `vehicle_class_id`, `tested_as_fuel_type_id`, `vin`, `registration`, `make_id`, `model_id`,
                         `country_of_registration_id`, `has_registration`, `mot_test_type_id`, `started_date`,
                         `completed_date`, `status_id`, `issued_date`, `expiry_date`, `full_partial_retest_id`, `number`,
                         `odometer_reading_id`, `private`, `created_by`, `created_on`) VALUES
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    # 10 records inserted

    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    # 20 records inserted

    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    # 30 records inserted

    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    # 40 records inserted

    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    # 50 records inserted

    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    # 60 records inserted

    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    # 70 records inserted

    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    # 80 records inserted

    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    # 90 records inserted

    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6)),
    (@tester, @vehicle, @document_id, @site, @vehicle_primary_colour, @vehicle_secondary_colour, @vehicle_class,
      @vehicle_fuel_type, @vehicle_vin, @vehicle_vrm, @vehicle_make, @vehicle_model, @vehicle_country, 1,
      @mot_test_type, @mot_test_start_date, @mot_test_completed_date, @mot_test_status, @mot_test_completed_date,
      @mot_test_expiry_date, @mot_test_full_retest_id, (SELECT MAX(mt.`number`) + 1 FROM `mot_test` mt),
      @odometer_reading, 0, @tester, CURRENT_TIMESTAMP(6));
    # 99 records inserted
END//
delimiter ;
