<?php
/**
 * @var array
 * @var int   $dobDay
 * @var int   $dobMonth
 * @var int   $dobYear
 */
use Dvsa\Mot\Frontend\PersonModule\Controller\ChangeDateOfBirthController;

echo $this->partial('partial/forms/errorMessagePageHeader.phtml', ['messages' => $errorMessages]);
?>

<form method="POST">
    <?php echo $this->csrfToken(); ?>

    <fieldset>
        <?php echo $this->partial('partial/gds/form/datePickerBox.phtml',
            [
                'id' => 'dateOfBirth',
                'label' => 'Date of birth',
                'required' => false,
                'optional' => false,
                'errorMessage' => !empty($errors[ChangeDateOfBirthController::FIELD_NAME]) ? $errors[ChangeDateOfBirthController::FIELD_NAME] : null,
                'day' => $this->withDefault('')->getValue($dobDay),
                'month' => $this->withDefault('')->getValue($dobMonth),
                'year' => $this->withDefault('')->getValue($dobYear),
                'help' => 'For example: 02 12 1970',
            ]
            );
        ?>
    </fieldset>
    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id' => 'submitDateOfBirthChange',
            'value' => 'Change date of birth',
        ]
    ); ?>
    <ul class="content-navigation__secondary">
        <li>
            <a id="cancel-btn" href="<?php
            echo $this->personProfileUrl()->toPersonProfile();
            ?>">Cancel and return to user profile</a>
        </li>
    </ul>
</form>
