<?php
use DvsaCommon\UrlBuilder\AuthorisedExaminerUrlBuilderWeb;

/** @var $authorisedExaminer \Dashboard\Model\AuthorisedExaminer */
?>
<header>
	<h2>
		<?php echo $this->escapeHtml($authorisedExaminer->getName()); ?>
		<span>
		    <a href="<?php echo AuthorisedExaminerUrlBuilderWeb::of($authorisedExaminer->getId()); ?>">
		        <?php echo $this->escapeHtml($authorisedExaminer->getReference()); ?>
		    </a>
		</span>
	</h2>
</header>