<?php
use DvsaCommon\UrlBuilder\AuthorisedExaminerUrlBuilderWeb;
use DvsaCommon\UrlBuilder\VehicleTestingStationUrlBuilderWeb;
use DvsaCommon\Constants\FeatureToggle;

?>
<div class="module-pivot-panel">
    <header class="pivot-panel_header">
        <h2 class="pivot-panel_title">AE management</h2>
    </header>
    <p>You can apply for</p>
    <ul>
        <li>
            <a href="<?php echo AuthorisedExaminerUrlBuilderWeb::create(); ?>"
               id="createAuthorisedExaminerLink">
                Create AE
            </a>
        </li>
        <?php if ($this->isFeatureEnabled(FeatureToggle::AO1_SITE_CREATE)): ?>
            <li>
                <a href="<?php echo VehicleTestingStationUrlBuilderWeb::create(); ?>"
                   id="action-create-vts">
                    Create Site
                </a>
            </li>
        <?php endif; ?>
    </ul>
</div>
