<?php
use DvsaCommon\UrlBuilder\AuthorisedExaminerUrlBuilderWeb;
use DvsaCommon\UrlBuilder\VehicleTestingStationUrlBuilderWeb;
use DvsaCommon\Constants\FeatureToggle;

?>
<div class="module-pivot-panel">
    <header class="pivot-panel_header">
        <h2 class="pivot-panel_title">Authorised Examiner management</h2>
    </header>
    <ul>
        <li>
            <a href="<?php echo AuthorisedExaminerUrlBuilderWeb::create(); ?>"
               id="createAuthorisedExaminerLink">
                Create an Authorised Examiner
            </a>
        </li>
        <li>
            <a href="<?php echo VehicleTestingStationUrlBuilderWeb::create(); ?>"
               id="action-create-vts">
                Create a site
            </a>
        </li>
    </ul>
</div>
