<?php
use DvsaMotTest\Controller\MotTestCertificatesController;
?>

<?php if ($jasperAsyncEnabled): ?>
    <div class="module-pivot-panel">
        <header class="pivot-panel_header">
            <h2 class="pivot-panel_title">Your VTS activity</h2>
        </header>
        <ul>
            <?php if ($jasperAsyncEnabled): ?>
                <li>
                    <a id="mot-test-certificates-list"
                       href="<?php echo $this->url(MotTestCertificatesController::ROUTE); ?>"> MOT test certificates
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>