<?php

use DvsaCommon\UrlBuilder\MotTestUrlBuilder;
use DvsaCommon\UrlBuilder\VehicleUrlBuilder;

if ($hasInProgressNonMotTest) {
    $nonMotTestUrl = MotTestUrlBuilder::motTest($inProgressNonMotTestNumber);
    $nonMotTestText = 'Enter non-MOT test results';
    $nonMotTestId = 'action-resume-non-mot';
} else {
    $nonMotTestUrl = VehicleUrlBuilder::nonMotTestSearch();
    $nonMotTestText = 'Start a non-MOT test';
    $nonMotTestId = 'action-start-non-mot';
}
?>

<div class="module-pivot-panel">
    <header class="pivot-panel_header">
        <h2 class="pivot-panel_title">Non-MOT test</h2>
    </header>
    <p>A non-MOT test will produce a test number and VT32/VE certificate. It will not show on a vehicle's MOT history.</p>
    <p>
        <a href="<?php echo $nonMotTestUrl ?>" class="btn btn-primary" id="<?php echo $nonMotTestId; ?>">
            <?php echo $nonMotTestText ?>
        </a>
    </p>
</div>



