<div class="module-pivot-panel">
    <header class="pivot-panel_header">
        <h2 class="pivot-panel_title">Contingency Tests</h2>
    </header>
    <ul>
        <li>
            <a id="action-view-performance-dashboard"
               href="<?php echo $this->url('contingency'); ?>">
                Record contingency test
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url('forms/contingency-pass-certificate') ?>" target="_blank">
                CT20 Pass Certificate</a>
        </li>
        <li>
            <a href="<?php echo $this->url('forms/contingency-advisory-certificate') ?>" target="_blank">
                CT32 Advisory Continuation Sheet</a>
        </li>
        <li>
            <a href="<?php echo $this->url('forms/contingency-fail-certificate') ?>" target="_blank">
                CT30 Fail Continuation Sheet</a>
        </li>
    </ul>
</div>



