<?php

use DvsaCommon\UrlBuilder\MotTestUrlBuilder;
use DvsaCommon\UrlBuilder\VehicleUrlBuilder;

if ($hasInProgressDemoTest) {
    $demoTestUrl = MotTestUrlBuilder::motTest($inProgressDemoTestNumber);
    $demoTestText = 'Resume training test';
    $demoTestId = 'action-resume-mot-demonstration';
} else {
    $demoTestUrl = VehicleUrlBuilder::demoSearch();
    $demoTestText = 'Start training test';
    $demoTestId = 'action-start-mot-demonstration';
}
?>

<div class="module-pivot-panel">
    <header class="pivot-panel_header">
        <h2 class="pivot-panel_title">Training</h2>
    </header>
    <p>Practice on any class of vehicle without using slots or recording the outcome.</p>
    <p>
        <a href="<?php echo $demoTestUrl ?>" class="btn btn-primary" id="<?php echo $demoTestId;?>">
            <?php echo $demoTestText ?>
        </a>
    </p>
</div>



