DELETE map FROM permission p
JOIN role_permission_map map ON map.permission_id = p.id
WHERE p.code IN (
  'AUTHORISED-EXAMINER-UPDATE',
  'VTS-UPDATE-CORRESPONDENCE-DETAILS',
  'VTS-UPDATE-BUSINESS-DETAILS',
  'VTS-UPDATE-SITE-DETAILS',
  'AUTHORISED-EXAMINER-STATUS-UPDATE'
);


DELETE p FROM permission p
WHERE p.code IN (
  'AUTHORISED-EXAMINER-UPDATE',
  'VTS-UPDATE-CORRESPONDENCE-DETAILS',
  'VTS-UPDATE-BUSINESS-DETAILS',
  'VTS-UPDATE-SITE-DETAILS',
  'AUTHORISED-EXAMINER-STATUS-UPDATE'
);
