<?php
use Dvsa\Mot\Frontend\PersonModule\ViewModel\TestQualityInformation\GroupStatisticsTable;

/** @var GroupStatisticsTable $group */
?>

<h3 class="key-value-list__header">
    Group <?php echo $group->getGroupCode() ?>
    <span class="key-value-list__meta">
        <?php echo $group->getGroupDescription() ?>
    </span>
</h3>

<table class="<?php echo $group->hasTests() ? 'table-reference' : 'table-reference--isempty' ?>"
       id="tqi-table-<?php echo $group->getGroupCode() ?>">
    <thead>
    <tr class="table-reference__head">
        <th></th>
        <th class="numeric">Tests done</th>
        <th class="numeric">Average vehicle age <span class='table-reference__meta'>(years)</span></th>
        <th class="numeric">Average test time <span class='table-reference__meta'>(minutes)</span></th>
        <th class="numeric">Tests failed</th>
    </tr>
    </thead>
    <tbody>
    <tr class="table-reference__row--primary">
        <td>
            Test statistics
        </td>

        <td class="numeric">
            <?php echo $group->getTestCount(); ?>
        </td>

        <?php echo $this->partial('partials/test-quality-group-not-available-check', [
            'hasTests'          => $group->hasTests(),
            'notAvailableText'  => $group->getNotAvailableText(),
            'value'             => $group->getAverageVehicleAge(),
        ]); ?>

        <?php echo $this->partial('partials/test-quality-group-not-available-check', [
            'hasTests'          => $group->hasTests(),
            'notAvailableText'  => $group->getNotAvailableText(),
            'value'             => $group->getAverageTestDuration(),
        ]); ?>

        <?php echo $this->partial('partials/test-quality-group-not-available-check', [
            'hasTests'          => $group->hasTests(),
            'notAvailableText'  => $group->getNotAvailableText(),
            'value'             => $group->getFailurePercentage(),
        ]); ?>

    </tr>
    <?php if ($group->hasTests()): ?>
            <tr class="">
                <td class="" colspan="5">
                    <a href="<?php echo $group->getComponentLink(); ?>">
                        <?php echo $group->getComponentLinkText(); ?>
                    </a>
                </td>
            </tr>
    <?php else: ?>
        <tr>
            <td colspan="5">
                No Group <?php echo $group->getGroupCode() ?> tests done
            </td>
        </tr>
    <?php endif ?>
    <?php if ($group->isNationalDataAvailable()): ?>
        <tr class="table-reference__row--secondary">
            <td>
                National average
            </td>

            <td class="numeric">
                <?php echo $group->getNationalTestCount(); ?>
            </td>

            <td class="numeric">
                <?php echo $group->getNationalAverageVehicleAge(); ?>
            </td>

            <td class="numeric">
                <?php echo $group->getNationalAverageTestDuration(); ?>
            </td>

            <td class="numeric">
                <?php echo $group->getNationalPercentageFailed(); ?>
            </td>
        </tr>
    <?php else: ?>
        <tr class="table-reference__row--secondary">
            <td colspan="5">
                National average not available
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>