<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'UserFacade\Exception\PermissionDoesNotExistException' => __DIR__ . '/src/UserFacade/Exception/PermissionDoesNotExistException.php',
  'UserFacade\Exception\RoleDoesNotExistException'       => __DIR__ . '/src/UserFacade/Exception/RoleDoesNotExistException.php',
  'UserFacade\Exception\UnauthenticatedException'        => __DIR__ . '/src/UserFacade/Exception/UnauthenticatedException.php',
  'UserFacade\Exception\UserDoesNotExistException'       => __DIR__ . '/src/UserFacade/Exception/UserDoesNotExistException.php',
  'UserFacade\Exception\UserExistsException'             => __DIR__ . '/src/UserFacade/Exception/UserExistsException.php',
  'UserFacade\Exception\UserFacadeException'             => __DIR__ . '/src/UserFacade/Exception/UserFacadeException.php',
  'UserFacade\Factory\UserFacadeLocalFactory'            => __DIR__ . '/src/UserFacade/Factory/UserFacadeLocalFactory.php',
  'UserFacade\Response\Response'                         => __DIR__ . '/src/UserFacade/Response/Response.php',
  'UserFacade\Response\User'                             => __DIR__ . '/src/UserFacade/Response/User.php',
  'UserFacade\Role'                                      => __DIR__ . '/src/UserFacade/Role.php',
  'UserFacade\UserFacadeInterface'                       => __DIR__ . '/src/UserFacade/UserFacadeInterface.php',
  'UserFacade\UserFacadeLocal'                           => __DIR__ . '/src/UserFacade/UserFacadeLocal.php',
);
