services:
    dvsa.test_support_helper:
        class: Dvsa\Mot\Behat\Support\Helper\TestSupportHelper
        arguments:
            - @dvsa.test_support_service_manager

    dvsa.mot_test_type_helper:
        class: Dvsa\Mot\Behat\Support\Helper\MotTestTypeHelper

    dvsa.api_resource_helper:
        class: Dvsa\Mot\Behat\Support\Helper\ApiResourceHelper
        arguments:
            - @dvsa.http_client.reflective

    dvsa.test_support_service_manager:
        class: Zend\ServiceManager\ServiceManager
        public: false
        factory: ["@dvsa.test_support_service_manager.factory", getServiceManager]

    dvsa.test_support_service_manager.factory:
        class: Dvsa\Mot\Behat\Support\Service\ServiceManager
        public: false
