<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DvsaAuthorisation\Factory\AuthorisationServiceFactory'    => __DIR__ . '/src/DvsaAuthorisation/Factory/AuthorisationServiceFactory.php',
  'DvsaAuthorisation\Factory\RoleProviderServiceFactory'     => __DIR__ . '/src/DvsaAuthorisation/Factory/RoleProviderServiceFactory.php',
  // REMOVED INVALID MAP: 'RoleProviderService'                                      => __DIR__ . '/src/DvsaAuthorisation/Factory/RoleProviderServiceFactory.php',
  'DvsaAuthorisation\Factory\SiteBusinessRoleServiceFactory' => __DIR__ . '/src/DvsaAuthorisation/Factory/SiteBusinessRoleServiceFactory.php',
  'DvsaAuthorisation\Factory\UserRoleServiceFactory'         => __DIR__ . '/src/DvsaAuthorisation/Factory/UserRoleServiceFactory.php',
  // REMOVED INVALID MAP: 'UserRoleService'                                          => __DIR__ . '/src/DvsaAuthorisation/Factory/UserRoleServiceFactory.php',
  // REMOVED INVALID MAP: 'getRepository'                                            => __DIR__ . '/src/DvsaAuthorisation/Factory/UserRoleServiceFactory.php',
  'DvsaAuthorisation\Model\OrganisationRole'                 => __DIR__ . '/src/DvsaAuthorisation/Model/OrganisationRole.php',
  'DvsaAuthorisation\Model\Permission'                       => __DIR__ . '/src/DvsaAuthorisation/Model/Permission.php',
  'DvsaAuthorisation\Model\Role'                             => __DIR__ . '/src/DvsaAuthorisation/Model/Role.php',
  'DvsaAuthorisation\Model\SiteRole'                         => __DIR__ . '/src/DvsaAuthorisation/Model/SiteRole.php',
  'DvsaAuthorisation\Service\AuthorisationService'           => __DIR__ . '/src/DvsaAuthorisation/Service/AuthorisationService.php',
  'DvsaAuthorisation\Service\AuthorisationServiceInterface'  => __DIR__ . '/src/DvsaAuthorisation/Service/AuthorisationServiceInterface.php',
  'DvsaAuthorisation\Service\RoleProviderService'            => __DIR__ . '/src/DvsaAuthorisation/Service/RoleProviderService.php',
  'DvsaAuthorisation\Service\SiteBusinessRoleService'        => __DIR__ . '/src/DvsaAuthorisation/Service/SiteBusinessRoleService.php',
  // REMOVED INVALID MAP: 'get'                                                      => __DIR__ . '/src/DvsaAuthorisation/Service/SiteBusinessRoleService.php',
  'DvsaAuthorisation\Service\UserRoleService'                => __DIR__ . '/src/DvsaAuthorisation/Service/UserRoleService.php',
);
