<?php
/** @var string $searchType */
/** @var \DvsaMotTest\View\VehicleSearchResult\VehicleSearchResultUrlTemplateInterface $urlTemplate */
/** @var \DvsaMotTest\View\VehicleSearchResult\VehicleSearchResultMessage $searchResultMessage */

use DvsaMotTest\Controller\VehicleSearchController;

$searchType = $this->searchType;

$isRetest = ($searchType === VehicleSearchController::SEARCH_TYPE_RETEST);
$isDemo = ($searchType === VehicleSearchController::SEARCH_TYPE_DEMO);
$isReplCert = ($searchType === VehicleSearchController::SEARCH_TYPE_CERTIFICATE);

//  --  title & header  --
if (!empty($this->title)) {
    $title = $this->title;
} else {
    $title = 'Vehicle search';

    if ($isRetest) {
        $title .= ' - retest';
    } elseif ($isDemo) {
        $title =  'DEMO ' . $title;
    }
}
$escTitle = $this->escapeHtml($title);

$this->headTitle($escTitle);
if (!$isRetest && !$isReplCert) {
    $this->layout()->setVariable('pageSubTitle', 'MOT testing');
}
if ($isReplCert) {
    $this->layout()->setVariable('pageSubTitle', 'Duplicate or replacement certificate');
}
$this->layout()->setVariable('pageTitle', $escTitle);

$noMatches = isset($noMatches) ? $noMatches : false;
$showCreateButton = isset($showCreateButton) ? $showCreateButton : false;
$results = isset($results) ? $results : null;
$tooManyMatches = isset($tooManyMatches) ? $tooManyMatches : null;
$registrationNumberMaxLength = isset($registrationNumberMaxLength) ? $registrationNumberMaxLength : 10;

$form = $this->form;
$action = (!empty($action)? $action : '');
$form->setAttribute('method', 'post');
$form->setAttribute('action', $action);
$form->prepare();

$data = [
    'registrationElement'         => $form->get('registration'),
    'vinElement'                  => $form->get('vin'),
    'submitElement'               => $form->get('submit'),
    'testNumberElement'           => $form->get('testNumber'),
    'searchType'                  => (isset($searchType) ? $searchType : null),
    'vinTypeElement'              => $form->get('vinType'),
    'previousRegistrationElement' => $form->get('previousSearchRegistration'),
    'previousVinElement'          => $form->get('previousSearchVin'),
];

echo $this->partial(
    'vehicleRetestSearch',
    [
        'form'                          => $form,
        'data'                          => $data,
        'noMatches'                     => $noMatches,
        'showCreateButton'              => $showCreateButton,
        'results'                       => $results,
        'tooManyMatches'                => $tooManyMatches,
        'registrationNumberMaxLength'   => $registrationNumberMaxLength,
    ]
);