<div class="text">
    <p class="lede">Please check the details below before you record the event.</p>
</div>

<form action="<?php echo $this->escapeHtmlAttr($this->url($routes['SUMMARY'], array('type' => $type, 'id' => $id))); ?>" method="POST" autocomplete="off" novalidate="">
    <?php echo $this->csrfToken(); ?>

    <table class="key-value-list">
        <tbody>
        <tr>
            <th scope="col" class="key-value-list__key">Date of event</th>
            <td class="key-value-list__value">
                <?php echo $this->escapeHtmlAttr($eventDate) ?>
            </td>
            <td class="key-value-list__item-action">
                <a href="<?php echo $this->escapeHtmlAttr($this->url($routes['RECORD'], array('type' => $type, 'id' => $id))); ?>">Change<span class="visuallyhidden"> event</span></a>
            </td>
        </tr>
        <tr>
            <th scope="col" class="key-value-list__key">Event</th>
            <td class="key-value-list__value">
                <?php echo $this->escapeHtmlAttr($eventTypeName) ?>
            </td>
            <td class="key-value-list__item-action">
                <a href="<?php echo $this->escapeHtmlAttr($this->url($routes['RECORD'], array('type' => $type, 'id' => $id))); ?>">Change<span class="visuallyhidden"> event</span></a>
            </td>
        </tr>
        <tr>
            <th scope="col" class="key-value-list__key">Outcome</th>
            <td class="key-value-list__value">
                <?php echo $this->escapeHtmlAttr($eventOutcomeCodeName) ?>
                <span class="key-value-list__meta">
                    <?php echo $this->escapeHtmlAttr($notes) ?>
                </span>
            </td>
            <td class="key-value-list__item-action">
                <a href="<?php echo $this->escapeHtmlAttr($this->url($routes['OUTCOME'], array('type' => $type, 'id' => $id))); ?>">Change<span class="visuallyhidden"> event outcome</span></a>
            </td>
        </tr>
        </tbody>
    </table>

    <nav class="content-navigation">
        <input type="submit" value="Record event" id="continue" class="button">

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtmlAttr($this->url($routes['OUTCOME'], array('type' => $type, 'id' => $id))); ?>">Back</a>
            </li>
        </ul>
    </nav>

</form>
