<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DvsaAuthentication\AuthAdapter\Rest'                                  => __DIR__ . '/src/DvsaAuthentication/AuthAdapter/Rest.php',
  'DvsaAuthentication\Controller\AuthenticationController'               => __DIR__ . '/src/DvsaAuthentication/Controller/AuthenticationController.php',
  'DvsaAuthentication\Listener\Factory\WebAuthenticationListenerFactory' => __DIR__ . '/src/DvsaAuthentication/Listener/Factory/WebAuthenticationListenerFactory.php',
  'DvsaAuthentication\Listener\WebAuthenticationListener'                => __DIR__ . '/src/DvsaAuthentication/Listener/WebAuthenticationListener.php',
  // REMOVED INVALID MAP: 'authenticationService'                                                => __DIR__ . '/src/DvsaAuthentication/Listener/WebAuthenticationListener.php',
  'DvsaAuthentication\Model\Identity'                                    => __DIR__ . '/src/DvsaAuthentication/Model/Identity.php',
  'DvsaAuthentication\Model\MotFrontendIdentityInterface'                => __DIR__ . '/src/DvsaAuthentication/Model/MotFrontendIdentityInterface.php',
  'DvsaAuthentication\Model\User'                                        => __DIR__ . '/src/DvsaAuthentication/Model/User.php',
  'DvsaAuthentication\Model\VehicleTestingStation'                       => __DIR__ . '/src/DvsaAuthentication/Model/VehicleTestingStation.php',
  'DvsaAuthentication\Service\Factory\WebAccessTokenServiceFactory'      => __DIR__ . '/src/DvsaAuthentication/Service/Factory/WebAccessTokenServiceFactory.php',
  'DvsaAuthentication\Service\WebAccessTokenService'                     => __DIR__ . '/src/DvsaAuthentication/Service/WebAccessTokenService.php',
);
