<?php
use UserAdmin\Presenter\UserProfilePresenter;

/** @var $profilePresenter UserProfilePresenter */
/** @var string $userProfileUrl */
/** @var string $resetClaimAccountUrlPost */
$this->headTitle('Reclaim account');
$personFullnameWithTitle = $profilePresenter->displayTitleAndFullName();
?>
<div id="reclaim-account-notification" class="text">
    <p class="lede">
        You should only start this process if <?php echo $this->escapeHtml($personFullnameWithTitle) ?> has forgotten
        their security questions and password.
    </p>

    <?php echo $this->partial('partial/gds/general/system-message',
        [
            'messages' => [
                'This will reset the user\'s password and require them to set up their security questions '
                .' and PIN when they next sign in.'
            ],
            'type' => 'important'
        ]
    ); ?>

</div>

<form method="POST" novalidate>
    <?php echo $this->csrfToken() ?>
    <nav class="content-navigation">
        <?php echo $this->partial(
            'partial/gds/form/control-navigation',
            [
                'id'            => 'reclaim-account-submit',
                'class'         => 'button-warning',
                'value'         => 'Reclaim account by post',
                'navigation'    => [
                    'Cancel and return to user profile' => $userProfileUrl,
                ]
            ]
        ); ?>
    </nav>
</form>

