<?php

use DvsaCommon\Enum\EmergencyReasonCode;

/**
 * @var \DvsaCommon\Dto\MotTesting\ContingencyMotTestDto      $dto
 * @var array $loggedInVts
 */

$radioTestWhoGroupValue   = $dto->getTestedByWhom();
$radioSiteGroupValue      = (int)$dto->getSiteId();
$ctCodeValue              = $dto->getContingencyCode();
$testerCodeValue          = $dto->getTesterCode();

$radioReasonGroupValue    = $dto->getReasonCode();
$otherReasonsValue        = $dto->getReasonText();

$vts = array();
@array_filter($loggedInVts, function(&$value, &$key) use (&$vts) {
    $vts['<b>' . $value['name'] . '</b>, ' . $value['address']] = $value['id'];
});


$title = 'Contingency Test Entry';

$this->headTitle($title);
echo $this->partial(
    'motTestProgress',
    [
        'currentStep' => -1,
        'title' => $title,
        'isMotContingency' => true
    ]
);

$this->headScript()->appendFile('/js/dvsa-mot-test/contingency-mot-test/index.js');

echo $this->partial('errorMessages', ['getFromFlash' => true]);
echo $this->partial('infoMessages', ['getFromFlash' => true]);
?>

<form action="<?php echo $this->url('contingency') ?>" method="POST" name="CTVerifcation" class="form-vertical" id="CTVerifcation">
    <?php echo $this->csrfToken() ?>
    <fieldset>

        <div class="row">
            <div class="col-sm-6">
                <?php echo $this->partial(
                    'radioElement',
                    [
                        'id'            => 'who-1',
                        'name'          => 'radio-test-who-group',
                        'isChecked'     => true,
                        'labelCssClass' => 'hidden',
                        'value'         => 'current',
                    ]
                );?>

                    <div class="otherTester" style="margin-top: 10px;" >
                        <label for="testerNumber">Please enter the ID of the tester that performed this contingency test</label>
                        <input type="text" id="testerNumber" name="testerNumber" value="<?php echo $this->escapeHtml($testerCodeValue) ?>" class="form-control form-control-max" placeholder="eg. SMIT0001" maxlength="8" />
                    </div>
            </div>
        </div>


        <div class="row multiple-sites">
            <div class="col-sm-6">
                <?php if(count($vts)>1): ?>
                <?php echo $this->partial(
                    'partial/forms/radioBoxMultiple.phtml',
                    [
                        'name'         => 'radio-site-group',
                        'checkedValue' => $radioSiteGroupValue,
                        'radioOptions' => $vts,
                        'escapeLabel' => false
                    ]
                ); ?>
                <?php else: ?>
                <?php echo $this->partial(
                    'partial/forms/hidden-element.phtml',
                    [
                        'id'          => 'radio-site-group',
                        'name'        => 'radio-site-group',
                        'value'       => array_pop($vts),
                    ]
                ); ?>
                <?php endif ?>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <div class="form-group" id="ct-field" style="display:inherit">
                    <label for="ct-code">Contingency code</label>
                    <input type="text" name="ct-code" class="form-control" id="ct-code" value="<?php echo $this->escapeHtml($ctCodeValue) ?>" maxlength="10">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <fieldset>
                    <div class="form-group">
                        <?php echo $this->partial(
                            'partial/forms/datePickerBox.phtml',
                            [
                                'prefix'    => 'dateTest',
                                'label'     => 'Date contingency test performed',
                                'day'       => $dto->getDateDay(),
                                'month'     => $dto->getDateMonth(),
                                'year'      => $dto->getDateYear(),
                                'help'      => 'For example, 08 10 2014'
                            ]
                        ); ?>
                    </div>
                </fieldset>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">
                <div class="form-group ct-reason">
                <?php echo $this->partial(
                    'partial/forms/radioBoxMultiple.phtml',
                    [
                        'name'         => 'radio-reason-group',
                        'checkedValue' => $this->escapeHtml($radioReasonGroupValue),
                        'labelCssClass' => 'block-label label-clear other-reason',
                        'radioOptions' => [
                            'System outage' => EmergencyReasonCode::SYSTEM_OUTAGE,
                            'Communication problem' => EmergencyReasonCode::COMMUNICATION_PROBLEM,
                            'Payment issue' => EmergencyReasonCode::PAYMENT_ISSUE,
                            'Other' => EmergencyReasonCode::OTHER,
                        ],
                        'label' => 'Reason for contingency test'
                    ]
                ); ?>
                    <div class="otherReasons" style="margin-top: 10px;">
                        <label for="otherReasons">Please enter other reason(s)</label>
                        <textarea name="other-reasons" id="otherReasons" rows="3" class="form-control form-control-max flexible-vert" ><?php echo $this->escapeHtml($otherReasonsValue) ?></textarea>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" style="margin-top: 25px;">
            <div class="col-sm-6">
                <div class="form-group">
                    <input type="submit" value="Confirm contingency test details" class="btn btn-primary" id="confirm_ct_button" />
                </div>
            </div>
        </div>


    </fieldset>
</form>
