<?php

use DvsaMotTest\View\ReplacementModelViewModel;

/**
 * @var ReplacementModelViewModel $model
 * @var $modelList
 * @var $make
 */
?>

<?php $this->placeholder('dashboard-section-header-caption')->captureStart('SET') ?>
    <h3>Model</h3>
<?php $this->placeholder('dashboard-section-header-caption')->captureEnd() ?>

<?php $this->placeholder('dashboard-section-header-value')->captureStart('SET') ?>
    <h3><strong><?php echo $this->escapeHTML($model->getName()); ?></strong></h3>
<?php $this->placeholder('dashboard-section-header-value')->captureEnd() ?>

<?php $this->placeholder('dashboard-section-body')->captureStart('SET') ?>
    <div class="clearfix">
        <div>
            <div class="row">
                <div class="form-group col-sm-6">
                    <input type="hidden" name="make" value="<?php echo $make->getCode(); ?>"/>
                    <select name="model" id="input-model" class="form-control input-small">
                        <option value="">Select a model</option>
                        <?php foreach ($modelList as $id => $modelRecord): ?>
                            <option
                                value="<?php echo $this->escapeHTML($modelRecord['code']); ?>"<?php if ($modelRecord['code'] == $model->getCode(
                                )
                            ): ?> selected<?php endif; ?>><?php echo $this->escapeHTML($modelRecord['name']); ?></option>
                        <?php endforeach; ?>
                        <option value="other">Other</option>
                    </select>
                </div>
            </div>
        </div>
    </div>


<?php $this->placeholder('dashboard-section-body')->captureEnd() ?>

<?php echo $this->partial(
    'dvsa-mot-test/dashboard/generic-section',
    [
        'sectionId' => 'model',
        'actionName' => 'updateModel',
        'displayBody' => $displayModelBody
    ]
);
