<?php

/**
 * @var OdometerReadingViewObject  $odometerReading
 * @var  $actionUrl
 */
use DvsaMotTest\Model\OdometerReadingViewObject;

?>

<?php $this->placeholder('dashboard-section-header-caption')->captureStart('SET') ?>
<h3>Odometer reading</h3>
<?php $this->placeholder('dashboard-section-header-caption')->captureEnd() ?>

<?php $this->placeholder('dashboard-section-header-value')->captureStart('SET') ?>
    <h3><strong><?php echo $odometerReading->getDisplayValue() ?></strong></h3>
<?php $this->placeholder('dashboard-section-header-value')->captureEnd() ?>


<?php $this->placeholder('dashboard-section-body')->captureStart('SET') ?>
  <div class="clearfix">
    <ul class="odometer-list ">

        <ul class="odometer-list">
            <li>
        <div class="form-inline">
            <div class="radio">
                <label class="form-group" for="odometerValue">
                    <input id="odometerValue" type="radio" name="odometerResultType" class="radio"
                           value="OK" <?php if ($odometerReading->getResultType() === 'OK') echo "checked" ?>
                           required="">
                </label>

                <div class="form-group">
                    <label class="sr-only" for="odometer">Odometer</label>
                    <input type="text" class="form-control" id="odometer" name="odometerValue"
                           value="<?php echo $this->escapeHtml($odometerReading->getValue()); ?>" maxlength="6">
                </div>
                <div class="form-group">
                    <label class="sr-only" for="unit">Unit</label>
                    <select class="form-control" id="unit" name="odometerUnit">
                        <option value="mi" <?php if ($odometerReading->getUnit() === 'mi'
                            || !$odometerReading->getUnit()
                        ) {
                            echo 'selected="selected"';
                        } ?>>Miles
                        </option>
                        <option value="km" <?php if ($odometerReading->getUnit() === 'km'
                        ) {
                            echo 'selected="selected"';
                        } ?>>Kilometres
                        </option>
                    </select>
                </div>
            </div>
        </div>
            </li>
            <li>
            <div class="radio form-group">
                <label for="notReadable">
                    <input id="notReadable" type="radio" name="odometerResultType" class="radio"
                           value="NOT_READ" <?php if ($odometerReading->getResultType() === 'NOT_READ') echo "checked" ?>
                           required="">
                    Odometer is not readable
                </label>
            </div>
            </li>
            <li>
            <div class="radio form-group">
                <label for="noOdometer">
                    <input id="noOdometer" type="radio" name="odometerResultType" class="radio"
                        <?php if ($odometerReading->getResultType() === 'NO_METER') echo "checked" ?>
                           value="NO_METER" required="">
                    There is no odometer
                </label>
            </div>
            </li>

    </ul>
  </div>
<?php $this->placeholder('dashboard-section-body')->captureEnd() ?>


    <?php echo $this->partial(
    'dvsa-mot-test/dashboard/generic-section',
    [
        'sectionId'    => 'odometer',
        'actionName'   => 'updateOdometer',
        'bodyVisible'  => $odometerReading->getModifiable()
    ]
);
