<?php
/**
 * @var \Organisation\ViewModel\Search\AeSearchViewModel
 */
$labelText = 'AE Number';
$inputId = 'number';
$inputName = 'number';
$help = 'For example, A12345';
$labelError = $viewModel->getErrorMessage();
$maxLength = $viewModel->getMaxSearchLength();

$errorMessages = $this->layout()->flashMessenger->getErrorMessages();
$successMessages = $this->layout()->flashMessenger->getSuccessMessages();
?>

<?php echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']); ?>
<?php echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']); ?>

<form method="POST">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <?php echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id' => $inputId,
                'name' => $inputName,
                'help' => $help,
                'errorMessage' => $labelError,
                'label' => $labelText,
                'value' => $viewModel->getSearch(),
                'maxLength' => $maxLength,
            ]
        ); ?>
    </fieldset>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id' => 'submitAeSearch',
            'value' => 'Search',
            'navigation' => [
                'Return home' => '/',
            ],
        ]
    ); ?>
</form>