<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'auth_for_ae_status' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class AuthorisationForAuthorisedExaminerStatusCode
{
    const UNKNOWN = 'UNKN';
    const APPLIED = 'APPLD';
    const APPROVED = 'APRVD';
    const LAPSED = 'LPSD';
    const WITHDRAWN = 'WDRWN';
    const SURRENDERED = 'SRNDR';
    const REJECTED = 'RJCTD';
    const RETRACTED = 'RTRCT';

    /**
     * @return array of values for the type AuthorisationForAuthorisedExaminerStatusCode
     */
    public static function getAll()
    {
        return [
            self::UNKNOWN,
            self::APPLIED,
            self::APPROVED,
            self::LAPSED,
            self::WITHDRAWN,
            self::SURRENDERED,
            self::REJECTED,
            self::RETRACTED,
        ];
    }

    /**
     * @param mixed $key a candidate AuthorisationForAuthorisedExaminerStatusCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
