<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'auth_for_testing_mot_at_site_status' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class AuthorisationForTestingMotAtSiteStatusCode
{
    const UNKNOWN = 'UNKN';
    const APPROVED = 'APRVD';

    /**
     * @return array of values for the type AuthorisationForTestingMotAtSiteStatusCode
     */
    public static function getAll()
    {
        return [
            self::UNKNOWN,
            self::APPROVED,
        ];
    }

    /**
     * @param mixed $key a candidate AuthorisationForTestingMotAtSiteStatusCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
