<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'certificate_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class CertificateTypeCode
{
    const TEST = 'T';
    const REPLACE = 'R';
    const DUPLICATE = 'D';
    const EXCHANGE = 'E';
    const TRANSFER = 'F';
    const VERIFY = 'V';

    /**
     * @return array of values for the type CertificateType
     */
    public static function getAll()
    {
        return [
            self::TEST,
            self::REPLACE,
            self::DUPLICATE,
            self::EXCHANGE,
            self::TRANSFER,
            self::VERIFY,
        ];
    }

    /**
     * @param mixed $key a candidate CertificateType value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
