<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'colour_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class ColourId
{
    const BEIGE = 1;
    const BLACK = 2;
    const BRONZE = 3;
    const BROWN = 4;
    const CREAM = 5;
    const GOLD = 6;
    const GREEN = 7;
    const GREY = 8;
    const MAROON = 9;
    const PURPLE = 10;
    const ORANGE = 11;
    const PINK = 12;
    const RED = 13;
    const SILVER = 14;
    const TURQUOISE = 15;
    const WHITE = 16;
    const YELLOW = 17;
    const MULTI_COLOUR = 18;
    const NOT_STATED = 19;
    const BLUE = 20;

    /**
     * @return array of values for the type ColourId
     */
    public static function getAll()
    {
        return [
            self::BEIGE,
            self::BLACK,
            self::BRONZE,
            self::BROWN,
            self::CREAM,
            self::GOLD,
            self::GREEN,
            self::GREY,
            self::MAROON,
            self::PURPLE,
            self::ORANGE,
            self::PINK,
            self::RED,
            self::SILVER,
            self::TURQUOISE,
            self::WHITE,
            self::YELLOW,
            self::MULTI_COLOUR,
            self::NOT_STATED,
            self::BLUE,
        ];
    }

    /**
     * @param mixed $key a candidate ColourId value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
