<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'colour_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class ColourCode
{
    const BEIGE = 'S';
    const BLACK = 'P';
    const BRONZE = 'B';
    const BROWN = 'A';
    const CREAM = 'V';
    const GOLD = 'G';
    const GREEN = 'H';
    const GREY = 'L';
    const MAROON = 'T';
    const PURPLE = 'K';
    const ORANGE = 'E';
    const PINK = 'D';
    const RED = 'C';
    const SILVER = 'M';
    const TURQUOISE = 'U';
    const WHITE = 'N';
    const YELLOW = 'F';
    const MULTI_COLOUR = 'R';
    const NOT_STATED = 'W';
    const BLUE = 'J';

    /**
     * @return array of values for the type ColourCode
     */
    public static function getAll()
    {
        return [
            self::BEIGE,
            self::BLACK,
            self::BRONZE,
            self::BROWN,
            self::CREAM,
            self::GOLD,
            self::GREEN,
            self::GREY,
            self::MAROON,
            self::PURPLE,
            self::ORANGE,
            self::PINK,
            self::RED,
            self::SILVER,
            self::TURQUOISE,
            self::WHITE,
            self::YELLOW,
            self::MULTI_COLOUR,
            self::NOT_STATED,
            self::BLUE,
        ];
    }

    /**
     * @param mixed $key a candidate ColourCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
