<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'company_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class CompanyTypeCode
{
    const COMPANY = 'RC';
    const PARTNERSHIP = 'P';
    const SOLE_TRADER = 'ST';
    const LIMITED_LIABILITY_PARTNERSHIP = 'LLP';
    const PUBLIC_BODY = 'PA';

    /**
     * @return array of values for the type CompanyTypeCode
     */
    public static function getAll()
    {
        return [
            self::COMPANY,
            self::PARTNERSHIP,
            self::SOLE_TRADER,
            self::LIMITED_LIABILITY_PARTNERSHIP,
            self::PUBLIC_BODY,
        ];
    }

    /**
     * @param mixed $key a candidate CompanyTypeCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
