<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'company_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class CompanyTypeName
{
    const REGISTERED_COMPANY = 'Registered Company';
    const PARTNERSHIP = 'Partnership';
    const SOLE_TRADER = 'Sole Trader';
    const LIMITED_LIABILITY_PARTNERSHIP = 'Limited Liability Partnership';
    const PUBLIC_AUTHORITY = 'Public Authority';

    /**
     * @return array of values for the type CompanyTypeName
     */
    public static function getAll()
    {
        return [
            self::REGISTERED_COMPANY,
            self::PARTNERSHIP,
            self::SOLE_TRADER,
            self::LIMITED_LIABILITY_PARTNERSHIP,
            self::PUBLIC_AUTHORITY,
        ];
    }

    /**
     * @param mixed $key a candidate CompanyTypeName value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
