<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'country_of_registration_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class CountryOfRegistrationCode
{
    const GB_UK_ENG_CYM_SCO_UK_GREAT_BRITAIN = 'GB';
    const GB_NI_UK_NORTHERN_IRELAND = 'NI';
    const GBA_GG_ALDERNEY = 'GBA';
    const GBG_GG_GUERNSEY = 'GBG';
    const GBJ_JE_JERSEY = 'GBJ';
    const GBM_IM_ISLE_OF_MAN = 'GBM';
    const A_AT_AUSTRIA = 'AT';
    const B_BE_BELGIUM = 'BE';
    const BG_BG_BULGARIA = 'BG';
    const CY_CY_CYPRUS = 'CY';
    const CZ_CZ_CZECH_REPUBLIC = 'CZ';
    const DK_DK_DENMARK = 'DK';
    const EST_EE_ESTONIA = 'EE';
    const FIN_FI_FINLAND = 'FI';
    const F_FR_FRANCE = 'FR';
    const D_DE_GERMANY = 'DE';
    const GBZ_GI_GIBRALTAR = 'GI';
    const GR_GR_GREECE = 'GR';
    const H_HU_HUNGARY = 'HU';
    const IRL_IE_IRELAND = 'IE';
    const I_IT_ITALY = 'IT';
    const LV_LV_LATVIA = 'LV';
    const LT_LT_LITHUANIA = 'LT';
    const L_LU_LUXEMBOURG = 'LU';
    const M_MT_MALTA = 'MT';
    const NL_NL_NETHERLANDS = 'NL';
    const PL_PL_POLAND = 'PL';
    const P_PT_PORTUGAL = 'PT';
    const RO_RO_ROMANIA = 'RO';
    const SK_SK_SLOVAKIA = 'SK';
    const SLO_SI_SLOVENIA = 'SI';
    const E_ES_SPAIN = 'ES';
    const S_SE_SWEDEN = 'SE';
    const NON_EU = 'XNEU';
    const NOT_KNOWN = 'XUKN';
    const NOT_APPLICABLE = 'XNA';

    /**
     * @return array of values for the type CountryOfRegistrationCode
     */
    public static function getAll()
    {
        return [
            self::GB_UK_ENG_CYM_SCO_UK_GREAT_BRITAIN,
            self::GB_NI_UK_NORTHERN_IRELAND,
            self::GBA_GG_ALDERNEY,
            self::GBG_GG_GUERNSEY,
            self::GBJ_JE_JERSEY,
            self::GBM_IM_ISLE_OF_MAN,
            self::A_AT_AUSTRIA,
            self::B_BE_BELGIUM,
            self::BG_BG_BULGARIA,
            self::CY_CY_CYPRUS,
            self::CZ_CZ_CZECH_REPUBLIC,
            self::DK_DK_DENMARK,
            self::EST_EE_ESTONIA,
            self::FIN_FI_FINLAND,
            self::F_FR_FRANCE,
            self::D_DE_GERMANY,
            self::GBZ_GI_GIBRALTAR,
            self::GR_GR_GREECE,
            self::H_HU_HUNGARY,
            self::IRL_IE_IRELAND,
            self::I_IT_ITALY,
            self::LV_LV_LATVIA,
            self::LT_LT_LITHUANIA,
            self::L_LU_LUXEMBOURG,
            self::M_MT_MALTA,
            self::NL_NL_NETHERLANDS,
            self::PL_PL_POLAND,
            self::P_PT_PORTUGAL,
            self::RO_RO_ROMANIA,
            self::SK_SK_SLOVAKIA,
            self::SLO_SI_SLOVENIA,
            self::E_ES_SPAIN,
            self::S_SE_SWEDEN,
            self::NON_EU,
            self::NOT_KNOWN,
            self::NOT_APPLICABLE,
        ];
    }

    /**
     * @param mixed $key a candidate CountryOfRegistrationCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
