<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'country_of_registration_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class CountryOfRegistrationId
{
    const GB_UK_ENG_CYM_SCO_UK_GREAT_BRITAIN = 1;
    const GB_NI_UK_NORTHERN_IRELAND = 2;
    const GBA_GG_ALDERNEY = 3;
    const GBG_GG_GUERNSEY = 4;
    const GBJ_JE_JERSEY = 5;
    const GBM_IM_ISLE_OF_MAN = 6;
    const A_AT_AUSTRIA = 7;
    const B_BE_BELGIUM = 8;
    const BG_BG_BULGARIA = 9;
    const CY_CY_CYPRUS = 10;
    const CZ_CZ_CZECH_REPUBLIC = 11;
    const DK_DK_DENMARK = 12;
    const EST_EE_ESTONIA = 13;
    const FIN_FI_FINLAND = 14;
    const F_FR_FRANCE = 15;
    const D_DE_GERMANY = 16;
    const GBZ_GI_GIBRALTAR = 17;
    const GR_GR_GREECE = 18;
    const H_HU_HUNGARY = 19;
    const IRL_IE_IRELAND = 20;
    const I_IT_ITALY = 21;
    const LV_LV_LATVIA = 22;
    const LT_LT_LITHUANIA = 23;
    const L_LU_LUXEMBOURG = 24;
    const M_MT_MALTA = 25;
    const NL_NL_NETHERLANDS = 26;
    const PL_PL_POLAND = 27;
    const P_PT_PORTUGAL = 28;
    const RO_RO_ROMANIA = 29;
    const SK_SK_SLOVAKIA = 30;
    const SLO_SI_SLOVENIA = 31;
    const E_ES_SPAIN = 32;
    const S_SE_SWEDEN = 33;
    const NON_EU = 34;
    const NOT_KNOWN = 35;
    const NOT_APPLICABLE = 36;

    /**
     * @return array of values for the type CountryOfRegistrationId
     */
    public static function getAll()
    {
        return [
            self::GB_UK_ENG_CYM_SCO_UK_GREAT_BRITAIN,
            self::GB_NI_UK_NORTHERN_IRELAND,
            self::GBA_GG_ALDERNEY,
            self::GBG_GG_GUERNSEY,
            self::GBJ_JE_JERSEY,
            self::GBM_IM_ISLE_OF_MAN,
            self::A_AT_AUSTRIA,
            self::B_BE_BELGIUM,
            self::BG_BG_BULGARIA,
            self::CY_CY_CYPRUS,
            self::CZ_CZ_CZECH_REPUBLIC,
            self::DK_DK_DENMARK,
            self::EST_EE_ESTONIA,
            self::FIN_FI_FINLAND,
            self::F_FR_FRANCE,
            self::D_DE_GERMANY,
            self::GBZ_GI_GIBRALTAR,
            self::GR_GR_GREECE,
            self::H_HU_HUNGARY,
            self::IRL_IE_IRELAND,
            self::I_IT_ITALY,
            self::LV_LV_LATVIA,
            self::LT_LT_LITHUANIA,
            self::L_LU_LUXEMBOURG,
            self::M_MT_MALTA,
            self::NL_NL_NETHERLANDS,
            self::PL_PL_POLAND,
            self::P_PT_PORTUGAL,
            self::RO_RO_ROMANIA,
            self::SK_SK_SLOVAKIA,
            self::SLO_SI_SLOVENIA,
            self::E_ES_SPAIN,
            self::S_SE_SWEDEN,
            self::NON_EU,
            self::NOT_KNOWN,
            self::NOT_APPLICABLE,
        ];
    }

    /**
     * @param mixed $key a candidate CountryOfRegistrationId value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
