<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'country_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class CountryCode
{
    const GREAT_BRITAIN = 'GB';
    const NORTHERN_IRELAND = 'NI';
    const ALDERNEY = 'GBA';
    const GUERNSEY = 'GBG';
    const JERSEY = 'GBJ';
    const ISLE_OF_MAN = 'GBM';
    const AUSTRIA = 'AT';
    const BELGIUM = 'BE';
    const BULGARIA = 'BG';
    const CYPRUS = 'CY';
    const CZECH_REPUBLIC = 'CZ';
    const DENMARK = 'DK';
    const ESTONIA = 'EE';
    const FINLAND = 'FI';
    const FRANCE = 'FR';
    const GERMANY = 'DE';
    const GIBRALTAR = 'GI';
    const GREECE = 'GR';
    const HUNGARY = 'HU';
    const IRELAND = 'IE';
    const ITALY = 'IT';
    const LATVIA = 'LV';
    const LITHUANIA = 'LT';
    const LUXEMBOURG = 'LU';
    const MALTA = 'MT';
    const NETHERLANDS = 'NL';
    const POLAND = 'PL';
    const PORTUGAL = 'PT';
    const ROMANIA = 'RO';
    const SLOVAKIA = 'SK';
    const SLOVENIA = 'SI';
    const SPAIN = 'ES';
    const SWEDEN = 'SE';
    const AFGHANISTAN = 'AF';
    const ALAND_ISLANDS = 'AX';
    const ALBANIA = 'AL';
    const ALGERIA = 'DZ';
    const AMERICAN_SAMOA = 'AS';
    const ANDORRA = 'AD';
    const ANGOLA = 'AO';
    const ANGUILLA = 'AI';
    const ANTARCTICA = 'AQ';
    const ANTIGUA_AND_BARBUDA = 'AG';
    const ARGENTINA = 'AR';
    const ARMENIA = 'AM';
    const ARUBA = 'AW';
    const AUSTRALIA = 'AU';
    const AZERBAIJAN = 'AZ';
    const BAHAMAS = 'BS';
    const BAHRAIN = 'BH';
    const BANGLADESH = 'BD';
    const BARBADOS = 'BB';
    const BELARUS = 'BY';
    const BELIZE = 'BZ';
    const BENIN = 'BJ';
    const BERMUDA = 'BM';
    const BHUTAN = 'BT';
    const BOLIVIA_PLURINATIONAL_STATE_OF = 'BO';
    const BONAIRE_SINT_EUSTATIUS_AND_SABA = 'BQ';
    const BOSNIA_AND_HERZEGOVINA = 'BA';
    const BOTSWANA = 'BW';
    const BOUVET_ISLAND = 'BV';
    const BRAZIL = 'BR';
    const BRITISH_INDIAN_OCEAN_TERRITORY = 'IO';
    const BRUNEI_DARUSSALAM = 'BN';
    const BURKINA_FASO = 'BF';
    const BURUNDI = 'BI';
    const CABO_VERDE = 'CV';
    const CAMBODIA = 'KH';
    const CAMEROON = 'CM';
    const CANADA = 'CA';
    const CAYMAN_ISLANDS = 'KY';
    const CENTRAL_AFRICAN_REPUBLIC = 'CF';
    const CHAD = 'TD';
    const CHILE = 'CL';
    const CHINA = 'CN';
    const CHRISTMAS_ISLAND = 'CX';
    const COCOS_KEELING_ISLANDS = 'CC';
    const COLOMBIA = 'CO';
    const COMOROS = 'KM';
    const CONGO = 'CG';
    const CONGO_DEMOCRATIC_REPUBLIC_OF_THE = 'CD';
    const COOK_ISLANDS = 'CK';
    const COSTA_RICA = 'CR';
    const COTE_DIVOIRE = 'CI';
    const CROATIA = 'HR';
    const CUBA = 'CU';
    const CURACAO = 'CW';
    const DJIBOUTI = 'DJ';
    const DOMINICA = 'DM';
    const DOMINICAN_REPUBLIC = 'DO';
    const ECUADOR = 'EC';
    const EGYPT = 'EG';
    const EL_SALVADOR = 'SV';
    const FALKLAND_ISLANDS_MALVINAS = 'FK';
    const ETHIOPIA = 'ET';
    const EQUATORIAL_GUINEA = 'GQ';
    const FAROE_ISLANDS = 'FO';
    const FIJI = 'FJ';
    const FRENCH_GUIANA = 'GF';
    const FRENCH_POLYNESIA = 'PF';
    const FRENCH_SOUTHERN_TERRITORIES = 'TF';
    const GABON = 'GA';
    const GAMBIA = 'GM';
    const GEORGIA = 'GE';
    const GHANA = 'GH';
    const GREENLAND = 'GL';
    const GRENADA = 'GD';
    const GUADELOUPE = 'GP';
    const GUAM = 'GU';
    const GUATEMALA = 'GT';
    const GUINEA = 'GN';
    const GUINEA_BISSAU = 'GW';
    const GUYANA = 'GY';
    const HAITI = 'HT';
    const HEARD_ISLAND_AND_MCDONALD_ISLANDS = 'HM';
    const HOLY_SEE = 'VA';
    const HONDURAS = 'HN';
    const HONG_KONG = 'HK';
    const ICELAND = 'IS';
    const INDIA = 'IN';
    const INDONESIA = 'ID';
    const IRAN_ISLAMIC_REPUBLIC_OF = 'IR';
    const IRAQ = 'IQ';
    const ISRAEL = 'IL';
    const JAMAICA = 'JM';
    const JAPAN = 'JP';
    const JORDAN = 'JO';
    const KAZAKHSTAN = 'KZ';
    const KENYA = 'KE';
    const KIRIBATI = 'KI';
    const KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF = 'KP';
    const KOREA_REPUBLIC_OF = 'KR';
    const KUWAIT = 'KW';
    const KYRGYZSTAN = 'KG';
    const LAO_PEOPLES_DEMOCRATIC_REPUBLIC = 'LA';
    const LEBANON = 'LB';
    const LESOTHO = 'LS';
    const LIBERIA = 'LR';
    const LIBYA = 'LY';
    const LIECHTENSTEIN = 'LI';
    const MACAO = 'MO';
    const MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF = 'MK';
    const MADAGASCAR = 'MG';
    const MALAWI = 'MW';
    const MALAYSIA = 'MY';
    const MALDIVES = 'MV';
    const MALI = 'ML';
    const MARSHALL_ISLANDS = 'MH';
    const MARTINIQUE = 'MQ';
    const MAURITANIA = 'MR';
    const MAURITIUS = 'MU';
    const MAYOTTE = 'YT';
    const MEXICO = 'MX';
    const MICRONESIA_FEDERATED_STATES_OF = 'FM';
    const MOLDOVA_REPUBLIC_OF = 'MD';
    const MONACO = 'MC';
    const MONGOLIA = 'MN';
    const MONTENEGRO = 'ME';
    const MONTSERRAT = 'MS';
    const MOROCCO = 'MA';
    const MOZAMBIQUE = 'MZ';
    const MYANMAR = 'MM';
    const NAMIBIA = 'NA';
    const NAURU = 'NR';
    const NEPAL = 'NP';
    const NEW_CALEDONIA = 'NC';
    const NEW_ZEALAND = 'NZ';
    const NICARAGUA = 'NIC';
    const NIGER = 'NE';
    const NIGERIA = 'NG';
    const NIUE = 'NU';
    const NORFOLK_ISLAND = 'NF';
    const NORTHERN_MARIANA_ISLANDS = 'MP';
    const NORWAY = 'NO';
    const OMAN = 'OM';
    const PAKISTAN = 'PK';
    const PALAU = 'PW';
    const PALESTINE_STATE_OF = 'PS';
    const PANAMA = 'PA';
    const PAPUA_NEW_GUINEA = 'PG';
    const PARAGUAY = 'PY';
    const PERU = 'PE';
    const PHILIPPINES = 'PH';
    const PITCAIRN = 'PN';
    const PUERTO_RICO = 'PR';
    const QATAR = 'QA';
    const REUNION = 'RE';
    const RUSSIAN_FEDERATION = 'RU';
    const RWANDA = 'RW';
    const SAINT_BARTHELEMY = 'BL';
    const SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = 'SH';
    const SAINT_KITTS_AND_NEVIS = 'KN';
    const SAINT_LUCIA = 'LC';
    const SAINT_MARTIN_FRENCH_PART = 'MF';
    const SAINT_PIERRE_AND_MIQUELON = 'PM';
    const SAINT_VINCENT_AND_THE_GRENADINES = 'VC';
    const SAMOA = 'WS';
    const SAN_MARINO = 'SM';
    const SAO_TOME_AND_PRINCIPE = 'ST';
    const SAUDI_ARABIA = 'SA';
    const SENEGAL = 'SN';
    const SERBIA = 'RS';
    const SEYCHELLES = 'SC';
    const SIERRA_LEONE = 'SL';
    const SINGAPORE = 'SG';
    const SINT_MAARTEN_DUTCH_PART = 'SX';
    const SOLOMON_ISLANDS = 'SB';
    const SOMALIA = 'SO';
    const SOUTH_AFRICA = 'ZA';
    const SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 'GS';
    const SOUTH_SUDAN = 'SS';
    const SRI_LANKA = 'LK';
    const SUDAN = 'SD';
    const SURINAME = 'SR';
    const SVALBARD_AND_JAN_MAYEN = 'SJ';
    const SWAZILAND = 'SZ';
    const SWITZERLAND = 'CH';
    const SYRIAN_ARAB_REPUBLIC = 'SY';
    const TAIWAN_PROVINCE_OF_CHINA = 'TW';
    const TAJIKISTAN = 'TJ';
    const TANZANIA_UNITED_REPUBLIC_OF = 'TZ';
    const THAILAND = 'TH';
    const TIMOR_LESTE = 'TL';
    const TOGO = 'TG';
    const TOKELAU = 'TK';
    const TONGA = 'TO';
    const TRINIDAD_AND_TOBAGO = 'TT';
    const TUNISIA = 'TN';
    const TURKEY = 'TR';
    const TURKMENISTAN = 'TM';
    const TURKS_AND_CAICOS_ISLANDS = 'TC';
    const TUVALU = 'TV';
    const UGANDA = 'UG';
    const UKRAINE = 'UA';
    const UNITED_ARAB_EMIRATES = 'AE';
    const UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'UM';
    const UNITED_STATES_OF_AMERICA = 'US';
    const URUGUAY = 'UY';
    const UZBEKISTAN = 'UZ';
    const VANUATU = 'VU';
    const VENEZUELA_BOLIVARIAN_REPUBLIC_OF = 'VE';
    const VIET_NAM = 'VN';
    const VIRGIN_ISLANDS_BRITISH = 'VG';
    const VIRGIN_ISLANDS_US = 'VI';
    const WALLIS_AND_FUTUNA = 'WF';
    const WESTERN_SAHARA = 'EH';
    const YEMEN = 'YE';
    const ZAMBIA = 'ZM';
    const ZIMBABWE = 'ZW';
    const ERITREA = 'ER';
    const ENGLAND = 'GBENG';
    const WALES = 'GBWLS';
    const SCOTLAND = 'GBSCT';

    /**
     * @return array of values for the type CountryCode
     */
    public static function getAll()
    {
        return [
            self::GREAT_BRITAIN,
            self::NORTHERN_IRELAND,
            self::ALDERNEY,
            self::GUERNSEY,
            self::JERSEY,
            self::ISLE_OF_MAN,
            self::AUSTRIA,
            self::BELGIUM,
            self::BULGARIA,
            self::CYPRUS,
            self::CZECH_REPUBLIC,
            self::DENMARK,
            self::ESTONIA,
            self::FINLAND,
            self::FRANCE,
            self::GERMANY,
            self::GIBRALTAR,
            self::GREECE,
            self::HUNGARY,
            self::IRELAND,
            self::ITALY,
            self::LATVIA,
            self::LITHUANIA,
            self::LUXEMBOURG,
            self::MALTA,
            self::NETHERLANDS,
            self::POLAND,
            self::PORTUGAL,
            self::ROMANIA,
            self::SLOVAKIA,
            self::SLOVENIA,
            self::SPAIN,
            self::SWEDEN,
            self::AFGHANISTAN,
            self::ALAND_ISLANDS,
            self::ALBANIA,
            self::ALGERIA,
            self::AMERICAN_SAMOA,
            self::ANDORRA,
            self::ANGOLA,
            self::ANGUILLA,
            self::ANTARCTICA,
            self::ANTIGUA_AND_BARBUDA,
            self::ARGENTINA,
            self::ARMENIA,
            self::ARUBA,
            self::AUSTRALIA,
            self::AZERBAIJAN,
            self::BAHAMAS,
            self::BAHRAIN,
            self::BANGLADESH,
            self::BARBADOS,
            self::BELARUS,
            self::BELIZE,
            self::BENIN,
            self::BERMUDA,
            self::BHUTAN,
            self::BOLIVIA_PLURINATIONAL_STATE_OF,
            self::BONAIRE_SINT_EUSTATIUS_AND_SABA,
            self::BOSNIA_AND_HERZEGOVINA,
            self::BOTSWANA,
            self::BOUVET_ISLAND,
            self::BRAZIL,
            self::BRITISH_INDIAN_OCEAN_TERRITORY,
            self::BRUNEI_DARUSSALAM,
            self::BURKINA_FASO,
            self::BURUNDI,
            self::CABO_VERDE,
            self::CAMBODIA,
            self::CAMEROON,
            self::CANADA,
            self::CAYMAN_ISLANDS,
            self::CENTRAL_AFRICAN_REPUBLIC,
            self::CHAD,
            self::CHILE,
            self::CHINA,
            self::CHRISTMAS_ISLAND,
            self::COCOS_KEELING_ISLANDS,
            self::COLOMBIA,
            self::COMOROS,
            self::CONGO,
            self::CONGO_DEMOCRATIC_REPUBLIC_OF_THE,
            self::COOK_ISLANDS,
            self::COSTA_RICA,
            self::COTE_DIVOIRE,
            self::CROATIA,
            self::CUBA,
            self::CURACAO,
            self::DJIBOUTI,
            self::DOMINICA,
            self::DOMINICAN_REPUBLIC,
            self::ECUADOR,
            self::EGYPT,
            self::EL_SALVADOR,
            self::FALKLAND_ISLANDS_MALVINAS,
            self::ETHIOPIA,
            self::EQUATORIAL_GUINEA,
            self::FAROE_ISLANDS,
            self::FIJI,
            self::FRENCH_GUIANA,
            self::FRENCH_POLYNESIA,
            self::FRENCH_SOUTHERN_TERRITORIES,
            self::GABON,
            self::GAMBIA,
            self::GEORGIA,
            self::GHANA,
            self::GREENLAND,
            self::GRENADA,
            self::GUADELOUPE,
            self::GUAM,
            self::GUATEMALA,
            self::GUINEA,
            self::GUINEA_BISSAU,
            self::GUYANA,
            self::HAITI,
            self::HEARD_ISLAND_AND_MCDONALD_ISLANDS,
            self::HOLY_SEE,
            self::HONDURAS,
            self::HONG_KONG,
            self::ICELAND,
            self::INDIA,
            self::INDONESIA,
            self::IRAN_ISLAMIC_REPUBLIC_OF,
            self::IRAQ,
            self::ISRAEL,
            self::JAMAICA,
            self::JAPAN,
            self::JORDAN,
            self::KAZAKHSTAN,
            self::KENYA,
            self::KIRIBATI,
            self::KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF,
            self::KOREA_REPUBLIC_OF,
            self::KUWAIT,
            self::KYRGYZSTAN,
            self::LAO_PEOPLES_DEMOCRATIC_REPUBLIC,
            self::LEBANON,
            self::LESOTHO,
            self::LIBERIA,
            self::LIBYA,
            self::LIECHTENSTEIN,
            self::MACAO,
            self::MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF,
            self::MADAGASCAR,
            self::MALAWI,
            self::MALAYSIA,
            self::MALDIVES,
            self::MALI,
            self::MARSHALL_ISLANDS,
            self::MARTINIQUE,
            self::MAURITANIA,
            self::MAURITIUS,
            self::MAYOTTE,
            self::MEXICO,
            self::MICRONESIA_FEDERATED_STATES_OF,
            self::MOLDOVA_REPUBLIC_OF,
            self::MONACO,
            self::MONGOLIA,
            self::MONTENEGRO,
            self::MONTSERRAT,
            self::MOROCCO,
            self::MOZAMBIQUE,
            self::MYANMAR,
            self::NAMIBIA,
            self::NAURU,
            self::NEPAL,
            self::NEW_CALEDONIA,
            self::NEW_ZEALAND,
            self::NICARAGUA,
            self::NIGER,
            self::NIGERIA,
            self::NIUE,
            self::NORFOLK_ISLAND,
            self::NORTHERN_MARIANA_ISLANDS,
            self::NORWAY,
            self::OMAN,
            self::PAKISTAN,
            self::PALAU,
            self::PALESTINE_STATE_OF,
            self::PANAMA,
            self::PAPUA_NEW_GUINEA,
            self::PARAGUAY,
            self::PERU,
            self::PHILIPPINES,
            self::PITCAIRN,
            self::PUERTO_RICO,
            self::QATAR,
            self::REUNION,
            self::RUSSIAN_FEDERATION,
            self::RWANDA,
            self::SAINT_BARTHELEMY,
            self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA,
            self::SAINT_KITTS_AND_NEVIS,
            self::SAINT_LUCIA,
            self::SAINT_MARTIN_FRENCH_PART,
            self::SAINT_PIERRE_AND_MIQUELON,
            self::SAINT_VINCENT_AND_THE_GRENADINES,
            self::SAMOA,
            self::SAN_MARINO,
            self::SAO_TOME_AND_PRINCIPE,
            self::SAUDI_ARABIA,
            self::SENEGAL,
            self::SERBIA,
            self::SEYCHELLES,
            self::SIERRA_LEONE,
            self::SINGAPORE,
            self::SINT_MAARTEN_DUTCH_PART,
            self::SOLOMON_ISLANDS,
            self::SOMALIA,
            self::SOUTH_AFRICA,
            self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS,
            self::SOUTH_SUDAN,
            self::SRI_LANKA,
            self::SUDAN,
            self::SURINAME,
            self::SVALBARD_AND_JAN_MAYEN,
            self::SWAZILAND,
            self::SWITZERLAND,
            self::SYRIAN_ARAB_REPUBLIC,
            self::TAIWAN_PROVINCE_OF_CHINA,
            self::TAJIKISTAN,
            self::TANZANIA_UNITED_REPUBLIC_OF,
            self::THAILAND,
            self::TIMOR_LESTE,
            self::TOGO,
            self::TOKELAU,
            self::TONGA,
            self::TRINIDAD_AND_TOBAGO,
            self::TUNISIA,
            self::TURKEY,
            self::TURKMENISTAN,
            self::TURKS_AND_CAICOS_ISLANDS,
            self::TUVALU,
            self::UGANDA,
            self::UKRAINE,
            self::UNITED_ARAB_EMIRATES,
            self::UNITED_STATES_MINOR_OUTLYING_ISLANDS,
            self::UNITED_STATES_OF_AMERICA,
            self::URUGUAY,
            self::UZBEKISTAN,
            self::VANUATU,
            self::VENEZUELA_BOLIVARIAN_REPUBLIC_OF,
            self::VIET_NAM,
            self::VIRGIN_ISLANDS_BRITISH,
            self::VIRGIN_ISLANDS_US,
            self::WALLIS_AND_FUTUNA,
            self::WESTERN_SAHARA,
            self::YEMEN,
            self::ZAMBIA,
            self::ZIMBABWE,
            self::ERITREA,
            self::ENGLAND,
            self::WALES,
            self::SCOTLAND,
        ];
    }

    /**
     * @param mixed $key a candidate CountryCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
