<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'direct_debit_status' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class DirectDebitStatusCode
{
    const CREATED = 'C';
    const ACTIVE = 'A';
    const SUSPENDED = 'S';
    const SUBMITTED = 'SBT';
    const FAILED = 'F';
    const RE_ACTIVATED = 'R';

    /**
     * @return array of values for the type DirectDebitStatusCode
     */
    public static function getAll()
    {
        return [
            self::CREATED,
            self::ACTIVE,
            self::SUSPENDED,
            self::SUBMITTED,
            self::FAILED,
            self::RE_ACTIVATED,
        ];
    }

    /**
     * @param mixed $key a candidate DirectDebitStatusCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
