<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'emergency_reason_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class EmergencyReasonCode
{
    const SYSTEM_OUTAGE = 'SO';
    const COMMUNICATION_PROBLEM = 'CP';
    const PAYMENT_ISSUE = 'PI';
    const OTHER = 'OT';

    /**
     * @return array of values for the type EmergencyReasonCode
     */
    public static function getAll()
    {
        return [
            self::SYSTEM_OUTAGE,
            self::COMMUNICATION_PROBLEM,
            self::PAYMENT_ISSUE,
            self::OTHER,
        ];
    }

    /**
     * @param mixed $key a candidate EmergencyReasonCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
