<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'enforcement_decision_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class EnfDecisionId
{
    const NOT_APPLICABLE = 1;
    const DEFECT_MISSED = 2;
    const INCORRECT_DECISION = 3;

    /**
     * @return array of values for the type EnfDecisionId
     */
    public static function getAll()
    {
        return [
            self::NOT_APPLICABLE,
            self::DEFECT_MISSED,
            self::INCORRECT_DECISION,
        ];
    }

    /**
     * @param mixed $key a candidate EnfDecisionId value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
