<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'enforcement_decision_outcome_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class EnfDecisionOutcomeId
{
    const NO_FURTHER_ACTION = 1;
    const ADVISORY_WARNING_LETTER = 2;
    const DISCIPLINARY_ACTION_REPORT = 3;

    /**
     * @return array of values for the type EnfDecisionOutcomeId
     */
    public static function getAll()
    {
        return [
            self::NO_FURTHER_ACTION,
            self::ADVISORY_WARNING_LETTER,
            self::DISCIPLINARY_ACTION_REPORT,
        ];
    }

    /**
     * @param mixed $key a candidate EnfDecisionOutcomeId value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
