<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'enforcement_full_partial_retest_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class EnfRetestModeId
{
    const FULL = 1;
    const PARTIAL = 2;

    /**
     * @return array of values for the type EnfRetestModeId
     */
    public static function getAll()
    {
        return [
            self::FULL,
            self::PARTIAL,
        ];
    }

    /**
     * @param mixed $key a candidate EnfRetestModeId value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
