<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'enforcement_visit_outcome_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class EnfSiteVisitOutcomeId
{
    const SATISFACTORY = 1;
    const SHORTCOMINGS_FOUND = 2;
    const ABANDONED = 3;

    /**
     * @return array of values for the type EnfSiteVisitOutcomeId
     */
    public static function getAll()
    {
        return [
            self::SATISFACTORY,
            self::SHORTCOMINGS_FOUND,
            self::ABANDONED,
        ];
    }

    /**
     * @param mixed $key a candidate EnfSiteVisitOutcomeId value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
