<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'equipment_model_status' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class EquipmentModelStatusCode
{
    const APPROVED = 'APRVD';
    const NOT_INSTALLABLE = 'NINST';
    const WITHDRAWN = 'WDRWN';

    /**
     * @return array of values for the type EquipmentModelStatusCode
     */
    public static function getAll()
    {
        return [
            self::APPROVED,
            self::NOT_INSTALLABLE,
            self::WITHDRAWN,
        ];
    }

    /**
     * @param mixed $key a candidate EquipmentModelStatusCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
