<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'event_category_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class EventCategoryName
{
    const AE_EVENT = 'AE Event';
    const VTS_EVENT = 'VTS Event';
    const NT_EVENTS = 'NT Events';

    /**
     * @return array of values for the type EventCategoryName
     */
    public static function getAll()
    {
        return [
            self::AE_EVENT,
            self::VTS_EVENT,
            self::NT_EVENTS,
        ];
    }

    /**
     * @param mixed $key a candidate EventCategoryName value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
