<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'fuel_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class FuelTypeId
{
    const PETROL = 1;
    const DIESEL = 2;
    const ELECTRIC = 3;
    const STEAM = 4;
    const LPG = 5;
    const CNG = 6;
    const LNG = 7;
    const FUEL_CELLS = 8;
    const OTHER = 9;
    const GAS = 10;
    const GAS_BI_FUEL = 11;
    const HYBRID_ELECTRIC_CLEAN = 12;
    const GAS_DIESEL = 13;
    const ELECTRIC_DIESEL = 14;

    /**
     * @return array of values for the type FuelTypeId
     */
    public static function getAll()
    {
        return [
            self::PETROL,
            self::DIESEL,
            self::ELECTRIC,
            self::STEAM,
            self::LPG,
            self::CNG,
            self::LNG,
            self::FUEL_CELLS,
            self::OTHER,
            self::GAS,
            self::GAS_BI_FUEL,
            self::HYBRID_ELECTRIC_CLEAN,
            self::GAS_DIESEL,
            self::ELECTRIC_DIESEL,
        ];
    }

    /**
     * @param mixed $key a candidate FuelTypeId value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
