<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'licence_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class LicenceTypeCode
{
    const DRIVING_LICENCE = 'DRIV';

    /**
     * @return array of values for the type LicenceTypeCode
     */
    public static function getAll()
    {
        return [
            self::DRIVING_LICENCE,
        ];
    }

    /**
     * @param mixed $key a candidate LicenceTypeCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
