<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'licence_country_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class LicenceCountryCode
{
    const GREAT_BRITAIN_ENGLAND_SCOTLAND_AND_WALES = 'GB';
    const NORTHERN_IRELAND = 'NI';
    const NON_UNITED_KINGDOM = 'NU';

    /**
     * @return array of values for the type LicenceCountryCode
     */
    public static function getAll()
    {
        return [
            self::GREAT_BRITAIN_ENGLAND_SCOTLAND_AND_WALES,
            self::NORTHERN_IRELAND,
            self::NON_UNITED_KINGDOM,
        ];
    }

    /**
     * @param mixed $key a candidate LicenceCountryCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
