<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'message_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class MessageTypeCode
{
    const PASSWORD_RESET_BY_LETTER = 'PRL';
    const USERNAME_REMINDER_BY_LETTER = 'URL';
    const PASSWORD_RESET_BY_EMAIL = 'PRE';
    const USERNAME_REMINDER_BY_EMAIL = 'URE';
    const ACCOUNT_RESET_BY_LETTER = 'ARL';

    /**
     * @return array of values for the type MessageTypeCode
     */
    public static function getAll()
    {
        return [
            self::PASSWORD_RESET_BY_LETTER,
            self::USERNAME_REMINDER_BY_LETTER,
            self::PASSWORD_RESET_BY_EMAIL,
            self::USERNAME_REMINDER_BY_EMAIL,
            self::ACCOUNT_RESET_BY_LETTER,
        ];
    }

    /**
     * @param mixed $key a candidate MessageTypeCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
