<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'mot_test_status' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class MotTestStatusName
{
    const ABANDONED = 'ABANDONED';
    const ABORTED = 'ABORTED';
    const ABORTED_VE = 'ABORTED_VE';
    const ACTIVE = 'ACTIVE';
    const FAILED = 'FAILED';
    const PASSED = 'PASSED';
    const REFUSED = 'REFUSED';

    /**
     * @return array of values for the type MotTestStatusName
     */
    public static function getAll()
    {
        return [
            self::ABANDONED,
            self::ABORTED,
            self::ABORTED_VE,
            self::ACTIVE,
            self::FAILED,
            self::PASSED,
            self::REFUSED,
        ];
    }

    /**
     * @param mixed $key a candidate MotTestStatusName value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
