<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'mot_test_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class MotTestTypeCode
{
    const NORMAL_TEST = 'NT';
    const PARTIAL_RETEST_LEFT_VTS = 'PL';
    const PARTIAL_RETEST_REPAIRED_AT_VTS = 'PV';
    const TARGETED_REINSPECTION = 'ER';
    const MOT_COMPLIANCE_SURVEY = 'EC';
    const INVERTED_APPEAL = 'EI';
    const STATUTORY_APPEAL = 'ES';
    const OTHER = 'OT';
    const RE_TEST = 'RT';
    const DEMONSTRATION_TEST_FOLLOWING_TRAINING = 'DT';
    const ROUTINE_DEMONSTRATION_TEST = 'DR';
    const NON_MOT_TEST = 'EN';

    /**
     * @return array of values for the type MotTestTypeCode
     */
    public static function getAll()
    {
        return [
            self::NORMAL_TEST,
            self::PARTIAL_RETEST_LEFT_VTS,
            self::PARTIAL_RETEST_REPAIRED_AT_VTS,
            self::TARGETED_REINSPECTION,
            self::MOT_COMPLIANCE_SURVEY,
            self::INVERTED_APPEAL,
            self::STATUTORY_APPEAL,
            self::OTHER,
            self::RE_TEST,
            self::DEMONSTRATION_TEST_FOLLOWING_TRAINING,
            self::ROUTINE_DEMONSTRATION_TEST,
            self::NON_MOT_TEST,
        ];
    }

    /**
     * @param mixed $key a candidate MotTestTypeCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
