<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'mot_test_status' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class MotTestStatusCode
{
    const ABANDONED = 'ABA';
    const ABORTED = 'ABR';
    const ABORTED_VE = 'ABRVE';
    const ACTIVE = 'A';
    const FAILED = 'F';
    const PASSED = 'P';
    const REFUSED = 'R';

    /**
     * @return array of values for the type MotTestStatusCode
     */
    public static function getAll()
    {
        return [
            self::ABANDONED,
            self::ABORTED,
            self::ABORTED_VE,
            self::ACTIVE,
            self::FAILED,
            self::PASSED,
            self::REFUSED,
        ];
    }

    /**
     * @param mixed $key a candidate MotTestStatusCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
