<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'organisation_contact_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class OrganisationContactTypeCode
{
    const REGISTERED_COMPANY = 'REGC';
    const CORRESPONDENCE = 'CORR';

    /**
     * @return array of values for the type OrganisationContactTypeCode
     */
    public static function getAll()
    {
        return [
            self::REGISTERED_COMPANY,
            self::CORRESPONDENCE,
        ];
    }

    /**
     * @param mixed $key a candidate OrganisationContactTypeCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
