<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'person_auth_type_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class PersonAuthType
{
    const PIN = 'PIN';
    const CARD = 'CARD';

    /**
     * @return array of values for the type PersonAuthType
     */
    public static function getAll()
    {
        return [
            self::PIN,
            self::CARD,
        ];
    }

    /**
     * @param mixed $key a candidate PersonAuthType value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
