<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'phone_contact_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class PhoneContactTypeCode
{
    const PERSONAL = 'PERS';
    const BUSINESS = 'BUS';
    const FAX = 'FAX';

    /**
     * @return array of values for the type PhoneContactTypeCode
     */
    public static function getAll()
    {
        return [
            self::PERSONAL,
            self::BUSINESS,
            self::FAX,
        ];
    }

    /**
     * @param mixed $key a candidate PhoneContactTypeCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
