<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'mot_test_reason_for_cancel_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class ReasonForCancelId
{
    const VTSIN = 5;
    const LOCTN = 6;
    const EQUIP = 12;
    const ILLNS = 13;
    const NODOC = 14;
    const DIRTY = 15;
    const FUEL = 16;
    const LOAD = 17;
    const SIZE = 18;
    const SMOKE = 19;
    const OPEN = 20;
    const DANGR = 21;
    const DIESL = 22;
    const STAMP = 23;
    const SYSTM = 24;
    const ABORT = 25;
    const OWNER = 27;
    const ERROR = 28;
    const ERORX = 29;

    /**
     * @return array of values for the type ReasonForCancelId
     */
    public static function getAll()
    {
        return [
            self::VTSIN,
            self::LOCTN,
            self::EQUIP,
            self::ILLNS,
            self::NODOC,
            self::DIRTY,
            self::FUEL,
            self::LOAD,
            self::SIZE,
            self::SMOKE,
            self::OPEN,
            self::DANGR,
            self::DIESL,
            self::STAMP,
            self::SYSTM,
            self::ABORT,
            self::OWNER,
            self::ERROR,
            self::ERORX,
        ];
    }

    /**
     * @param mixed $key a candidate ReasonForCancelId value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
