<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'site_status_lookup' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class SiteStatusCode
{
    const APPROVED = 'AV';
    const APPLIED = 'AP';
    const RETRACTED = 'RE';
    const REJECTED = 'RJ';
    const LAPSED = 'LA';
    const EXTINCT = 'EX';

    /**
     * @return array of values for the type SiteStatusCode
     */
    public static function getAll()
    {
        return [
            self::APPROVED,
            self::APPLIED,
            self::RETRACTED,
            self::REJECTED,
            self::LAPSED,
            self::EXTINCT,
        ];
    }

    /**
     * @param mixed $key a candidate SiteStatusCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
