<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'site_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class SiteTypeCode
{
    const AREA_OFFICE = 'AO';
    const CONTRACTED_TRAINING_CENTRE = 'CTC';
    const VEHICLE_TESTING_STATION = 'VTS';
    const VEHICLE_RECORDS_OFFICE = 'VRO';
    const GOODS_VEHICLE_TESTING_STATION = 'GVTS';
    const SERVICE_DESK = 'SRVDK';
    const HEAD_OFFICE = 'HO';
    const COURSE_VENUE = 'CRSVN';
    const OFFSITE = 'OFFST';

    /**
     * @return array of values for the type SiteTypeCode
     */
    public static function getAll()
    {
        return [
            self::AREA_OFFICE,
            self::CONTRACTED_TRAINING_CENTRE,
            self::VEHICLE_TESTING_STATION,
            self::VEHICLE_RECORDS_OFFICE,
            self::GOODS_VEHICLE_TESTING_STATION,
            self::SERVICE_DESK,
            self::HEAD_OFFICE,
            self::COURSE_VENUE,
            self::OFFSITE,
        ];
    }

    /**
     * @param mixed $key a candidate SiteTypeCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
