<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'site_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class SiteTypeName
{
    const AREA_OFFICE = 'Area Office';
    const TRAINING_CENTRE = 'Training Centre';
    const VEHICLE_TESTING_STATION = 'Vehicle Testing Station';
    const VEHICLE_RECORDS_OFFICE = 'Vehicle Records Office';
    const GOODS_VEHICLE_TESTING_STATION = 'Goods Vehicle Testing Station';
    const SERVICE_DESK = 'Service Desk';
    const HEAD_OFFICE = 'Head Office';
    const COURSE_VENUE = 'Course Venue';
    const OFFSITE = 'Offsite';

    /**
     * @return array of values for the type SiteTypeName
     */
    public static function getAll()
    {
        return [
            self::AREA_OFFICE,
            self::TRAINING_CENTRE,
            self::VEHICLE_TESTING_STATION,
            self::VEHICLE_RECORDS_OFFICE,
            self::GOODS_VEHICLE_TESTING_STATION,
            self::SERVICE_DESK,
            self::HEAD_OFFICE,
            self::COURSE_VENUE,
            self::OFFSITE,
        ];
    }

    /**
     * @param mixed $key a candidate SiteTypeName value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
