<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'site_business_role' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class SiteBusinessRoleCode
{
    const TESTER = 'TESTER';
    const SITE_MANAGER = 'SITE-MANAGER';
    const SITE_ADMIN = 'SITE-ADMIN';

    /**
     * @return array of values for the type SiteBusinessRoleCode
     */
    public static function getAll()
    {
        return [
            self::TESTER,
            self::SITE_MANAGER,
            self::SITE_ADMIN,
        ];
    }

    /**
     * @param mixed $key a candidate SiteBusinessRoleCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
