<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'special_notice_audience_type' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 */
class SpecialNoticeAudienceTypeId
{
    const DVSA_AUDIENCE = 1;
    const VTS_AUDIENCE = 2;
    const TESTER_AUDIENCE = 3;

    /**
     * @return array of values for the type SpecialNoticeAudienceTypeId
     */
    public static function getAll()
    {
        return [
            self::DVSA_AUDIENCE,
            self::VTS_AUDIENCE,
            self::TESTER_AUDIENCE,
        ];
    }

    /**
     * @param mixed $key a candidate SpecialNoticeAudienceTypeId value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
