<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'vehicle_class' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class VehicleClassCode
{
    const CLASS_1 = '1';
    const CLASS_2 = '2';
    const CLASS_3 = '3';
    const CLASS_4 = '4';
    const CLASS_5 = '5';
    const CLASS_7 = '7';

    /**
     * @return array of values for the type VehicleClassCode
     */
    public static function getAll()
    {
        return [
            self::CLASS_1,
            self::CLASS_2,
            self::CLASS_3,
            self::CLASS_4,
            self::CLASS_5,
            self::CLASS_7,
        ];
    }

    /**
     * @return array of values of the type VehicleClassCode for Class 3 and above
     */
    public static function getClass3AndAbove()
    {
        return [
            self::CLASS_3,
            self::CLASS_4,
            self::CLASS_5,
            self::CLASS_7,
        ];
    }

    /**
     * @return array of values of the type VehicleClassCode for group A classes
     */
    public static function getGroupAClasses()
    {
        return [
            self::CLASS_1,
            self::CLASS_2,
        ];
    }

    /**
     * @return array of values of the type VehicleClassCode for group B classes
     */
    public static function getGroupBClasses()
    {
        return self::getClass3AndAbove();
    }

    /**
     * @param mixed $key a candidate VehicleClassCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
