<?php

namespace DvsaCommon\Enum;

/**
 * Enum class generated from the 'vehicle_class_group' table
 *
 * DO NOT EDIT! -- THIS CLASS IS GENERATED BY mot-common-web-module/generate_enums.php
 * @codeCoverageIgnore
 */
class VehicleClassGroupCode
{
    const UNKNOWN = 'UNKN';
    const BIKES = 'A';
    const CARS_ETC = 'B';

    /**
     * @return array of values for the type VehicleClassGroupCode
     */
    public static function getAll()
    {
        return [
            self::UNKNOWN,
            self::BIKES,
            self::CARS_ETC,
        ];
    }

    /**
     * @param mixed $key a candidate VehicleClassGroupCode value
     *
     * @return true if $key is in the list of known values for the type
     */
    public static function exists($key)
    {
        return in_array($key, self::getAll(), true);
    }
}
