<?php

use Dashboard\Controller\UserHomeController;
use DvsaCommon\Date\DateTimeDisplayFormat;
use DvsaCommon\Enum\AuthorisationForTestingMotStatusCode;
use DvsaCommon\UrlBuilder\PersonUrlBuilderWeb;

/**
 * @var \Dashboard\Model\PersonalDetails       $personalDetails
 * @var array                                  $motAuthorisations
 * @var \DvsaClient\Entity\TesterAuthorisation $authorisation
 */

$isAllowEdit = $this->isAllowEdit;
$motAuthorisations = $this->motAuthorisations;

$fullNameArray = array_filter([
        $personalDetails->getTitle(),
        $personalDetails->getFirstName(),
        $personalDetails->getMiddleName(),
        $personalDetails->getSurname(),
    ],
    'strlen');

$escFullName = $this->escapeHtml(implode(" ",$fullNameArray));

$fullAddressArray = array_filter([
        $personalDetails->getAddressLine1(),
        $personalDetails->getAddressLine2(),
        $personalDetails->getAddressLine3(),
        $personalDetails->getTown(),
        $personalDetails->getPostcode(),
    ],
    'strlen');
$escFullAddress = $this->escapeHtml(implode(", ", $fullAddressArray)) ?: null;

$this->layout()->setVariable('pageSubTitle', $isViewingOwnProfile ? 'Your profile' : 'Profile of');
$this->layout()->setVariable('pageTitle', $escFullName);

echo $this->partial('errorMessages', ['getFromFlash' => true]);
?>

<h3 class="heading-medium">Personal details</h3>
<table class="key-value-list">
    <tbody>
        <tr>
            <th class="key-value-list__key">
                Name
            </th>
            <td class="key-value-list__value" id="display-name">
                <?php echo $escFullName; ?>
            </td>
        </tr>
        <tr>
            <th class="key-value-list__key">
                Date of birth
            </th>
            <td class="key-value-list__value" id="dateOfBirth">
                <?php echo DateTimeDisplayFormat::textDate($personalDetails->getDateOfBirth()); ?>
            </td>
        </tr>
        <?php if (!empty ($drivingLicenceNumber) && !empty($drivingLicenceRegion)): ?>
            <tr>
                <th class="key-value-list__key">
                    Driving licence
                </th>
                <td class="key-value-list__value--numeric" id="drivingLicence">
                    <?php echo $this->escapeHtml($drivingLicence); ?>
                </td>
            </tr>
        <?php endif; ?>
        <tr>
            <th class="key-value-list__key">
                Roles
            </th>
            <td class="key-value-list__value" id="display-role">
                <?php echo $this->escapeHtml(implode(', ', $personalDetails->getRoles())); ?>
            </td>
        </tr>
    </tbody>
</table>

<h3 class="heading-medium">Contact details</h3>
<?php if ($isAllowEdit): ?>
    <a
        class="key-value-list__action"
        id="edit-user-profile"
        href="<?php echo $this->escapeHtmlAttr(PersonUrlBuilderWeb::profileEdit()); ?>">
        Change details
    </a>
<?php endif; ?>
<table class="key-value-list">
    <tbody>
        <tr>
            <th class="key-value-list__key">
                Address
            </th>
            <td class="key-value-list__value" id="full-address">
                <?php echo $escFullAddress; ?>
            </td>
        </tr>
        <tr>
            <th class="key-value-list__key">
                Email
            </th>
            <td class="key-value-list__value" id="email-address">
                <?php echo $this->escapeHtml($personalDetails->getEmail()); ?>
            </td>
        </tr>
        <tr>
            <th class="key-value-list__key">
                Telephone
            </th>
            <td class="key-value-list__value--numeric" id="telephone-number">
                <?php echo $this->escapeHtml($personalDetails->getPhoneNumber()); ?>
            </td>
        </tr>
    </tbody>
</table>

<h3 id="roles-and-associations" class="heading-medium">Roles and associations</h3>
    <table class="key-value-list">
        <tbody>
        <?php
            foreach ($rolesAndAssociations as $item):
                $escAddress = $this->escapeHtml($item["address"]);
                $escRole = $this->escapeHtml($item["role"]);
                $escId = $this->escapeHtml($item['id']);
                $escName = $this->escapeHtml($item['name']);
                ?>
                    <tr>
                        <th class="key-value-list__key">
                            <?php echo $escName; ?>
                            <?php if ($escAddress): ?>
                                <span class="key-value-list__meta"><?php echo $escAddress; ?></span>
                            <?php endif ?>
                        </th>
                        <td class="key-value-list__value" <?php echo
                            ( $escId ? ' id="role-' . $escRole . '-' .  $escId . '"' : 'id="role-' . $escRole .'"');
                        ?>><?php echo $escRole; ?></td>
                    </tr>
                <?php 
            endforeach; ?>
    </tbody>
</table>

<?php if($authorisation->hasAnyTestingAuthorisation()): ?>
    <h3 id="tester-qualification-status" class="heading-medium">Tester qualification status</h3>
    <table class="key-value-list">
        <tbody>
            <tr>
                <th class="key-value-list__key">
                    Group A
                    <span class="key-value-list__meta">Class 1, Class 2</span>
                </th>
                <td class="key-value-list__value" id="group-a-status">
                    <?php echo $authorisation->getGroupAStatus()->getName(); ?>
                </td>
            </tr>
            <tr>
                <th class="key-value-list__key">
                    Group B
                    <span class="key-value-list__meta">Class 3, Class 4, Class 5, Class 7</span>
                </th>
                <td class="key-value-list__value" id="group-b-status">
                    <?php echo $authorisation->getGroupBStatus()->getName(); ?>
                </td>
            </tr>
        </tbody>
    </table>
<?php endif; ?>

<?php if ($isAllowEdit): ?>
    <h3 class="heading-medium">Account security</h3>
    <table class="key-value-list">
        <tbody>
            <tr>
                <th class="key-value-list__key">
                    PIN
                </th>
                <td class="key-value-list__value">
                    <a href="<?php echo $this->escapeHtmlAttr(PersonUrlBuilderWeb::securityQuestions());?>" id="change-security-settings">Reset PIN</a>
                </td>
            </tr>
        </tbody>
    </table>
<?php endif; ?>

        <?php

        // if ($this->authorizationHelper()->isGranted(PermissionInSystem::MOT_CAN_ASSIGN_TESTER_PENDING_DEMO_ROLE)) :

        /** @var $motAuthorisations array */
        $personId = $personalDetails->getId();

        if (AuthorisationForTestingMotStatusCode::INITIAL_TRAINING_NEEDED === $motAuthorisations['class1']
            && AuthorisationForTestingMotStatusCode::INITIAL_TRAINING_NEEDED === $motAuthorisations['class2']
        ) : 
        ?>
        
        <h3 class="heading-medium">Initial training for class 1 and 2</h3>
        <form class="form-horizontal" method="post"
              action="<?php echo $this->escapeHtmlAttr(PersonUrlBuilderWeb::updateAuthMotTesting($personId)); ?>">
            <?php echo $this->csrfToken();

            echo $this->partial(
                'hiddenElement',
                [
                    'name'  => 'group',
                    'value' => '1',
                ]
            );

            echo $this->partial(
                'submitElement',
                [
                    'id'    => 'initial-training-successful',
                    'name'  => 'result',
                    'label' => 'Successful',
                    'cssClass' => 'button',
                    'value' => '1',

                ]
            );

            echo $this->partial(
                'submitElement',
                [
                    'id'       => 'initial-training-fail',
                    'name'     => 'result',
                    'label'    => 'Unsuccessful',
                    'cssClass' => 'button-warning',
                    'value'    => '0',

                    ]
                ); ?>
            </form>

        <?php endif; ?>

        <?php
        if (AuthorisationForTestingMotStatusCode::INITIAL_TRAINING_NEEDED === $motAuthorisations['class3']
            && AuthorisationForTestingMotStatusCode::INITIAL_TRAINING_NEEDED === $motAuthorisations['class4']
            && AuthorisationForTestingMotStatusCode::INITIAL_TRAINING_NEEDED === $motAuthorisations['class5']
            && AuthorisationForTestingMotStatusCode::INITIAL_TRAINING_NEEDED === $motAuthorisations['class7']
        ) : ?>
            
            <h3 class="heading-medium">Initial training for class 3 to 7</h3>
            <form class="form-horizontal" method="post"
                  action="<?php echo $this->escapeHtmlAttr(PersonUrlBuilderWeb::updateAuthMotTesting($personId)); ?>">
                <?php echo $this->csrfToken();

                echo $this->partial(
                    'hiddenElement',
                    [
                        'name'  => 'group',
                        'value' => '2',
                    ]
                );
                echo $this->partial(
                    'submitElement',
                    [
                        'id'    => 'initial-training-successful',
                        'name'  => 'result',
                        'label' => 'Successful',
                        'cssClass' => 'button',
                        'value' => '1',

                    ]
                );

                echo $this->partial(
                    'submitElement',
                    [
                        'id'       => 'initial-training-fail',
                        'name'     => 'result',
                        'label'    => 'Unsuccessful',
                        'cssClass' => 'button-warning',
                        'value'    => '0',
                    ]
                ); ?>
            </form>

    <?php endif; ?>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a href="<?php echo $this->escapeHtmlAttr($this->url(UserHomeController::ROUTE));?>">Return Home</a>
        </li>
    </ul>
</nav>

