<?php

use Dashboard\Controller\UserHomeController;
use DvsaCommon\Date\DateTimeDisplayFormat;
use DvsaCommon\Enum\AuthorisationForTestingMotStatusCode;
use DvsaCommon\UrlBuilder\PersonUrlBuilderWeb;

/**
 * @var \Dashboard\Model\PersonalDetails       $personalDetails
 * @var array                                  $motAuthorisations
 * @var \DvsaClient\Entity\TesterAuthorisation $authorisation
 */

$isAllowEdit = $this->isAllowEdit;
$motAuthorisations = $this->motAuthorisations;

$fullAddressArray = array_filter([
        $personalDetails->getAddressLine1(),
        $personalDetails->getAddressLine2(),
        $personalDetails->getAddressLine3(),
        $personalDetails->getTown(),
        $personalDetails->getPostcode(),
    ],
    'strlen');
$escFullAddress = $this->escapeHtml(implode(", ", $fullAddressArray)) ?: null;

$this->layout()->setVariable('pageSubTitle', $isViewingOwnProfile ? 'Your profile' : 'Profile of');
$this->layout()->setVariable('pageTitle', $personalDetails->getFullName());

echo $this->partial('errorMessages', ['getFromFlash' => true]);

echo $this->partial('partial/gds/general/system-message', ['messages' =>  $this->layout()->flashMessenger->getSuccessMessages(), 'type' => 'success']);
?>

<h3 class="heading-medium">Personal details</h3>
<table class="key-value-list">
    <tbody>
        <?php if($canViewUsername): ?>
            <tr>
                <th class="key-value-list__key">
                    Username
                </th>
                <td class="key-value-list__value" id="display-username">
                    <?php echo $this->escapeHtml($personalDetails->getUsername()); ?>
                </td>
            </tr>
        <?php endif; ?>
        <tr>
            <th class="key-value-list__key">
                Name
            </th>
            <td class="key-value-list__value" id="display-name">
                <?php echo $this->escapeHtml($personalDetails->getFullName()); ?>
            </td>
        </tr>
        <tr>
            <th class="key-value-list__key">
                Date of birth
            </th>
            <td class="key-value-list__value" id="dateOfBirth">
                <?php echo DateTimeDisplayFormat::textDate($personalDetails->getDateOfBirth()); ?>
            </td>
        </tr>
        <?php if (!empty ($drivingLicenceNumber) && !empty($drivingLicenceRegion)): ?>
            <tr>
                <th class="key-value-list__key">
                    Driving licence
                </th>
                <td class="key-value-list__value--numeric" id="drivingLicence">
                    <?php echo $this->escapeHtml($drivingLicence); ?>
                </td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<h3 class="heading-medium">Contact details</h3>
<?php if ($isAllowEdit): ?>
    <a
        class="key-value-list__action"
        id="edit-user-profile"
        href="<?php echo $this->escapeHtmlAttr(PersonUrlBuilderWeb::profileEdit()); ?>">
        Change details
    </a>
<?php endif; ?>
<table class="key-value-list">
    <tbody>
        <tr>
            <th class="key-value-list__key">
                Address
            </th>
            <td class="key-value-list__value" id="full-address">
                <?php echo $escFullAddress; ?>
            </td>
        </tr>
        <tr>
            <th class="key-value-list__key">
                Email
            </th>
            <td class="key-value-list__value" id="email-address">
                <?php echo $this->escapeHtml($personalDetails->getEmail()); ?>
            </td>
        </tr>
        <tr>
            <th class="key-value-list__key">
                Telephone
            </th>
            <td class="key-value-list__value--numeric" id="telephone-number">
                <?php echo $this->escapeHtml($personalDetails->getPhoneNumber()); ?>
            </td>
        </tr>
    </tbody>
</table>

<?php if ($systemRoles) : ?>
    <h3 id="roles-internal" class="heading-medium"><?php echo($this->escapeHtml("Roles")); ?></h3>
    <?php echo $this->partial('dashboard/partials/profile/system-roles.phtml', [ 'roles' => $systemRoles]) ?>
<?php endif; ?>

<?php if(!$rolesAndAssociations && !$systemRoles) : ?>
    <h3 id="roles" class="heading-medium">Roles</h3>
    <div class="text">
        <p>No roles assigned</p>
    </div>
<?php endif; ?>


<?php if($authorisation->hasAnyTestingAuthorisation()) : ?>
    <h3 id="tester-qualification-status" class="heading-medium">Tester qualification status</h3>
    <table class="key-value-list">
        <tbody>
            <tr>
                <th class="key-value-list__key">
                    Group A
                    <span class="key-value-list__meta">Class 1, Class 2</span>
                </th>
                <td class="key-value-list__value" id="group-a-status">
                    <?php echo $authorisation->getGroupAStatus()->getName(); ?>
                </td>
            </tr>
            <tr>
                <th class="key-value-list__key">
                    Group B
                    <span class="key-value-list__meta">Class 3, Class 4, Class 5, Class 7</span>
                </th>
                <td class="key-value-list__value" id="group-b-status">
                    <?php echo $authorisation->getGroupBStatus()->getName(); ?>
                </td>
            </tr>
        </tbody>
    </table>
<?php endif; ?>

<?php if ($isAllowEdit): ?>
    <h3 class="heading-medium">Account security</h3>
    <table class="key-value-list">
        <tbody>
            <tr>
                <th class="key-value-list__key">
                    Password
                </th>
                <td class="key-value-list__value">
                    <a href="<?php echo $this->url('user-home/profile/change-password') ?>" id="change-password">Change your password</a>
                </td>
            </tr>
            <tr>
                <th class="key-value-list__key">
                    PIN
                </th>
                <td class="key-value-list__value">
                    <a href="<?php echo $this->escapeHtmlAttr(PersonUrlBuilderWeb::securityQuestions());?>" id="change-security-settings">Reset PIN</a>
                </td>
            </tr>
        </tbody>
    </table>
<?php endif; ?>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a href="<?php echo $this->escapeHtmlAttr($this->url(UserHomeController::ROUTE));?>">Return Home</a>
        </li>
    </ul>
</nav>

