<?php

use Dashboard\Controller\NotificationController;

    $this->placeholder('hero')
        ->set($this->partial('primaryAction/' . $dashboard->getHero(), ['dashboard' => $dashboard]));
?>

<?php echo $this->partial('errorMessages', ['getFromFlash' => true]); ?>

<div class="row">
    <div class="col-sm-6">
        <?php echo $this->partial('dashboard/specialNotice', $specialNotice); ?>
        <?php if ($dashboard->getHero() != 'vehicle-examiner'): ?>
            <?php echo $this->partial(
                'notification/list',
                [
                    'notifications' => $dashboard->getNotifications(),
                    'limit'         => NotificationController::SHORT_LIST_LIMIT
                ]
            );
            ?>
        <?php endif; ?>

    </div>
    <div class="col-sm-6">
        <?php if ($dashboard->getHero() == 'vehicle-examiner'): ?>
            <?php echo $this->partial('dashboard/veList'); ?>

        <?php else: ?>
            <?php if ($this->authorisationHelper()->isGranted(\DvsaCommon\Auth\PermissionInSystem::VEHICLE_TESTING_STATION_LIST)) : ?>
                <?php echo $this->partial('dashboard/vtsList'); ?>
            <?php endif; ?>
            <?php if ($this->authorisationHelper()->isGranted(\DvsaCommon\Auth\PermissionInSystem::DISPLAY_DVSA_ADMIN_BOX)) : ?>
                <?php echo $this->partial('dashboard/dvsaAdminBox'); ?>
            <?php endif; ?>

            <?php if ($dashboard->getHero() == 'finance'): ?>
                <?php echo $this->partial('dashboard/financeBox'); ?>
            <?php endif; ?>

            <section class="module-pivot-panel" id="ae-vts-list">
                <header class="pivot-panel_header">
                    <h2 class="pivot-panel_title">Roles</h2>
                </header>
                <p>You have the following roles</p>
                <ul>
                    <li id="display-role">
                        <?php echo $this->escapeHtml(
                            implode(', ', $personalDetails->getRoles())
                        ); ?>
                    </li>
                </ul>
            </section>

            <?php if ($this->authorisationHelper()->isGranted(\DvsaCommon\Auth\PermissionInSystem::DISPLAY_TESTER_STATS_BOX)) : ?>
                <?php echo $this->partial('dashboard/testerStatsBox'); ?>
            <?php endif; ?>
            <?php if ($this->authorisationHelper()->isGranted(\DvsaCommon\Auth\PermissionInSystem::DISPLAY_TESTER_CONTINGENCY_BOX)) : ?>
                <?php echo $this->partial('dashboard/testerContingencyBox'); ?>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
