<?php

use Dashboard\Controller\NotificationController;
use DvsaCommon\Auth\PermissionInSystem;
use DvsaCommon\Auth\PermissionAtSite;

    $this->placeholder('hero')
        ->set($this->partial('primaryAction/' . $dashboard->getHero(), ['dashboard' => $dashboard, 'canPerformTest' => $canPerformTest]));
?>

<?php echo $this->partial('errorMessages', ['getFromFlash' => true]); ?>

<div class="row">
    <div class="col-sm-6">
        <?php echo $this->partial('dashboard/specialNotice', $specialNotice); ?>
            <?php echo $this->partial(
                'notification/list',
                [
                    'notifications' => $dashboard->getNotifications(),
                    'limit'         => NotificationController::SHORT_LIST_LIMIT
                ]
            );
            ?>
    </div>
    <div class="col-sm-6">
        <?php if ($dashboard->getHero() === 'vehicle-examiner'): ?>
            <?php echo $this->partial('dashboard/veList'); ?>
        <?php endif; ?>

        <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::VEHICLE_TESTING_STATION_LIST)): ?>
            <?php echo $this->partial('dashboard/vtsList'); ?>
        <?php endif; ?>
        <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::DISPLAY_DVSA_ADMIN_BOX)): ?>
            <?php echo $this->partial('dashboard/dvsaAdminBox'); ?>
        <?php endif; ?>

        <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::SLOTS_REPORTS_GENERATE)): ?>
            <?php echo $this->partial('dashboard/financeBox'); ?>
        <?php endif; ?>

        <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::DISPLAY_TESTER_STATS_BOX)) : ?>
            <?php echo $this->partial('dashboard/testerStatsBox'); ?>
        <?php endif; ?>

        <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::MOT_DEMO_TEST_PERFORM)) : ?>
            <?php echo $this->partial('dashboard/trainingTestBox',
                [
                    'hasInProgressTrainingTest' => $dashboard->hasDemoTestInProgress(),
                    'inProgressTrainingTestNumber' => $dashboard->getInProgressDemoTestNumber()
                ]
            ); ?>
        <?php endif; ?>

        <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::DISPLAY_TESTER_CONTINGENCY_BOX)) : ?>
            <?php echo $this->partial('dashboard/testerContingencyBox'); ?>
        <?php endif; ?>
    </div>
</div>


<script>
    /* #VM-10326 */
    window.onload = function () {
        if (typeof ga === 'function') {
            ga('send', 'pageview', {
                'page': '/',
                'title': 'user home'
            });
        }
    };
</script>
