<h3>User Details</h3>
<p>Information about a system user.</p>

<dl class="dl-horizontal">
    <dt>ID</dt>
    <dd><?php echo $this->escapeHtml($this->user->getId()); ?></dd>

    <dt>Username</dt>
    <dd><?php echo $this->escapeHtml($this->user->getUsername()); ?></dd>

    <dt>Display Name</dt>
    <dd><?php echo $this->escapeHtml($this->user->getFullName()); ?></dd>

    <dt>Display Role</dt>
    <dd></dd>

</dl>

<?php
// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('user_admin/update', ['userid' => $this->user->getId()]));
$form->setAttribute('class', 'form-horizontal');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

?>
<?php
/*
<div>
    <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
            <?php
            $roles = $form->get('roles');
            echo $this->formMultiCheckbox($roles);
            ?>
        </div>
        <div class="form-groupx">
            <?php echo $this->formSubmit($form->get('send')) ?>
        </div>
    </form>
</div>
*/
?>