-- VM-9671
-- Updated schema in vehicle and dvla_vehicle tables needs to be reflected
-- in history tables.

alter table `vehicle_hist`
add column `registration_collapsed` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT 'registration/VRM with special characters removed by trigger' AFTER `registration`,
add column `vin_collapsed` varchar(30) CHARACTER SET latin1 DEFAULT NULL COMMENT 'vin with special characters removed by trigger' AFTER `vin`,
add column `vin_collapsed_reversed` varchar(30) CHARACTER SET latin1 DEFAULT NULL COMMENT 'vin with special characters removed and reversed by trigger' AFTER `vin_collapsed`,
add index `in_vehicle_hist_registration_collapsed` (`registration_collapsed` ASC),
add index `in_vehicle_hist_vin_collapsed` (`vin_collapsed` ASC),
add index `in_vehicle_hist_vin_collapsed_reversed` (`vin_collapsed_reversed` ASC)
;

alter table `dvla_vehicle_hist`
add column `registration_collapsed` varchar(13) CHARACTER SET latin1 DEFAULT NULL COMMENT 'registration/VRM with special characters removed by trigger' AFTER `registration`,
add column `vin_collapsed` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT 'vin with special characters removed by trigger' AFTER `vin`,
add column `vin_collapsed_reversed` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT 'vin with special characters removed and reversed by trigger' AFTER `vin_collapsed`
;

-- Update history table triggers
DROP TRIGGER `tr_dvla_vehicle_au`;

CREATE TRIGGER `tr_dvla_vehicle_au` AFTER UPDATE ON `dvla_vehicle`
FOR EACH ROW INSERT INTO `dvla_vehicle_hist`
  (
    `id`,
    `registration`,
    `registration_collapsed`,
    `registration_validation_character`,
    `vin`,
    `vin_collapsed`,
    `vin_collapsed_reversed`,
    `model_code`,
    `make_code`,
    `make_in_full`,
    `colour_1_code`,
    `colour_2_code`,
    `propulsion_code`,
    `designed_gross_weight`,
    `unladen_weight`,
    `engine_number`,
    `engine_capacity`,
    `seating_capacity`,
    `manufacture_date`,
    `first_registration_date`,
    `is_seriously_damaged`,
    `recent_v5_document_number`,
    `is_vehicle_new_at_first_registration`,
    `body_type_code`,
    `wheelplan_code`,
    `sva_emission_standard`,
    `ct_related_mark`,
    `vehicle_id`,
    `dvla_vehicle_id`,
    `eu_classification`,
    `mass_in_service_weight`,
    `mot1_legacy_id`,
    `created_by`,
    `created_on`,
    `last_updated_by`,
    `last_updated_on`,
    `version`,
    `batch_number`
  )
VALUES
  (
    OLD.`id`,
    OLD.`registration`,
    OLD.`registration_collapsed`,
    OLD.`registration_validation_character`,
    OLD.`vin`,
    OLD.`vin_collapsed`,
    OLD.`vin_collapsed_reversed`,
    OLD.`model_code`,
    OLD.`make_code`,
    OLD.`make_in_full`,
    OLD.`colour_1_code`,
    OLD.`colour_2_code`,
    OLD.`propulsion_code`,
    OLD.`designed_gross_weight`,
    OLD.`unladen_weight`,
    OLD.`engine_number`,
    OLD.`engine_capacity`,
    OLD.`seating_capacity`,
    OLD.`manufacture_date`,
    OLD.`first_registration_date`,
    OLD.`is_seriously_damaged`,
    OLD.`recent_v5_document_number`,
    OLD.`is_vehicle_new_at_first_registration`,
    OLD.`body_type_code`,
    OLD.`wheelplan_code`,
    OLD.`sva_emission_standard`,
    OLD.`ct_related_mark`,
    OLD.`vehicle_id`,
    OLD.`dvla_vehicle_id`,
    OLD.`eu_classification`,
    OLD.`mass_in_service_weight`,
    OLD.`mot1_legacy_id`,
    OLD.`created_by`,
    OLD.`created_on`,
    OLD.`last_updated_by`,
    OLD.`last_updated_on`,
    OLD.`version`,
    OLD.`batch_number`
  );

DROP TRIGGER `tr_dvla_vehicle_ad`;

CREATE TRIGGER `tr_dvla_vehicle_ad` AFTER DELETE ON `dvla_vehicle`
FOR EACH ROW INSERT INTO `dvla_vehicle_hist`
  (
    `id`,
    `registration`,
    `registration_collapsed`,
    `registration_validation_character`,
    `vin`,
    `vin_collapsed`,
    `vin_collapsed_reversed`,
    `model_code`,
    `make_code`,
    `make_in_full`,
    `colour_1_code`,
    `colour_2_code`,
    `propulsion_code`,
    `designed_gross_weight`,
    `unladen_weight`,
    `engine_number`,
    `engine_capacity`,
    `seating_capacity`,
    `manufacture_date`,
    `first_registration_date`,
    `is_seriously_damaged`,
    `recent_v5_document_number`,
    `is_vehicle_new_at_first_registration`,
    `body_type_code`,
    `wheelplan_code`,
    `sva_emission_standard`,
    `ct_related_mark`,
    `vehicle_id`,
    `dvla_vehicle_id`,
    `eu_classification`,
    `mass_in_service_weight`,
    `mot1_legacy_id`,
    `created_by`,
    `created_on`,
    `last_updated_by`,
    `last_updated_on`,
    `version`,
    `batch_number`
  )
VALUES
  (
    OLD.`id`,
    OLD.`registration`,
    OLD.`registration_collapsed`,
    OLD.`registration_validation_character`,
    OLD.`vin`,
    OLD.`vin_collapsed`,
    OLD.`vin_collapsed_reversed`,
    OLD.`model_code`,
    OLD.`make_code`,
    OLD.`make_in_full`,
    OLD.`colour_1_code`,
    OLD.`colour_2_code`,
    OLD.`propulsion_code`,
    OLD.`designed_gross_weight`,
    OLD.`unladen_weight`,
    OLD.`engine_number`,
    OLD.`engine_capacity`,
    OLD.`seating_capacity`,
    OLD.`manufacture_date`,
    OLD.`first_registration_date`,
    OLD.`is_seriously_damaged`,
    OLD.`recent_v5_document_number`,
    OLD.`is_vehicle_new_at_first_registration`,
    OLD.`body_type_code`,
    OLD.`wheelplan_code`,
    OLD.`sva_emission_standard`,
    OLD.`ct_related_mark`,
    OLD.`vehicle_id`,
    OLD.`dvla_vehicle_id`,
    OLD.`eu_classification`,
    OLD.`mass_in_service_weight`,
    OLD.`mot1_legacy_id`,
    OLD.`created_by`,
    OLD.`created_on`,
    OLD.`last_updated_by`,
    OLD.`last_updated_on`,
    OLD.`version`,
    OLD.`batch_number`
  );

DROP TRIGGER `tr_vehicle_au`;

CREATE TRIGGER `tr_vehicle_au` AFTER UPDATE ON `vehicle`
FOR EACH ROW INSERT INTO  `vehicle_hist`
  (
    `id`,
    `registration`,
    `registration_collapsed`,
    `empty_vrm_reason_id`,
    `vin`,
    `vin_collapsed`,
    `vin_collapsed_reversed`,
    `empty_vin_reason_id`,
    `vehicle_class_id`,
    `make_id`,
    `model_id`,
    `model_detail_id`,
    `body_type_id`,
    `year`,
    `make_name`,
    `model_name`,
    `model_detail_name`,
    `manufacture_date`,
    `first_registration_date`,
    `first_used_date`,
    `primary_colour_id`,
    `secondary_colour_id`,
    `fuel_type_id`,
    `wheelplan_type_id`,
    `seating_capacity`,
    `no_of_seat_belts`,
    `seat_belts_last_checked`,
    `weight`,
    `weight_source_id`,
    `country_of_registration_id`,
    `cylinder_capacity`,
    `transmission_type_id`,
    `sva_emission_std`,
    `engine_number`,
    `chassis_number`,
    `is_new_at_first_reg`,
    `eu_classification`,
    `mass_in_service_weight`,
    `dvla_vehicle_id`,
    `is_damaged`,
    `is_destroyed`,
    `is_incognito`,
    `mot1_legacy_id`,
    `created_by`,
    `created_on`,
    `last_updated_by`,
    `last_updated_on`,
    `version`,
    `batch_number`
  )
VALUES
  (
    OLD.`id`,
    OLD.`registration`,
    OLD.`registration_collapsed`,
    OLD.`empty_vrm_reason_id`,
    OLD.`vin`,
    OLD.`vin_collapsed`,
    OLD.`vin_collapsed_reversed`,
    OLD.`empty_vin_reason_id`,
    OLD.`vehicle_class_id`,
    OLD.`make_id`,
    OLD.`model_id`,
    OLD.`model_detail_id`,
    OLD.`body_type_id`,
    OLD.`year`,
    OLD.`make_name`,
    OLD.`model_name`,
    OLD.`model_detail_name`,
    OLD.`manufacture_date`,
    OLD.`first_registration_date`,
    OLD.`first_used_date`,
    OLD.`primary_colour_id`,
    OLD.`secondary_colour_id`,
    OLD.`fuel_type_id`,
    OLD.`wheelplan_type_id`,
    OLD.`seating_capacity`,
    OLD.`no_of_seat_belts`,
    OLD.`seat_belts_last_checked`,
    OLD.`weight`,
    OLD.`weight_source_id`,
    OLD.`country_of_registration_id`,
    OLD.`cylinder_capacity`,
    OLD.`transmission_type_id`,
    OLD.`sva_emission_std`,
    OLD.`engine_number`,
    OLD.`chassis_number`,
    OLD.`is_new_at_first_reg`,
    OLD.`eu_classification`,
    OLD.`mass_in_service_weight`,
    OLD.`dvla_vehicle_id`,
    OLD.`is_damaged`,
    OLD.`is_destroyed`,
    OLD.`is_incognito`,
    OLD.`mot1_legacy_id`,
    OLD.`created_by`,
    OLD.`created_on`,
    OLD.`last_updated_by`,
    OLD.`last_updated_on`,
    OLD.`version`,
    OLD.`batch_number`
  );

DROP TRIGGER `tr_vehicle_ad`;

CREATE TRIGGER `tr_vehicle_ad` AFTER DELETE ON `vehicle`
FOR EACH ROW INSERT INTO  `vehicle_hist`
  (
    `id`,
    `registration`,
    `registration_collapsed`,
    `empty_vrm_reason_id`,
    `vin`,
    `vin_collapsed`,
    `vin_collapsed_reversed`,
    `empty_vin_reason_id`,
    `vehicle_class_id`,
    `make_id`,
    `model_id`,
    `model_detail_id`,
    `body_type_id`,
    `year`,
    `make_name`,
    `model_name`,
    `model_detail_name`,
    `manufacture_date`,
    `first_registration_date`,
    `first_used_date`,
    `primary_colour_id`,
    `secondary_colour_id`,
    `fuel_type_id`,
    `wheelplan_type_id`,
    `seating_capacity`,
    `no_of_seat_belts`,
    `seat_belts_last_checked`,
    `weight`,
    `weight_source_id`,
    `country_of_registration_id`,
    `cylinder_capacity`,
    `transmission_type_id`,
    `sva_emission_std`,
    `engine_number`,
    `chassis_number`,
    `is_new_at_first_reg`,
    `eu_classification`,
    `mass_in_service_weight`,
    `dvla_vehicle_id`,
    `is_damaged`,
    `is_destroyed`,
    `is_incognito`,
    `mot1_legacy_id`,
    `created_by`,
    `created_on`,
    `last_updated_by`,
    `last_updated_on`,
    `version`,
    `batch_number`
  )
VALUES
  (
    OLD.`id`,
    OLD.`registration`,
    OLD.`registration_collapsed`,
    OLD.`empty_vrm_reason_id`,
    OLD.`vin`,
    OLD.`vin_collapsed`,
    OLD.`vin_collapsed_reversed`,
    OLD.`empty_vin_reason_id`,
    OLD.`vehicle_class_id`,
    OLD.`make_id`,
    OLD.`model_id`,
    OLD.`model_detail_id`,
    OLD.`body_type_id`,
    OLD.`year`,
    OLD.`make_name`,
    OLD.`model_name`,
    OLD.`model_detail_name`,
    OLD.`manufacture_date`,
    OLD.`first_registration_date`,
    OLD.`first_used_date`,
    OLD.`primary_colour_id`,
    OLD.`secondary_colour_id`,
    OLD.`fuel_type_id`,
    OLD.`wheelplan_type_id`,
    OLD.`seating_capacity`,
    OLD.`no_of_seat_belts`,
    OLD.`seat_belts_last_checked`,
    OLD.`weight`,
    OLD.`weight_source_id`,
    OLD.`country_of_registration_id`,
    OLD.`cylinder_capacity`,
    OLD.`transmission_type_id`,
    OLD.`sva_emission_std`,
    OLD.`engine_number`,
    OLD.`chassis_number`,
    OLD.`is_new_at_first_reg`,
    OLD.`eu_classification`,
    OLD.`mass_in_service_weight`,
    OLD.`dvla_vehicle_id`,
    OLD.`is_damaged`,
    OLD.`is_destroyed`,
    OLD.`is_incognito`,
    OLD.`mot1_legacy_id`,
    OLD.`created_by`,
    OLD.`created_on`,
    OLD.`last_updated_by`,
    OLD.`last_updated_on`,
    OLD.`version`,
    OLD.`batch_number`
  );

-- UPDATE fields using triggers
UPDATE `vehicle` SET `registration`=`registration`;
UPDATE `dvla_vehicle` SET `registration`=`registration`;