<?php
use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;

?>

<div class="text">
    <p class="lede">Please check that the details below are correct.</p>
</div>

<h2 class="heading-medium">Your details</h2>

<table class="key-value-list">
    <caption class="visuallyhidden">Summary of your details</caption>
    <tbody>
    <tr>
        <th scope="col" class="key-value-list__key">
            Email address
        </th>
        <td id="emailAddress" scope="col" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($emailAddress) ?>
        </td>
        <td scope="col" class="key-value-list__item-action">
            <a id="change-email" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->emailStep());?>">Change<span class="visuallyhidden"> email address</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Name
        </th>
        <td id="displayName" scope="col" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($displayName) ?>
        </td>
        <td scope="col" class="key-value-list__item-action">
            <a id="change-name" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->detailsStep());?>">Change<span class="visuallyhidden"> name</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Telephone number
        </th>
        <td id="phone" scope="col" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($phone) ?>
        </td>
        <td scope="col" class="key-value-list__item-action">
            <a id="change-phone" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->detailsStep());?>">Change<span class="visuallyhidden"> telephone number</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Address
        </th>
        <td id="address" scope="col" class="key-value-list__value">
            <?php
                if (is_array($address) && count($address)) {
                    foreach ($address as $key => $value) {
                        echo $this->escapeHtmlAttr($value)."<br/>";
                    }
                }
            ?>
        </td>
        <td scope="col" class="key-value-list__item-action">
            <a id="change-address" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->addressStep());?>">Change<span class="visuallyhidden"> address</span></a>
        </td>
    </tr>
    </tbody>
</table>

<h2 class="heading-medium">Your account security</h2>

<table class="key-value-list">
    <caption class="visuallyhidden">Summary of your details</caption>
    <tbody>
    <tr>
        <th scope="col" class="key-value-list__key">
            First security question
        </th>
        <td id="firstQuestion" scope="col" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($firstQuestion) ?>
            <br>
            <span id="answer1Obfuscated" class="masked-text"><?php echo $answer1Obfuscated ?></span>
        </td>
        <td scope="col" class="key-value-list__item-action">
            <a id="change-security-one" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->securityQuestionStepOne());?>">Change<span class="visuallyhidden"> first security question</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Second security question
        </th>
        <td id="secondQuestion" scope="col" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($secondQuestion) ?>
            <br>
            <span id="answer2Obfuscated" class="masked-text"><?php echo $answer2Obfuscated ?></span>
        </td>
        <td scope="col" class="key-value-list__item-action">
            <a id="change-security-two" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->securityQuestionStepTwo());?>">Change<span class="visuallyhidden"> second security question</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Password
        </th>
        <td id="passwordObfuscated" scope="col" class="key-value-list__value">
            <span class="masked-text"><?php echo $passwordObfuscated ?></span>
        </td>
        <td scope="col" class="key-value-list__item-action">
            <a id="change-password" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->passwordStep());?>">Change<span class="visuallyhidden"> password</span></a>
        </td>
    </tr>
    </tbody>
</table>

<form action="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->summaryStep());?>" method="POST">
    <?php echo $this->csrfToken(); ?>
    <nav class="content-navigation<?php echo $emailIsDuplicated != '' ? '--notice' : ''; ?>" <?php echo $emailIsDuplicated != '' ? 'id="duplicatedEmailAddress"' : ''; ?>>

        <?php if ($emailIsDuplicated): ?>

            <h3 class="content-navigation__heading"><?php echo $this->escapeHtmlAttr($emailAddress) ?> is used by another account</h3>
            <p>Using the same email address on multiple accounts is not recommended. If you're having problems signing in, you should:</p>
            <ul id="duplicateEmailResolutions" class="list-bullet">
                <li><a href="/forgotten-password">Reset your password</a> if you've forgotten your password</li>
                <li>Call <strong><?php echo $helpDesk['name'] ?></strong> on <strong><?php echo $helpDesk['phoneNumber'] ?></strong> if you've forgotten your username</li>
                <li>Check your SPAM folder if you've created an account but not received your username by email</li>
            </ul>

        <?php endif; ?>

        <input type="submit" value="Create your account" id="continue" class="button">

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->passwordStep());?>" id="back">Back</a>
            </li>
        </ul>

    </nav>
</form>