<?php
use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;

?>

<div class="text">
    <p class="lede">Check that the information is correct before you create your account.</p>
</div>

<h2 class="heading-medium">Your details</h2>

<table class="key-value-list">
    <caption class="visuallyhidden">Summary of your details</caption>
    <tbody>
    <tr>
        <th scope="col" class="key-value-list__key">
            Email address
        </th>
        <td id="emailAddress" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($emailAddress) ?>
        </td>
        <td class="key-value-list__item-action">
            <a id="change-email" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->emailStep()); ?>">Change<span class="visuallyhidden"> email address</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Name
        </th>
        <td id="displayName" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($displayName) ?>
        </td>
        <td class="key-value-list__item-action">
            <a id="change-name" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->detailsStep()); ?>">Change<span class="visuallyhidden"> name</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Date of birth
        </th>
        <td id="date-of-birth" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($dateOfBirth); ?>
        </td>
        <td class="key-value-list__item-action">
            <a id="change-phone" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->detailsStep()); ?>">Change<span class="visuallyhidden"> date of birth</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Address
        </th>
        <td id="address" class="key-value-list__value">
            <?php
                if (is_array($address) && count($address)) {
                    foreach ($address as $key => $value) {
                        echo $this->escapeHtmlAttr($value).'<br/>';
                    }
                }
            ?>
        </td>
        <td class="key-value-list__item-action">
            <a id="change-address" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->contactDetailsStep()); ?>">Change<span class="visuallyhidden"> address</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Phone number
        </th>
        <td id="phone" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($phone) ?>
        </td>
        <td class="key-value-list__item-action">
            <a id="change-phone" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->contactDetailsStep()); ?>">Change<span class="visuallyhidden"> phone number</span></a>
        </td>
    </tr>
    </tbody>
</table>

<h2 class="heading-medium">Your account security</h2>

<table class="key-value-list">
    <caption class="visuallyhidden">Summary of your details</caption>
    <tbody>
    <tr>
        <th scope="col" class="key-value-list__key">
            First security question
        </th>
        <td id="firstQuestion" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($firstQuestion) ?>
            <br>
            <span id="securityQuestionOneAnswer" class="font-small"><?php echo $this->escapeHtml($securityQuestionOneAnswer)  ?></span>
        </td>
        <td class="key-value-list__item-action">
            <a id="change-security-one" href="<?php echo $this->escapeHtmlAttr($this->url('account-register/security-questions')); ?>">Change<span class="visuallyhidden"> first security question</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Second security question
        </th>
        <td id="secondQuestion" class="key-value-list__value">
            <?php echo $this->escapeHtmlAttr($secondQuestion) ?>
            <br>
            <span id="securityQuestionTwoAnswer" class="font-small"><?php echo $this->escapeHtml($securityQuestionTwoAnswer) ?></span>
        </td>
        <td class="key-value-list__item-action">
            <a id="change-security-two" href="<?php echo $this->escapeHtmlAttr($this->url('account-register/security-questions')); ?>">Change<span class="visuallyhidden"> second security question</span></a>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Password
        </th>
        <td id="passwordObfuscated" class="key-value-list__value">
            <span class="masked-text"><?php echo $passwordObfuscated ?></span>
        </td>
        <td class="key-value-list__item-action">
            <a id="change-password" href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->passwordStep()); ?>">Change<span class="visuallyhidden"> password</span></a>
        </td>
    </tr>
    </tbody>
</table>

<form action="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->summaryStep()); ?>" method="POST">
    <?php echo $this->csrfToken(); ?>
    <nav class="content-navigation">
        <input type="submit" value="Create your account" id="continue" class="button">
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->passwordStep()); ?>" id="back">Back</a>
            </li>
        </ul>
    </nav>
</form>