<?php
/**
 * @var \DashBoard\ViewModel\RemoveRoleViewModel
 */
?>

<div class="text">
    <p class="lede">
        Are you sure you want to remove the role of
        <strong><?php echo $this->escapeHtml($viewModel->getRoleName()); ?></strong>
        at
        <strong><?php echo $this->escapeHtml($viewModel->getEntityName()); ?></strong>?
    </p>
</div>

<form action="<?php
echo $this->url(null, [
    'id' => $viewModel->getPersonId(),
    'positionId' => $viewModel->getPositionId(),
    'entityId' => $viewModel->getEntityId(), ]
);
?>" method="post">
    <?php echo $this->csrfToken(); ?>
    <nav class="content-navigation">

        <input type="submit" name="submit" id="confirm" class="button" value="Remove role">

        <ul class="content-navigation__secondary">
            <li>
                <a id="cancel-and-return-to-profile" href="<?php
                    echo $this->personProfileUrl()->fromPersonProfile('trade-roles'); ?>">
                    Cancel and return to roles and associations
                </a>
            </li>
        </ul>
    </nav>
</form>
