<h1>Duplicate or replacement certificate</h1>

<?php

use DvsaMotTest\Controller\VehicleSearchController;

/** @var DvsaCommon\Dto\Vehicle\History\VehicleHistoryDto $vehicleHistory */

echo $this->partial('errorMessages', ['getFromFlash' => true]);
echo $this->partial('vehicleSummary', ['vehicle' => $this->vehicle]);
?>
<div class="row">
<?php
echo $this->partial(
    'vehicle/history',
    [
        'vehicleHistory' => $vehicleHistory,
        'isDvsaUser'     => true,
        'isManySites'    => true,
    ]
);
?>

    <nav class="col-sm-8 module-content-navigation">
        <ul class="content-navigation_secondary">
            <li>
                <a href="<?php echo $this->url(
                    VehicleSearchController::ROUTE_REPLACEMENT_CERTIFICATE_VEHICLE_SEARCH,
                    [],
                    ['query' => ['vin'=>$this->vin, 'registration'=>$this->registration]]); ?>" id="return_to_replacement_search">
                    Return to duplicate or replacement certificate - search
                </a>
            </li>
        </ul>
    </nav>
</div>
