<?php
use DvsaMotTest\Controller\VehicleSearchController;

?>

<h1>Duplicate or replacement certificate</h1>

<?php
/** @var DvsaCommon\Dto\Vehicle\History\VehicleHistoryDto $vehicleHistory */
echo $this->partial('errorMessages', [
    'getFromFlash' => true,
    'errorTitle' => 'Problem with the form',
]);
echo $this->partial('vehicleSummary', ['vehicle' => $this->vehicle]);

//  --  draw list of certificates in this site  --
echo $this->partial(
    'vehicle/history',
    [
        'vehicleHistory' => $vehicleHistory,
        'isDvsaUser' => false,
        'siteName' => $this->siteName,
        'isManySites' => false,
    ]
);
?>

<div class="clearfix"></div>

<h2>Documents not issued at this VTS</h2>

<div id="historyOnOtherSite" class="row">
    <?php if ($vehicleHistory->hasHistoryOnOtherSite()) : ?>
        <div class="results-entry col-sm-8">
            <?php
            foreach ($vehicleHistory->getIteratorOnOtherSite() as $item) :
                /** @var DvsaCommon\Dto\Vehicle\History\VehicleHistoryItemDto $item */
                $escId = $this->escapeHtmlAttr($item->getId());
                ?>
                <div class="row">
                    <div class="results-entry-item clearfix">
                        <?php
                        //  --  status  --
                        echo $this->partial('vehicle/history-item', ['vehicleHistoryItem' => $item]);
                        ?>

                        <div class="col-sm-3">
                            &nbsp;
                        </div>

                        <div class="col-sm-4">
                            <a href="<?php echo $this->url('mot-test-certificate', ['motTestNumber' => $item->getMotTestNumber()]); ?>"
                               id="view-<?php echo $this->escapeHtmlAttr($item->getMotTestNumber()) ?>" class="btn btn-primary">View</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <span class="divider"></span>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else : ?>
        <div class="results-entry col-sm-8">
            <p>No items found</p>
        </div>
    <?php endif; ?>

    <nav class="col-sm-8 module-content-navigation">
        <ul class="content-navigation_secondary">
            <li>
                <a href="<?php echo $this->url(
                    VehicleSearchController::ROUTE_REPLACEMENT_CERTIFICATE_VEHICLE_SEARCH,
                    [],
                    ['query' => ['vin' => $this->vin, 'registration' => $this->registration]]
                ); ?>" id="return_to_replacement_search">
                    Return to find a vehicle
                </a>
            </li>
        </ul>
    </nav>
</div>

