<?php
/** @var string $searchType */
/** @var \DvsaMotTest\View\VehicleSearchResult\VehicleSearchResultUrlTemplateInterface $urlTemplate */
/** @var \DvsaMotTest\View\VehicleSearchResult\VehicleSearchResultMessage $searchResultMessage */

$searchType = $this->searchType;

//  --  title & header  --
if (!empty($this->title)) {
    $title = $this->title;
} else {
    $title = 'Find a vehicle';

    if ($isRetest) {
        $title .= ' - retest';
    }
}
$escTitle = $this->escapeHtml($title);

$this->headTitle($escTitle);

$this->layout()->setVariable('pageTitle', $escTitle);

$noMatches = isset($noMatches) ? $noMatches : false;
$showCreateButton = isset($showCreateButton) ? $showCreateButton : false;
$results = isset($results) ? $results : null;
$tooManyMatches = isset($tooManyMatches) ? $tooManyMatches : null;
$registrationNumberMaxLength = isset($registrationNumberMaxLength) ? $registrationNumberMaxLength : 10;

$form = $this->form;
$action = (!empty($action)? $action : '');
$form->setAttribute('method', 'post');
$form->setAttribute('action', $action);
$form->prepare();

$data = [
    'registrationElement'         => $form->get('registration'),
    'vinElement'                  => $form->get('vin'),
    'submitElement'               => $form->get('submit'),
    'searchType'                  => (isset($searchType) ? $searchType : null),
];

echo $this->partial(
    'vehicleSearch',
    [
        'form'                          => $form,
        'data'                          => $data,
        'noMatches'                     => $noMatches,
        'showCreateButton'              => $showCreateButton,
        'results'                       => $results,
        'tooManyMatches'                => $tooManyMatches,
        'registrationNumberMaxLength'   => $registrationNumberMaxLength,
        'urlTemplate'                   => $urlTemplate,
        'searchResultMessage'          => $searchResultMessage,
    ]
);
