<?php
use Site\UpdateVtsProperty\Process\Form\NamePropertyForm;
use Site\UpdateVtsProperty\UpdateVtsPropertyViewModel;

/** @var UpdateVtsPropertyViewModel $viewModel */

/** @var NamePropertyForm $form */
$form = $viewModel->getForm();
?>
<fieldset>
    <?php echo $this->partial(
        'partial/gds/form/control',
        [
            'element' => $form->getNameElement()
        ]
    );?>
</fieldset>
