<?php
use DvsaCommon\Utility\ArrayUtils;
use DvsaCommon\UrlBuilder\UserAdminUrlBuilderWeb;

/** @var \UserAdmin\Presenter\UserProfilePresenter $presenter */
/** @var string $searchResultsUrl */
/** @var string $emailAddressUrl */
/** @var string $emailValue */
/** @var string $emailConfirmValue */
/** @var string $previousProfileUrl */
/** @var bool $isViewingOwnProfile */
/**
 * @var bool $newProfileEnabled
 */

$errorMessages = [];

foreach ($this->layout()->flashMessenger->getErrorMessages() as $key => $value) {
    $errorMessages += $value;
}

echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $this->layout()->flashMessenger->getErrorMessages()]);

$isEmail = empty(trim($presenter->displayEmail())) ? false : true;

?>

<?php
    if (!$newProfileEnabled) {
        echo '<div class="lede">
                <p>Provide an email address for <?php echo $this->escapeHtml($presenter->displayFullName()) ?></p>
              </div>';
    }
?>


<form id="emailAddressForm" action="<?php echo $this->escapeHtmlAttr($emailAddressUrl); ?>" method="POST">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <?php

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => 'email',
                'name'          => 'email',
                'errorMessage'  => ArrayUtils::tryGet($errorMessages, 'email'),
                'label'         => 'Email address',
                'value'         => $emailValue,
            ]
        );

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => 'emailConfirm',
                'name'          => 'emailConfirm',
                'errorMessage'  => ArrayUtils::tryGet($errorMessages, 'emailConfirm'),
                'label'         => 'Confirm email address',
                'value'         => $emailConfirmValue,
            ]
        );
        ?>
    </fieldset>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'            => 'submitEmailAddress',
            'value'         => 'Change email address',
            'linkMessage'   => $newProfileEnabled ? $this->serverUrl(true) : $emailAddressUrl,
            'navigation'    => [
                $isViewingOwnProfile ? 'Cancel and return to your profile'
                : 'Cancel and return to user profile' => $newProfileEnabled ?
                    $this->personProfileUrl()->toPersonProfile() :
                    UserAdminUrlBuilderWeb::of()->userProfile($presenter->getPersonId()),
            ]
        ]
    ); ?>
</form>

<script>
    document.onreadystatechange = function () {
        $('#emailAddressForm').submit(function() {
            $('#submitEmailAddress').attr('disabled','disabled');
        });
    };
</script>
