<?php
use DvsaCommon\Utility\ArrayUtils;
use DvsaCommon\UrlBuilder\UserAdminUrlBuilderWeb;

/** @var \UserAdmin\Presenter\UserProfilePresenter $presenter */
/** @var string $searchResultsUrl */
/** @var string $emailAddressUrl */
/** @var string $emailValue */
/** @var string $emailConfirmValue */
/**
 * @var bool $newProfileEnabled
 */

$errorMessages      = $this->layout()->flashMessenger->getErrorMessages();
$successMessages    = $this->layout()->flashMessenger->getSuccessMessages();

echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);

$isEmail = empty(trim($presenter->displayEmail())) ? false : true;

?>

<div class="lede">
    <p>Provide an email address for <?php echo $this->escapeHtml($presenter->displayFullName()) ?></p>
</div>


<form id="emailAddressForm" action="<?php echo $this->escapeHtmlAttr($emailAddressUrl); ?>" method="POST">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <?php

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => 'email',
                'name'          => 'email',
                'errorMessage'  => ArrayUtils::tryGet($errorMessages, 'email'),
                'label'         => 'Email address',
                'value'         => $emailValue,
                'type'          => 'email'
            ]
        );

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => 'emailConfirm',
                'name'          => 'emailConfirm',
                'errorMessage'  => ArrayUtils::tryGet($errorMessages, 'emailConfirm'),
                'label'         => 'Confirm email address',
                'value'         => $emailConfirmValue,
                'type'          => 'email'
            ]
        );
        ?>
    </fieldset>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'            => 'submitEmailAddress',
            'value'         => 'Change email address',
            'linkMessage'   => $emailAddressUrl,
            'navigation'    => [
                'Cancel and return to user profile' => $newProfileEnabled ? '/preview/profile/' . $presenter->getPersonId() : UserAdminUrlBuilderWeb::of()->userProfile($presenter->getPersonId()),
            ]
        ]
    ); ?>
</form>

<script>
    document.onreadystatechange = function () {
        $('#emailAddressForm').submit(function() {
            $('#submitEmailAddress').attr('disabled','disabled');
        });
    };
</script>
