<?php

use \UserAdmin\Controller\PersonRoleController;
use \UserAdmin\Presenter\UserProfilePresenter as Presenter;

/** @var Presenter $presenter */

if ($presenter->canDisplayDvsaRoleSection()): ?>
    <h3 class="heading-medium">Roles</h3>

    <?php if ($presenter->hasDvsaRoles()): ?>

        <table class="key-value-list">
            <tbody>
            <?php
            /** @var array $currentInternalRoles */
            $currentInternalRoles = $presenter->getPersonAssignedInternalRoleCodes();

            foreach ($currentInternalRoles as $role): ?>
                <tr>
                    <th class="key-value-list__key">
                        <strong><?php echo $this->escapeHtml($role); ?></strong>
                    </th>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

    <?php else : ?>
        <p>No roles assigned.</p>
    <?php endif; ?>

    <?php if (true === $presenter->canManageDvsaRoles() && false === $presenter->isManagingOwnRoles()): ?>
        <p>
            <a href="<?php echo $this->url(PersonRoleController::URL_MANAGE_INTERNAL_ROLE, ['personId' => $presenter->getPersonId()]); ?>"
               class="key-value-list__action">
                Manage roles
            </a>
        </p>
    <?php endif; ?>

<?php endif; ?>

