<h3 class="heading-medium">Roles and associations</h3>
<table class="key-value-list">
    <tbody>
    <tr>
        <?php if ($systemRoles = $presenter->getSystemRoles()): ?>
            <th class="key-value-list__key"></th>
            <td id="roles-system" class="key-value-list__value">
                <?php echo join('<br />', $systemRoles) ?>
            </td>
        <?php endif; ?>
    </tr>
    <?php foreach ($presenter->getSiteAndOrganisationRoles() as $id => $organisationUnit):
        $escRoute = $organisationUnit['route']; // VM-8519 Route is static no escaping required
        ?>
        <tr>
            <th class="key-value-list__key">
                <a href="<?php echo $escRoute; ?>"
                   title="<?php echo $this->escapeHtmlAttr($organisationUnit['name']); ?>">
                    <?php echo $this->escapeHtml($organisationUnit['name']) ?>
                </a>
                <?php echo $this->escapeHtml($organisationUnit['number']) ?>
                <span class="key-value-list__meta"><?php echo $this->escapeHtml($organisationUnit['address']); ?></span>
            </th>
            <td id="roles-<?php echo md5($organisationUnit['name']) ?>" class="key-value-list__value">
                <?php if (isset($organisationUnit['roles'])): ?>
                    <?php echo join('<br />', $organisationUnit['roles']) ?>
                <?php else: ?>
                    No Roles
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>