<?php
use \UserAdmin\Presenter\UserProfilePresenter as Presenter;
/** @var Presenter $presenter */
$associatedSitesAndOrganisations = $presenter->getSiteAndOrganisationRoles();

if (!empty($associatedSitesAndOrganisations)):
?>
<h3 class="heading-medium">Roles and associations</h3>
<table class="key-value-list">
    <tbody>
    <?php foreach ($associatedSitesAndOrganisations as $id => $unit): ?>
        <tr>
            <th class="key-value-list__key">
                <a href="<?php echo $unit['route']; ?>"
                   title="<?php echo $this->escapeHtmlAttr($unit['name']); ?>">
                    <?php echo $this->escapeHtml($unit['name']) ?>
                </a>
                <?php echo $this->escapeHtml($unit['number']) ?>
                <span class="key-value-list__meta"><?php echo $this->escapeHtml($unit['address']); ?></span>
            </th>
            <td id="roles-<?php echo md5($unit['name']) ?>" class="key-value-list__value">
                <?php if (isset($unit['roles'])): ?>
                    <?php echo join('<br />', $unit['roles']) ?>
                <?php else: ?>
                    No Roles
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif ?>