<?php
/** @var \UserAdmin\ViewModel\UserProfile\TesterAuthorisationViewModel $viewModel */
?>

<h3 class="heading-medium">Tester qualification status</h3>
<table class="key-value-list">
    <tbody>
    <tr>
        <th class="key-value-list__key">
            Group A
            <span class="key-value-list__meta">Class 1, Class 2</span>
        </th>
        <td class="key-value-list__value" id="group-a-qualification-status">
            <?php echo $viewModel->getTesterAuthorisation()->getGroupAStatus()->getName() ?>
            <?php if ($viewModel->canAlterTesterAuthorisation()): ?>
                <span class="key-value-list__meta">
                    <a id="record-demo-a" href="<?php
                    echo $this->url(
                            'user_admin/profile/change-qualification-status',
                            [
                                'personId' => $viewModel->getTesterId(),
                                'vehicleClassGroup' => 'A'
                            ], [
                                'query' => $searchQueryParams
                            ]
                        ); ?>">Change qualification status</a>
                </span>
            <?php endif ?>
        </td>
    </tr>
    <tr>
        <th class="key-value-list__key">
            Group B
            <span class="key-value-list__meta">Class 3, Class 4, Class 5, Class 7</span>
        </th>
        <td class="key-value-list__value" id="group-b-qualification-status">
            <?php echo $viewModel->getTesterAuthorisation()->getGroupBStatus()->getName() ?>
            <?php if ($viewModel->canAlterTesterAuthorisation()) :?>
                <span class="key-value-list__meta">
                    <a id="record-demo-b" href="<?php
                    echo $this->url(
                            'user_admin/profile/change-qualification-status',
                            [
                                'personId' => $viewModel->getTesterId(),
                                'vehicleClassGroup' => 'B'
                            ], [
                            'query' => $searchQueryParams
                            ]
                        ); ?>">Change qualification status</a>
                </span>
            <?php endif ?>
        </td>
    </tr>
    </tbody>
</table>
