<?php
use DvsaCommon\UrlBuilder\AuthorisedExaminerUrlBuilderWeb;

/* @var $site */

$this->layout()->setVariable('pageTitle', 'Slot usage');
$this->layout()->setVariable('pageSubTitle', $this->escapeHtml($organisation->getName()));
?>
<div class="row">
    <?php
    if (!$this->isPdf) {
        echo $this->partial(
            'errorMessages',
            array('errorTitle' => 'Please check the form', 'getFromFlash' => true)
        );
    }
    ?>
</div>
<div class="row slot-usage-totals">
    <div class="col-md-3">
        <h4>Total usage</h4>
    </div>
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-3 report-quarter">
                <h3><?php echo $this->escapeHtml($periodUsage[0]); ?></h3>
                <span>Today</span>
            </div>
            <div class="col-md-3 report-quarter">
                <h3><?php echo $this->escapeHtml($periodUsage[1]); ?></h3>
                <span>Last 7 days</span>
            </div>
            <div class="col-md-3 report-quarter">
                <h3><?php echo $this->escapeHtml($periodUsage[2]); ?></h3>
                <span>Last 30 days</span>
            </div>
            <div class="col-md-3 report-quarter">
                <h3><?php echo $this->escapeHtml($periodUsage[3]); ?></h3>
                <span>Last year</span>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <?php

    if ($this->isPdf) {
        $escMainColumnClass = 'col-lg-12';
    } else {
        $escMainColumnClass = 'col-md-9'; ?>
        <div class="col-md-3">
            <?php
            echo $this->partial(
                'partials/table/date-filter.phtml',
                array(
                    'form' => $form,
                    'currentDateRange' => $currentDateRange,
                    'currentParams' => $params,
                    'legendFrom' => 'Start date',
                    'legendTo' => 'End date',
                    'dateRanges' => $dateRanges,
                )
            ); ?>
            <a href="<?php echo $this->url('report', [], ['query' => ['route' => $route, 'routeParameters' => $routeParameters, 'returnTo' => $returnTo]]); ?>" id="download" class="btn btn-primary">Download report</a>
        </div>
        <?php

    }
    ?>
    <div class="<?php echo $escMainColumnClass; ?> slot-usage-table">
        <span>
            <?php if ($searchText): ?><strong>"<?php echo $this->escapeHtml($searchText); ?>"</strong> <?php endif; ?>
            <strong><?php echo $this->escapeHtml($slotUsageForCurrentQuery); ?></strong> slots used <strong><?php echo $this->escapeHtml($dateRangeLabel); ?></strong>
        </span>
        <?php echo $this->table->render($this); ?>
    </div>
</div>

<div class="row">
    <nav class="module-content-navigation col-sm-12">
        <ul class="content-navigation_secondary">
            <li>
                <a id="returnToAe" href="<?php echo AuthorisedExaminerUrlBuilderWeb::of($organisation->getId()); ?>">Return to Authorised Examiner</a>
            </li>
        </ul>
    </nav>
</div>
