<?php

$sectionName = "Authorised Examiner";
$taskName = "Remove an AEP";

$this->headTitle($sectionName . ' - ' . $taskName);
$this->layout()->setVariable('pageSubTitle', $this->translate($sectionName));
$this->layout()->setVariable('pageTitle', $this->translate($taskName));

/**
 * @var \DvsaClient\Entity\Person       $principal
 * @var \DvsaCommon\Dto\Organisation\OrganisationDto $authorisedExaminer
 * @var String                          $cancelRoute
 */
?>

<h3>
    Are you sure you want to remove
    <span id="display-name">
        <?php echo $this->escapeHtml($principal->getFullName()); ?>
    </span>
    as Authorised Examiner Principal of <?php echo $this->escapeHtml($authorisedExaminer->getName()); ?>?
</h3>

<form method="POST">
    <?php echo $this->csrfToken() ?>

    <div class="form-group">
        <?php echo $this->partial(
            'submitElement',
            [
                'label' => 'Confirm',
                'id'    => 'confirm-button'
            ]
        ); ?>
    </div>
    <div class="form-group">
        <a id="cancel" href="<?php echo $this->escapeHtml($cancelRoute); ?>">Back to AE overview</a>
    </div>
</form>
