<?php

/**
 * @var \Organisation\ViewModel\AuthorisedExaminer\AeRemovePrincipalViewModel $viewModel
 * @var \Zend\Mvc\Controller\Plugin\FlashMessenger                   $flashMessenger
 */

$viewModel = $this->viewModel;

//  show api errors
$flashMessenger = $this->layout()->flashMessenger;
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'failure']
);
?>

<form method="POST" action="#" autocomplete="off" novalidate>
    <?php echo $this->csrfToken() ?>

    <?php
    echo $this->partial(
        'partial/gds/gds-table/gds-key-value-table',
        [
            'table' => $viewModel->getGdsTable(),
        ]
    );
    ?>

    <?php
    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'         => 'confirm-button',
            'value'      => 'Remove principal',
            'class'      => 'button-warning',
            'navigation' => [
                'Cancel and return to authorised examiner' => $viewModel->getCancelUrl(),
            ],
        ]
    );
    ?>
</form>
