<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Site\Authorization\VtsOverviewPagePermissions'       => __DIR__ . '/src/Site/Authorization/VtsOverviewPagePermissions.php',
  // REMOVED INVALID MAP: 'positions'                                           => __DIR__ . '/src/Site/Authorization/VtsOverviewPagePermissions.php',
  'Site\Controller\RoleController'                      => __DIR__ . '/src/Site/Controller/RoleController.php',
  'Site\Controller\SiteSearchController'                => __DIR__ . '/src/Site/Controller/SiteSearchController.php',
  'Site\Controller\SiteTestingDailyScheduleController'  => __DIR__ . '/src/Site/Controller/SiteTestingDailyScheduleController.php',
  'Site\Controller\VehicleTestingStationController'     => __DIR__ . '/src/Site/Controller/VehicleTestingStationController.php',
  'Site\Factory\Controller\RoleControllerFactory'       => __DIR__ . '/src/Site/Factory/Controller/RoleControllerFactory.php',
  // REMOVED INVALID MAP: 'get'                                                 => __DIR__ . '/src/Site/Factory/Controller/RoleControllerFactory.php',
  'Site\Factory\Controller\SiteSearchControllerFactory' => __DIR__ . '/src/Site/Factory/Controller/SiteSearchControllerFactory.php',
  // REMOVED INVALID MAP: 'SiteSearchController'                                => __DIR__ . '/src/Site/Factory/Controller/SiteSearchControllerFactory.php',
  'Site\Fieldset\VehicleTestingStationFormFieldSet'     => __DIR__ . '/src/Site/Fieldset/VehicleTestingStationFormFieldSet.php',
  'Site\Form\VehicleTestingStationForm'                 => __DIR__ . '/src/Site/Form/VehicleTestingStationForm.php',
  'Site\Form\VtsContactDetailsUpdateForm'               => __DIR__ . '/src/Site/Form/VtsContactDetailsUpdateForm.php',
  'Site\Model\SitePersonnel'                            => __DIR__ . '/src/Site/Model/SitePersonnel.php',
  'Site\Presenter\VtsPresenter'                         => __DIR__ . '/src/Site/Presenter/VtsPresenter.php',
  'Site\Traits\SiteServicesTrait'                       => __DIR__ . '/src/Site/Traits/SiteServicesTrait.php',
  'Site\ViewModel\MotTest\MotTestInProgressViewModel'   => __DIR__ . '/src/Site/ViewModel/MotTest/MotTestInProgressViewModel.php',
  'Site\ViewModel\Role\RemoveRoleConfirmationViewModel' => __DIR__ . '/src/Site/ViewModel/Role/RemoveRoleConfirmationViewModel.php',
  'Site\ViewModel\SiteSearchViewModel'                  => __DIR__ . '/src/Site/ViewModel/SiteSearchViewModel.php',
  'Site\ViewModel\VTSDecorator'                         => __DIR__ . '/src/Site/ViewModel/VTSDecorator.php',
);
