<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Report\Filter\FilterBuilder'               => __DIR__ . '/src/Report/Filter/FilterBuilder.php',
  'Report\Filter\DatesGroupElement'           => __DIR__ . '/src/Report/Filter/Form/DatesGroupElement.php',
  'Report\Filter\DatesRangesHelper'           => __DIR__ . '/src/Report/Filter/View/Helper/DatesRangesHelper.php',
  'Report\Filter\RangesHelper'                => __DIR__ . '/src/Report/Filter/View/Helper/RangesHelper.php',
  'Report\Table\ColumnOptions'                => __DIR__ . '/src/Report/Table/ColumnOptions.php',
  'Report\Table\Formatter\Bold'               => __DIR__ . '/src/Report/Table/Formatter/Bold.php',
  'Report\Table\Formatter\FormatterInterface' => __DIR__ . '/src/Report/Table/Formatter/FormatterInterface.php',
  'Report\Table\Formatter\Subline'            => __DIR__ . '/src/Report/Table/Formatter/Subline.php',
  // REMOVED INVALID MAP: 'ReportModel'                               => __DIR__ . '/src/Report/Table/Model/ReportModel.php',
  'Report\Table\Table'                        => __DIR__ . '/src/Report/Table/Table.php',
  'Report\Table\TableBuilder'                 => __DIR__ . '/src/Report/Table/TableBuilder.php',
  'Report\Table\TableOptions'                 => __DIR__ . '/src/Report/Table/TableOptions.php',
);
