<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Report\Filter\FilterBuilder'               => __DIR__ . '/src/Report/Filter/FilterBuilder.php',
  'Report\Table\ColumnOptions'                => __DIR__ . '/src/Report/Table/ColumnOptions.php',
  'Report\Table\Formatter\Bold'               => __DIR__ . '/src/Report/Table/Formatter/Bold.php',
  'Report\Table\Formatter\FormatterInterface' => __DIR__ . '/src/Report/Table/Formatter/FormatterInterface.php',
  'Report\Table\Formatter\MotTestLink'        => __DIR__ . '/src/Report/Table/Formatter/MotTestLink.php',
  'Report\Table\Formatter\SiteLink'           => __DIR__ . '/src/Report/Table/Formatter/SiteLink.php',
  'Report\Table\Formatter\SubRow'             => __DIR__ . '/src/Report/Table/Formatter/SubRow.php',
  'Report\Table\Table'                        => __DIR__ . '/src/Report/Table/Table.php',
  'Report\Table\TableOptions'                 => __DIR__ . '/src/Report/Table/TableOptions.php',
);
