<?php
use DvsaCommon\Auth\PermissionInSystem;

$removed = isset($removed) ? $removed : false;
$title = $removed ? 'Removed Special Notices' : 'Special Notices';
$this->headTitle($title);
?>

<div class="row" id="content">
    <div class="col-lg-12 header-container">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <div>
            <a href="<?php echo $this->url(\Dashboard\Controller\UserHomeController::ROUTE); ?>" class="btn btn-primary" id="returnDashboard">Back</a>
        </div>
    </div>
</div>



<?php echo $this->partial('errorMessages', ['getFromFlash' => true]); ?>
<?php echo $this->partial('infoMessages', ['getFromFlash' => true]); ?>

<div id="special-notices">
    <div class="row">
        <div class="col-sm-5">
            <img src="/img/dvsa-org-logo@2x.png" width="154" alt="Driver and Vehicle Standards Agency">
        </div>
    </div>

    <div class="row">
        <div class="col-lg-8">
            <p>
                <?php if ($removed): ?>
                    <a href="<?php echo $this->url('special-notices/all'); ?>" id="current_special_notice" class="btn btn-link">Current special notices</a>
                <?php else: ?>
                    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::SPECIAL_NOTICE_CREATE)): ?>
                        <a href="<?php echo $this->url('special-notices/create'); ?>" id="create_special_notice" class="btn btn-primary">Create special notice</a>
                    <?php endif; ?>
                    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::SPECIAL_NOTICE_READ_REMOVED)): ?>
                        <a href="<?php echo $this->url('special-notices/removed'); ?>" id="removed_special_notice" class="btn btn-link">Removed special notices</a>
                    <?php endif; ?>
                <?php endif; ?>
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="status-neutral">
                <div class="row">
                    <div class="col-sm-12">
                        <h4>
                            <?php if ($removed): ?>
                                Removed notices
                            <?php else: ?>
                                Current notices
                            <?php endif; ?>
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php if($specialNotices) : ?>
        <?php echo $this->partial(
            'specialNotice', ['specialNotices' => $specialNotices, 'showRemoveButton' => !$removed, 'canAcknowledge' => $canAcknowledge, 'canRemove' => $canRemove, 'canUpdate' => $canUpdate]
        ); ?>
    <?php else : ?>
        <p>There are currently no notices in the back log.</p>
    <?php endif; ?>

</div>

<div>
    <span class="divider full"></span>
</div>

<p>If you have any queries regarding this Special Notice or other testing matters,
<?php echo lcfirst(trim($this->partial('partial/gds/general/contactHelpdesk', ['config' => $this->config['helpdesk']]))); ?></p>

<script>
    var converter = new Showdown.converter();

    $("[id^=special-notice-content] > p").each(function() {
        $(this).html(converter.makeHtml($(this).text().trim()));
    });

    $("[id^=special-notice-content]").addClass("collapse");

    $("[id^=special-notice-content]").on('shown.bs.collapse hidden.bs.collapse', function (e) {
        e.stopPropagation();
        $(this).parent().find("span").eq(2).toggleClass("fa-chevron-down fa-chevron-up");
    });

    $(".special-notice-remove-button").on('click', function(e) {
        return confirm("This action will delete this notice from the library.\nDo you want to continue?");
    });
</script>
