<?php
use DvsaMotTest\ViewModel\StartTestConfirmationViewModel;

/**
 * @var StartTestConfirmationViewModel $viewModel
 */


$title = 'Vehicle details changed';
$header = 'Vehicle Details Changed';

/** @var \DvsaCommon\Dto\Vehicle\AbstractVehicleDto $vehicleDetails */
$vehicleDetails = $this->vehicleDetails;

$this->headTitle($title);
echo $this->partial(
    'motTestProgress',
    [
        'currentStep' => 1,
        'title' => $header,
        'isMotContingency' => $this->isMotContingency
    ]
);
echo $this->partial('errorMessages', ['getFromFlash' => true]);
?>

<form action="<?php echo $viewModel->getConfirmActionUrl() ?>" method="POST">

    <?php echo $this->csrfToken() ?>
    <input type="hidden" name="primaryColour"
           value="<?php echo $this->escapeHtmlAttr($vehicleDetails->getColour()->getCode()); ?>" />
    <input type="hidden" name="secondaryColour"
           value="<?php echo $this->escapeHtmlAttr($vehicleDetails->getColourSecondary()->getCode()); ?>" />
    <input type="hidden" name="vehicleClass"
           value="<?php echo $this->escapeHtmlAttr($vehicleDetails->getClassCode()); ?>" />
    <input type="hidden" name="fuelType"
           value="<?php echo $this->escapeHtmlAttr($vehicleDetails->getFuelType()->getCode()); ?>" />
    <input type="hidden" name="motTestType"
           value="<?php echo $this->escapeHtmlAttr($viewModel->getMethod()); ?>" />

    <div class="row">
        <div class="col-sm-8">
            <?php
                echo $this->partial(
                    'otpInput',
                    [
                        'canTestWithoutOpt' => false,
                        'errorMessage' => $this->otpErrorMessage,
                        'shortErrorMessage' => $this->otpErrorShortMessage
                    ]
                );
            ?>
            <nav class="module-content-navigation">
                <input type="submit" class="button" value="Confirm changes" id="confirm_vehicle_changes">
                <ul class="content-navigation_secondary">
                    <li>
                        <a href="<?php echo $viewModel->getConfirmActionUrl() ?>">Cancel vehicle changes</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

</form>
