<?php

use Application\Build\BuildConfig;
use Dashboard\Controller\UserHomeController;
use Dvsa\Mot\Frontend\AuthenticationModule\Controller\LogoutController;
use DvsaCommon\Auth\PermissionInSystem;
use DvsaCommon\Constants\Role;
use DvsaCommon\UrlBuilder\PersonUrlBuilderWeb;
use Core\Presenter\MastheadPresenter;

$mastheadPresenter = new MastheadPresenter;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php echo $this->headTitle('MOT', 'PREPEND')->setSeparator(' - '); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Base Styles -->
    <?php echo $this->headLink()->appendStylesheet($this->basePath('css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('css/font-awesome.min.css'))
        ->appendStylesheet($this->basePath('css/app.css'))
        ->appendStylesheet($this->basePath('css/refactor.css'));
    ?>

    <link type="image/x-icon" rel="shortcut icon"
          href="/assets/images/favicon.ico">

    <?php
    // Items must be pre-pended in reverse order so that, any items appended will get added
    // after our files. This guarantees all libraries to be enabled in all pages.
    $this->headScript()
        ->prependFile(
            $this->basePath('js/' . BuildConfig::getJavaScriptLessThanIe9Filename()),
            'text/javascript',
            ['conditional' => 'lt IE 9']
        )
        ->prependFile($this->basePath('js/' . BuildConfig::getJavaScriptLibrariesFilename()));

    echo $this->headScript();
    ?>

    <script type="text/javascript"><?php echo $this->gtmDataLayer()->render(); ?></script>
</head>
<body>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PS5VXQ"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PS5VXQ');</script>
<!-- End Google Tag Manager -->
<script type="text/javascript">document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>


<?php echo $this->partial('partial/fragments/header-govuk',
    [
        'hideUserNav' => $this->hideUserNav,
        'isHomePage' => $this->isHomePage,
        'isYourProfile' => $this->isYourProfile
    ]); ?>

<div class="container">
    <div class="module-colour-flash">
    </div>
</div>

<div class="container">
    <p class="module-phase">
        <strong class="phase-name is-beta">BETA</strong>
        This is a new service - your
        <a id="feedback-link" target="_blank" href="<?php echo $this->escapeHtmlAttr($mastheadPresenter->getFeedbackUrl()) ?>">feedback</a>
        will help us to improve it.
    </p>
</div>

<div class="container">
    <?php echo $this->placeholder('banner'); ?>
</div>

<?php echo $this->placeholder('hero'); ?>

<div class="container">

    <?php echo $this->placeholder('progressBar'); ?>

    <!-- Progress Tracker -->
    <?php if ($this->progressBar): ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="progress-tracker">
                    <ul class="list-unstyled">
                        <li class="done"><i class="fa fa-arrow-circle-right"></i>Step name</li>
                        <li class="active"><i class="fa fa-arrow-circle-right"></i>Step name</li>
                        <li><i class="fa fa-arrow-circle-right"></i>Step name</li>
                        <li><i class="fa fa-arrow-circle-right"></i>Step name</li>
                    </ul>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <!-- END -->

    <!-- Titles -->
    <?php if (isset($this->pageSubTitle) or (isset($this->pageTitle))): ?>
        <div class="row">
            <div class="col-lg-12">
                <h1>
                    <small><?php echo $this->escapeHtml($this->pageSubTitle); ?></small>
                    <?php echo $this->escapeHtml($this->pageTitle); ?>
                    <?php if (isset($this->pageTertiaryTitle)): ?>
                        <small><?php echo $this->escapeHtml($this->pageTertiaryTitle); ?></small>
                    <?php endif; ?>
                </h1>
                <hr class="hr-thick"/>
            </div>
        </div>
    <?php endif; ?>
    <!-- END -->

    <?php if (isset($applicationNavigator)) : ?>

        <div class="row">
            <?php echo $this->partial('applicationSteps', ['applicationNavigator' => $applicationNavigator]); ?>
            <div class="col-sm-8  col-sm-offset-1" id="content">
                <h1><?php echo $this->escapeHtml($title); ?></h1>
                <?php echo $this->content; // should be escaped in controller ?>
            </div>
        </div>

    <?php else : ?>
        <div class="row contents">
            <div class="col-lg-12">
                <?php echo $this->content; // should be escaped in controller  ?>
            </div>
        </div>
    <?php endif; ?>

</div>
<!-- /container -->
<footer role="contentinfo" id="footer" class="module-global-footer">
    <div class="container">
        <div class="row global-footer_links">
            <div class="col-md-8 col-sm-12">
                <div class="global-footer_resources">
                    <h3><?php echo $this->resourcesOnGovUkHelper()->getTitle(); ?></h3>
                    <nav class="global-footer_navigation-resources">
                        <ul class="list-unstyled">
                            <?php foreach ($this->resourcesOnGovUkHelper()->getDocuments() as $key => $resource) : ?>
                                <li>
                                    <a id="resources_<?php echo $key ?>" href="<?php echo $resource['url']; ?>">
                                        <?php echo $resource['name']; ?>
                                    </a>
                                    <?php echo $resource['help_text']; ?>
                                </li>
                            <?php endforeach?>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class=" col-md-4 col-sm-12">
                <div class="global-footer_resources">
                    <h3><?php echo $this->manualsHelper()->getTitle(); ?></h3>
                    <nav class="global-footer_navigation-resources">
                        <ul class="list-unstyled">
                            <?php foreach ($this->manualsHelper()->getDocuments() as $key => $resource) : ?>
                                <li>
                                    <a id="manuals_<?php echo $key ?>" href="<?php echo $resource['url']; ?>">
                                        <?php echo $resource['name']; ?>
                                    </a>
                                </li>
                            <?php endforeach?>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-md-12 col-sm-12">

                <hr class="global-footer_divider" />

            </div>

        </div>

        <div class="row">
            <div class="col-sm-9 global-footer_meta">
                <nav class="global-footer_navigation">
                    <ul>
                        <li><a href="https://www.gov.uk/help/cookies">Cookies</a></li>
                        <li>
                            Built by the Driver &amp; Vehicle Standards Agency
                            <?php
                            $releaseTagTemplate = '<span class="tt-hint">Release {release_tag_name}</span>';
                            echo $this->getReleaseTag()->renderReleaseTag($releaseTagTemplate);
                            ?>
                        </li>
                    </ul>
                </nav>
                <p class="global-footer_licence">
                    <a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2"
                       class="licence-logo">
                        Open Government Licence
                    </a>
                    All content is available under the
                    <a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2">
                        Open Government Licence v2.0
                    </a>, except where otherwise stated
                </p>
            </div>
            <div class="col-sm-3 global-footer_copyright">
                <a href="http://www.nationalarchives.gov.uk/information-management/our-services/crown-copyright.htm">
                    &copy; Crown copyright
                </a>
            </div>
        </div>
    </div>
</footer>
<?php echo $this->inlineScript(); ?>

</body>
</html>
