<?php

use Core\ViewModel\Sidebar\SidebarInterface;

/** @var $sidebar SidebarInterface */

?>

<!DOCTYPE html>
<!--[if lt IE 9]><html class="lte-ie8" lang="en"><![endif]-->
<!--[if gt IE 8]><!--><html lang="en"><!--<![endif]-->
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <?php echo $this->headTitle('MOT', 'PREPEND')->setSeparator(' - '); ?>

    <script type="text/javascript">
        (function(){if(navigator.userAgent.match(/IEMobile\/10\.0/)){var d=document,c="appendChild",a=d.createElement("style");a[c](d.createTextNode("@-ms-viewport{width:auto!important}"));d.getElementsByTagName("head")[0][c](a);}})();
    </script>

    <!--[if gt IE 8]><!--><link href="/assets/stylesheets/govuk-template.css" media="screen" rel="stylesheet" type="text/css" /><!--<![endif]-->
    <!--[if IE 6]><link href="/assets/stylesheets/govuk-template-ie6.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 7]><link href="/assets/stylesheets/govuk-template-ie7.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 8]><link href="/assets/stylesheets/govuk-template-ie8.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->

    <link href="/assets/stylesheets/govuk-template-print.css" media="print" rel="stylesheet" type="text/css" />

    <!--[if IE 8]>
    <script type="text/javascript">
        (function(){if(window.opera){return;}
            setTimeout(function(){var a=document,g,b={families:(g=
                    ["nta"]),urls:["/assets/stylesheets/fonts-ie8.css"]},
                c="/assets/javascripts/vendor/goog/webfont-debug.js",d="script",
                e=a.createElement(d),f=a.getElementsByTagName(d)[0],h=g.length;WebFontConfig
                ={custom:b},e.src=c,f.parentNode.insertBefore(e,f);for(;h=h-1;a.documentElement
                .className+=' wf-'+g[h].replace(/\s/g,'').toLowerCase()+'-n4-loading');},0)
        })()
    </script>
    <![endif]-->
    <!--[if gte IE 9]><!-->
    <link href="/assets/stylesheets/fonts.css" media="all" rel="stylesheet" type="text/css" />
    <!--<![endif]-->


    <!--[if lt IE 9]>
    <script src="/assets/javascripts/ie.js" type="text/javascript"></script>
    <![endif]-->

    <link rel="shortcut icon" href="/assets/images/favicon.ico" type="image/x-icon" />

    <!-- Size for iPad and iPad mini (high resolution) -->
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/assets/images/apple-touch-icon-152x152.png">
    <!-- Size for iPhone and iPod touch (high resolution) -->
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/assets/images/apple-touch-icon-120x120.png">
    <!-- Size for iPad 2 and iPad mini (standard resolution) -->
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/assets/images/apple-touch-icon-76x76.png">
    <!-- Default non-defined size, also used for Android 2.1+ devices -->
    <link rel="apple-touch-icon-precomposed" href="/assets/images/apple-touch-icon-60x60.png">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="/assets/images/opengraph-image.png">
    <!--[if gt IE 8]><!--><link href="/assets/stylesheets/dvsa.css"  rel="stylesheet" type="text/css"><!--<![endif]-->
    <!--[if IE 6]><link href="/assets/stylesheets/dvsa-ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 7]><link href="/assets/stylesheets/dvsa-ie7.css" rel="stylesheet" type="text/css" /><![endif]-->
    <!--[if IE 8]><link href="/assets/stylesheets/dvsa-ie8.css" rel="stylesheet" type="text/css" /><![endif]-->

    <script type="text/javascript"><?php echo $this->gtmDataLayer()->render(); ?></script>
</head>
<body class="">
<?php if (getenv(APPLICATION_ENV) != 'development'): ?>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PS5VXQ"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PS5VXQ');</script>
<!-- End Google Tag Manager -->
<?php endif; ?>
<script type="text/javascript">document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>
    <div id="skiplink-container">
        <div>
            <a href="#content" class="skiplink">Skip to main content</a>
        </div>
    </div>
    <div id="global-cookie-message">
        <div class="outer-block">
            <div class="inner-block">
                <p>GOV.UK uses cookies to make the site simpler. <a href="https://www.gov.uk/help/cookies">Find out more about cookies</a></p>
            </div>
        </div>
    </div>
    <!--end global-cookie-message-->

    <?php
    if ($this->hideUserNav != true):
        echo $this->partial('partial/fragments/header-govuk');
    else :
        echo $this->partial(
            'partial/fragments/header-govuk',
            [
                'hideUserNav' => $this->hideUserNav,
            ]
        );
    endif;
    ?>
<div id="global-header-bar">
    <div class="inner-block">
        <div class="header-bar"></div>
    </div>
</div>
<?php echo $this->placeholder('hero'); ?>

<main id="content" role="main">
    <?php echo $this->partial('partial/fragments/phase-banner'); ?>

    <div class="container">

        <?php echo $this->placeholder('progressBar'); ?>

        <!-- Breadcrumbs -->
        <?php if ($this->breadcrumbs): ?>
            <?php echo $this->partial(
                'partial/gds/general/breadcrumb',
                $this->breadcrumbs
            ); ?>
        <?php endif; ?>
        <!-- END -->

        <?php if (isset($sidebar) && !empty($sidebar)): ?>

            <div class="grid-row">

                <div class="column-two-thirds">

        <?php endif; ?>

        <!-- Titles -->
        <?php if (isset($this->pageSubTitle) or (isset($this->pageTitle))): ?>
            <?php echo $this->partial(
                'partial/gds/general/header',
                [
                    'type'  => $this->pageSubTitle,
                    'title' => $this->pageTitle,
                    'tertiary' => $this->pageTertiaryTitle,
                    'progress'  => $this->progress,
                ]
            ); ?>
        <?php endif; ?>
        <!-- END -->

        <?php if (isset($applicationNavigator)) : ?>

            <div class="row">
                <?php echo $this->partial('applicationSteps', ['applicationNavigator' => $applicationNavigator]); ?>
                <div class="col-sm-8  col-sm-offset-1" id="content">
                    <h1><?php echo $this->escapeHtml($title); ?></h1>
                    <?php echo $this->content; // should be escaped in controller ?>
                </div>
            </div>

        <?php else : ?>
            <div class="row contents">
                <div class="col-lg-12">
                    <!-- lede   -->
                    <?php if ($this->pageLede) : ?>
                        <div class="lede">
                            <p><?php echo $this->escapeHtml($this->pageLede); ?></p>
                        </div>
                    <?php endif; ?>
                    <!-- end    -->

                    <?php echo $this->content; // should be escaped in controller ?>
                </div>
            </div>
        <?php endif; ?>

        <?php if (isset($sidebar) && !empty($sidebar)): ?>

            </div>

            <div class="column-third">

                <?php  echo $this->partial($sidebar->getPartialTemplate(), ['sidebar' => $sidebar]); ?>

            </div>

        <?php endif; ?>

    </div>
    <!-- /container -->
</main>
<?php echo $this->partial('partial/fragments/footer-govuk'); ?>

<script src="/assets/javascripts/govuk-template.js?0.10.1"></script>
<script src="/assets/javascripts/vendor/jquery-1.11.0.min.js"></script>
<script src="/assets/javascripts/govuk/selection-buttons.js"></script>
<script src="/assets/javascripts/application.js"></script>
<script src="/assets/javascripts/vendor/details.polyfill.js"></script>
<?php echo $this->headScript(); ?>
<?php echo $this->inlineScript(); ?>

</body>
</html>
