<?php
use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;

?>

<div class="text">
    <p class="lede">We will create your user ID from this information and email you with news about the MOT testing service.</p>
</div>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $errorsSummary]); ?>

<form action="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->detailsStep()); ?>"
      method="POST" autocomplete="off" novalidate="">
    <?php echo $this->csrfToken(); ?>

    <fieldset>
        <legend class="form-title heading-large" id="newUserName">Your name</legend>

        <?php
        $classFormGroup =  $firstNameHasError ? 'has-error' : '';
        echo $this->partial(
            'partial/forms/inputBox.phtml', [
                'id'    => 'firstName',
                'label' => 'First name',
                'labelId' => 'first-name',
                'type'  => 'text',
                'classFormGroup' => $classFormGroup,
                'errors' => $errors['firstName'],
                'classLabel' => 'form-label',
                'value' => $firstName ? : '',
                'optional' => false,
            ]
        );

        $classFormGroup =  $middleNameHasError ? 'has-error' : '';
        echo $this->partial(
            'partial/forms/inputBox.phtml', [
                'id'    => 'middleName',
                'label' => 'Middle name',
                'labelId' => 'middle-name',
                'type'  => 'text',
                'classFormGroup' => $classFormGroup,
                'errors' => $errors['middleName'],
                'classLabel' => 'form-label',
                'value' => $middleName ? : '',
                'optional' => true,
            ]
        );

        $classFormGroup =  $lastNameHasError ? 'has-error' : '';
        echo $this->partial(
            'partial/forms/inputBox.phtml', [
                'id'    => 'lastName',
                'label' => 'Last name',
                'labelId' => 'last-name',
                'type'  => 'text',
                'classFormGroup' => $classFormGroup,
                'errors' => $errors['lastName'],
                'classLabel' => 'form-label',
                'value' => $lastName ? : '',
                'optional' => false,
            ]
        ); ?>

    </fieldset>

    <fieldset>
        <legend class="form-title heading-large" id="phone-legend">Your telephone number</legend>

        <?php
        $classFormGroup =  $phoneHasError ? 'has-error' : '';
        echo $this->partial(
            'partial/forms/inputBox.phtml', [
                'id'    => 'phone',
                'label' => 'Telephone number',
                'labelId' => 'telephone-number',
                'type'  => 'text',
                'classFormGroup' => $classFormGroup,
                'errors' => $errors['phone'],
                'classLabel' => 'form-label',
                'value' => $phone ? : '',
                'optional' => false,
            ]
        ); ?>

    </fieldset>

    <nav class="content-navigation">
        <?php
        echo $this->partial(
            'submitElement',
            [
                'label' => 'Continue',
                'id' => 'continue',
                'name' => 'action',
                'value' => 'Continue',
                'cssClass' => 'button'
            ]
        );
        ?>

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->emailStep()); ?>"
                   id="back">Back</a>
            </li>
        </ul>
    </nav>
</form>
