<?php

use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;

?>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $errorsSummary]); ?>

<form action="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->detailsStep()); ?>"
      method="POST" autocomplete="off" novalidate="">
    <?php echo $this->csrfToken(); ?>

    <fieldset>
        <legend class="form-title heading-large" id="newUserName">Name</legend>
        <p class="lede">Enter all of your names in full - don't use initials.</p>

        <?php
        $classFormGroup =  $firstNameHasError ? 'has-error' : '';
        echo $this->partial(
            'partial/forms/inputBox.phtml', [
                'id'    => 'firstName',
                'label' => 'First name',
                'labelId' => 'first-name',
                'type'  => 'text',
                'classFormGroup' => $classFormGroup,
                'errors' => $errors['firstName'],
                'classLabel' => 'form-label',
                'value' => $firstName ? : '',
                'optional' => false,
            ]
        );

        $classFormGroup =  $middleNameHasError ? 'has-error' : '';
        echo $this->partial(
            'partial/forms/inputBox.phtml', [
                'id'    => 'middleName',
                'label' => 'Middle name',
                'labelId' => 'middle-name',
                'type'  => 'text',
                'classFormGroup' => $classFormGroup,
                'errors' => $errors['middleName'],
                'classLabel' => 'form-label',
                'value' => $middleName ? : '',
                'optional' => true,
            ]
        );

        $classFormGroup =  $lastNameHasError ? 'has-error' : '';
        echo $this->partial(
            'partial/forms/inputBox.phtml', [
                'id'    => 'lastName',
                'label' => 'Last name',
                'labelId' => 'last-name',
                'type'  => 'text',
                'classFormGroup' => $classFormGroup,
                'errors' => $errors['lastName'],
                'classLabel' => 'form-label',
                'value' => $lastName ? : '',
                'optional' => false,
            ]
        ); ?>

    </fieldset>

    <legend class="form-title heading-large" id="newUserDob">Date of birth</legend>
    <p class="lede">
        This helps DVSA to identify you if you contact them.
    </p>
    <div class="form-group <?php if ($dateHasError) echo ' has-error' ?>">
            <fieldset>
                <div class="form-date <?php if ($dateHasError) echo ' has-error' ?>">
                    <p>Enter your date of birth</p>
                    <span class="form-hint">For example, 31 03 2015
                        <?php
                        if ($dateHasError) {
                            echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['date']]);
                        }
                        ?>
                    </span>
                    <div class="form-group form-group-day">
                        <label for="day">Day</label>
                        <input type="text" id="day" name="day" class="form-control" value="<?php echo $this->escapeHtmlAttr($day);?>">
                    </div>
                    <div class="form-group form-group-month">
                        <label for="month">Month</label>
                        <input type="text" id="month" name="month" class="form-control" value="<?php echo $this->escapeHtmlAttr($month);?>">
                    </div>
                    <div class="form-group form-group-year">
                        <label for="year">Year</label>
                        <input type="text" id="year" name="year" class="form-control" value="<?php echo $this->escapeHtmlAttr($year);?>">
                    </div>
                </div>
            </fieldset>
    </div>

    <nav class="content-navigation">
        <?php
        echo $this->partial(
            'submitElement',
            [
                'label' => 'Continue',
                'id' => 'continue',
                'name' => 'action',
                'value' => 'Continue',
                'cssClass' => 'button'
            ]
        );
        ?>

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->emailStep()); ?>"
                   id="back">Back</a>
            </li>
        </ul>
    </nav>
</form>
