<?php
use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;

?>

<div class="text">
    <p class="lede">Create your MOT testing account by providing us with the following details. We will create your User
        ID from this information.</p>
</div>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $errorsSummary]); ?>

<form action="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->detailsStep()); ?>"
      method="POST" autocomplete="off" novalidate="">
    <?php echo $this->csrfToken(); ?>

    <fieldset>
        <legend class="form-title heading-large" id="newUserName">Your name</legend>

        <div class="form-group<?php if ($firstNameHasError) echo ' has-error' ?>">
            <label for="firstName" class="form-label">
                First name
                <?php
                    if ($firstNameHasError) {
                        echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['firstName']]);
                    }
                ?>
            </label>
            <input type="text" name="firstName" id="firstName" class="form-control"
                   value="<?php echo $this->escapeHtmlAttr($firstName) ?>">
        </div>

        <div class="form-group">
            <label for="middleName" class="form-label">
                Middle name (optional)
            </label>
            <input type="text" name="middleName" id="middleName" class="form-control"
                   value="<?php echo $this->escapeHtmlAttr($middleName) ?>">
        </div>

        <div class="form-group<?php if ($lastNameHasError) echo ' has-error' ?>">
            <label for="lastName" class="form-label">
                Last name
                <?php
                if ($lastNameHasError) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['lastName']]);
                }
                ?>
            </label>
            <input type="text" name="lastName" id="lastName" class="form-control"
                   value="<?php echo $this->escapeHtmlAttr($lastName) ?>">
        </div>

    </fieldset>

    <fieldset>
        <legend class="form-title heading-large" id="email">Your email address</legend>


        <div class="form-group<?php if ($emailAddressHasError) echo ' has-error' ?>">
            <label for="emailAddress" class="form-label">
                Email address
                <span class="form-hint">Your User ID will be sent to this address</span>
                <?php
                if ($emailAddressHasError) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['emailAddress']]);
                }
                ?>
            </label>
            <input type="email" name="emailAddress" id="emailAddress" class="form-control form-control-1-3"
                   value="<?php echo $this->escapeHtmlAttr($emailAddress) ?>">
        </div>


        <div class="form-group<?php if ($confirmEmailAddressHasError) echo ' has-error' ?>">
            <label for="confirmEmailAddress" class="form-label">
                Re-type your email address
                <?php
                if ($confirmEmailAddressHasError) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['confirmEmailAddress']]);
                }
                ?>
            </label>
            <input type="email" name="confirmEmailAddress" id="confirmEmailAddress"
                   class="form-control form-control-1-3"
                   value="<?php echo $this->escapeHtmlAttr($confirmEmailAddress) ?>">
        </div>


    </fieldset>

    <nav class="content-navigation">

        <input type="submit" value="Continue" id="continue" class="button">

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->createStep()); ?>"
                   id="back">Back</a>
            </li>
        </ul>
    </nav>
</form>
