<?php
use \Dvsa\Mot\Frontend\SecurityCardModule\CardValidation\ViewModel\PinFailLockedViewModel;

/* @var PinFailLockedViewModel $pinFailLocked */
?>

<div class="banner banner--error column-two-thirds">
    <span class="banner__heading-large">Account locked for <?php echo $pinFailLocked->getLockoutTimeMins() ?> minutes</span>
    <span>Try again later or sign in without your security card</span>
</div>
<div class="text">
    <nav class="content-navigation">
        <a class="button" href="<?php echo $this->url('lost-or-forgotten-card') ?>">Sign in without your security card</a>
        <ul class="content-navigation__secondary">
            <li>
                <a id="logout" href ='<?php echo $this->url('logout') ?>'>Return to sign in</a>
            </li>
        </ul>
    </nav>
</div>
