<?php

use Report\Table\ColumnOptions;

/**
 * @var \Report\Table\Table
 * @var ColumnOptions[]     $columns
 */
$table = $this->table;
$columns = $table->getColumns();
$data = $table->getData();

if (empty($data)) {
    return null;
}
?>

<table class="<?php echo $table->getTableOptions()->getTableClass(); ?>" id="<?php echo $table->getTableOptions()->getTableId() ?>">
    <thead>
        <tr>
            <?php
            /** @var ColumnOptions $col */
            foreach ($columns as $col):
                $escTitle = $this->escapeHtml($col->getTitle());
                $escSortCssClass = $col->getSortCssClass();
                $escThColspan = $col->getThColspan();
                $escThCssClass = $col->getThClass();
                ?>
                <th scope="col" class="<?php echo $escThCssClass; ?>"
                    <?php if (!empty($escThColspan)): ?>
                        colspan="<?php echo $escThColspan; ?>"
                    <?php endif; ?>>
                    <?php if (!empty($col->getSortBy())): ?>
                        <a href="<?php echo $col->getUrl($this); ?>" class="<?php echo $escSortCssClass; ?>">
                            <?php echo $escTitle; ?>
                        </a>
                    <?php else:
                        echo $escTitle;
                    endif; ?>
                </th>
            <?php endforeach; ?>
        </tr>

        <?php if ($table->getTableOptions()->hasMetaTitle()): ?>
            <tr class="meta-row">
                <?php
                /** @var ColumnOptions $col */
                foreach ($columns as $col):
                    $escSubTitle = $this->escapeHtml($col->getSubTitle());
                    $escThSubTitleColspan = $col->getThSubTitleColspan();
                    ?>
                    <?php if (isset($escSubTitle) || isset($escThSubTitleColspan)): ?>
                        <th scope="col" colspan="<?php echo $escThSubTitleColspan; ?>">
                            <?php if (isset($escSubTitle)): ?>
                            <span class="table-default__meta">
                                <?php echo $escSubTitle; ?>
                            </span>
                            <?php  endif; ?>
                        </th>
                <?php endif;
                endforeach; ?>
            </tr>
        <?php endif; ?>
    </thead>

    <tbody>
        <?php foreach ($table->getData() as $row):
            ?>
            <tr>
                <?php foreach ($columns as $col):
                    $escTdCssClass = $col->getTdClass();
                    $escBody = $col->renderCellContent($row, $this);
                    ?>
                    <td class="<?php echo $escTdCssClass; ?>">
                        <?php echo $escBody ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>