<?php

/**
 * @var \Account\ViewModel\PasswordResetFormModel $viewModel
 * @var \DateInterval $interval
 */

$viewModel = $this->viewModel;

$errorMessages  = $this->layout()->flashMessenger->getErrorMessages();

$this->layout()->setVariable('pageSubTitle', '');
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);
?>

<p class="lede">We have sent you an email with a link to reset your password.</p>
<p>The link to reset your password will expire in 1 hour 30 minutes.</p>
<p>If you do not receive an email after 15 minutes and you have checked your spam folder, then: </p>
<p><?php echo lcfirst(trim($this->partial('partial/gds/general/contactHelpdesk', ['config' => $viewModel->getConfig()['helpdesk']]))); ?></p>

<?php

echo $this->partial(
    'partial/gds/form/control-navigation-secondary',
    [
        'navigation'    => [
            'Sign in' => '/',
        ]
    ]
);
?>
