<?php

$cfg = $viewModel['helpdesk'];

$phone = (isset($cfg['phoneNumber']) ? $cfg['phoneNumber'] : null);
$name = (isset($cfg['name']) ? $cfg['name'] : null);

$message = [
    [
        'type' => 'normal',
        'm' => 'Your user account does not contain an email address so we are unable to email the password reset instructions to you. Please contact the ' . $this->escapeHtml($name) . ' on '
    ],
    [
        'type' => 'bold',
        'm' => $phone
    ],
];
$errorMessages  = $this->layout()->flashMessenger->getErrorMessages();

?>

<?php echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']); ?>

<p class="lede">Your user ID has no email address so the password reset link <strong>cannot be emailed</strong> to you.</p>

<?php echo $this->partial('partial/gds/general/message', ['message' => $message]); ?>

<?php echo $this->partial(
    'partial/gds/form/control-navigation-secondary',
    [
        'navigation'    => [
            'Sign in' => '/',
        ]
    ]
); ?>
