<?php
$errorMessages = $this->layout()->flashMessenger->getErrorMessages();
?>

<?php echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']); ?>

<p class="lede">Contact the DVSA helpdesk to reset your account security.</p>

<div>
    <?php echo $this->partial('partial/gds/general/contactHelpdesk', ['config' => $viewModel['helpdesk']]); ?>
</div>

<p>You will need to prove your identity by answering some questions about yourself.</p>

<?php if ($isLoggedIn === false): ?>
    <?php echo $this->partial(
        'partial/gds/form/control-navigation-secondary',
        [
            'navigation'    => [
                'Sign in' => '/',
            ]
        ]
    ); ?>
<?php endif; ?>
