<?php

/**
 * @var ChangePasswordFormModel
 */
use Account\ViewModel\ChangePasswordFormModel;
use DvsaCommon\UrlBuilder\AccountUrlBuilderWeb;

$this->headScript()->appendFile('/js/dvsa.js');

//  --  errors  --
$errorMessages = $this->layout()->flashMessenger->getErrorMessages();
$successMessages = $this->layout()->flashMessenger->getSuccessMessages();

echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);

if (!count($errorMessages)):

$this->inlineScript()->appendFile('/js/dvsa.js');

?>
<form method="POST">
    <?php
    echo $this->csrfToken();

    echo $this->partial(
        'partial/gds/general/password-criteria',
        [
            'username' => $viewModel->getUsername(),
        ]
    );
    ?>

    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id' => ChangePasswordFormModel::FIELD_PASS,
                'errorMessage' => $viewModel->getError(ChangePasswordFormModel::FIELD_PASS),
                'label' => 'New password',
                'value' => $viewModel->getPassword(),
                'type' => 'password',
            ]
        );

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id' => ChangePasswordFormModel::FIELD_PASS_CONFIRM,
                'errorMessage' => $viewModel->getError(ChangePasswordFormModel::FIELD_PASS_CONFIRM),
                'label' => 'Confirm new password ',
                'value' => $viewModel->getPasswordConfirm(),
                'type' => 'password',
            ]
        );
        ?>
    </fieldset>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id' => 'submitPass',
            'value' => 'Reset password',
        ]
    ); ?>
</form>

<?php endif; ?>

<?php if ($viewModel->isTryAgainLink()) : ?>
    <nav class="content-navigation">
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo AccountUrlBuilderWeb::of()->forgottenPassword(); ?>">Try again</a>
            </li>
        </ul>
    </nav>
<?php endif; ?>
