<?php

/**
 * @var PasswordResetFormModel
 */
use Account\ViewModel\PasswordResetFormModel;

$this->headTitle('Forgotten your password');

?>

<p class="lede">Answer your security questions to reset your password.</p>

<?php
$errorMessages = $this->layout()->flashMessenger->getErrorMessages();
$successMessages = $this->layout()->flashMessenger->getSuccessMessages();

echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);
?>

<form id="usernameValidationForm" method="POST" action="<?php echo $viewModel->getCurrentPage() ?>">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <?php
        echo $this->partial(
           'partial/gds/form/control-legend', [
                'id' => 'userAccount',
                'text' => 'User ID',
                'altLegendClass' => 'heading-medium',
             ]
        );

        echo '<p>For example, SMIT0001</p>';

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id' => PasswordResetFormModel::FIELD_USERNAME,
                'errorMessage' => $viewModel->getError(PasswordResetFormModel::FIELD_USERNAME),
                'label' => 'User ID',
                'value' => $viewModel->getUsername(),
                'autoCompleteOff' => true,
                'labelVisuallyHidden' => true,
                'errorOutsideLabel' => true,
            ]
        );
        ?>
    </fieldset>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id' => 'submitUserId',
            'value' => 'Continue',
            'navigation' => [
                'Cancel and return to sign in' => '/',
            ],
        ]
    ); ?>
</form>

<script>
    document.onreadystatechange = function () {
        $('#usernameValidationForm').submit(function() {
            $('#submitUserId').attr('disabled','disabled');
        });
    };
</script>
