<?php

/**
 * @var PasswordResetFormModel   $viewModel
 */

use Account\ViewModel\PasswordResetFormModel;

$this->headTitle('Forgotten your password');

?>

<p class="lede">You can reset your password by answering your chosen security questions.</p>

<?php
$errorMessages = $this->layout()->flashMessenger->getErrorMessages();
$successMessages = $this->layout()->flashMessenger->getSuccessMessages();

echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);
?>

<form id="usernameValidationForm" method="POST" action="<?php echo $viewModel->getCurrentPage() ?>">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <?php
        echo $this->partial(
           'partial/gds/form/control-legend', [
                'id' => 'userAccount',
	            'text' => 'User ID',
                'altLegendClass' => 'heading-medium',
             ]
        );

        echo '<p>Tell us your user ID so that we can find your security questions.</p>';

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => PasswordResetFormModel::FIELD_USERNAME,
                'errorMessage'  => $viewModel->getError(PasswordResetFormModel::FIELD_USERNAME),
                'label'         => 'User ID',
                'value'         => $viewModel->getUsername(),
                'autoCompleteOff' => true,
                'labelVisuallyHidden' => true,
                'errorOutsideLabel' => true,
            ]
        );
        ?>
    </fieldset>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'            => 'submitUserId',
            'value'         => 'Continue',
            'navigation'    => [
                'Cancel and return to sign in' => '/',
            ]
        ]
    ); ?>
</form>

<script>
    document.onreadystatechange = function () {
        $('#usernameValidationForm').submit(function() {
            $('#submitUserId').attr('disabled','disabled');
        });
    };
</script>
