<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DvsaEventApi\Controller\EventController'          => __DIR__ . '/src/DvsaEventApi/Controller/EventController.php',
  'DvsaEventApi\Factory\Service\EventServiceFactory' => __DIR__ . '/src/DvsaEventApi/Factory/Service/EventServiceFactory.php',
  // REMOVED INVALID MAP: 'EventService'                                     => __DIR__ . '/src/DvsaEventApi/Factory/Service/EventServiceFactory.php',
  // REMOVED INVALID MAP: 'getRepository'                                    => __DIR__ . '/src/DvsaEventApi/Factory/Service/EventServiceFactory.php',
  // REMOVED INVALID MAP: 'get'                                              => __DIR__ . '/src/DvsaEventApi/Factory/Service/EventServiceFactory.php',
  'DvsaEventApi\Service\EventService'                => __DIR__ . '/src/DvsaEventApi/Service/EventService.php',
  'DvsaEventApi\Service\Mapper\EventListMapper'      => __DIR__ . '/src/DvsaEventApi/Service/Mapper/EventListMapper.php',
);
