<?php
use Core\Formatting\AddressFormatter;
use DvsaCommon\Enum\SiteContactTypeCode;

/** @var \DvsaCommon\Dto\Site\VehicleTestingStationDto $site */

$site = $this->viewModel->site;
$siteAddress = null;
if(!is_null($site)){
    $contact = $site->getContactByType(SiteContactTypeCode::BUSINESS);
    if(!is_null($contact)){
        $siteAddress = $contact->getAddress();
    }
}

?>
<?php echo $this->partial('errorMessages', array('getFromFlash' => true)); ?>
<h3 class="summary-heading">Certificate details</h3>


<?php
echo $this->partial(
    'partial/gds/gds-table/gds-key-value-table',
    [
        'table' => $this->viewModel->table,
    ]
);
?>

<h3 class="summary-heading">Location of Demo test</h3>

<table class="key-value-list">
    <tbody>
    <tr>
        <th class="key-value-list__key">
            VTS ID
        </th>
        <td class="key-value-list__value">
            <?php echo $site ? $site->getSiteNumber() : 'Not recorded' ?>
        </td>
    </tr>
    <tr>
        <th class="key-value-list__key">
            Vehicle Testing Station
        </th>
        <td class="key-value-list__value">
            <?php echo $site ? $site->getName() : 'Unknown' ?>
            <span class="key-value-list__meta"><?php echo $siteAddress ? (new AddressFormatter())
                    ->setAddressPartsGlue(', ')
                    ->escapedDtoToMultiLine($siteAddress)
                : '' ?></span
        </td>
    </tr>
    </tbody>
</table>

<form novalidate="" autocomplete="off" method="POST" action="">
    <?php echo $this->csrfToken(); ?>

    <nav class="content-navigation">
        <input type="submit" class="button" value="Add certificate" id="confirm-button">
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->viewModel->backUrl ?>">Back to add a certificate</a>
            </li>
        </ul>
    </nav>
</form>
