<?php
use Dvsa\Mot\Frontend\PersonModule\ViewModel\QualificationDetailsViewModel;

/**
 * @var QualificationDetailsViewModel $viewModel
 */

?>
<?php echo $this->partial('infoMessages', ['getFromFlash' => true]); ?>
<?php
$successMessages = $this->layout()->flashMessenger->getSuccessMessages();
echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
?>
<?php echo $this->partial('errorMessages', array('getFromFlash' => true)); ?>

<?php if ($viewModel->canUserSeeGuidance()): ?>
    <div class="text">
        <p class="lede">
            If you’ve passed your initial MOT tester training, enter your certificate details to request a demo test.
        </p>
        <p>We’ll contact you to arrange a demo MOT test with a Vehicle Examiner.</p>
    </div>
<?php endif ?>

<div>
    <h3 class="summary-heading">
        Group A
        <span class="summary-heading__action">
            Class 1 and 2
        </span>
    </h3>
    <?php echo $this->partial(
        'partial/gds/gds-table/gds-summary-smaller-key-table',
        [
            'table' => $viewModel->getQualificationDetailsGroupAViewModel()->getTable('group-A'),
        ]
    );?>

    <h3 class="summary-heading">
        Group B
        <span class="summary-heading__action">
            Class 3, 4, 5 and 7
        </span>
    </h3>
    <?php echo $this->partial(
        'partial/gds/gds-table/gds-summary-smaller-key-table',
        [
            'table' => $viewModel->getQualificationDetailsGroupBViewModel()->getTable('group-B'),
        ]
    );?>

    <nav class="content-navigation">
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $viewModel->getReturnLink() ?>"><?php echo $viewModel->getReturnLinkText() ?></a>
            </li>
        </ul>
    </nav>
</div>