<?php

use Core\ViewModel\Gds\Table\GdsTable;

/** @var GdsTable $table */
if (!isset($table) || !$table instanceof GdsTable) {
    throw new InvalidArgumentException('This partial expects variable $table of type '.GdsTable::class);
}

?>
<table class="key-value-list">
    <?php if ($table->isHeaderSet()): ?>
        <thead>
        <tr>
            <th colspan="2">
                <?php echo $this->escapeHtml($table->getHeaderText()); ?>
            </th>
        </tr>
        </thead>
        <tbody>
    <?php endif ?>
    <?php foreach ($table->getRows() as $row): ?>
        <tr>
            <?php
                $id = $row->getHtmlId();
                $escape = $row->getValue()->isEscapeRequired();
                $value = $row->getValue()->getContent();
                $value = ($value === null ? 'N/A' : $value);
            ?>

            <th class="key-value-list__key">
                <?php echo $this->escapeHtml($row->getLabel()->getContent()); ?>
            </th>

            <td class="key-value-list__value"
                <?php
            echo $id ? ' id="'.$this->escapeHtmlAttr($id).'"' : '';
            echo $row->isHtmlClassSet() ? ' class="'.$this->escapeHtmlAttr($row->getHtmlClass()).'"' : '';
            echo $colspan ? ' colspan="'.$this->escapeHtmlAttr($colspan).'"' : '';
            ?>>
                <?php echo $escape ? $this->escapeHtml($value) : $value; ?>
            </td>
            <?php if (!empty($row->hasActionLink())):
                echo '<td class="key-value-list__item-action">';

                foreach ($row->getActionLinks() as $actionLink):
                    $id = ($actionLink->getHtmlId()) ? $actionLink->getHtmlId() : 'change';
                    echo '<a href="'.$actionLink->getUrl().'" title="'.$actionLink->getTooltip().'"'.($row->getHtmlId() ? (' id="'.$this->escapeHtmlAttr($row->getHtmlId()).'-'.$id.'"') : '')
                        .'>'.$actionLink->getText().'<span class="visuallyhidden"> '.$this->escapeHtml($row->getLabel()->getContent()).'</span>
                        </a>&nbsp';
                endforeach;

                echo '</td>';

                endif;
            ?>

        </tr>
    <?php endforeach; ?>
    </tbody>
</table>