<?php

use DvsaCommon\UrlBuilder\VehicleTestingStationUrlBuilderWeb;
use DvsaCommon\Utility\ArrayUtils;

$days = [
    1 => 'Monday',
    2 => 'Tuesday',
    3 => 'Wednesday',
    4 => 'Thursday',
    5 => 'Friday',
    6 => 'Saturday',
    7 => 'Sunday'
];

$errorData = isset($errorData) ? $errorData : '';

$openHours = $this->siteOpeningHours;
?>
<h1>
    <small>Vehicle Testing Station</small>
    <span>Change testing hours</span>
</h1>

<hr class="hr-thick">

<?php echo $this->partial('errorMessages', ['getFromFlash' => true]); ?>

<div class="row" id="opening-hours">
    <div class="col-sm-8">
        <form method="POST" role="form">
            <?php echo $this->csrfToken() ?>

            <?php for($i = 0; $i < 7; $i++) :
                $dayName = strtolower($days[$i+1]);

                $isOpenTimeAm = (ArrayUtils::tryGet($openHours, $dayName.'OpenTimePeriod') === 'am');
                $isOpenTimePm = (ArrayUtils::tryGet($openHours, $dayName.'OpenTimePeriod') === 'pm');
                $isCloseTimeAm = (ArrayUtils::tryGet($openHours, $dayName.'CloseTimePeriod') === 'am');
                $isCloseTimePm = (ArrayUtils::tryGet($openHours, $dayName.'CloseTimePeriod') === 'pm');

                $isClosedVal = ArrayUtils::tryGet($openHours, $dayName . 'IsClosed');
                $isClosed = (bool) ($isClosedVal === null || $isClosedVal === 'true' ? true : $isClosedVal);

                $openTime = ArrayUtils::tryGet($openHours, $dayName.'OpenTime');
                $closeTime = ArrayUtils::tryGet($openHours, $dayName.'CloseTime');

                //  errors
                $errOpenTime = ArrayUtils::tryGet($errorData, $dayName."OpenTime");
                $isErrOpenTime = !empty($errOpenTime);

                $errCloseTime = ArrayUtils::tryGet($errorData, $dayName."CloseTime");
                $isErrCloseTime = !empty($errCloseTime);
                ?>

                <fieldset>
                    <legend><?php echo $this->escapeHtml($days[$i+1]);?></legend>

        <div class="row">
            <div class="col-sm-2">
                <!--<div class="form-group has-error">-->
                <div class="form-group <?php echo ($isErrOpenTime ? 'has-error" id="error-'. $errOpenTime['ref'] : '') ?>">
                    <label class="control-label" for="<?php echo $this->escapeHtml($dayName);?>-time-text-open">Opening Time</label>
                    <input type="text"
                       class="form-control form-control-xs"
                       id="<?php echo $this->escapeHtml($dayName);?>-time-text-open"
                       name="<?php echo $this->escapeHtml($dayName);?>OpenTime"
                       value="<?php echo $this->escapeHtml($openTime);?>">
			   </div>
		    </div>

		    <div class="col-sm-4">
                <div class="form-group">
                    <label class="block-label" for="<?php echo $this->escapeHtml($dayName);?>-am-radio-open">
                        <input type="radio" value="am"
                           name="<?php echo $this->escapeHtml($dayName);?>OpenTimePeriod"
                           id="<?php echo $this->escapeHtml($dayName);?>-am-radio-open"
                           <?php echo $isOpenTimeAm ? 'checked' : '' ?>>
                        am
                    </label>
                    <label class="block-label" for="<?php echo $this->escapeHtml($dayName);?>-pm-radio-open">
                        <input type="radio" value="pm"
                           name="<?php echo $this->escapeHtml($dayName);?>OpenTimePeriod"
                           id="<?php echo $this->escapeHtml($dayName);?>-pm-radio-open"
                           <?php echo $isOpenTimePm ? 'checked' : '' ?>>
                        pm
                    </label>
                </div>
            </div>
		</div>

		<div class="row">
		    <div class="col-sm-2">
			    <!--<div class="form-group has-error">-->
			    <div class="form-group <?php echo ($isErrCloseTime ? 'has-error" id="error-'. $errCloseTime['ref'] : '') ?>">
				<label class="control-label" for="<?php echo $this->escapeHtml($dayName);?>-time-text-close">Closing time</label>
				    <input type="text"
					   class="form-control form-control-xs"
					   id="<?php echo $this->escapeHtml($dayName);?>-time-text-close"
					   name="<?php echo $this->escapeHtml($dayName);?>CloseTime"
					   value="<?php echo $this->escapeHtml($closeTime)?>">
			    </div>
		    </div>
		    <div class="col-sm-4">
			<div class="form-group">
				<label class="block-label" for="<?php echo $this->escapeHtml($dayName);?>-am-radio-close">
				    <input type="radio" value="am"
					   name="<?php echo $this->escapeHtml($dayName);?>CloseTimePeriod"
					   id="<?php echo $this->escapeHtml($dayName);?>-am-radio-close"
					   <?php echo $isCloseTimeAm ? 'checked' : '' ?>>
				    am
				</label>
				<label class="block-label" for="<?php echo $this->escapeHtml($dayName);?>-pm-radio-close">
				    <input type="radio" value="pm"
					   name="<?php echo $this->escapeHtml($dayName);?>CloseTimePeriod"
					   id="<?php echo $this->escapeHtml($dayName);?>-pm-radio-close"
					    <?php echo $isCloseTimePm ? 'checked' : '' ?>>
				    pm
				</label>
		        </div>
                    </div>
	        </div>

            <?php if($isErrOpenTime) : ?>
                <div class="row">
                    <div class="col-sm-12"><?php echo $this->escapeHtml($errOpenTime['error']['displayMessage']) ?></div>
                </div>
            <?php endif; ?>

            <?php if($isErrCloseTime) : ?>
                <div class="row">
                    <div class="col-sm-12"><?php echo $this->escapeHtml($errCloseTime['error']['displayMessage']) ?></div>
                </div>
            <?php endif; ?>

		<div class="row">
		    <div class="col-sm-6">
			<div class="info-notice">
			    <div class="form-group">
			    <p>
			    <?php echo $this->partial(
				'checkboxElement',
				[
				    'id'        => $dayName . 'isClosed',
				    'labelId'   => $dayName . 'isClosedLabel',
				    'value'     => 'true',
				    'name'      => $this->escapeHtml($dayName).'IsClosed',
                    'isChecked' => $isClosed,
				    'label'     => 'Closed all day ' . $dayName,
				]
				); ?>
			    </p>
			    </div>
			</div>
	           </div>
		</div>

                </fieldset>
            <?php endfor; ?>

            <p>
                <button id="update-opening-hours" type="submit" class="btn btn-primary">Change testing hours</button>
            </p>
            <p>
                <a href="<?php echo VehicleTestingStationUrlBuilderWeb::byId($this->siteId); ?> ">
                    Cancel and return to Vehicle Testing Station
                </a>
            </p>
        </form>
    </div>
</div>
