<?php

use DvsaCommon\Date\DateTimeDisplayFormat;

/**
 * @var \Event\ViewModel\Event\EventDetailViewModel     $viewModel
 */

?>
<?php
    echo $this->partial('errorMessages', ['getFromFlash' => true, 'isShowHidden' => true]);
    echo $this->partial('infoMessages', ['getFromFlash' => true]);
?>
<table class="key-value-list">
    <tbody>
        <tr>
            <th class="key-value-list__key">Event type</th>
            <td class="key-value-list__value"><?php echo $this->escapeHtml($viewModel->getEvent()->getType()); ?></td>
        </tr>
        <tr>
            <th class="key-value-list__key">Description</th>
            <td class="key-value-list__value">

                <?php
                    $outcome = $this->escapeHtml($viewModel->getEvent()->getEventOutcomeDescription());
                    $notes = $this->escapeHtml($viewModel->getEvent()->getDescription());
                ?>
               <?php
                    if($outcome!= '') {
                        echo'<strong>'.$outcome.'<strong>'. '<span class="key-value-list__meta">'.$notes.'</span>';

                    } else {
                        echo $notes;
                    }
                ?>
            </td>
        </tr>
        <tr>
            <th class="key-value-list__key">Added by</th>
            <td class="key-value-list__value">
                <?php echo $this->escapeHtml($viewModel->getEvent()->getAddedByName()); ?>
            </td>
        </tr>
        <tr>
            <th class="key-value-list__key">Event date</th>
            <td class="key-value-list__value">
                <?php echo $this->escapeHtml(DateTimeDisplayFormat::textDate($viewModel->getEvent()->getDate())); ?>
            </td>
        </tr>
    </tbody>
</table>

<nav class="content-navigation">

    <ul class="content-navigation__secondary">
        <li><a href="<?php echo $viewModel->getGoBackLink(); ?>">Go back</a></li>
    </ul>

</nav>

