<?php

use DvsaCommon\Date\DateTimeDisplayFormat;

/**
 * @var \Event\ViewModel\Event\EventDetailViewModel     $viewModel
 */

?>
<div class="row">
    <div class="col-lg-12">
        <h1>
            <small><?php echo $this->escapeHtml($viewModel->getTitle()); ?></small>
            <span><?php echo $this->escapeHtml($viewModel->getName()); ?></span>
        </h1>
        <hr class="hr-thick"/>
    </div>
</div>
<?php
    echo $this->partial('errorMessages', ['getFromFlash' => true, 'isShowHidden' => true]);
    echo $this->partial('infoMessages', ['getFromFlash' => true]);
?>
<div class="row contents">
    <div class="col-lg-12">

        <div class="row module-present-data">
            <div class="col-sm-4">
                <h3>Event details</h3>
            </div>

            <dl class="vertical col-sm-4 " >
                <dt >Event type</dt>
                <dd  id="event-type"><?php echo $this->escapeHtml($viewModel->getEvent()->getType()); ?></dd>
            </dl>

            <dl class="vertical col-sm-4" >
                <dt >Event date</dt>
                <dd  id="event-date"><?php echo $this->escapeHtml(DateTimeDisplayFormat::textDateTimeShort($viewModel->getEvent()->getDate())); ?></dd>
            </dl>
        </div>
        <div class="row module-present-data">
            <dl class="vertical col-sm-8 col-sm-offset-4" >
                <dt >Description</dt>
                <dd  id="description"><?php echo $this->escapeHtml($viewModel->getEvent()->getDescription()); ?></dd>
            </dl>
        </div>

        <hr class="hr-thin"/>

        <div class="row btn-bar">
            <div class="col-lg-12 btn-bar">
                <a href="<?php echo $viewModel->getGoBackLink(); ?>">Go back</a>
            </div>
        </div>
    </div>
</div>