<?php

use DvsaCommon\Date\DateTimeDisplayFormat;

// $this->headLink()->appendStylesheet('/css/jquery.dataTables.css');
// $this->headLink()->appendStylesheet('/assets/stylesheets/dataTables.css');

/**
 * @var \Event\ViewModel\Event\EventViewModel
 * @var \DvsaCommon\Dto\Organisation\OrganisationDto $organisation
 * @var array                                        $site
 * @var \DvsaClient\Entity\Person                    $person
 * @var \DvsaCommon\Dto\Event\EventFormDto           $formModel
 * @var \DvsaClient\ViewModel\DateTimeViewModel      $dateFrom
 * @var \DvsaClient\ViewModel\DateTimeViewModel      $dateTo
 */
$formModel = $viewModel->getFormModel();
$isShowDate = $formModel->isShowDate();
$search = $formModel->getSearch();
$dateFrom = $formModel->getDateFrom();
$dateTo = $formModel->getDateTo();

$events = $viewModel->getEventList()->getEvents();

$goBackLink = $viewModel->getGoBackLink();

?>

<div class="">

<?php
    echo $this->partial('partial/gds/general/system-message.phtml', [
            'messages' => $this->flashMessenger()->getErrorMessages(),
            'type' => 'failure',
        ]
    );

    echo $this->partial('partial/gds/general/system-message.phtml', [
            'messages' => $this->flashMessenger()->getSuccessMessages(),
            'type' => 'success',
        ]
    );

    // TODO: Format/classes for error messages
    //echo $this->partial('errorMessages', ['getFromFlash' => true, 'isShowHidden' => true]);
    echo $this->partial('infoMessages', ['getFromFlash' => true]);
?>

</div>

<div class="layout-filter-data data-tables">

    <!-- data table col 2/3 start -->
    <div class="layout-filter-data__results">

        <h2 class="result__group-heading" id="events-title">Loading events list...</h2>

        <div class="slot-usage-table">
            <div class="table-responsive">
                <table class="table table-striped nowrap" id="listLogs">
                    <thead>
                    <tr>
                        <th>Type</th>
                        <th width="20%">Date</th>
                        <th>Description</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 0; ?>
                    <input name="go_back_link" value="<?php echo $goBackLink ?>" style="display: none">
                    <?php foreach ($events as $event): ?>
                        <?php $escClass = ($i++ % 2 == 0 ? 'even' : 'odd'); ?>
                        <tr class="<?php echo $escClass; ?>">
                            <td class="truncate" title="<?php echo $this->escapeHtml($event->getType()); ?>">
                                <a href="<?php
                                    echo $viewModel->getEventDetailLink($event->getId());
                                ?>">
                                    <?php echo $this->escapeHtml($event->getType()); ?>
                                </a>
                            </td>
                            <td><?php echo DateTimeDisplayFormat::textDateShort($event->getDate()); ?></td>

                            <?php
                                $tempDescription = $this->escapeHtml($event->getDescription());
                                $tempOutcome = $this->escapeHtml($event->getEventOutcomeDescription());

                                if (!empty($tempOutcome)) {
                                    $finalDescription = $tempOutcome.'. '.$tempDescription;
                                } else {
                                    $finalDescription = $tempDescription;
                                }
                            ?>

                            <td class="truncate" title="<?php echo $finalDescription; ?>">
                                <?php echo $finalDescription; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

                 <div class="" style="margin-top:20px;">
                     <?php if ($canRecordEvent === true): ?>
                        <a href="<?php echo $this->escapeHtmlAttr($this->url('event-manual-add/start', array('type' => $type, 'id' => $id))); ?>">Record an event</a>
                    <?php endif; ?>

                </div>

            </div>

        </div>

    </div>
    <!-- data table col 2/3 end -->

    <!-- filters col 1/3 start -->
    <div class="layout-filter-data__filters">

        <h2 class="filter__group-heading">Filters</h2>

        <form action="" method="GET" name="CustomDateSearch" class="form-vertical" id="eventsFilterForm">

            <div class="filter">
                <label for="filter-search" class="filter__heading">Search</label>
                <div class="filter__content--text">
                    <!--<input id="filter-search" type="text" class="form-control">-->
                    <?php
                    echo $this->partial(
                        'inputElement',
                        [
                            'name' => 'search',
                            'id' => 'search',
                            'class' => 'form-control',
                            'value' => $search,
                        ]
                    );
                    ?>
                </div>
                <span class="filter__help">Filter by Type and/or Description.</span>
            </div>

            <div class="filter">
                <h3 class="filter__heading">Filter by date range</h3>
                <?php
                echo $this->partial(
                    'hiddenElement',
                    [
                        'name' => 'isShowDate',
                        'id' => 'isShowDate',
                        'value' => $isShowDate,
                    ]
                );
                //'value' => $isShowDate
                ?>
                <!-- <h3 class="filter__heading">Custom date</h3> -->
                <div class="filter__content" id="dateRangeFields">

                    <div class="form-group module-filters">
                        <fieldset>
                            <?php
                            echo $this->partial(
                                'partials/form/date-group.phtml',
                                [
                                    'legend' => 'From',
                                    'fieldKey' => \DvsaCommon\Dto\Event\EventFormDto::FLD_DATE_FROM,
                                    'valueDay' => $dateFrom->getDay(),
                                    'valueMonth' => $dateFrom->getMonth(),
                                    'valueYear' => $dateFrom->getYear(),
                                    'hint' => 'For example, 31 03 2015',
                                ]
                            );
                            echo $this->partial(
                                'partials/form/date-group.phtml',
                                [
                                    'legend' => 'To',
                                    'fieldKey' => \DvsaCommon\Dto\Event\EventFormDto::FLD_DATE_TO,
                                    'valueDay' => $dateTo->getDay(),
                                    'valueMonth' => $dateTo->getMonth(),
                                    'valueYear' => $dateTo->getYear(),
                                    'hint' => '',
                                ]
                            );
                            ?>
                            <input type="submit" name="submit" class="button btn-primary" value="Apply">

                        </fieldset>

                        <a href="<?php echo $viewModel->getCurrentPage(); ?>">Reset date filter</a>

                    </div>

                </div>

            </div>

        </form>

    </div>

    <!-- filters col 1/3 end-->

</div>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a href="<?php echo $viewModel->getGoBackLink(); ?>">Return to the  <?php echo $this->escapeHtml($viewModel->getEventType()); ?> overview</a>
        </li>
    </ul>
</nav>


<?php
/**
 * To enable the password validator's JS widget.
 */
$currentPage = $viewModel->getCurrentPage();
$isShowDateValue = '';
if ($isShowDate === true) {
    $isShowDateValue = 'true';
} else {
    $isShowDateValue = 'false';
}

$inlineScript = <<<EOT
    $(document).ready(function () {
        new EventListHelper($isShowDateValue, '$currentPage');
    });
EOT;

$this->headScript()
        ->appendFile('/assets/javascripts/vendor/jquery.dataTables.min.js')
        ->appendFile('/assets/javascripts/dataTables.events.min.js')
        ->appendScript($inlineScript);
?>

