<?php

use Organisation\Form\AeStatusForm;

/**
 * @var \Organisation\ViewModel\AuthorisedExaminer\AeFormViewModel $model
 * @var AeStatusForm                                               $form
 * @var \Zend\Mvc\Controller\Plugin\FlashMessenger                 $flashMessenger
 */

$model = $this->model;
$form = $model->getForm();

//  show api errors
$flashMessenger = $this->layout()->flashMessenger;
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'failure']
);
?>

<form method="POST" action="<?php echo $form->getFormUrl(); ?>">
    <?php echo $this->csrfToken() ?>
    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendStatusAreaOffice', 'text' => 'Status']
        );
        echo $this->partial(
            'partial/gds/form/control-select-group',
            [
                'id'           => AeStatusForm::FIELD_STATUS,
                'label'        => 'AE status',
                'errorMessage' => $form->getError(AeStatusForm::FIELD_STATUS),
                'value'        => $form->getStatus(),
                'options'      => $form->getStatuses(),
                'inputModifier'=> '1-4',
            ]
        );
        ?>
    </fieldset>

    <?php
    echo $this->partial(
        '/organisation/authorised-examiner/partials/area-office-select',
        [
            'value' => $form->getAssignedAreaOffice(),
            'options' => $form->getAreaOfficeOptions(),
            'errorMessage' => $form->getError(AeStatusForm::FIELD_AO_NUMBER),
        ]
    );

//    // TODO: Currently (27/Aug/15) there exists no way to look up a site entity
//    // by "area number". 1.16 is due by *next* Tuesday. Deal with it! Putting
//    // this string here allows us to ->findOneBy(/siteNumber/) in the API.
//    echo $this->partial(
//        'partials/form/hidden-element',
//        [
//            'name' => 'area-office-label',
//            'value' => $form->getAssignedAreaOfficeLabel()
//        ]
//    )
    ?>

    <?php
    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'         => 'submitAeStatus',
            'value'      => 'Continue to summary',
            'navigation' => [
                'Cancel and return to AE details' => $model->getCancelUrl(),
            ],
        ]
    );
    ?>
</form>
