<?php $this->layout('layout/layout-govuk.phtml'); ?>
    <header class="transaction-header">
        <h1 class="transaction-header__title">Your security card has been ordered</h1>
        <p class="transaction-header__next-step">Activate your card as soon as it arrives</p>
    </header>
    <div class="text">
            <h3 class="heading-medium">What happens next?</h3>
            <p>Your card will be delivered by second class post and should arrive within 5 working days. You do not have to sign for the delivery.</p>
            <p>You can continue to sign in until then, using:</p>
            <ul class="list-bullet">
                <li>your user ID</li>
                <li>your password</li>
                <li>your security questions</li>
            </ul>
            <p>Activate your card as soon as it arrives. You can do this from your profile.</p>
            <p>If the card hasn’t arrived in 7 working days then contact the helpdesk.</p>
            <nav class="content-navigation">
                <ul class="content-navigation__secondary">
                    <li>
                        <a href="/">Continue to home</a>
                    </li>
                </ul>
            </nav>
    </div>