<?php
use Zend\Form\Form;

/** @var Form $form */
/** @var bool $useFormName */

if($form->getMessages()): ?>

<div class="validation-summary" id="validation-summary-id">
    <h2 class="heading-medium">There was a problem</h2>
    <ol>
        <?php /** @var \Zend\Form\ElementInterface $element */ ?>
        <?php foreach($form->getElements() as $element): ?>
            <?php foreach($element->getMessages() as $message): ?>
                <li>
                    <?php if(isset($useFormName) && true === $useFormName): ?>
                        <?php
                        // you can't have spaces (and other "special" characters (e.g dots) in form's name attribute so its better to use
                        // underscores in forms name and replace those here to get better looking validation msg.
                        ?>
                        <?php echo $this->escapeHtml(str_replace('_',' ',$element->getName())); ?> -
                        <?php echo $this->escapeHtml(lcfirst($message)); ?>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($element->getLabel()); ?> -
                        <?php echo $this->escapeHtml(lcfirst($$message)); ?>
                    <?php endif; ?>

                </li>
                <?php break; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
