<?php
use DvsaCommon\Auth\PermissionInSystem;

$hasInProgressTest = $this->dashboardDataProvider()->hasTestInProgress();
?>

<section class="module-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-8 hero-content">
                <h1>
                    <small>MOT modernisation</small>
                    Your home
                </h1>
                <p>DVSA administrator view</p>
            </div>
            <div class="col-md-4 hero-actions">
                <?php if ($hasInProgressTest && $this->authorisationHelper()->isGranted(PermissionInSystem::MOT_TEST_REINSPECTION_PERFORM)) : ?>
                    <a href="<?php echo $this->url(
                        'mot-test',
                        ['motTestNumber' => $this->dashboardDataProvider()->getInProgressTestNumber()]
                    ); ?>"
                       class="btn btn-primary btn-lg"
                       id="action-resume-mot-test">Resume Reinspection
                        <span class="fa fa-chevron-right"> </span>
                    </a>
                <?php endif; ?>
                <h2>Advanced searches</h2>
                <?php echo $this->partial('primaryAction/links', ['dashboard' => $dashboard]); ?>
            </div>
        </div>
    </div>
</section>
