<section class="module-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-8 hero-content">
                <h1>
                    <small>MOT modernisation</small>
                    Your home
                </h1>
                <p>Authorised Examiner management view</p>
            </div>
            <div class="col-md-4 hero-actions">
                <h2>Slot balance</h2>

                <p class="large-text" id="slot-count"><?php echo intval($dashboard->getOverallSlotCount()); ?></p>
                <?php $siteNumber = intval($dashboard->getOverallSiteCount()); ?>
                <?php if ($siteNumber > 1) : ?>
                    <p>for <?php echo $this->escapeHtml($siteNumber); ?> sites</p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
