<?php
use DvsaCommon\Auth\PermissionInSystem;
use DvsaMotTest\Controller\VehicleSearchController;
?>
<section class="module-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-8 hero-content">
                <h1>
                    <small>MOT modernisation</small>
                    Your home
                </h1>
                <p>Authorised Examiner management view</p>
            </div>
            <div id="hero-actions" class="col-md-4 hero-actions">
                <h2>Slot balance</h2>

                <p class="large-text" id="slot-count"><?php echo intval($dashboard->getOverallSlotCount()); ?></p>
                <?php $siteNumber = intval($dashboard->getOverallSiteCount()); ?>
                <?php if ($siteNumber > 1) : ?>
                    <p>for <?php echo $this->escapeHtml($siteNumber); ?> sites</p>
                <?php endif; ?>

                <ul class="list-unstyled">
                    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::CERTIFICATE_SEARCH)): ?>
                        <li>
                            <a href="<?php echo $this->url(VehicleSearchController::ROUTE_REPLACEMENT_CERTIFICATE_VEHICLE_SEARCH); ?>"
                               id="action-start-certificate-reissue">
                                replacement/duplicate certificate
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</section>
