<?php 
?>
<section class="module-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-8 hero-content">
                <h1>
                    <small>MOT modernisation</small>
                    Your home
                </h1>
                <p>DVSA Finance view</p>
            </div>
            <div id="hero-actions" class="col-md-4 hero-actions">
                <h2>Advanced searches</h2>
                <?php echo $this->partial('primaryAction/links', ['dashboard' => $dashboard]); ?>
            </div>
        </div>
    </div>
</section>
