<?php
/** @var $dashboard \Dashboard\Model\Dashboard */
use DvsaCommon\Auth\PermissionInSystem;
use DvsaCommon\UrlBuilder\AuthorisedExaminerUrlBuilderWeb;
use DvsaMotTest\Controller\VehicleSearchController;
use UserAdmin\Controller\UserSearchController;

?>
<ul class="list-unstyled">
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::AUTHORISED_EXAMINER_LIST)): ?>
        <li>
            <a href="<?php echo AuthorisedExaminerUrlBuilderWeb::of()->aeSearch(); ?>">
                AE information
            </a>
        </li>
    <?php endif; ?>
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::DVSA_SITE_SEARCH)): ?>
        <li>
            <a href="<?php echo $this->url('vehicle-testing-station-search'); ?>">
                site information
            </a>
        </li>
    <?php endif; ?>
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::USER_SEARCH)): ?>
        <li>
            <a href="<?php echo $this->url(UserSearchController::ROUTE_USER_SEARCH); ?>"
               id="action-start-user-search">
                user search
            </a>
        </li>
    <?php endif; ?>
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::CERTIFICATE_SEARCH)): ?>
        <li>
            <a href="<?php echo $this->url(VehicleSearchController::ROUTE_REPLACEMENT_CERTIFICATE_VEHICLE_SEARCH); ?>"
               id="action-start-certificate-reissue">
                replacement/duplicate certificate
            </a>
        </li>
    <?php endif; ?>
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::FULL_VEHICLE_MOT_TEST_HISTORY_VIEW)): ?>
        <li>
            <a href="<?php echo $this->url('vehicle/search'); ?>">
                vehicle information
            </a>
        </li>
    <?php endif; ?>
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::MOT_TEST_LIST)): ?>
        <li>
            <a href="<?php echo $this->url('mot-test-search'); ?>">
                MOT tests
            </a> (comparison of tests available)
        </li>
    <?php endif; ?>
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::VIEW_USERS_IN_DEMO_TEST_NEEDED_STATE)): ?>
        <li>
            <a id="demo-test-requests" href="<?php echo $this->url('user_admin/demo-test-requests'); ?>">
                Demo test requests
            </a>
        </li>
    <?php endif; ?>
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::SLOTS_TRANSACTION_READ_FULL)): ?>
        <li>
            <a id="transactions" href="<?php echo $this->url('transaction-search'); ?>">
                Payments
            </a>
        </li>
    <?php endif; ?>
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::SLOTS_DIRECT_DEBIT_SEARCH)): ?>
        <li>
            <a id="transactions" href="<?php echo $this->url('direct-debit-search'); ?>">
                Direct Debit
            </a>
        </li>
    <?php endif; ?>
    <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::GENERATE_SATISFACTION_SURVEY_REPORT)): ?>
        <li>
            <a href="<?php echo $this->url('survey-reports'); ?>"
               id="action-start-survey-reports">
                Generate survey report
            </a>
        </li>
    <?php endif; ?>
    <?php if ($this->isTwoFaEnabled() && $this->authorisationHelper()->isGranted(PermissionInSystem::VIEW_SECURITY_CARD_ORDER)): ?>
        <li>
            <a href="<?php echo $this->url('security-card-order-report-list'); ?>"
               id="action-security-card-order-report-list">
                Security card order list
            </a>
        </li>
    <?php endif; ?>
</ul>
