<section class="module-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-8 hero-content">
                <h1>
                    <small>MOT modernisation</small>
                    Your home
                </h1>
                <p>Your access is restricted to the demo mode. Only fully qualified testers employed at a VTS have
                    access to the full system.</p>
            </div>
            <div class="col-md-4 hero-actions">
                <a href="<?php echo $this->url('demo-vehicle-search') ?>" class="btn btn-primary btn-lg" id="action-start-mot-training-mode">
                    Start Demo Test <span class="fa fa-chevron-right"> </span>
                </a>
            </div>
        </div>
    </div>
</section>