<?php
use Dvsa\Mot\Frontend\AuthenticationModule\Model\VehicleTestingStation;
use DvsaCommon\Auth\PermissionInSystem;
use DvsaMotTest\Controller\VehicleSearchController;

$isTestingEnabled = $this->authorisationHelper()->isGranted(\DvsaCommon\Auth\PermissionInSystem::MOT_TEST_START);

/** @var VehicleTestingStation $testersCurrentVts */
$testersCurrentVts = $this->identityHelper()->getCurrentVts();
$hasSlots = isset($testersCurrentVts) && ($testersCurrentVts->getSlots() > 0);
$hasInProgressTest = $this->dashboardDataProvider()->hasTestInProgress();

?>

<section class="module-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-8 hero-content">
                <h1>
                    <small>MOT modernisation</small>
                    Your home
                </h1>
                <p>Tester view</p>
            </div>
            <div class="col-md-4 hero-actions">
                <?php if ($this->dashboardDataProvider()->isTesterAtAnySite()): ?>
                    <?php if ($isTestingEnabled) : ?>
                        <?php if ($hasInProgressTest) : ?>
                            <a href="<?php echo $this->url(
                                'mot-test',
                                ['motTestNumber' => $this->dashboardDataProvider()->getInProgressTestNumber()]
                            ); ?>"
                               class="btn btn-primary btn-lg"
                               id="action-resume-mot-test">
                                <?php echo $this->dashboardDataProvider()->getEnterTestResultsLabel(); ?>
                                <span class="fa fa-chevron-right"> </span>
                            </a>
                        <?php elseif (!empty($testersCurrentVts) && !$hasSlots) : ?>
                            <p>No slots available, please purchase test slots</p>
                        <?php else : ?>
                            <a href="<?php echo $this->url('vehicle-search'); ?>"
                               class="btn btn-primary btn-lg"
                               id="action-start-mot-test">Start MOT test
                                <span class="fa fa-chevron-right"> </span>
                            </a>
                        <?php endif; ?>
                    <?php else: ?>
                        <a href="<?php echo $this->url('demo-vehicle-search') ?>" class="btn btn-primary btn-lg" id="action-start-mot-training-mode">
                            Start Demo Test <span class="fa fa-chevron-right"> </span>
                        </a>
                    <?php endif; ?>
                    <ul class="list-unstyled">
                        <?php if ($isTestingEnabled) : ?>
                            <li>
                                <a href="<?php echo $this->url('demo-vehicle-search') ?>"
                                   id="action-start-mot-training-mode">start MOT training mode</a>
                            </li>
                        <?php endif; ?>
                        <?php if (!$hasInProgressTest && $this->authorisationHelper()->isGranted(\DvsaCommon\Auth\PermissionInSystem::CERTIFICATE_REPLACEMENT)) : ?>
                            <li>
                                <a href="<?php echo $this->url(VehicleSearchController::ROUTE_REPLACEMENT_CERTIFICATE_VEHICLE_SEARCH); ?>"
                                   id="action-start-certificate-reissue">replacement/duplicate certificate</a>
                            </li>
                        <?php endif; ?>
                        <?php if ($isTestingEnabled) : ?>
                            <li>
                                <a href="<?php echo $this->url('forms'); ?>" id="mot-forms">MOT forms</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                <?php endif ?>
            </div>
        </div>
    </div>
</section>
