<section class="module-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-8 hero-content">
                <h1>
                    <small>MOT modernisation</small>
                    Your home
                </h1>
                <p>Your access is restricted to the demo mode. Only fully qualified testers employed at a VTS have
                    access to the full system.</p>
            </div>
        </div>
    </div>
</section>
