<section class="module-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-8 hero-content">
                <h1>
                    <small>MOT modernisation</small>
                    Your home
                </h1>
                <p>Welcome to MOT modernisation.</p>
            </div>
            <div id="hero-actions" class="col-md-4 hero-actions">
                <?php echo $this->partial('primaryAction/links'); ?>
            </div>
        </div>
    </div>
</section>
