<?php

use Core\Routing\VtsRoutes;
use Site\UpdateVtsProperty\UpdateVtsPropertyReviewViewModel;

/**
 * @var UpdateVtsPropertyReviewViewModel $viewModel
 */
?>
<?php echo $this->partial('errorMessages', array('getFromFlash' => true)); ?>
<?php
echo $this->partial(
    'partial/gds/gds-table/gds-key-value-table',
    [
        'table' => $viewModel->getSummary(),
    ]
);
?>

<form novalidate="" autocomplete="off" method="POST" action="<?php echo VtsRoutes::of($this)->vtsReviewEditProperty($viewModel->getVtsId(), $viewModel->getPropertyName(), $viewModel->getFormUuid()); ?>">
    <?php echo $this->csrfToken(); ?>

    <nav class="content-navigation">
        <input type="submit" class="button" value="<?php echo $viewModel->getSubmitButtonText() ?>" id="submitUpdate">
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo VtsRoutes::of($this)->vtsEditProperty($viewModel->getVtsId(), $viewModel->getPropertyName(), $viewModel->getFormUuid()); ?>">Back</a>
            </li>
        </ul>
    </nav>
</form>
