<?php

/**
 * @var \Organisation\ViewModel\AuthorisedExaminer\AeFormViewModel $model
 * @var AeCreateForm                                               $form
 * @var \Zend\Mvc\Controller\Plugin\FlashMessenger                 $flashMessenger
 */

use DvsaClient\ViewModel\PhoneFormModel;
use DvsaCommon\Enum\OrganisationContactTypeCode;
use Organisation\Form\AeCreateForm;

$model = $this->model;
$form = $model->getForm();

//  show api errors
$flashMessenger = $this->layout()->flashMessenger;
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'failure']
);
?>

<form method="POST" action="<?php echo $form->getFormUrl(); ?>">
    <?php echo $this->csrfToken() ?>
    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendBusiness', 'text' => 'Their business details']
        );

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'           => AeCreateForm::FIELD_NAME,
                'label'        => 'Business name',
                'title'        => 'Enter AE business name',
                'value'        => $form->getName(),
                'errorMessage' => $form->getError(AeCreateForm::FIELD_NAME),
                'maxLength'    => 60,
                'autofocus'    => true,
            ]
        );
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'           => AeCreateForm::FIELD_TRADING_AS,
                'label'        => 'Trading name',
                'title'        => 'Enter AE trading as',
                'errorMessage' => $form->getError(AeCreateForm::FIELD_TRADING_AS),
                'value'        => $form->getTradingAs(),
                'maxLength'    => 60,
            ]
        );
        echo $this->partial(
            'partial/gds/form/control-select-group',
            [
                'id'           => AeCreateForm::FIELD_COMPANY_TYPE,
                'label'        => 'Business type',
                'errorMessage' => $form->getError(AeCreateForm::FIELD_COMPANY_TYPE),
                'value'        => $form->getCompanyType(),
                'options'      => $form->getCompanyTypes(),
            ]
        );
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'           => AeCreateForm::FIELD_REG_NR,
                'label'        => 'Company number (for limited companies only)',
                'title'        => 'Enter Company number',
                'elementId'    => 'registeredCompanyNumberDiv',
                'errorMessage' => $form->getError(AeCreateForm::FIELD_REG_NR),
                'value'        => $form->getRegisteredCompanyNumber(),
                'maxLength'    => 20,
            ]
        );
        ?>
    </fieldset>
    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendBusinessContact', 'text' => 'Their business contact details']
        );

        $busContactModel = $form->getBusContactModel();

        //  business contact :: address
        echo $this->partial(
            'partial/gds/form/control-address-group',
            [
                'id'    => 'address',
                'group' => OrganisationContactTypeCode::REGISTERED_COMPANY,
                'form'  => $busContactModel->getAddressModel(),
            ],
            'Core'
        );

        //  business contact :: phone number
        $phoneModel = $busContactModel->getPhoneModel();
        $fieldId = OrganisationContactTypeCode::REGISTERED_COMPANY . PhoneFormModel::FIELD_NUMBER;
        $fieldName = OrganisationContactTypeCode::REGISTERED_COMPANY . '[' . PhoneFormModel::FIELD_NUMBER . ']';
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => $fieldId,
                'name'          => $fieldName,
                'errorMessage'  => $phoneModel->getError($fieldName),
                'inputModifier' => '1-3',
                'label'         => 'Phone number',
                'value'         => $phoneModel->getNumber(),
                'maxLength'     => 24,
            ]
        );

        //  business contact :: email elements
        echo $this->partial(
            'partial/gds/form/control-email-conf-group',
            [
                'id'    => 'email',
                'key'   => 'Email address not provided',
                'group' => OrganisationContactTypeCode::REGISTERED_COMPANY,
                'form'  => $busContactModel->getEmailModel(),
            ],
            'Core'
        );
        ?>
    </fieldset>

    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend',
            ['id' => 'legendCorrespondenceContact', 'text' => 'Correspondence contact details']
        );

        echo $this->partial(
            'partial/gds/form/control-is-the-same',
            [
                'title'      => 'Are they the same as the business contact details? ',
                'name'       => AeCreateForm::FIELD_IS_CORR_DETAILS_THE_SAME,
                'value'      => $form->isCorrDetailsTheSame(),
                'addressElm' => 'addressDetailsFragmentDiv',
            ],
            'Core'
        );

        ?>
        <div id="addressDetailsFragmentDiv">
            <?php
            $corrContactModel = $form->getCorrContactModel();

            //  correspondence contact :: address
            echo $this->partial(
                'partial/gds/form/control-address-group',
                [
                    'id'    => 'address',
                    'group' => OrganisationContactTypeCode::CORRESPONDENCE,
                    'form'  => $corrContactModel->getAddressModel(),
                ],
                'Core'
            );

            //  correspondence contact :: phone number
            $phoneModel = $corrContactModel->getPhoneModel();
            $fieldId = OrganisationContactTypeCode::CORRESPONDENCE . PhoneFormModel::FIELD_NUMBER;
            $fieldName = OrganisationContactTypeCode::CORRESPONDENCE . '[' . PhoneFormModel::FIELD_NUMBER . ']';
            echo $this->partial(
                'partial/gds/form/control-text-group',
                [
                    'id'            => $fieldId,
                    'name'          => $fieldName,
                    'errorMessage'  => $phoneModel->getError($fieldName),
                    'inputModifier' => '1-3',
                    'label'         => 'Phone number',
                    'value'         => $phoneModel->getNumber(),
                    'maxLength'     => 24,
                ]
            );

            //  correspondence contact :: email elements
            echo $this->partial(
                'partial/gds/form/control-email-conf-group',
                [
                    'id'    => 'email',
                    'key'   => 'Email address not provided',
                    'group' => OrganisationContactTypeCode::CORRESPONDENCE,
                    'form'  => $corrContactModel->getEmailModel(),
                ],
                'Core'
            );
            ?>
        </div>
    </fieldset>

    <?php
    echo $this->partial(
        '/organisation/authorised-examiner/partials/area-office-select',
        [
            'value' => $form->getAssignedAreaOffice(),
            'options' => $form->getAreaOfficeOptions(),
            'errorMessage' => $form->getError(AeCreateForm::FIELD_AO_NR),
        ]
    );
    ?>

    <?php
    echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'         => 'submitAeEdit',
            'value'      => 'Continue',
            'navigation' => [
                'Cancel and return home' => $model->getCancelUrl(),
            ],
        ]
    );
    ?>
</form>

<?php $this->inlineScript()->captureStart(); ?>

$(function() {
    if (!!'<?php echo (bool)$form->isCorrDetailsTheSame(); ?>') {
        $('#addressDetailsFragmentDiv').hide();
    }
});

<?php $this->inlineScript()->captureEnd(); ?>
