<?php

/**
 * @var AeContactDetailsForm $form
 * @var \Zend\Mvc\Controller\Plugin\FlashMessenger $flashMessenger
 */

use DvsaClient\ViewModel\PhoneFormModel;
use DvsaCommon\Enum\OrganisationContactTypeCode;
use Organisation\Form\AeContactDetailsForm;

//  show api errors
$flashMessenger = $this->layout()->flashMessenger;
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'failure']
);
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getSuccessMessages(), 'type' => 'success']
);

$form = $this->form;
$contactModel = $form->getCorrContactModel();

?>

<form method="POST">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <?php echo $this->partial('partial/gds/form/control-legend',    ['id' => 'legendEmail', 'text' => 'Email']); ?>
        <p id="textWarning">The email address should be one you have easy and regular access to and will be used to send you important
            messages that will be required outside of the MOT Testing Service application - for example, username and
            password reminders.<br>
            <strong>You could be without access for up to 5 working days</strong> if you don't supply an email address.
        </p>


        <?php
        //  correspondence contact :: email elements
        echo $this->partial(
            'partial/gds/form/control-email-conf-group',
            [
                'id'    => 'email',
                'group' => OrganisationContactTypeCode::CORRESPONDENCE,
                'form'  => $contactModel->getEmailModel(),
            ],
            'Core'
        );
        ?>
    </fieldset>

    <fieldset>
        <?php
        echo $this->partial('partial/gds/form/control-legend', ['id' => 'legendTelephone', 'text' => 'Telephone']);

        //  correspondence contact :: phone number
        $phoneModel = $contactModel->getPhoneModel();
        $fieldId = OrganisationContactTypeCode::CORRESPONDENCE. PhoneFormModel::FIELD_NUMBER;
        $fieldName = OrganisationContactTypeCode::CORRESPONDENCE. '['. PhoneFormModel::FIELD_NUMBER.']';
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => $fieldId,
                'name'          => $fieldName,
                'errorMessage'  => $phoneModel->getError(PhoneFormModel::FIELD_NUMBER),
                'inputModifier' => '1-4',
                'label'         => 'Phone number',
                'value'         => $phoneModel->getNumber(),
            ]
        );
        ?>
    </fieldset>
    <fieldset>
        <?php echo $this->partial(
            'partial/gds/form/control-legend', ['id' => 'legendBusiness', 'text' => 'Business address']
        ); ?>
        <p class="lede">
            <?php echo $this->partial(
                'partial/gds/general/display-address-bloc',
                [
                    'address' => $form->getBusContact()->getAddress(),
                ]
            ); ?>
            <br/>
        </p>
    </fieldset>
    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend', ['id' => 'legendCorrespondence', 'text' => 'Correspondence address']
        );

        echo $this->partial(
            'partial/gds/form/control-is-the-same',
            [
                'title'      => 'Is this the same as the business address?',
                'name'       => AeContactDetailsForm::FIELD_IS_CORR_ADDR_THE_SAME,
                'value'      => $form->isCorrAddressTheSame(),
                'addressElm' => 'addressCorrespondence',
            ],
            'Core'
        );

        //  correspondence contact :: address
        echo $this->partial(
            'partial/gds/form/control-address-group',
            [
                'id'    => 'addressCorrespondence',
                'group' => OrganisationContactTypeCode::CORRESPONDENCE,
                'form'  => $contactModel->getAddressModel(),
            ],
            'Core'
        );
        ?>
    </fieldset>
    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'            => 'submitAeEdit',
            'value'         => 'Save contact details',
            'navigation'    => [
                'Cancel and return to AE Details' => $form->getCancelUrl(),
            ]
        ]
    ); ?>
</form>

<?php $this->inlineScript()->captureStart(); ?>

$(function() {
    if (!!'<?php echo $form->isCorrAddressTheSame(); ?>') {
        $('#addressCorrespondence').hide();
    }
});

<?php $this->inlineScript()->captureEnd(); ?>
