<?php

use Core\Formatting\AddressFormatter;
use Core\Routing\AeRoutes;
use Dashboard\Controller\UserHomeController;
use Dvsa\Mot\Frontend\PersonModule\View\ContextProvider;
use DvsaCommon\Dto\Organisation\OrganisationSiteLinkDto;
use DvsaCommon\Utility\AddressUtils;
use Organisation\Controller\AuthorisedExaminerPrincipalController;
use Organisation\Controller\RoleController;
use Organisation\Controller\SiteController;
use Organisation\UpdateAeProperty\UpdateAePropertyAction;

/**
 * @var \Organisation\ViewModel\View\Index\IndexViewModel $viewModel
 * @var \Organisation\Presenter\AuthorisedExaminerPresenter $presenter
 * @var \Application\View\Helper\AuthorisationHelper      $authHelper
 * @var \DvsaCommon\Dto\Organisation\OrganisationDto $organisation
 */
$authHelper = $this->authorisationHelper();
$withdrawalDate = $this->withdrawalDate;
$orgId = $this->organisationId;
?>

<?php echo $this->partial('infoMessages', ['getFromFlash' => true]); ?>
<?php
$successMessages = $this->layout()->flashMessenger->getSuccessMessages();
echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
?>
<h3 class="summary-heading">
    Business details
</h3>

<?php
echo $this->partial(
    'partial/gds/gds-table/gds-summary-table',
        [
        'table' => $viewModel->buildAEBusinessDetailsSummaryTable(),
        ]
    );
?>



<h3 class="summary-heading">
    Contact details
</h3>

<?php if($organisation->getRegisteredCompanyContactDetail()):
    echo $this->partial(
    'partial/gds/gds-table/gds-summary-table',
    [
    'table' => $viewModel->buildAERegisteredOfficeSummaryTable(),
    ]
    );
endif; ?>

<?php if($organisation->getCorrespondenceContactDetail()):
    echo $this->partial(
    'partial/gds/gds-table/gds-summary-table',
    [
    'table' => $viewModel->buildAECorrespondenceSummaryTable(),
    ]
    );
endif; ?>

<?php if($viewModel->getViewAuthorisation()->canViewPersonnel()) :?>
    <h3 class="summary-heading">
        Roles
        <?php if($viewModel->getViewAuthorisation()->canNominate()): ?>
            <span class="summary-heading__action">
                <a href="<?php echo $this->url(RoleController::ROUTE_ROLES, ['id' => $orgId]); ?>" id="assign-a-role">
                    Assign a role
                </a>
            </span>
        <?php endif; ?>
    </h3>

    <table class="table-summary">
        <tbody>
        <?php $escUsersWithRolesCount = 0;
        foreach ($viewModel->getEmployees() as $employee): ?>
            <?php foreach ($employee->getPositions() as $pio): ?>
            <tr id="authorised-examiner-designated-manager-<?php echo $escUsersWithRolesCount++; ?>">
                <th class="table-summary__key">
                    <?php if ($viewModel->getViewAuthorisation()->canViewProfile($employee->getPerson())): ?>
                        <a href="<?php echo $this->isFeatureEnabled('new_person_profile')
                                            ? $this->url(ContextProvider::AE_PARENT_ROUTE,
                                                [
                                                    'authorisedExaminerId' => $orgId,
                                                    'id' => $employee->getPerson()->getId()
                                                ]
                                            )
                                            : $this->url(UserHomeController::ROUTE_PROFILE, ['id' => $employee->getPerson()->getId()]); ?>">
                            <?php echo $this->escapeHtml($employee->getPerson()->getFullname()); ?>
                            <?php if ($viewModel->getViewAuthorisation()->canViewUsername()):
                                echo "(" . $this->escapeHtml($employee->getPerson()->getUsername()) . ")";
                            endif; ?>
                        </a>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($employee->getPerson()->getFullname());
                        if ($viewModel->getViewAuthorisation()->canViewUsername()):
                            echo "(" . $this->escapeHtml($employee->getPerson()->getUsername()) . ")";
                        endif; ?>
                    <?php endif; ?>
                </th>

                <td class="table-summary__value">

                        <div id="role-assignment-<?php echo $this->escapeHtmlAttr($employee->getPerson()->getId() . "-" . $pio->getRole()); ?>" class="text">
                            <?php echo $this->escapeHtml($pio->getRole()); ?>
                            <?php if ($pio->isPending()): ?>
                                <br />
                                <span class="key-value-list__meta">Pending</span>
                            <?php endif; ?>
                        </div>
                        <?php if (($pio->isActive() || $pio->isPending()) && $viewModel->getViewAuthorisation()->canRemovePosition($pio)) : ?>

                            <a id="remove-role" class="table-summary__action" href="<?php echo $this->url(
                                RoleController::ROUTE_REMOVE_ROLE,
                                [
                                    'id'     => $orgId,
                                    'roleId' => $pio->getId(),
                                ]
                            );?>">Remove
                            <span class="visuallyhidden">
                                <?php echo $this->escapeHtml($employee->getPerson()->getFullname()) ?>
                            </span>
                            </a>
                        <?php endif ?>

                </td>

            </tr>
            <?php endforeach ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php if ($viewModel->getViewAuthorisation()->canViewVtsList()): ?>
    <h3 class="summary-heading">
        Vehicle Testing Stations
        <?php if ($viewModel->getViewAuthorisation()->canCreateSiteAssociation()) : ?>
            <span class="summary-heading__action">
                <a href="<?php echo $this->url(SiteController::ROUTE_LINK, ['id' =>$orgId]); ?>" >Add site associations</a>
            </span>
        <?php endif; ?>
    </h3>

    <table class="table-summary">
        <tbody>
        <?php
        $itemCount = 0;
        $totalItems = count($viewModel->getVehicleTestingStations());

        foreach ($viewModel->getVehicleTestingStations() as $vtsIdx => $vts):
        $itemCount++;

        $vtsId = $vts->getId();
        $siteNumber = $vts->getSiteNumber();

        $vtsElementId = 'vehicle-testing-station-' . ($vtsIdx + 1);
        ?>
        <tr id="<?php echo $this->escapeHtmlAttr($vtsElementId); ?>">
            <th class="table-summary__key">

                <?php if ($viewModel->getViewAuthorisation()->canViewVts($vtsId)): ?>
                    <a href="<?php echo $this->url(SiteController::ROUTE_INDEX, ['id' => $vtsId]); ?>">
                        <?php echo $this->escapeHtml($vts->getName()); ?>
                    </a>
                <?php else: ?>
                    <?php echo $this->escapeHtml($vts->getName()); ?>
                <?php endif; ?>

                <?php if ($viewModel->shouldViewContactDetailsForVts() && $vts->getContacts()) : ?>
                    <span class="table-summary__meta">
                            <?php echo $this->escapeHtml(
                                AddressUtils::stringify($vts->getContacts()[0]->getAddress())
                            ); ?>
                        </span>
                <?php endif; ?>
            </th>

            <td class="table-summary__value">
                <?php echo $this->escapeHtml($vts->getSiteNumber()); ?>
                <?php if ($viewModel->getViewAuthorisation()->canRemoveSiteAssociation()) : ?>
                    <?php
                    $linkWithAe = $vts->getLinkWithAe();
                    if ($linkWithAe instanceof OrganisationSiteLinkDto) : ?>
                        <span class="key-value-list__meta">
                            <a href="<?php echo $this->url(SiteController::ROUTE_UNLINK, [
                                'id' => $orgId,
                                'linkId' => $linkWithAe->getId()
                            ]);
                            ?>" class="table-summary__action">
                                Remove
                                <span class="visuallyhidden"> <?php echo $this->escapeHtml($vts->getName()); ?></span>
                            </a>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php if ($viewModel->canViewAepSection()): ?>
    <h3 class="summary-heading">
        Authorised Examiner Principals
        <?php if ($viewModel->getViewAuthorisation()->canCreateAuthorisedExaminerPrincipal()): ?>
            <span class="summary-heading__action">
                <a id="add-aep" href="<?php echo AeRoutes::of($this)->aeAddPrincipal($orgId); ?>">
                    Add a principal
                </a>
            </span>
        <?php endif; ?>
    </h3>

    <?php if ($viewModel->hasPrincipals()): ?>
        <table id="aeps" class="table-default">
            <thead>
                <tr>
                    <th scope="col" class="table-default__head">Name</th>
                    <th scope="col" class="table-default__head">Address</th>
                    <th scope="col" class="table-default__head">Date of birth</th>
                    <th scope="col" class="table-default__head visuallyhidden">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($viewModel->getPrincipals() as $principalIdx => $principal) :
                    $escPrincipalKey = (int)$principalIdx + 1;
                    $contact = $viewModel->getPrincipalContactDetails($principalIdx);
                ?>
                    <tr id="<?php echo 'authorised-examiner-principal-' . $escPrincipalKey; ?>">
                        <td class="table-default__body--primary" id="aep-name-<?php echo $principal->getId() ?>">
                            <?php echo $this->escapeHtml($principal->getDisplayName()); ?>
                        </td>
                        <td class="table-default__body" id="aep-address-<?php echo $principal->getId() ?>" >
                            <?php echo (new AddressFormatter())->escapedDtoToMultiLine($contact->getAddress(), true); ?>
                        </td>
                        <td class="table-default__body" id="aep-birth-<?php echo $principal->getId() ?>">
                            <?php echo $this->escapeHtml($principal->displayDateOfBirth()); ?>
                        </td>
                        <td class="table-default__body--action" id="aep-action-<?php echo $principal->getId() ?>">
                                <?php if($viewModel->getViewAuthorisation()->canRemoveAuthorisedExaminerPrincipal()):
                                    $escUrlRemove = $this->url(AuthorisedExaminerPrincipalController::ROUTE_REMOVE_CONFIRMATION, [
                                        'id' => $orgId,
                                        'principalId' => $principal->getId()
                                    ]); ?>
                                    <a class="remove-aep" id="remove-aep-<?php echo $principal->getId() ?>" href="<?php echo $escUrlRemove; ?>">Remove</a>
                                    <span class="visuallyhidden"><?php echo $principal->getDisplayName() ?></span>
                                <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>

<?php echo $this->directDebitInfo($orgId); ?>

<?php echo $this->partial('/organisation/authorised-examiner/partials/index-buttons', ['urlBack' => $this->urlBack]); ?>
