<?php

use Dashboard\Controller\UserHomeController;
use DvsaCommon\Dto\Organisation\OrganisationSiteLinkDto;
use DvsaCommon\Utility\AddressUtils;
use Organisation\Controller\AuthorisedExaminerPrincipalController;
use Organisation\Controller\RoleController;
use Organisation\Controller\SiteController;

/**
 * @var \Organisation\ViewModel\View\Index\IndexViewModel $viewModel
 * @var \Organisation\Presenter\AuthorisedExaminerPresenter $presenter
 * @var \Application\View\Helper\AuthorisationHelper      $authHelper
 * @var \DvsaCommon\Dto\Organisation\OrganisationDto $organisation
 */
$authHelper = $this->authorisationHelper();
$withdrawalDate = $this->withdrawalDate;
$orgId = $this->organisationId;
?>

<?php echo $this->partial('infoMessages', ['getFromFlash' => true]); ?>
<?php
$successMessages = $this->layout()->flashMessenger->getSuccessMessages();
echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
?>
<h3 class="summary-heading">
    Business details
<?php if ($viewModel->getViewAuthorisation()->canUpdateAE()): ?>
    <span class="summary-heading__action">
        <a href="<?php echo $this->escapeHtmlAttr($presenter->getChangeStatusUrl()); ?>">
            Change status & area office
        </a>
    </span>
<?php endif; ?>
</h3>

<table class="table-summary">
    <tbody>
    <tr>
        <th class="table-summary__key">
            Name
        </th>
        <td id="ae-name" class="table-summary__value">
            <?php echo $this->escapeHtml($presenter->getName()); ?>
        </td>
    </tr>
    <tr>
        <th class="table-summary__key">
            Business type
        </th>

        <td id="ae-type" class="table-summary__value">
            <?php echo $this->escapeHtml($presenter->getCompanyType()); ?>
            <span class="table-summary__meta" id="ae-company-number">
                <?php echo $this->escapeHtml($presenter->getCompanyNumber()); ?>
            </span>
        </td>
    </tr>
    <tr>
        <th class="table-summary__key">
            Trading as
        </th>

        <td id="ae-tradename" class="table-summary__value">
            <?php echo $this->escapeHtml($presenter->getTradingName()); ?>
        </td>
    </tr>
    <tr>
        <th id="ae-number" class="table-summary__key">
            AE ID
        </th>

        <td class="table-summary__value">
            <?php echo $this->escapeHtml($presenter->getNumber()); ?>
        </td>
    </tr>
<?php if ($viewModel->getViewAuthorisation()->canViewAeStatus()): ?>
    <tr>
        <th class="table-summary__key">
            AE Appeal status
        </th>

        <td id="ae-auth-status" class="table-summary__value">
            <?php echo "N/A"; /* @todo will be implemented in future */ ?>
        </td>
    </tr>
    <tr>
        <th class="table-summary__key">
            AE Withdrawal date
        </th>

        <td id="ae-withdraw-date" class="table-summary__value">
            <?php echo $withdrawalDate ? $this->escapeHtml($withdrawalDate) : 'N/A'; //@todo add to presenter ?>
        </td>
    </tr>
    <tr>
        <th class="table-summary__key">
            DVSA area office
        </th>

        <td id="ae-dvsa-area-office" class="table-summary__value">
            <?php echo $this->aoOfficeLabel ? $this->escapeHtml($this->aoOfficeLabel) : 'N/A'; ?>
        </td>
    </tr>
<?php endif; ?>
    </tbody>
</table>

<h3 class="summary-heading">
    Contact details
    <?php if($viewModel->getViewAuthorisation()->canUpdateAE()): ?>
        <span class="summary-heading__action">
            <a id="change-contact-details" href="<?php echo $this->escapeHtmlAttr($presenter->getChangeDetailsUrl()); ?>">
                Change contact details
            </a>
        </span>
    <?php endif; ?>
</h3>

<?php $contactDetail = $organisation->getRegisteredCompanyContactDetail(); ?>
<?php if($contactDetail): ?>
    <?php echo $this->partial('/organisation/authorised-examiner/partials/contact-detail', [
        'title' => 'Registered office',
        'contactDetail' => $contactDetail,
        //@todo: add more convention, less configuration and update ids in selenium tests
        'ids' => [
            'address' => 'reg_AE_address',
            'email' => 'reg_email',
            'phone' => 'reg_telephone',
        ],
    ]); ?>
<?php endif; ?>

<?php $correspondenceDetail = $organisation->getCorrespondenceContactDetail(); ?>
<?php if($correspondenceDetail): ?>
    <?php echo $this->partial('/organisation/authorised-examiner/partials/contact-detail', [
        'title' => 'Correspondence',
        'contactDetail' => $correspondenceDetail,
        //@todo: add more convention, less configuration and update ids in selenium tests
        'ids' => [
            'address' => 'cor_address',
            'email' => 'cor_email',
            'phone' => 'cor_phone'
        ],
    ]); ?>
<?php endif; ?>

<?php if($viewModel->getViewAuthorisation()->canViewPersonnel()) :?>
    <h3 class="summary-heading">
        Roles
        <?php if($viewModel->getViewAuthorisation()->canNominate()): ?>
            <span class="summary-heading__action">
                <a href="<?php echo $this->url(RoleController::ROUTE_ROLES, ['id' => $orgId]); ?>" id="assign-a-role">
                    Assign a role
                </a>
            </span>
        <?php endif; ?>
    </h3>

    <table class="table-summary">
        <tbody>
        <?php $escUsersWithRolesCount = 0;
        foreach ($viewModel->getEmployees() as $employee): ?>
            <?php foreach ($employee->getPositions() as $pio): ?>
            <tr id="authorised-examiner-designated-manager-<?php echo $escUsersWithRolesCount++; ?>">
                <th class="table-summary__key">
                    <?php if ($viewModel->getViewAuthorisation()->canViewProfile($employee->getPerson())): ?>
                        <a href="<?php echo $this->isFeatureEnabled('new_person_profile')
                                            ? $this->url('newProfile',
                                                [
                                                    'personId' => $employee->getPerson()->getId()
                                                ],
                                                [
                                                    'query' => [
                                                        'context' => 'ae'
                                                    ],
                                                ]
                                            )
                                            : $this->url(UserHomeController::ROUTE_PROFILE, ['id' => $employee->getPerson()->getId()]); ?>">
                            <?php echo $this->escapeHtml($employee->getPerson()->getFullname()); ?>
                            <?php if ($viewModel->getViewAuthorisation()->canViewUsername()):
                                echo "(" . $this->escapeHtml($employee->getPerson()->getUsername()) . ")";
                            endif; ?>
                        </a>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($employee->getPerson()->getFullname());
                        if ($viewModel->getViewAuthorisation()->canViewUsername()):
                            echo "(" . $this->escapeHtml($employee->getPerson()->getUsername()) . ")";
                        endif; ?>
                    <?php endif; ?>
                </th>

                <td class="table-summary__value">

                        <div id="role-assignment-<?php echo $this->escapeHtmlAttr($employee->getPerson()->getId() . "-" . $pio->getRole()); ?>" class="text">
                            <?php echo $this->escapeHtml($pio->getRole()); ?>
                            <?php if ($pio->isPending()): ?>
                                <br />
                                <span class="key-value-list__meta">Pending</span>
                            <?php endif; ?>
                        </div>
                        <?php if (($pio->isActive() || $pio->isPending()) && $viewModel->getViewAuthorisation()->canRemovePosition($pio)) : ?>

                            <a id="remove-role" class="table-summary__action" href="<?php echo $this->url(
                                RoleController::ROUTE_REMOVE_ROLE,
                                [
                                    'id'     => $orgId,
                                    'roleId' => $pio->getId(),
                                ]
                            );?>">Remove
                            <span class="visuallyhidden">
                                <?php echo $this->escapeHtml($employee->getPerson()->getFullname()) ?>
                            </span>
                            </a>
                        <?php endif ?>

                </td>

            </tr>
            <?php endforeach ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php if ($viewModel->getViewAuthorisation()->canViewVtsList()): ?>
    <h3 class="summary-heading">
        Vehicle Testing Stations
        <?php if ($viewModel->getViewAuthorisation()->canCreateSiteAssociation()) : ?>
            <span class="summary-heading__action">
                <a href="<?php echo $this->url(SiteController::ROUTE_LINK, ['id' =>$orgId]); ?>" >Add site associations</a>
            </span>
        <?php endif; ?>
    </h3>

    <table class="table-summary">
        <tbody>
        <?php
        $itemCount = 0;
        $totalItems = count($viewModel->getVehicleTestingStations());

        foreach ($viewModel->getVehicleTestingStations() as $vtsIdx => $vts):
        $itemCount++;

        $vtsId = $vts->getId();
        $siteNumber = $vts->getSiteNumber();

        $vtsElementId = 'vehicle-testing-station-' . ($vtsIdx + 1);
        ?>
        <tr id="<?php echo $this->escapeHtmlAttr($vtsElementId); ?>">
            <th class="table-summary__key">

                <?php if ($viewModel->getViewAuthorisation()->canViewVts($vtsId)): ?>
                    <a href="<?php echo $this->url(SiteController::ROUTE_INDEX, ['id' => $vtsId]); ?>">
                        <?php echo $this->escapeHtml($vts->getName()); ?>
                    </a>
                <?php else: ?>
                    <?php echo $this->escapeHtml($vts->getName()); ?>
                <?php endif; ?>

                <?php if ($viewModel->shouldViewContactDetailsForVts() && $vts->getContacts()) : ?>
                    <span class="table-summary__meta">
                            <?php echo $this->escapeHtml(
                                AddressUtils::stringify($vts->getContacts()[0]->getAddress())
                            ); ?>
                        </span>
                <?php endif; ?>
            </th>

            <td class="table-summary__value">
                <?php echo $this->escapeHtml($vts->getSiteNumber()); ?>
                <?php if ($viewModel->getViewAuthorisation()->canRemoveSiteAssociation()) : ?>
                    <?php
                    $linkWithAe = $vts->getLinkWithAe();
                    if ($linkWithAe instanceof OrganisationSiteLinkDto) : ?>
                        <span class="key-value-list__meta">
                            <a href="<?php echo $this->url(SiteController::ROUTE_UNLINK, [
                                'id' => $orgId,
                                'linkId' => $linkWithAe->getId()
                            ]);
                            ?>" class="table-summary__action">
                                Remove
                                <span class="visuallyhidden"> <?php echo $this->escapeHtml($vts->getName()); ?></span>
                            </a>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php if ($viewModel->canViewAeSection()): ?>
    <h3 class="summary-heading">
        Authorised Examiner Principles
        <?php if ($viewModel->getViewAuthorisation()->canCreateAuthorisedExaminerPrincipal()): ?>
            <span class="summary-heading__action">
                <a id="add-aep" href="<?php echo $this->url(AuthorisedExaminerPrincipalController::ROUTE_INDEX, ['id' => $orgId]); ?>">
                    Add an AEP
                </a>
            </span>
        <?php endif; ?>
    </h3>

    <table class="table-summary">
        <tbody>
            <?php foreach ($viewModel->getPrincipals() as $principalIdx => $principal) :
                $escPrincipalKey = (int)$principalIdx + 1;
                $contact = $viewModel->getPrincipalPersonalContact($principalIdx);
            ?>
                <tr id="<?php echo 'authorised-examiner-principal-' . $escPrincipalKey; ?>">
                    <th class="table-summary__key">
                        <?php echo $this->escapeHtml($principal->getFullName()); ?>

                        <?php if (isset($contact)): ?>
                            <span class="table-summary__meta">
                                <?php echo $this->escapeHtml(AddressUtils::stringify($contact->getAddress())); ?>
                            </span>
                        <?php endif; ?>
                    </th>

                    <td class="table-summary__value">
                        <?php if (isset($contact)): ?>
                            <?php echo $this->escapeHtml($contact->getPrimaryEmailAddress()); ?>
                            <br>
                            <?php echo $this->escapeHtml($contact->getPrimaryPhoneNumber()); ?>
                            <br>
                            <?php if($viewModel->getViewAuthorisation()->canRemoveAuthorisedExaminerPrincipal()):
                                $escUrlRemove = $this->url(AuthorisedExaminerPrincipalController::ROUTE_REMOVE_CONFIRMATION, [
                                    'id' => $orgId,
                                    'principalId' => $principal->getId()
                                ]); ?>
                                <br>
                                <a id="remove-aep" href="<?php echo $escUrlRemove; ?>">Remove</a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php echo $this->directDebitInfo($orgId); ?>

<?php echo $this->partial('/organisation/authorised-examiner/partials/index-buttons', ['urlBack' => $this->urlBack]); ?>
