<?php

foreach ($currentParams as $key => $val) {
    if ($form->has($key) && $form->get($key) instanceof \Zend\Form\Element\Hidden) {
        echo $this->formHidden($form->get($key));
    }
}

echo $this->partial(
    'dateFromTo',
    array(
        'dayFrom' => $form->get('dateFromDay'),
        'monthFrom' => $form->get('dateFromMonth'),
        'yearFrom' => $form->get('dateFromYear'),
        'legendFrom' => 'From',
        'dayTo' => $form->get('dateToDay'),
        'monthTo' => $form->get('dateToMonth'),
        'yearTo' => $form->get('dateToYear'),
        'legendTo' => 'To',
        'applyButton' => $form->get('submit'),
        'currentRange' => $currentDateRange,
    )
);
