<div class="row contents"> 
    <nav class="col-sm-12 module-filter-nav">
        <h4 class="module-filter-nav__header">Date range</h4>
        <ul class="module-filter-nav__list">
        <?php
            foreach ($dateRanges as $rangeKey => $rangeValue) {
                echo $this->dateRange($rangeKey, $rangeValue, $currentDateRange, $currentParams);
            }
        ?>
        </ul>
    </nav>
</div>