<div class="form-group">
    <fieldset>
        <?php if ($legend) { ?>
            <legend class="form-label" style="font-weight: bold;"><?php echo $this->escapeHtml($legend); ?></legend>
        <?php } ?>
        <div class="date-group">
            <div class="form-group form-group-day">
                <?php 
                    echo $this->formLabel($day);
                    echo $this->formInput($day);
                ?>
            </div>
            <div class="form-group form-group-month">
                <?php 
                    echo $this->formLabel($month);
                    echo $this->formInput($month);
                ?>
            </div>
            <div class="form-group form-group-year">
                <?php 
                    echo $this->formLabel($year);
                    echo $this->formInput($year);
                ?>
            </div>
        </div>
    </fieldset>
</div>