<?php

echo $this->form()->openTag($form);

echo $this->partial(
    'dateRangeList',
    array(
        'dateRanges' => $dateRanges,
        'currentDateRange' => $currentDateRange,
        'currentParams' => $currentParams
    )
);

echo $this->partial(
    'dateForm',
    array(
         'form' => $form,
         'currentParams' => $currentParams,
         'currentDateRange' => $currentDateRange,
         'legendFrom' => 'From',
         'legendTo' => 'To',
     )
);

$this->form()->closeTag();
