<div class="form-group custom-date-range" style="<?php echo ($currentRange == 'custom' ? '' : 'display: none;'); ?>">
    <fieldset>
        <?php
            echo $this->partial(
                'dateGroupFormElement', 
                array(
                    'day' => $dayFrom, 
                    'month' => $monthFrom,
                    'year' => $yearFrom,
                    'legend' => $legendFrom
                )
            );
        ?>

        <?php
            echo $this->partial(
                'dateGroupFormElement', 
                array(
                    'day' => $dayTo, 
                    'month' => $monthTo,
                    'year' => $yearTo,
                    'legend' => $legendTo
                )
            );
        ?>
        <?php echo $this->formSubmit($applyButton); ?>
    </fieldset>
</div>