<?php
use DvsaCommon\Date\DateUtils;

$label = isset($label) ? $label : '';
$prefix = isset($prefix) ? $prefix : '';
$postfix = isset($postfix) ? $postfix : '';
$required = isset($required) && $required === false ? false : true;

$dayIdValue = $prefix . ($prefix ? 'Day' : 'day') . $postfix;
$monthIdValue = $prefix . ($prefix ? 'Month' : 'month') . $postfix;
$yearIdValue = $prefix . ($prefix ? 'Year' : 'year') . $postfix;

$defaultDay = null;
$defaultMonth = null;
$defaultYear = null;

$yearStart = isset($yearStart) ? $yearStart : 1925;
$yearEnd = isset($yearEnd) ? $yearEnd : DateUtils::today()->format("Y");

if (isset($value)) {
    $value = mb_substr($value, 0, 10);
    $parts = explode('-', $value);

    if (count($parts) === 3) {
        $defaultDay = $parts[2];
        $defaultMonth = $parts[1];
        $defaultYear = $parts[0];
    }
}
?>

<div class="form-group">
    <label for="<?php echo $this->escapeHtml($dayIdValue); ?>"
           class="col-sm-4 control-label"><?php echo $this->escapeHtml($label); ?></label>
    <label for="<?php echo $this->escapeHtml($monthIdValue); ?>" class="hidden">Month of birth</label>
    <label for="<?php echo $this->escapeHtml($yearIdValue); ?>" class="hidden">Year of birth</label>

    <div class="col-sm-2">

        <select id="<?php echo $this->escapeHtml($dayIdValue); ?>" name="<?php echo $this->escapeHtml($dayIdValue); ?>"
                class="form-control input-small ">
            <?php for ($i = 1; $i <= 31; $i++) : ?>
                <option value="<?php echo $i; ?>"
                        <?php if ($i === intval($defaultDay)) : ?>selected<?php endif; ?>>
                    <?php echo $i; ?>
                </option>
            <?php endfor; ?>
        </select>
    </div>
    <div class="col-sm-2 datePickerInput">
        <select id="<?php echo $this->escapeHtml($monthIdValue); ?>"
                name="<?php echo $this->escapeHtml($monthIdValue); ?>" class="form-control input-small">
            <option value="01" <?php if ('01' === $defaultMonth) : ?>selected<?php endif; ?>>January</option>
            <option value="02" <?php if ('02' === $defaultMonth) : ?>selected<?php endif; ?>>February</option>
            <option value="03" <?php if ('03' === $defaultMonth) : ?>selected<?php endif; ?>>March</option>
            <option value="04" <?php if ('04' === $defaultMonth) : ?>selected<?php endif; ?>>April</option>
            <option value="05" <?php if ('05' === $defaultMonth) : ?>selected<?php endif; ?>>May</option>
            <option value="06" <?php if ('06' === $defaultMonth) : ?>selected<?php endif; ?>>June</option>
            <option value="07" <?php if ('07' === $defaultMonth) : ?>selected<?php endif; ?>>July</option>
            <option value="08" <?php if ('08' === $defaultMonth) : ?>selected<?php endif; ?>>August</option>
            <option value="09" <?php if ('09' === $defaultMonth) : ?>selected<?php endif; ?>>September</option>
            <option value="10" <?php if ('10' === $defaultMonth) : ?>selected<?php endif; ?>>October</option>
            <option value="11" <?php if ('11' === $defaultMonth) : ?>selected<?php endif; ?>>November</option>
            <option value="12" <?php if ('12' === $defaultMonth) : ?>selected<?php endif; ?>>December</option>
        </select>
    </div>
    <div class="col-sm-2 datePickerInput">
        <input
            type="number"
            id="<?php echo $this->escapeHtml($yearIdValue); ?>"
            name="<?php echo $this->escapeHtml($yearIdValue); ?>"
            value="<?php echo $this->escapeHtml($defaultYear); ?>"
            placeholder="year"
            <?php if ($required) : ?>
                required
            <?php endif; ?>
            maxlength="4"
            min="<?php echo $this->escapeHtml($yearStart); ?>"
            max="<?php echo $this->escapeHtml($yearEnd); ?>"
            class="form-control input-small">
    </div>
</div>