<?php
$fieldsetClass = isset($fieldsetClass) ? $fieldsetClass : 'fs-inline';
$label = isset($label) ? $label : '';
$labelId = isset($labelId) ? $labelId : '';
$value = isset($value) ? $value : '';
$name = isset($name) ? $name : '';
$required = isset($required) ? $required : false;
$option1 = isset($option1) ? $option1 : '';
$option2 = isset($option2) ? $option2 : '';
$labelId1 = 'radioOption' . ucfirst($name) . $option1;
$labelId2 = 'radioOption' . ucfirst($name) . $option2;
$id1 = $name . $option1;
$id2 = $name . $option2;
$option1Value = isset($option1Value) ? $option1Value : $option1;
$option2Value = isset($option2Value) ? $option2Value : $option2;


?>

<div class="form-group">
    <fieldset class="<?php echo $this->escapeHtml($fieldsetClass); ?>">
        <div class="col-sm-4 control-label">
            <legend id="<?php echo $this->escapeHtml($labelId); ?>"><?php echo $this->escapeHtml($label); ?></legend>
        </div>
        <div class="col-sm-6">
            <?php echo $this->partial(
                'radioElement',
                [
                    'id'        => $id1,
                    'name'      => $name,
                    'value'     => $option1Value,
                    'isChecked' => $option1Value === $value,
                    'label'     => $option1,
                    'labelId'   => $labelId1,
                    'required'  => $required,
                ]
            );

            echo $this->partial(
                'radioElement',
                [
                    'id'        => $id2,
                    'name'      => $name,
                    'value'     => $option2Value,
                    'isChecked' => $option2Value === $value,
                    'label'     => $option2,
                    'labelId'   => $labelId2,
                    'required'  => $required,
                ]
            );
            ?>
        </div>
    </fieldset>
</div>
