<?php
$id = isset($id) ? $id : '';
$name = isset($name) ? $name : $id;
$label = isset($label) ? $label : '';
$labelId = isset($labelId) ? $labelId : '';
$type = isset($type) ? $type : 'text';
$cssClass = isset($cssClass) ? $cssClass : '';
$labelLayout = isset($labelLayout) ? $labelLayout : 'col-sm-4';
$disabled = isset($disabled) ? $disabled : '';
$required = isset($required) ? $required : false;
$optional = isset($optional) && true === $optional ? false : true;
$pattern = isset($pattern) ? $pattern : '';
$min = isset($min) ? $min : '';
$maxLength = isset($maxLength) ? $maxLength : '';
$max = isset($max) ? $max : '';
$title = isset($title) ? $title : '';
$elementId = isset($elementId) ? $elementId : '';

$showPasswordMeter = $this->withDefault(false)->getValue($showPasswordMeter);
?>

<div class="form-group" <?php echo $elementId ? 'id="' . $this->escapeHtml($elementId) . '"' : ''; ?>>
    <label for="<?php echo $this->escapeHtml($id); ?>" id="<?php echo $this->escapeHtml($labelId); ?>"
           class="<?php echo $this->escapeHtml($labelLayout); ?> control-label"><?php echo $this->escapeHtml($label); ?>
        <?php if ($label) : ?>
            <?php if (!$required && $optional) : ?>
                (optional)
            <?php endif; ?>
        <?php endif; ?>
    </label>

    <div class="col-sm-6">
        <?php echo $this->partial(
            'inputElement',
            [
                'id'        => $id,
                'name'      => $name,
                'cssClass'  => $cssClass,
                'disabled'  => $disabled,
                'required'  => $required,
                'pattern'   => $pattern,
                'min'       => $min,
                'maxLength' => $maxLength,
                'max'       => $max,
                'title'     => $title,
                'type'      => 'password'
            ]
        ); ?>
        <?php if ($showPasswordMeter) : ?>
            <style type="text/css" scoped="scoped">
                .password_strength_container {
                    position: relative;
                    width: 100%;
                    margin-top: 2px;
                    height: 25px;
                }

                .password_strength_bg {
                    height: 4px;
                    background-color: #E8E8E8;
                    width: 100%;
                    position: absolute;
                    left: 0px;
                }

                .password_strength {
                    height: 4px;
                    background-color: rgb(200, 24, 24);
                    width: 0px;
                    position: absolute;
                    left: 0px;
                }

                .password_strength_separator {
                    height: 4px;
                    width: 2px;
                    background-color: #FFFFFF;
                    position: absolute;
                }

                .password_strength_desc {
                    float: right;
                    margin-top: 6px;
                    line-height: 16px;
                    font-size: 11px;
                }
            </style>
            <div class="password_strength_container">
                <div class="password_strength_bg"></div>
                <div class="password_strength"></div>
                <div style="left: 25%;" class="password_strength_separator"></div>
                <div style="left: 50%;" class="password_strength_separator"></div>
                <div style="left: 75%;" class="password_strength_separator"></div>
                <div style="" class="password_strength_desc"></div>
            </div>
        <?php endif ?>
    </div>
</div>
