<?php
$id = isset($id) ? $id : '';
$name = isset($name) ? $name : $id;
$label = isset($label) ? $label : 'Submit form';
$cssClass = isset($cssClass) ? $cssClass : 'btn btn-primary btn-large';
$value = isset($value) ? $value : '';
$disabled = (isset($disabled) && true === $disabled) ? true : false;
$toggle = isset($toggle) ? $toggle : false;
$target = isset($target) ? $target : false;

$t = [
    '<button'
    , ' name="', $this->escapeHtml($name), '"'
    , ' id="', $this->escapeHtml($id), '"'
    , ' value="', $this->escapeHtml($value), '"'
    , ' type="submit"'
    , ' class="', $this->escapeHtml($cssClass), '"'
    , ($disabled ? ' disabled' : '')
    , ($toggle ? ' data-toggle="' . $this->escapeHtml($toggle) . '"' : '')
    , ($target ? ' data-target="' . $this->escapeHtml($target) . '"' : '')
    , '>'
    , $this->escapeHtml($label)
    , '</button>'
];

echo implode('', $t);
