<?php
use Organisation\UpdateAeProperty\Process\Form\NamePropertyForm;

/** @var \Organisation\UpdateAeProperty\UpdateAePropertyViewModel $viewModel */

/** @var NamePropertyForm $form */
$form = $viewModel->getForm();

$this->headTitle('Change business name');
?>
<fieldset>
    <?php echo $this->partial(
        'partial/gds/form/control',
        [
            'element' => $form->getNameElement(),
        ]
    ); ?>
</fieldset>
