<?php

use Organisation\UpdateAeProperty\Process\Form\AreaOfficePropertyForm;

/** @var \Organisation\UpdateAeProperty\UpdateAePropertyViewModel $viewModel */

/** @var AreaOfficePropertyForm $form */
$form = $viewModel->getForm();

$this->headTitle('Change area office');
?>
<fieldset>
    <?php echo $this->partial(
        'partial/gds/form/control',
        [
            'element' => $form->getAreaOfficeElement()
        ]
    );?>
</fieldset>
