<table class="key-value-list">
    <tbody>
    <tr>
        <th class="key-value-list__key">
            Name
        </th>
        <td class="key-value-list__value">
            <?php echo $this->escapeHtml($testerName); ?>
        </td>
    </tr>
    <tr>
        <th class="key-value-list__key">
            Testing group
        </th>
        <td class="key-value-list__value">
            <?php if ($group === 'A'): ?>
                Group A
                <span class="key-value-list__meta">Class 1, Class 2</span>
            <?php elseif ($group === 'B'): ?>
                Group B
                <span class="key-value-list__meta">Class 3, Class 4, Class 5, Class 7</span>
            <?php endif ?>
        </td>
    </tr>
    <tr>
        <th class="key-value-list__key">
            Qualification status
        </th>
        <td class="key-value-list__value">
            <?php echo $this->escapeHtml($status); ?>
        </td>
    </tr>
    </tbody>
</table>

<form method="post" action="<?php echo $this->url(
    'user_admin/user-profile/change-qualification-status/confirmation',
    ['personId' => $testerId, 'vehicleClassGroup' => $group]
) ?>">

    <?php echo $this->csrfToken() ?>

    <nav class="content-navigation">
        <input id="confirm-record-demo-test" type="submit" class="button" value="Confirm qualification status"/>
        <ul class="content-navigation__secondary">
            <li>
                <a id="cancel-record-demo-test" href="<?php echo $this->url(
                    'user_admin/user-profile/change-qualification-status',
                    ['personId' => $testerId, 'vehicleClassGroup' => $group]
                ); ?>">Back to change qualification status</a>
            </li>
        </ul>
    </nav>
    </form>
