<?php
/**
 * @var \Organisation\ViewModel\AuthorisedExaminer\AeFormViewModel
 * @var AeLinkSiteForm                                             $form
 * @var \Zend\Mvc\Controller\Plugin\FlashMessenger                 $flashMessenger
 */
use Organisation\Form\AeLinkSiteForm;

$this->inlineScript()->appendFile($this->basePath('/assets/javascripts/vendor/typeahead.bundle.min.js'));
$this->inlineScript()->appendFile($this->basePath('/js/organisation/link-site-to-ae.js'));

$model = $this->model;
$form = $model->getForm();

//  show api errors
$flashMessenger = $this->layout()->flashMessenger;
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'failure']
);
?>

<form method="POST">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <?php echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id' => 'siteNumber',
                'help' => 'For example, V1234',
                'errorMessage' => $form->getError(AeLinkSiteForm::FIELD_SITE_NR),
                'label' => 'Site ID',
                'value' => $form->getSiteNumber(),
                'maxLength' => $form->getMaxInputLength(),
            ]
        ); ?>
    </fieldset>
    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id' => 'submitAeLink',
            'value' => 'Associate this site',
            'navigation' => [
                'Cancel and return to Authorised Examiner' => $model->getCancelUrl(),
            ],
        ]
    ); ?>
</form>

<?php $this->inlineScript()->captureStart(); ?>
    var sites = [
        <?php foreach ($form->getSites() as $site) {
        echo '"'.$this->escapeJs($site['site_number']).'",';
    }
        ?>
    ];
<?php $this->inlineScript()->captureEnd();
