<?php
/**
 * @var \DvsaClient\Entity\Person                    $nominee
 * @var \DvsaCommon\Dto\Organisation\OrganisationDto $authorisedExaminer
 * @var string                                       $roleName
 */
?>

<header class="content-header">
    <h1>
        <span class="content-header__type">
           Authorised Examiner
        </span>

        <span class="content-header__title">
            Summary and confirmation
        </span>
    </h1>
</header>

<?php echo $this->partial('errorMessages', ['getFromFlash' => true]); ?>

<div class="text">

    <p class="lede">Review the summary below before confirming:</p>

    <table class="key-value-list">
        <tbody>
            <tr>
                <th class="key-value-list__key">Name</th>
                <td class="key-value-list__value">
                    <?php echo $this->escapeHtml($nominee->getFullName()); ?>
                    <span class="key-value-list__meta"><?php echo $this->escapeHtml($nominee->getUsername()); ?></span>
                </td>
            </tr>

            <tr>
                <th class="key-value-list__key">New role</th>
                <td class="key-value-list__value"><?php echo $roleName ?></td>
            </tr>

        </tbody>
    </table>


</div>

<div class="message">
    <p>A notification will be sent to the user. To make the role active they must accept the role nomination.</p>
</div>

<form method="POST">
    <nav class="content-navigation">
        <?php echo $this->csrfToken() ?>
        <?php echo $this->partial('submitElement', ['cssClass' => 'button', 'id' => 'confirm-role', 'label' => 'Confirm']); ?>
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->url('authorised-examiner/list-user-roles', [
                        'personId' => $nominee->getId(),
                        'id' => $authorisedExaminer->getId(),
                    ]); ?>">Back to choose a role</a>
            </li>
        </ul>
    </nav>
</form>
