<?php

/**
 * @var $personUsername
 * @var $hasRoleOption
 * @var $id
 */
use DvsaCommon\UrlBuilder\AuthorisedExaminerUrlBuilderWeb;

/**
 * @var \Organisation\Form\SelectRoleForm $form
 */
?>

<header class="content-header">
    <h1>
        <span class="content-header__type">
            Authorised Examiner
        </span>

        <span class="content-header__title">
            <?php if ($hasRoleOption): ?>
                Choose a role
            <?php else: ?>
                Search for a user
            <?php endif; ?>
        </span>
    </h1>
</header>

<div class="text">

    <?php if ($hasRoleOption): ?>

        <p class="lede">Choose a new role for the following person:</p>

        <table class="key-value-list">
            <tbody>
                <tr>
                    <th class="key-value-list__key">Name</th>
                    <td class="key-value-list__value">
                        <?php echo $this->escapeHtml($personFullName); ?>
                        <span class="key-value-list__meta"><?php echo $this->escapeHtml($personUsername); ?></span>
                    </td>
                </tr>
            </tbody>
        </table>

        <br />

    <?php else: ?>
        <div class="message--failure">
            <p>We could not find the user <strong>'<?php echo $this->escapeHtml($personUsername); ?>'</strong>.</p>
        </div>
    <?php endif; ?>

</div>

<div>
    <?php
    $form = $this->form;
    $form->setAttribute('action', 'foo')->prepare();
    ?>
    <form action="<?php
    echo $this->url(
        'authorised-examiner/list-user-roles',
        [
            'id'       => $id,
            'personId' => $personId
        ]
    ); ?>" method="POST">
        <?php echo $this->csrfToken() ?>
        <?php echo $this->formRow($form->get('csrf')); ?>

        <?php if ($hasRoleOption): ?>
            <fieldset>
                <legend class="form-title heading-large" style="clear:both;">Available roles</legend>
                <div class="form-group<?php echo ($form->getRoleId()->getMessages()) ? ' has-error' : ''; ?>">
                    <fieldset>
                        <legend class="form-label">Select a role
                            <?php if ($form->getRoleId()->getMessages()) : ?>
                                <span class="validation-message" id="error2">You must select a role</span>
                            <?php endif; ?>
                        </legend>
                        <?php echo $this->formRow($form->getRoleId(), null, false); ?>
                    </fieldset>
                </div>
            </fieldset>
        <?php endif; ?>

        <nav class="content-navigation">
            <?php if ($hasRoleOption): ?>
                <?php echo $this->formInput($form->get('submit')); ?>
            <?php endif; ?>

            <ul class="content-navigation__secondary">
                <li>
                    <a id="vehicle-testing-station-home"
                       href="<?php echo AuthorisedExaminerUrlBuilderWeb::roles($id); ?>"
                       class="btn btn-link">Back to user search</a>
                </li>
            </ul>
        </nav>
    </form>
</div>
