<?php
/**
 * @var \DvsaClient\Entity\Person $nominee
 * @var int                       $vehicleTestingStationId
 * @var string                    $roleName
 * @var boolean                   $twoFactorEnabled
 */
?>

<header class="content-header">
    <h1>
        <span class="content-header__type">
           Vehicle testing station
        </span>

        <span class="content-header__title">
            Review role details
        </span>
    </h1>
</header>

<?php echo $this->partial('errorMessages', ['getFromFlash' => true]); ?>

<div class="text">

    <p class="lede">Check that this information is correct before you assign the new role.</p>

    <table class="key-value-list">
        <tbody>
            <tr>
                <th class="key-value-list__key">Name</th>
                <td class="key-value-list__value">
                    <?php echo $this->escapeHtml($nominee->getFullName()); ?>
                    <span class="key-value-list__meta"><?php echo $this->escapeHtml($nominee->getUsername()); ?></span>
                </td>
            </tr>

            <tr>
                <th class="key-value-list__key">New role</th>
                <td class="key-value-list__value"><?php echo $roleName ?></td>
            </tr>

        </tbody>
    </table>

</div>

<?php if ($twoFactorEnabled): ?>
    <div class="message" id="security-card-notification">
        <p>The user will receive a notification of the nomination. </p>
        <p>To accept or reject the role the user needs an active security card. </p>
        If they do not have one they will need to order one and activate it.
    </div>
    <?php else: ?>
        <div class="message">
            <p>The user will receive a role nomination in their notifications. They must accept this for the role to become active.</p>
        </div>
    <?php endif; ?>

<form method="POST">
    <nav class="content-navigation">
        <?php echo $this->csrfToken() ?>
        <?php echo $this->partial('submitElement', ['cssClass' => 'button', 'id' => 'confirm-role', 'label' => 'Assign role']); ?>
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->url('vehicle-testing-station-list-user-roles', [
                        'vehicleTestingStationId' => $vehicleTestingStationId,
                        'personId' => $nominee->getId()
                    ]); ?>">Back to choose a role</a>
            </li>
        </ul>
    </nav>
</form>
