<?php
use Site\Controller\RoleController;
use Site\Controller\VehicleTestingStationController;

$this->headTitle('Assign a role');

?>
<header class="content-header">
    <h1>
        <span class="content-header__type">
           Vehicle Testing Station
        </span>

        <span class="content-header__title">
             Assign a role
        </span>
    </h1>
</header>

<?php if ($userNotFound) : ?>
    <div class="message--failure">
        <p>We could not find the user <strong><?php echo $this->escapeHtml($personId); ?></strong>.</p>
    </div>
<?php endif; ?>

<?php echo $this->partial('errorMessages', array('getFromFlash' => true, 'isShowHidden' => true)); ?>

<div class="text">
    <p class="lede">Search for a user to assign a role to them.</p>
</div>
<form action="<?php echo $this->url(
    RoleController::ROUTE_SEARCH_FOR_PERSON,
    [
        'vehicleTestingStationId' => $vehicleTestingStationId,
    ]
); ?>" method="POST">
    <fieldset>
        <legend class="form-title heading-large" id="">Username</legend>
            <?php echo $this->csrfToken() ?>
        <span class="form-hint">For example, SMIT0001</span>
            <?php echo $this->partial(
                'inputBox',
                [
                    'id' => 'userSearchBox',
                    'required' => true,
                    'labelLayout' => 'form-label',
                    'name' => 'userSearchBox',
                    'class' => 'form-control',
                    'maxLength' => 100,
                ]
            );
            ?>
    </fieldset>

    <nav class="content-navigation">
        <?php
        echo $this->partial(
            'submitElement',
            [
                'label' => 'Search',
                'id' => 'search-button',
                'name' => 'action',
                'value' => 'search',
                'cssClass' => 'button'
            ]
        );
        ?>

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->url('vehicle-testing-station', ['id' => $vehicleTestingStationId]
                ); ?>">Cancel and return to <?php echo $this->escapeHtml($vehicleTestingStation->getName()) ?></a>
            </li>
        </ul>
    </nav>
</form>