<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Session\Container'              => __DIR__ . '/src/Session/Container.php',
  'Session\Service\SessionFactory' => __DIR__ . '/src/Session/Service/SessionFactory.php',
);
