<form action="<?php echo $this->url($searchResultsRoute); ?>" method="GET" role="form" novalidate>
    <fieldset>
        <?php
        echo $this->partial(
            'partial/forms/inputBox.phtml',
            [
                'id'       => 'username',
                'label'    => 'Username',
                'classLabel'    => 'form-label',
                'required' => true,
                'value'    => $this->withDefault('')->getValue($username),
            ]
        );
        echo $this->partial(
            'partial/forms/inputBox.phtml',
            [
                'id'       => 'firstName',
                'label'    => 'First name',
                'classLabel'    => 'form-label',
                'required' => true,
                'value'    => $this->withDefault('')->getValue($firstName),
            ]
        );
        echo $this->partial(
            'partial/forms/inputBox.phtml',
            [
                'id'       => 'lastName',
                'label'    => 'Last name',
                'classLabel'    => 'form-label',
                'required' => true,
                'value'    => $this->withDefault('')->getValue($lastName),
            ]
        );

        echo $this->partial(
            'partial/gds/form/datePickerBox.phtml',
            [
                'label'  => 'Date of birth',
                'day'    => $this->withDefault('')->getValue($dobDay),
                'month'  => $this->withDefault('')->getValue($dobMonth),
                'year'   => $this->withDefault('')->getValue($dobYear),
                'help'   => 'For example: 02 12 1970',
            ]
        );

        if ($userSearchExtended) {
            echo $this->partial(
                'partial/forms/inputBox.phtml',
                [
                    'id'       => 'town',
                    'label'    => 'Town',
                    'classLabel'    => 'form-label',
                    'required' => true,
                    'value'    => $this->withDefault('')->getValue($town),
                ]
            );
        }

        echo $this->partial(
            'partial/forms/inputBox.phtml',
            [
                'id'       => 'postcode',
                'label'    => 'Postcode',
                'classLabel'    => 'form-label',
                'required' => true,
                'value'    => $this->withDefault('')->getValue($postcode),
            ]
        );
        ?>
    </fieldset>
    <div class="form-group">
        <?php
        echo $this->partial(
            'partial/forms/submitElement.phtml',
            [
                'label' => 'Search',
                'cssClass' => 'button'
            ]
        );
        ?>
    </div>
</form>
