    <?php
    /** @var $roles array */
    ?>

    <table class="key-value-list">
        <tbody>
        <?php
        foreach ($roles as $role) : ?>
            <tr>
                <th class="key-value-list__key">
                    <?php echo $this->escapeHtml($role['name']); ?>
                    <?php if ($role['address']) : ?>
                        <span class="key-value-list__meta"><?php echo $this->escapeHtml($role['address']); ?></span>
                    <?php endif ?>
                </th>
                <td class="key-value-list__value" <?php echo
                ( $this->escapeHtml($role['id']) ? ' id="role-' . $this->escapeHtml($role["role"]) . '-' .
                    $this->escapeHtml($role['id']) . '"' : 'id="role-' . $this->escapeHtml($role["role"]) .'"');
                ?>><?php echo $this->escapeHtml($role["nicename"]); ?></td>
            </tr>
            <?php
        endforeach; ?>
        </tbody>
    </table>

    <nav class="content-navigation">
        <ul class="content-navigation__secondary">
            <li>
                <?php /** if javascript is enabled clicking this link triggers window.history.back() */ ?>
                <a class="history-go-back" href="<?php echo $backToProfileUrl; ?>">Return to user profile</a>
            </li>
        </ul>
    </nav>

    <script type="application/javascript">
        /**
         * Searches for all <a> tags with class="history-go-back" and makes them behave like browsers back button
         */
        window.addEventListener('load', function() {
            $('.history-go-back').click(function (e) {
                window.history.back();
                e.stopPropagation();
            });
        });
    </script>