    <?php
    /** @var $roles array */
    use Dashboard\Service\TradeRolesAssociationsService;
    use DvsaCommon\Auth\PermissionAtOrganisation;
    use DvsaCommon\Auth\PermissionAtSite;
    use DvsaCommon\UrlBuilder\AuthorisedExaminerUrlBuilderWeb;
    use DvsaCommon\UrlBuilder\VehicleTestingStationUrlBuilderWeb;
    ?>

    <table class="key-value-list" id="user-trade-roles-table">
        <tbody>
        <?php
        foreach ($roles as $role) : ?>
            <tr>
                <th class="key-value-list__key">
                    <?php if(isset($role['roletype'])
                        && $role['roletype'] == TradeRolesAssociationsService::ROLETYPE_ORGANISATIONS
                        && $this->authorisationHelper()->isGrantedAtOrganisation(PermissionAtOrganisation::AUTHORISED_EXAMINER_READ, $role['id'])): ?>
                        <a href="<?php echo AuthorisedExaminerUrlBuilderWeb::of($role['id']) ?>">
                            <?php echo $this->escapeHtml($role['name']); ?>
                        </a>
                    <?php elseif (isset($role['roletype'])
                        && $role['roletype'] == TradeRolesAssociationsService::ROLETYPE_SITES
                        && $this->authorisationHelper()->isGrantedAtSite(PermissionAtSite::VEHICLE_TESTING_STATION_READ, $role['id'])): ?>
                        <a href="<?php echo VehicleTestingStationUrlBuilderWeb::byId($role['id']) ?>">
                            <?php echo $this->escapeHtml($role['name']); ?>
                        </a>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($role['name']); ?>
                    <?php endif ?>
                    <?php if ($role['address']) : ?>
                        <span class="key-value-list__meta"><?php echo $this->escapeHtml($role['address']); ?></span>
                    <?php endif ?>
                </th>
                <td class="key-value-list__value" <?php echo
                ( $this->escapeHtml($role['id']) ? ' id="role-' . $this->escapeHtml($role["role"]) . '-' .
                    $this->escapeHtml($role['id']) . '"' : 'id="role-' . $this->escapeHtml($role["role"]) .'"');
                ?>><?php echo $this->escapeHtml($role["nicename"]); ?></td>
            </tr>
            <?php
        endforeach; ?>
        </tbody>
    </table>
