<table class="key-value-list">
    <tbody>
    <?php
    foreach ($roles as $role) : ?>
        <tr>
            <th class="key-value-list__key">
                <?php echo $this->escapeHtml($role['name']); ?>
                <?php if ($role['address']) : ?>
                    <span class="key-value-list__meta"><?php echo $this->escapeHtml($role['address']); ?></span>
                <?php endif ?>
            </th>
            <td class="key-value-list__value" <?php echo
             $role['id'] ? ' id="role-'.$this->escapeHtmlAttr($role['role']['code']).'-'.
                $this->escapeHtmlAttr($role['id']).'"' : 'id="role-'.$this->escapeHtmlAttr($role['role']['code']).'"';
            ?>><?php echo $this->escapeHtml($role['nicename']); ?></td>
        </tr>
        <?php
    endforeach; ?>
    </tbody>
</table>
