<?php
use Dashboard\ViewModel\UserTradeRolesViewModel;
use Dvsa\Mot\Frontend\PersonModule\View\ContextProvider;
use DvsaCommon\Constants\FeatureToggle;
use Dvsa\Mot\Frontend\PersonModule\Security\PersonProfileGuard;
/** @var $userTradeRolesViewModel UserTradeRolesViewModel */

$i = 0;
$j = 0;
foreach ($userTradeRolesViewModel->getTradeRoles() as $tradeRoles) : ?>
    <?php foreach ($tradeRoles as $roleType) : ?>
        <?php $personTradeRole = $roleType[0] ?>
        <h2 class="entity-header">
            <span class="entity-header__type">
                <?php echo $userTradeRolesViewModel->isRoleTypeSite($personTradeRole)
                    ? 'Vehicle Testing Station'
                    : 'Authorised Examiner' ?>
            </span>
            <span class="entity-header__title">
                <?php if($userTradeRolesViewModel->shouldDisplayLink($personTradeRole)): ?>
                    <a href="<?php echo $userTradeRolesViewModel->getUrlForRole($personTradeRole) ?>">
                        <?php echo $this->escapeHtml($personTradeRole->getWorkplaceName()); ?>
                    </a>
                <?php else: ?>
                    <?php echo $this->escapeHtml($personTradeRole->getWorkplaceName()); ?>
                <?php endif ?>
            </span>
            <span class="entity-header__tertiary">
                <strong><?php echo $personTradeRole->getNumber() ?></strong><?php echo (!empty($personTradeRole->getAddress()) ? ', ' : ''); ?>
                <?php if ($personTradeRole->getAddress()) : ?>
                    <?php echo $this->escapeHtml($personTradeRole->getAddress()); ?>
                <?php endif ?>
            </span>
        </h2>
        <table class="matched-records" id="user-trade-roles-table-<?php echo $j++ ?>">
            <thead>
                <tr>
                    <th class="matched-records__key visuallyhidden">Role</th>
                    <th class="matched-records__key visuallyhidden">Action</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($roleType as $personTradeRole) : ?>
                <tr>
                    <td class="matched-records__value">
                        <?php echo $this->escapeHtml($userTradeRolesViewModel->getTradeRoleNameByCode($personTradeRole->getRoleCode())); ?>
                    </td>
                    <?php $roleCode = $this->escapeHtml($personTradeRole->getRoleCode()) . '-' . $this->escapeHtml($personTradeRole->getWorkplaceId()); ?>
                    <td class="matched-records__value--right" <?php echo sprintf('id="role-%s"', $roleCode); ?>>
                        <?php if ($userTradeRolesViewModel->canBeRemoved($personTradeRole)): ?>
                            <a href="<?php echo $userTradeRolesViewModel->getUrlForRemoveRole($personTradeRole); ?>" id="remove-role-link-<?php echo $i++ ?>">Remove</a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endforeach; ?>
<?php endforeach; ?>
