<?php
    use Dashboard\ViewModel\UserTradeRolesViewModel;
    /** @var $userTradeRolesViewModel UserTradeRolesViewModel */
?>

    <table class="key-value-list" id="user-trade-roles-table">
        <tbody>
        <?php
        foreach ($userTradeRolesViewModel->getRolesAndAssociations() as $role) : ?>
            <tr>
                <th class="key-value-list__key">
                    <?php if($userTradeRolesViewModel->shouldDisplayLink($role['roletype'], $role['id'])): ?>
                        <a href="<?php echo $userTradeRolesViewModel->getUrlForRole($role['roletype'], $role['id']) ?>">
                            <?php echo $this->escapeHtml($role['name']); ?>
                        </a>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($role['name']); ?>
                    <?php endif ?>
                    <?php if ($role['address']) : ?>
                        <span class="key-value-list__meta"><?php echo $this->escapeHtml($role['address']); ?></span>
                    <?php endif ?>
                </th>
                <td class="key-value-list__value" <?php echo
                ( $this->escapeHtml($role['id']) ? ' id="role-' . $this->escapeHtml($role["role"]) . '-' .
                    $this->escapeHtml($role['id']) . '"' : 'id="role-' . $this->escapeHtml($role["role"]) .'"');
                ?>><?php echo $this->escapeHtml($role["nicename"]); ?></td>
            </tr>
            <?php
        endforeach; ?>
        </tbody>
    </table>
