<?php
use Dashboard\ViewModel\UserTradeRolesViewModel;
/** @var $userTradeRolesViewModel UserTradeRolesViewModel */


?>
    <table class="key-value-list" id="user-trade-roles-table">
        <tbody>
        <?php
        $i = 0;
        foreach ($userTradeRolesViewModel->getTradeRoles() as $personTradeRole) : ?>
            <tr>
                <th class="key-value-list__key">
                    <?php if($userTradeRolesViewModel->shouldDisplayLink($personTradeRole)): ?>
                        <a href="<?php echo $userTradeRolesViewModel->getUrlForRole($personTradeRole) ?>">
                            <?php echo $this->escapeHtml($personTradeRole->getWorkplaceName()); ?>
                        </a>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($personTradeRole->getWorkplaceName()); ?>
                    <?php endif ?>
                    <?php if ($personTradeRole->getAddress()) : ?>
                        <span class="key-value-list__meta"><?php echo $this->escapeHtml($personTradeRole->getAddress()); ?></span>
                    <?php endif ?>
                </th>
                <td class="key-value-list__value" <?php echo
                (' id="role-' . $this->escapeHtmlAttr($personTradeRole->getRoleCode()) . '-' . $this->escapeHtmlAttr($personTradeRole->getWorkplaceId()) . '"' );
                ?>>
                    <?php echo $this->escapeHtml($userTradeRolesViewModel->getTradeRoleNameByCode($personTradeRole->getRoleCode())); ?></td>
                <td>
                    <?php if ($userTradeRolesViewModel->canBeRemoved($personTradeRole)): ?>
                        <a href="<?php echo $userTradeRolesViewModel->getUrlForRemoveRole($personTradeRole, $this->url) ?>"
                        id="remove-role-link-<?php echo $i++ ?>">Remove</a>
                    <?php endif ?>
                </td>
            </tr>
            <?php
        endforeach; ?>
        </tbody>
    </table>
