<?php
$title = 'Create an account';
$this->headTitle($title);
$this->layout()->setVariable('pageSubTitle', 'MOT testing service');
?>
<?php
use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;

?>
<div class="text">

    <p class="lede">You need to create an account before using the MOT testing service. This should take 5 minutes</p>

    <h2 class="heading-medium">Before you start</h2>

    <p>Only people who need to use the MOT testing service for work - for example MOT testers, garage managers and DVSA staff - should create an account.</p>
    <p>Do not create a new account if you already have one.</p>
    <p>You will need:</p>
    <ul class="list-bullet">
        <li>your email address</li>
        <li>your telephone number</li>
        <li>your address</li>
        <li>your date of birth</li>
    </ul>
</div>

<form action="#">

    <nav class="content-navigation">

        <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->emailStep()); ?>" id="continue"
           class="button">Continue</a>

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->url('login') ?>" id="signIn">Cancel and return to sign in</a>
            </li>
        </ul>

    </nav>

</form>