<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'CensorApi\Factory\Service\CensorPhraseRepositoryFactory' => __DIR__ . '/src/CensorApi/Factory/Service/CensorPhraseRepositoryFactory.php',
  'CensorApi\Factory\Service\CensorServiceFactory'          => __DIR__ . '/src/CensorApi/Factory/Service/CensorServiceFactory.php',
  'CensorApi\Service\CensorService'                         => __DIR__ . '/src/CensorApi/Service/CensorService.php',
);
