<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DvsaElasticSearch\Model\ESConfig'               => __DIR__ . '/src/DvsaElasticSearch/Model/ESConfig.php',
  'DvsaElasticSearch\Model\ESDocMotTest'           => __DIR__ . '/src/DvsaElasticSearch/Model/ESDocMotTest.php',
  'DvsaElasticSearch\Model\ESDocMotTestLog'        => __DIR__ . '/src/DvsaElasticSearch/Model/ESDocMotTestLog.php',
  'DvsaElasticSearch\Model\ESDocType'              => __DIR__ . '/src/DvsaElasticSearch/Model/ESDocType.php',
  'DvsaElasticSearch\Model\ESDocVehicle'           => __DIR__ . '/src/DvsaElasticSearch/Model/ESDocVehicle.php',
  'DvsaElasticSearch\Query\FbQueryMotTest'         => __DIR__ . '/src/DvsaElasticSearch/Query/FbQueryMotTest.php',
  // REMOVED INVALID MAP: 'getSearchRecent'                                => __DIR__ . '/src/DvsaElasticSearch/Query/FbQueryMotTest.php',
  'DvsaElasticSearch\Query\FbQueryMotTestLog'      => __DIR__ . '/src/DvsaElasticSearch/Query/FbQueryMotTestLog.php',
  'DvsaElasticSearch\Query\FbQueryVehicle'         => __DIR__ . '/src/DvsaElasticSearch/Query/FbQueryVehicle.php',
  // REMOVED INVALID MAP: 'vehicleRepo'                                    => __DIR__ . '/src/DvsaElasticSearch/Query/FbQueryVehicle.php',
  'DvsaElasticSearch\Query\IFbQuery'               => __DIR__ . '/src/DvsaElasticSearch/Query/IFbQuery.php',
  'DvsaElasticSearch\Query\IQuery'                 => __DIR__ . '/src/DvsaElasticSearch/Query/IQuery.php',
  'DvsaElasticSearch\Query\SuperSearchQuery'       => __DIR__ . '/src/DvsaElasticSearch/Query/SuperSearchQuery.php',
  'DvsaElasticSearch\Service\ElasticSearchService' => __DIR__ . '/src/DvsaElasticSearch/Service/ElasticSearchService.php',
);
