<?php

use Dvsa\Mot\Frontend\MotTestModule\Controller\SurveyPageController;
use Dvsa\Mot\Frontend\MotTestModule\Model\SurveyRating;
/**
* @var SurveyRating $ratings
*/

$this->layout()->setVariable('pageTitle', "Give feedback");
?>

<div class="text">
    <p>Before you go, please help us to make the service better by giving some quick feedback.</p>
</div>

<form method="POST">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <legend class="form-label-bold">Overall, how did you feel about the service you received today?</legend>

        <input type="hidden" name="<?php echo SurveyPageController::TOKEN_KEY ?>" value="<?php echo $this->token?>"/>

        <?php

        $options = [];
        foreach ($ratings->getAll() as $key => $value) {
            $ratingOption = [
                'inputName' => 'satisfactionRating',
                'value' => $value,
                'key' => $key,
            ];
            array_push($options, $ratingOption);
        }

        echo $this->partial(
            'partial/gds/form/control-radio-group',
            [
                'name' => 'satisfactionRating',
                'splitLastOption' => false,
                'options' => $options
            ]
        );
        ?>
    </fieldset>
    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id' => 'submitSurvey',
            'value' => 'Send feedback',
        ]
    ); ?>
    <ul class="content-navigation__secondary">
        <li>
            <a id="cancel-and-return" href="<?php
            echo '/';
            ?>">
                <?php echo 'Sign in' ?>
            </a>
        </li>
    </ul>
</form>
