<?php

$this->layout()->setVariable('pageTitle', 'Thank you for your feedback');

?>

<div class="text">
    <p class="lede">Your feedback will help us improve the MOT testing service.</p>
    <p>If you want to leave more detailed comments, please complete the <a href="http://www.smartsurvey.co.uk/s/MOTFeedback/">feedback survey</a>.</p>
    <form action="#">
        <nav class="content-navigation">
            <ul class="content-navigation__secondary">
                <li>
                    <a id="back-to-home-link" href="/">Return home</a>
                </li>
            </ul>
        </nav>
    </form>
</div>