<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DvsaAuthentication\Authentication\Adapter\AuthenticationAdapterTrait'                             => __DIR__ . '/src/DvsaAuthentication/Authentication/Adapter/AuthenticationAdapterTrait.php',
  'DvsaAuthentication\Authentication\Adapter\OpenAM\Factory\OpenAMApiCredentialsBasedAdapterFactory' => __DIR__ . '/src/DvsaAuthentication/Authentication/Adapter/OpenAM/Factory/OpenAMApiCredentialsBasedAdapterFactory.php',
  // REMOVED INVALID MAP: 'getRealm'                                                                                         => __DIR__ . '/src/DvsaAuthentication/Authentication/Adapter/OpenAM/Factory/OpenAMApiCredentialsBasedAdapterFactory.php',
  // REMOVED INVALID MAP: 'get'                                                                                              => __DIR__ . '/src/DvsaAuthentication/Authentication/Adapter/OpenAM/Factory/OpenAMApiTokenBasedAdapterFactory.php',
  // REMOVED INVALID MAP: 'getRepository'                                                                                    => __DIR__ . '/src/DvsaAuthentication/Authentication/Adapter/OpenAM/Factory/OpenAMApiTokenBasedAdapterFactory.php',
  'DvsaAuthentication\Authentication\Adapter\OpenAM\Factory\OpenAMApiTokenBasedAdapterFactory'       => __DIR__ . '/src/DvsaAuthentication/Authentication/Adapter/OpenAM/Factory/OpenAMApiTokenBasedAdapterFactory.php',
  // REMOVED INVALID MAP: 'getIdentityAttributeUsername'                                                                     => __DIR__ . '/src/DvsaAuthentication/Authentication/Adapter/OpenAM/Factory/OpenAMApiTokenBasedAdapterFactory.php',
  'DvsaAuthentication\Authentication\Adapter\OpenAM\OpenAMApiCredentialsBasedAdapter'                => __DIR__ . '/src/DvsaAuthentication/Authentication/Adapter/OpenAM/OpenAMApiCredentialsBasedAdapter.php',
  'DvsaAuthentication\Authentication\Adapter\OpenAM\OpenAMApiTokenBasedAdapter'                      => __DIR__ . '/src/DvsaAuthentication/Authentication/Adapter/OpenAM/OpenAMApiTokenBasedAdapter.php',
  'DvsaAuthentication\Authentication\Listener\ApiAuthenticationListener'                             => __DIR__ . '/src/DvsaAuthentication/Authentication/Listener/ApiAuthenticationListener.php',
  'DvsaAuthentication\Authentication\Listener\AuthenticationListenerFactory'                         => __DIR__ . '/src/DvsaAuthentication/Authentication/Listener/AuthenticationListenerFactory.php',
  'DvsaAuthentication\Factory\ApiTokenServiceFactory'                                                => __DIR__ . '/src/DvsaAuthentication/Factory/ApiTokenServiceFactory.php',
  'DvsaAuthentication\Factory\AuthenticationServiceFactory'                                          => __DIR__ . '/src/DvsaAuthentication/Factory/AuthenticationServiceFactory.php',
  // REMOVED INVALID MAP: 'setAdapter'                                                                                       => __DIR__ . '/src/DvsaAuthentication/Factory/AuthenticationServiceFactory.php',
  'DvsaAuthentication\Factory\IdentityProviderFactory'                                               => __DIR__ . '/src/DvsaAuthentication/Factory/IdentityProviderFactory.php',
  'DvsaAuthentication\Identity'                                                                      => __DIR__ . '/src/DvsaAuthentication/Identity.php',
  'DvsaAuthentication\IdentityProvider'                                                              => __DIR__ . '/src/DvsaAuthentication/IdentityProvider.php',
  'DvsaAuthentication\Authentication\Service\ApiTokenService'                                        => __DIR__ . '/src/DvsaAuthentication/Service/ApiTokenService.php',
);
