<?php
use DvsaCommon\Enum\MotTestTypeCode;

if (!isset($defaultValue['score'])) {
    $defaultValue['score'] = 0;
}
    if (!isset($defaultValue['decision'])) {
        $defaultValue['decision'] = 1;
    }
    if (!isset($defaultValue['category'])) {
        $defaultValue['category'] = 1;
    }
    if (!isset($defaultValue['justification'])) {
        $defaultValue['justification'] = '';
    }
?>
<tr>
    <td colspan="5"><span class="<?php echo $this->escapeHtmlAttr($this->divider); ?>"></span></td>
</tr>
<?php $escRowClass = \DvsaCommon\Utility\EnumUtils::isTesterType($this->testType)
    ? 'tester-row'
    : 'vehicle-examiner-row'; ?>
<tr id="<?php echo $this->htmlId('rfr-%s-%s-%s', $this->id, $this->testType, $this->type); ?>"
    class="<?php echo $escRowClass; ?> sel-rfr-<?php echo $escSeleniumIndex; ?> sel-type-<?php echo $this->escapeHtmlAttr($testType); ?>
    <?php if (!empty($formError)) {
        echo ' has-error ';
    } ?>">
    <td>
        <?php
        // Add an internal anchor for the link from the top of the page error message.
        // This allows users to click straight to the invalid input for longer forms.
        // This line has more than one form element, any of which could fail, so we can
        // output more than link if needed here.
        if (!empty($formError) && is_array($formError)) {
            foreach ($formError as $key => $data) {
                if (is_array($data) && isset($data['ref'])) {
                    echo '<span id="error-'.$this->escapeHtmlAttr($data['ref']).'"></span>'.PHP_EOL;
                }
            }
        }
        ?>
        <span class="tester"><?php echo $this->escapeHtml($this->tester); ?></span>
        <br/>
        <?php echo $this->escapeHtml($this->description); ?>

        <?php if (!empty($this->rfrId)): ?>
            <span class="visually-hidden">Manual reference</span>

            <a data-toggle="modal" class="rfr-dialog-link"
               href="<?php echo $this->htmlId('#rfr-details-dialog-%s', $this->inspectionManualReference); ?>">
                <?php echo $this->escapeHtml($this->inspectionManualReference); ?></a>

            <?php echo $this->partial(
                'dvsa-mot-enforcement/mot-test/differences-found-between-tests/partials/manual-reference-modal',
                array(
                    'inspectionManualReference' => $this->inspectionManualReference,
                    'inspectionManualDescription' => $this->inspectionManualDescription,
                    'rfrId' => $this->rfrId,
                )
                );
            ?>
        <?php endif; ?>
        <?php echo $this->escapeHtml($this->locationLateral); ?>
        <?php echo $this->escapeHtml($this->locationLongitudinal); ?>
        <?php echo $this->escapeHtml($this->locationVertical); ?>

        <?php if (!empty($this->comment)): ?>
            (<?php echo $this->escapeHtml($this->comment); ?>)
        <?php endif; ?>

        <?php if ('ADVISORY' === $this->type): ?>
            <br/><strong>ADVISORY</strong>
        <?php elseif ('FAIL' === $this->type): ?>
            <br/><strong>FAIL</strong>
        <?php elseif ('PRS' === $this->type): ?>
            <br/><strong>PRS</strong>
        <?php endif; ?>
    </td>
    <td>
        <?php if (MotTestTypeCode::TARGETED_REINSPECTION === $this->testType && $this->notTested): ?>
            <p class="text-muted text-left">Disregard</p>
            <?php echo $this->partial('hiddenElement',
                array(
                    'id' => $this->htmlId('mappedRfr-%s-%s-%s-score', $this->id, $this->testType, $this->type),
                    'name' => $this->htmlId('mappedRfrs[%s][score]', $this->id, $this->testType, $this->type),
                    'value' => 1,
                ));
            ?>
        <?php else: ?>
            <?php
            echo $this->partial('selectElementExtended',
                array(
                    'id' => $this->htmlId('mappedRfr-%s-%s-%s-score', $this->id, $this->testType, $this->type),
                    'name' => $this->htmlId('mappedRfrs[%s][score]', $this->id),
                    'cssClass' => $this->htmlId('form-control point-score %s %s', $this->testType, $this->inspectionManualReference),
                    'options' => $this->dataCatalog->getScores(),
                    'value' => $defaultValue['score'],
                    'inputErrorClass' => (current(array_keys($formError)) == 'score' ? 'inputError' : ''),
                )); ?>
        <?php endif; ?>
    </td>
    <td>


        <?php if ('ER' == $this->testType && $this->notTested): ?>
            <p class="text-muted text-left">Not Applicable</p>

            <?php echo $this->partial('hiddenElement',
                array(
                    'id' => $this->htmlId('mappedRfr-%s-%s-%s-decision', $this->id, $this->testType, $this->type),
                    'name' => $this->htmlId('mappedRfrs[%s][decision]', $this->id, $this->testType, $this->type),
                    'value' => 1,
                ));
            ?>
        <?php else: ?>
            <?php
            $decisionTypeOptions = $this->dataCatalog->getDecisions($this->testType);
            $decisionTypeOptions[''] = 'Please select';
            ksort($decisionTypeOptions);
            echo $this->partial('selectElement',
                array(
                    'id' => $this->htmlId('mappedRfr-%s-%s-%s-decision', $this->id, $this->testType, $this->type),
                    'name' => $this->htmlId('mappedRfrs[%s][decision]', $this->id),
                    'cssClass' => $this->htmlId('form-control defects-decisions %s %s', $this->testType, $this->inspectionManualReference),
                    'options' => $decisionTypeOptions,
                    'value' => $defaultValue['decision'],
                    'inputErrorClass' => (current(array_keys($formError)) == 'decision' ? 'inputError' : ''),
                )); ?>
        <?php endif; ?>

    </td>
    <td>
        <?php if ('ER' == $this->testType && $this->notTested): ?>
            <p class="text-muted text-left">Not Applicable</p>

            <?php echo $this->partial('hiddenElement',
                array(
                    'id' => $this->htmlId('mappedRfr-%s-%s-%s-category', $this->id, $this->testType, $this->type),
                    'name' => $this->htmlId('mappedRfrs[%s][category]', $this->id, $this->testType, $this->type),
                    'value' => 1,
                ));
            ?>
        <?php else: ?>
            <?php

            $categoriesOptions = $this->dataCatalog->getCategories();
            $categoriesOptions[''] = 'Please select';
            ksort($categoriesOptions);

            echo $this->partial('selectElement',
                array(
                    'id' => $this->htmlId('mappedRfr-%s-%s-%s-category', $this->id, $this->testType, $this->type),
                    'name' => $this->htmlId('mappedRfrs[%s][category]', $this->id),
                    'cssClass' => $this->htmlId('form-control categories %s %s',
                            $this->testType, $this->inspectionManualReference),
                    'options' => $categoriesOptions,
                    'value' => $defaultValue['category'],
                    'inputErrorClass' => (current(array_keys($formError)) == 'category' ? 'inputError' : ''),
                )); ?>
        <?php endif; ?>
    </td>

    <td>
        <?php if ('ER' == $this->testType && $this->notTested): ?>
            <p class="text-muted text-left">Not Applicable</p>
            <?php echo $this->partial('hiddenElement',
                array(
                    'id' => $this->htmlId('mappedRfr-%s-%s-%s-justification', $this->id, $this->testType, $this->type),
                    'name' => $this->htmlId('mappedRfrs[%s][justification]', $this->id),
                    'value' => '',
                )); ?>
        <?php else: ?>
            <div class="form-group"><textarea name="<?php echo  $this->htmlId('mappedRfrs[%s][justification]', $this->id); ?>"
                      id="<?php echo $this->htmlId('mappedRfr-%s-%s-%s-justification', $this->id, $this->testType, $this->type); ?>"
                      cols="30"
                      rows="3"
                      class="<?php echo $this->htmlId('form-control flexible-vert justification %s %s', $this->testType, $this->inspectionManualReference);
                      if (!empty($formError) && 'justification' == current(array_keys($formError))) {
                          echo ' inputError';
                      }
                      ?>"><?php echo $this->escapeHtml($defaultValue['justification']); ?></textarea></div>
        <?php endif; ?>
    </td>
</tr>
