<?php
use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;

?>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $errorsSummary]); ?>


<form action="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->securityQuestionStepTwo());?>"
      method="POST" autocomplete="off" novalidate="">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <legend class="form-title heading-large" id="">Choose another question</legend>

        <div class="form-group">
            <label class="form-label" for="question2">Select a question to answer</label>
            <select class=" form-control form-control-1-2" id="question2" name="question2">
                <?php
                foreach ($questions as $key => $value) {
                    $select = $question2 == $key? 'selected' : '';
                    ?>
                    <option <?php echo $select; ?> value="<?php echo $key; ?>">
                        <?php echo $value; ?></option>
                    <?php
                } ?>
            </select>
        </div>

        <div class="form-group<?php if ($answer2HasError) echo ' has-error' ?>">
            <label class="form-label" for="answer2">Your answer
                <?php
                if ($answer2HasError) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['answer2']]);
                }
                ?>
            </label> <input class=" form-control form-control-1-4"
                id="answer2" name="answer2" type="text" value="<?php echo $this->escapeHtmlAttr($answer2) ?>">
        </div>
    </fieldset>

    <nav class="content-navigation">

        <input type="submit" value="Continue" id="continue" class="button">

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->securityQuestionStepOne());?>" id="back">Back</a>
            </li>
        </ul>

    </nav>
</form>