<?php
$id = isset($id) ? $id : '';
$name = isset($name) ? $name : $id;
$value = isset($value) ? $value : '';
$defaultValue = isset($defaultValue) ? $defaultValue : '';
$label = isset($label) ? $label : '';
$isChecked = (isset($isChecked) && true === $isChecked) ? true : false;
?>

<div class="form-group">
    <label for="<?php echo $this->escapeHtmlAttr($id); ?>" class="checkbox-inline">
        <?php echo $this->partial(
            'partial/forms/checkbox-element.phtml',
            [
                'id' => $id,
                'name' => $name,
                'value' => $value,
                'defaultValue' => $defaultValue,
                'isChecked' => $isChecked,
            ]
        ); ?>
        <?php if ($label) : ?>
            <?php echo $this->escapeHtml($label); ?>
        <?php endif; ?>
    </label>
</div>