<?php
$id = isset($id) ? $id : '';
$name = isset($name) ? $name : $id;
$value = isset($value) ? $value : '';
$defaultValue = isset($defaultValue) ? $defaultValue : '';
$isChecked = (isset($isChecked) && true === $isChecked) ? true : false;
$labelId = isset($labelId) ? $labelId : '';
$label = isset($label) ? $label : '';

?>
<?php echo $this->partial(
    'partial/forms/hidden-element.phtml', [
        'name'  => $name,
        'value' => $defaultValue,
        'id'    => 'hidden_' . $id
    ]
); ?>
<label for="<?php echo $this->escapeHtmlAttr($id); ?>" id="<?php echo $this->escapeHtmlAttr($labelId); ?>"
       class="control-label"><?php echo $this->escapeHtml($label); ?>
</label>

<input value="<?php echo $this->escapeHtmlAttr($value); ?>" name="<?php echo $this->escapeHtmlAttr($name); ?>"
       id="<?php echo $this->escapeHtmlAttr($id); ?>" type="checkbox"
    <?php if (true === $isChecked) : ?>
        checked
    <?php endif; ?>
    >
