<?php
$id = isset($id) ? $id : '';
$name = isset($name) ? $name : $id;
$defaultValue = isset($defaultValue) ? $defaultValue : '';
$label = isset($label) ? $label : '';
$type = isset($type) ? $type : 'text';
$cssClass = isset($cssClass) ? $cssClass : '';
$value = isset($value) ? $value : '';
$disabled = isset($disabled) ? $disabled : '';
$required = isset($required) ? $required : false;
$optional = isset($optional) ? $optional : true;
$pattern = isset($pattern) ? $pattern : '';
$min = isset($min) ? $min : '';
$maxLength = isset($maxLength) ? $maxLength : '';
$max = isset($max) ? $max : '';
$title = isset($title) ? $title : '';
$elementId = isset($elementId) ? $elementId : '';
$escapedHintText = isset($hintText) ? '<p class="help-block">' . $this->escapeHtmlAttr($hintText) . '</p>' : '';
$classFormGroup = isset($classFormGroup) ? $classFormGroup : '';
$classLabel = isset($classLabel) ? $classLabel : '';
$labelId = isset($labelId) ? $labelId : str_replace(' ', '-', $classFormGroup . $label);
$formHintText = isset($formHintText) ? $formHintText : '';
$errors = isset($errors) ? $errors : '';
?>

<div class="form-group <?php echo $this->escapeHtmlAttr($classFormGroup); ?>" <?php echo $elementId ? 'id="'. $this->escapeHtmlAttr($elementId) .'"' : ''; ?>>
    <label for="<?php echo $this->escapeHtmlAttr($id); ?>" id="<?php echo $this->escapeHtmlAttr($labelId); ?>" class="<?php echo $this->escapeHtmlAttr($classLabel); ?>">
            <?php 
                echo $this->escapeHtml($label);
                if (!$required && $optional) {
                    echo ' (optional)';
                }
                if (isset($formHintText)): ?>
                    <span class="form-hint">
                        <?php echo $formHintText; ?>
                    </span>
                <?php endif;
                if (isset($errors)) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors]);
                }
            ?>
    </label>
    <?php echo $escapedHintText; ?>

    <?php echo $this->partial(
        'partial/forms/inputElement.phtml',
        [
            'id'        => $id,
            'type'      => $type,
            'name'      => $name,
            'cssClass'  => $cssClass,
            'value'     => $value,
            'disabled'  => $disabled,
            'required'  => $required,
            'pattern'   => $pattern,
            'min'       => $min,
            'maxLength' => $maxLength,
            'max'       => $max,
            'title'     => $title
        ]
    ); ?>
</div>