<?php
$id = isset($id) ? $id : '';
$labelId = isset($labelId) ? $labelId : '';
$name = isset($name) ? $name : '';
$option = isset($option) ? $option : '';
$required = isset($required) ? $required : '';
$optionValue = isset($optionValue) ? $optionValue : $option;
$labelCssClass = (isset($labelCssClass) && !is_null($labelCssClass)) ? $labelCssClass : 'block-label';

// vars added to make interface more consistent across partials
$value = isset($value) ? $value : $optionValue;
$isChecked = isset($isChecked) ? $isChecked : $value === $optionValue;
$label = isset($label) ? $label : $option;
$escapeLabel = isset($escapeLabel) ? $escapeLabel : true;
?>

<label for="<?php echo $this->escapeHtmlAttr($id); ?>" class="<?php echo $this->escapeHtmlAttr($labelCssClass); ?>" id="<?php echo $this->escapeHtmlAttr($labelId); ?>">
    <input
        type="radio"
        id="<?php echo $this->escapeHtmlAttr($id); ?>"
        <?php if ($isChecked) : ?>
            checked
        <?php endif; ?>
        name="<?php echo $this->escapeHtmlAttr($name); ?>"
        value="<?php echo $this->escapeHtmlAttr($value); ?>"
        <?php if ($required) : ?>required<?php endif; ?>/>
    <?php if ($escapeLabel): ?>
        <?php echo $this->escapeHtml($label) ?>
    <?php else: ?>
        <?php echo $label ?>
    <?php endif ?>
</label>