<div id="global-breadcrumb" class="header-context">
    <nav>
        <ol class="group">
            <li id="breadcrumb-0"><a href="/">Home</a></li>

            <?php
            use DvsaCommon\Utility\ArrayUtils;

$counter = 1;
            if (ArrayUtils::isAssoc($breadcrumbs)):
            foreach ($breadcrumbs as $name => $link): ?>
                <li id="breadcrumb-<?php echo $counter++ ?>">
                    <?php if (!empty($link)): ?>
                        <a href="<?php echo $this->escapeHtmlAttr($link); ?>"><?php echo $this->escapeHtml($name); ?></a>
                    <?php else: ?>
                        <?php echo $this->escapeHtmlAttr($name); ?>
                    <?php endif; ?>
                </li>
            <?php endforeach;
            else :
            foreach ($breadcrumbs as $pair):
                foreach ($pair as $name => $link): ?>
                <li id="breadcrumb-<?php echo $counter++ ?>">
                    <?php if (!empty($link)): ?>
                        <a href="<?php echo $this->escapeHtmlAttr($link); ?>"><?php echo $this->escapeHtml($name); ?></a>
                    <?php else: ?>
                        <?php echo $this->escapeHtmlAttr($name); ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; endforeach; endif; ?>
        </ol>
    </nav>
</div>
