<div id="global-breadcrumb" class="header-context">
    <nav role="navigation">
        <ol class="group">
            <li><a href="/">Home</a></li>
            <?php foreach ($breadcrumbs as $name => $link): ?>
                <li>
                    <?php if (!empty($link)): ?>
                        <a href="<?php echo $this->escapeHtmlAttr($link); ?>"><?php echo $this->escapeHtml($name); ?></a>
                    <?php else: ?>
                        <?php echo $this->escapeHtmlAttr($name); ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </nav>
</div>
