<?php

$name = (isset($this->config['name']) ? $this->config['name'] : null);
$phone = (isset($this->config['phoneNumber']) ? $this->config['phoneNumber'] : null);
$openingHrsWeekdays	=	(isset($this->config['openingHrsWeekdays']) ? $this->config['openingHrsWeekdays'] : null);
$openingHrsSaturday	=	(isset($this->config['openingHrsSaturday']) ? $this->config['openingHrsSaturday'] : null);
$openingHrsSunday	=	(isset($this->config['openingHrsSunday']) ? $this->config['openingHrsSunday'] : null);
?>
<p>
	Call the DVSA Helpdesk <?php echo $this->escapeHtml($name); ?> on <strong><?php echo $this->escapeHtml($phone); ?></strong>
</p>

<p>Opening hours are:</p>

<p>
	<?php echo $this->escapeHtml($openingHrsWeekdays); ?> <br>
	<?php echo $this->escapeHtml($openingHrsSaturday); ?><br>
	<?php echo $this->escapeHtml($openingHrsSunday); ?>
</p>