<?php
use Core\ViewModel\Header\HeaderTertiaryList;

/** @var string $type */
/** @var string $title */
/** @var string $progress */
/** @var string|HeaderTertiaryList $tretiary */
?>
<header class="content-header">
    <h1>
        <span class="content-header__type"><?php echo $this->escapeHtml($type); ?></span>
        <span class="content-header__title"><?php echo $this->escapeHtml($title); ?></span>
        <?php if (isset($progress)): ?>
            <span class="content-header__progress"><?php echo $this->escapeHtml($progress); ?></span>
        <?php endif; ?>
    </h1>
    <?php if (isset($tertiary)): ?>
        <?php if (is_string($tertiary)): ?>
            <h2>
                <span class="content-header__tertiary"><?php echo $this->escapeHtml($tertiary); ?></span>
            </h2>
        <?php elseif ($tertiary instanceof HeaderTertiaryList): ?>
            <ul class="content-header__tertiary-list">
                <?php foreach ($tertiary->getElements() as $element): ?>
                    <li class="<?php echo $element->isBold() ? "content-header__list-item--primary": "content-header__list-item" ?>">
                        <?php echo $element->getText(); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <?php endif; ?>
</header>