<div id="password-criteria-scope" class="module-criteria">
    <span>Your new password must have:</span>
    <ul class="criteria__list">
        <li data-criteria="minLength" data-criteria-param="8" class="criteria__criterion">8 or more characters</li>
        <li data-criteria="hasNumeric" class="criteria__criterion">1 or more numbers</li>
        <li data-criteria="hasMixedCase" class="criteria__criterion">upper and lower case letters</li>
    </ul>
    <p>It can't be a password you have used before.</p>
</div>

<?php $this->inlineScript()->captureStart(); ?>
    var passwordCriteria = new DVSA.criteriaValidation({
        trigger: document.querySelector("#password"),
        criteria: document.querySelector('#password-criteria-scope')
    });

    passwordCriteria.checkCriteria();
<?php $this->inlineScript()->captureEnd(); ?>
