<?php
    // If a $username was supplied to this partial we can extend the checking
    // by ensuring the new password value does not match this value.
    $mustNots = [];
    if (isset($username)) {
        $mustNots[] = sprintf(
            '<li data-criteria="notMatch" data-criteria-param="%s" class="criteria__criterion">match your username</li>',
            $username
            );
    }
?>
<label>Your new password must have:
    <div id="password-criteria-scope" class="module-criteria">
        <ul class="criteria__list">
            <li data-criteria="minLength" data-criteria-param="8" class="criteria__criterion">8, or more, characters</li>
            <li data-criteria="hasNumeric" class="criteria__criterion">1, or more, numbers</li>
            <li data-criteria="hasMixedCase" class="criteria__criterion">upper and lower case letters</li>
        </ul>
        <span>and, must not</span>
        <?php if (count($mustNots)): ?>
            <ul class="criteria__list">
                <?php foreach($mustNots as $escMustNot): ?>
                    <?php echo $escMustNot; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</label>


<?php $this->inlineScript()->captureStart(); ?>
    var passwordCriteria = new DVSA.criteriaValidation({
        trigger: document.querySelector("#password"),
        criteria: document.querySelector('#password-criteria-scope')
    });

    passwordCriteria.checkCriteria();

<?php $this->inlineScript()->captureEnd(); ?>
