<?php
use Core\ViewModel\Sidebar\GeneralSidebar;
use Core\ViewModel\Sidebar\GeneralSidebarLink;
use Core\ViewModel\Sidebar\GeneralSidebarLinkList;
use Core\ViewModel\Sidebar\GeneralSidebarStatusBox;
use Core\ViewModel\Sidebar\SidebarButton;
use DvsaCommon\Utility\TypeCheck;

/** @var $sidebar \Core\ViewModel\Sidebar\GeneralSidebar */

TypeCheck::assertInstance($sidebar, GeneralSidebar::class);

?>

<div class="related">

    <?php foreach ($sidebar->getSidebarItems() as $sideBarItem) : ?>

        <?php if ($sideBarItem instanceof GeneralSidebarStatusBox): ?>

            <ul class="related__status">

                <?php foreach ($sideBarItem->getItems() as $statusItem): ?>
                    <li <?php echo ($statusItem->getHtmlId() ? 'id="' . $this->escapeHtmlAttr($statusItem->getHtmlId()). '"' : '') ?>>
                        <span
                            class="<?php echo $statusItem->getBadge()->getCssClass() ?>">
                            <?php echo($statusItem->escapeValue() ? $this->escapeHtml($statusItem->getValue()) : $statusItem->getValue()); ?>
                        </span>
                        <strong>
                            <?php echo($statusItem->escapeKey() ? $this->escapeHtml($statusItem->getKey()) : $statusItem->getKey()); ?>
                        </strong>
                        <?php if ($statusItem->getSecondaryText() !== null): ?>
                            <br/>
                            <span
                                class="text-secondary">
                                <?php echo($statusItem->escapeSecondaryText() ? $this->escapeHtml($statusItem->getSecondaryText()) : $statusItem->getSecondaryText()); ?>
                            </span>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>

            </ul>

        <?php endif; ?>

        <?php if ($sideBarItem instanceof GeneralSidebarLinkList): ?>
            <div class="related__section">
                <h2 class="related__section-title"><?php echo $this->escapeHtml($sideBarItem->getTitle()); ?></h2>

                <ul class="related__section-links">

                    <?php foreach ($sideBarItem->getLinks() as $link): ?>
                        <li>
                            <?php
                                if($link instanceof SidebarButton) {
                                    echo $this->partial('/partial/gds/general/sidebar/button', ['button' => $link]);
                                } elseif($link instanceof GeneralSidebarLink) {
                                    echo $this->partial('/partial/gds/general/sidebar/general-link', ['link' => $link]);
                                }
                            ?>
                        </li>

                    <?php endforeach; ?>

                </ul>
            </div>

        <?php endif; ?>

    <?php endforeach; ?>

</div>
