<?php
use Core\ViewModel\Sidebar\GeneralSidebar;
use Core\ViewModel\Sidebar\GeneralSidebarLinkList;
use Core\ViewModel\Sidebar\GeneralSidebarStatusBox;
use DvsaCommon\Utility\TypeCheck;

/** @var $sidebar \Core\ViewModel\Sidebar\GeneralSidebar */

TypeCheck::assertInstance($sidebar, GeneralSidebar::class);

?>

<div class="related">

    <?php foreach($sidebar->getSidebarItems() as $sideBarItem) : ?>

            <?php if($sideBarItem instanceof GeneralSidebarStatusBox): ?>

                <ul class="related__status">

                    <?php foreach ($sideBarItem->getItems() as $statusItem): ?>
                            <li>
                                <span class="badge<?php echo $statusItem->getModifier() != '' ? '--' . $statusItem->getModifier() : ''; ?>"><?php echo $this->escapeHtml($statusItem->getValue()); ?></span>
                                <strong><?php echo $this->escapeHtml($statusItem->getKey()); ?></strong>
                            </li>
                    <?php endforeach; ?>

                </ul>

            <?php endif; ?>

        <?php if ($sideBarItem instanceof GeneralSidebarLinkList): ?>
            <div class="related__section">
                <h2 class="related__section-title"><?php echo $this->escapeHtml($sideBarItem->getTitle()); ?></h2>

                <ul class="related__section-links">

                <?php foreach ($sideBarItem->getLinks() as $link): ?>
                    <li>
                        <a id="<?php echo $this->escapeHtmlAttr($link->getHtmlId()); ?>"
                           href="<?php echo $this->escapeHtmlAttr($link->getUrl()); ?>">
                            <?php echo $this->escapeHtml($link->getText()); ?>
                        </a>
                    </li>

                <?php endforeach; ?>

                </ul>
            </div>

        <?php endif; ?>

    <?php endforeach; ?>

</div>
