<?php
$escMessageType = (isset($type))? 'message--' . $this->escapeHtmlAttr($type) : 'message';
?>

<?php
if (!empty($messages)) {
    foreach ($messages as $message) {
        ?>
        <div class="<?php echo $escMessageType; ?>" id="validation-<?php echo $escMessageType; ?>">
            <?php if (!empty($this->heading)): ?>
                <h3 class="message__heading"><?php echo $this->escapeHtml($this->heading); ?></h3>
            <?php endif; ?>

            <?php if (is_array($message)): ?>
                <p><?php echo sprintf(
                        '%s<strong>%s</strong>',
                        $this->escapeHtml($message[0]),
                        $this->escapeHtml($message[1])
                    ); ?></p>
            <?php else: ?>
                <p><?php echo $this->escapeHtml($message); ?></p>
            <?php endif; ?>
        </div>
        <?php
    }
}
?>