<?php
use DvsaCommon\Date\DateTimeDisplayFormat;
use \Zend\Form\Element;
use \Zend\Form\Element\Radio;
use \Zend\Form\Element\Select;
use \Zend\Form\Element\DateSelect;

?>
<section class="module-present-data">

    <h2>
        <?php echo $this->escapeHtml($title); ?>
        <span id="<?php echo $this->escapeHtmlAttr(str_replace(' ', '_', $title)); ?>">
          <a href="<?php echo $this->basePath('vehicle-step/' . $this->escapeUrl($this->url)); ?>"
             id="<?php echo strtolower(str_replace(' ', '-', $title)) ?>-change-this">Change this</a>
        </span>
    </h2>

    <dl class="horizontal large">

        <?php
        foreach ($sectionData as $element) :
            $id = $element['id'];
            $label = $element['label'];
            $value = $element['value'];
            ?>
            <dt>
                <?php echo $this->escapeHtml($label); ?>
            </dt>
            <dd id="<?php echo $this->escapeHtmlAttr($id); ?>">
                <?php echo $this->escapeHtml($value); ?>
            </dd>

        <?php
        endforeach;
        ?>

    </dl>

</section>
