<?php
use DvsaCommon\Utility\ArrayUtils;
?>

<?php /** @var $form \DvsaMotTest\NewVehicle\Form\CreateVehicleStepOneForm */ ?>

<?php $this->headScript()->appendFile('/js/dvsa-2100.js'); ?>

<div class="row">
    <div class="col-lg-12">
        <!-- PROGRESS TRACKER: OPTIONAL -->
        <div class="progress-tracker">
            <ul class="list-unstyled">
                <li class="active"><i class="fa fa-arrow-circle-right"></i>Vehicle identification</li>
                <li><i class="fa fa-arrow-circle-right"></i>Vehicle specification</li>
                <li><i class="fa fa-arrow-circle-right"></i>Summary</li>
            </ul>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h1>Create a new vehicle record</h1>
        <p style="font-size:22px;">You will need information on the vehicle’s identification and specification to create a new record.</p>
        <p>Your new record will be checked by the DVLA and DVSA. Make sure you have the correct details and you can’t find the vehicle in the <a href="<?php echo $this->url('vehicle-search'); ?>">vehicle search</a>.</p>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">

        <?php
        $form = $form->prepare();
        echo $this->form()->openTag($form);

        $fields = $form->get('vehicleForm');
        ?>
        <?php if($this->form->getMessages()): ?>
            <div class="validation-summary" id="validation-summary-id">
                <h2>There was a problem with the information you entered:</h2>
                <ol>
                    <?php foreach($form->getMessages() as $field => $fieldMessages): ?>
                        <?php foreach($fieldMessages as $fieldName => $message): ?>
                            <?php
                            $field = $form->getFromFieldset($fieldName);
                            $fieldName = $field->getLabel();
                            ?>
                            <li><?php echo $this->escapeHtml($fieldName); ?> - <?php echo $this->escapeHtml(end($message)); ?></li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        <?php endif; ?>
        <?php ?>
        <fieldset>
            <legend><?php echo $form->get('vehicleForm')->getOption('legend'); ?></legend>
            <?php echo $this->csrfToken() ?>
            <div class="form-group<?php if($form->getCountryOfRegistration()->getMessages()): ?> has-error<?php endif; ?>">
                <?php echo $this->formLabel($form->getCountryOfRegistration()); ?>
                <?php if($form->getCountryOfRegistration()->getMessages()): ?>
                    <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getCountryOfRegistration()->getMessages()); ?></span>
                <?php endif; ?>
                <?php echo $this->formElement($form->getCountryOfRegistration()); ?>
            </div>

            <div class="form-group">
                <div class="form-group form-group-related<?php if($form->getRegistrationNumber()->getMessages()): ?> has-error<?php endif; ?>">
                    <?php echo $this->formLabel($form->getRegistrationNumber()); ?>
                    <?php if($form->getRegistrationNumber()->getMessages()): ?>
                        <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getRegistrationNumber()->getMessages()); ?></span>
                    <?php endif; ?>
                    <?php echo $this->formElement($form->getRegistrationNumber()); ?>
                </div>
                <div class="panel-indent <?php if($form->getEmptyVrmReason()->getMessages()): ?> has-error<?php endif; ?>">
                    <label for="<?php echo $form->getEmptyVrmReason()->getName(); ?>">
                        <?php echo $form->getEmptyVrmReason()->getLabel(); ?>
                        <?php if($form->getEmptyVrmReason()->getMessages()): ?>
                            <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getEmptyVrmReason()->getMessages()); ?></span>
                        <?php endif; ?>
                    </label>
                    <select class="<?php echo implode(' ', $form->getEmptyVrmReason()->getAttribute('class')); ?>" id="<?php echo $this->escapeHtml($form->getEmptyVrmReason()->getAttribute('id'))?>" name="<?php echo $this->escapeHtml($form->getEmptyVrmReason()->getName())?>">
                        <?php foreach ($form->getEmptyVrmReason()->getOptions()['value_options'] as $code => $option): ?>
                            <option <?php echo ($form->getEmptyVrmReason()->getValue() == $code ? 'selected="selected"' : "") ?> value="<?php echo $this->escapeHtml($code) ?>">
                                <?php echo $this->escapeHtml($option) ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="form-group form-group-related<?php if($form->getVin()->getMessages()): ?> has-error<?php endif; ?>">
                    <?php echo $this->formLabel($form->getVin()); ?>
                    <?php if($form->getVin()->getMessages()): ?>
                        <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getVin()->getMessages()); ?></span>
                    <?php endif; ?>
                    <?php echo $this->formElement($form->getVin()); ?>
                </div>
                <div class="panel-indent <?php if($form->getEmptyVinReason()->getMessages()): ?> has-error<?php endif; ?>">
                    <label for="<?php echo $form->getEmptyVinReason()->getName(); ?>">
                        <?php echo $form->getEmptyVinReason()->getLabel(); ?>
                        <?php if($form->getEmptyVinReason()->getMessages()): ?>
                            <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getEmptyVinReason()->getMessages()); ?></span>
                        <?php endif; ?>
                    </label>
                    <select class="<?php echo implode(' ', $form->getEmptyVinReason()->getAttribute('class')); ?>" id="<?php echo $this->escapeHtml($form->getEmptyVinReason()->getAttribute('id'))?>" name="<?php echo $this->escapeHtml($form->getEmptyVinReason()->getName())?>">
                        <?php foreach ($form->getEmptyVinReason()->getOptions()['value_options'] as $code => $option): ?>
                            <option <?php echo ($form->getEmptyVinReason()->getValue() == $code ? 'selected="selected"' : "") ?> value="<?php echo $this->escapeHtml($code) ?>">
                                <?php echo $this->escapeHtml($option) ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="form-group form-group-related <?php if($form->getMake()->getMessages()): ?> has-error<?php endif; ?>">
                    <label for="<?php echo $form->getMake()->getName(); ?>">
                        <?php echo $form->getMake()->getLabel(); ?>
                        <?php if($form->getMake()->getMessages()): ?>
                            <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getMake()->getMessages()); ?></span>
                        <?php endif; ?>
                    </label>
                    <select class="form-control" data-target-value="OTHER" data-target="tgt-other-make-v" id="make" name="<?php echo $this->escapeHtml($form->getMake()->getName())?>" aria-controls="tgt-other-make-v" aria-expanded="false">
                        <?php foreach ($form->getMake()->getOptions()['value_options'] as $code => $option): ?>
                            <option <?php echo ($form->getMake()->getValue() == $code ? 'selected="selected"' : "") ?> value="<?php echo $this->escapeHtml($code) ?>">
                                <?php echo $this->escapeHtml($option) ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div id="tgt-other-make-v" class="panel-indent <?php if($form->getMakeOther()->getMessages()): ?> has-error<?php endif; ?> toggle-content" aria-hidden="true">
                    <label for="other-make-v">
                        <?php echo $form->getMakeOther()->getLabel() ?>
                        <?php if($form->getMakeOther()->getMessages()): ?>
                            <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getMakeOther()->getMessages()); ?></span>
                        <?php endif; ?>
                    </label>
                    <?php echo $this->formElement($form->getMakeOther()); ?>
                </div>
            </div>
            <div class="form-group <?php if($form->getDateOfFirstUse()->getMessages()): ?> has-error<?php endif; ?>">
                <fieldset>
                    <?php echo $this->formLabel($form->getDateOfFirstUse()); ?>
                    <p class="help-block"><?php echo $form->getDateOfFirstUse()->getOption('hint'); ?></p>
                    <?php if($form->getDateOfFirstUse()->getMessages()): ?>
                        <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getDateOfFirstUse()->getMessages()); ?></span>
                    <?php endif; ?>
                    <div class="date-group">
                        <div class="form-group form-group-day">
                            <label for="day">Day</label>
                            <?php echo $this->formText($form->getDateOfFirstUse()->getDayElement()->setAttributes(['class' => 'form-control', 'id' => 'day'])); ?>
                        </div>
                        <div class="form-group form-group-month">
                            <label for="month">Month</label>
                            <?php echo $this->formText($form->getDateOfFirstUse()->getMonthElement()->setAttributes(['class' => 'form-control', 'id' => 'month'])); ?>
                        </div>
                        <div class="form-group form-group-year">
                            <label for="year">Year</label>
                            <?php echo $this->formText($form->getDateOfFirstUse()->getYearElement()->setAttributes(['class' => 'form-control', 'id' => 'year'])); ?>
                        </div>
                    </div>
                </fieldset>
            </div>

            <div class="form-group<?php if($form->getTransmissionType()->getMessages()): ?> has-error<?php endif; ?>">
                <legend class="form-label">
                    <?php echo $form->getTransmissionType()->getLabel(); ?>
                </legend>
                <?php if($form->getTransmissionType()->getMessages()): ?>
                    <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getTransmissionType()->getMessages()); ?></span>
                <?php endif; ?>
                <?php echo $this->formElement($form->getTransmissionType()); ?>
            </div>
        </fieldset>
        <nav class="module-content-navigation">
            <?php echo $this->formElement($this->form->get('submit')); ?>
            <ul class="content-navigation_secondary">
                <li>
                    <a id="cancel-link" href="<?php echo $this->url('vehicle-step', ['action' => 'cancel']) ?> ">Cancel and return to find a vehicle</a>
                </li>
            </ul>
        </nav>
        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>

<script>
    DVSA.selectToggle.init();
</script>
