<?php
use DvsaCommon\Utility\ArrayUtils;
?>

<?php /** @var $form \DvsaMotTest\NewVehicle\Form\CreateVehicleStepTwoForm */ ?>

<?php $this->headScript()->appendFile('/js/dvsa.js?v2.10.0'); ?>

<div class="row">
    <div class="col-lg-12">
        <div class="progress-tracker">
            <ul class="list-unstyled">
                <li class="done"><i class="fa fa-arrow-circle-right"></i>Vehicle identification</li>
                <li class="active"><i class="fa fa-arrow-circle-right"></i>Vehicle specification</li>
                <li><i class="fa fa-arrow-circle-right"></i>Summary</li>
            </ul>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h1>Create a new vehicle record</h1>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">

        <?php
        $form = $this->form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <?php if($this->form->getMessages()): ?>
            <div class="validation-summary" id="validation-summary-id">
                <h2>There was a problem with the information you entered:</h2>
                <ol>
                    <?php foreach($this->form->getMessages() as $field => $fieldMessages): ?>
                        <?php foreach($fieldMessages as $field => $message):
                            $fieldName = strtoupper($field) == $field ? $field : $this->camelCaseToReadable($field); ?>
                            <li><?php echo $this->escapeHtml($fieldName); ?> - <?php echo $this->escapeHtml(end($message)); ?></li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        <?php endif; ?>

        <fieldset>
            <legend><?php echo $form->get('vehicleForm')->getOption('legend'); ?></legend>
            <?php echo $this->csrfToken() ?>
            <div class="form-group">
                <div class="form-group form-group-related <?php if($form->getModel()->getMessages()): ?> has-error<?php endif; ?>">
                    <label for="model">
                        Model
                        <?php if($form->getModel()->getMessages()): ?>
                            <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getModel()->getMessages()); ?></span>
                        <?php endif; ?>
                    </label>
                    <select class="form-control" data-target-value="OTHER" data-target="tgt-other-model-v" id="model" name="<?php echo $this->escapeHtml($form->getModel()->getName())?>" aria-controls="tgt-other-model-v" aria-expanded="false">
                        <?php foreach ($form->getModel()->getOptions()['value_options'] as $code => $option): ?>
                            <option <?php echo ($form->getModel()->getValue() == $code ? 'selected="selected"' : "") ?> value="<?php echo $this->escapeHtml($code) ?>">
                                <?php echo $this->escapeHtml($option) ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div id="tgt-other-model-v" class="panel-indent <?php if($form->getModelOther()->getMessages()): ?>has-error<?php endif; ?> toggle-content" aria-hidden="true">
                    <label for="other-model-v">
                        <?php echo $form->getModelOther()->getLabel(); ?>
                        <?php if($form->getModelOther()->getMessages()): ?>
                            <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getModelOther()->getMessages()); ?></span>
                        <?php endif; ?>
                    </label>
                    <?php echo $this->formElement($form->getModelOther()); ?>
                </div>
            </div>

            <div class="form-group<?php if($form->getVehicleClass()->getMessages()): ?> has-error<?php endif; ?>">
                <?php echo $this->formLabel($form->getVehicleClass()); ?>
                <?php if($form->getVehicleClass()->getMessages()): ?>
                    <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getVehicleClass()->getMessages()); ?></span>
                <?php endif; ?>
                <?php echo $this->formElement($form->getVehicleClass()); ?>
            </div>

            <div class="form-group">
                <div class="form-group form-group-related<?php if($form->getFuelType()->getMessages()): ?> has-error<?php endif; ?>">
                    <?php echo $this->formLabel($form->getFuelType()); ?>
                    <?php if($form->getFuelType()->getMessages()): ?>
                        <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getFuelType()->getMessages()); ?></span>
                    <?php endif; ?>
                    <select class="form-control" data-target-value="<?php echo $ccRequiredFuelType ?>" data-target="tgt-div-cylinder-capacity" id=<?php echo $form->getFuelType()->getAttribute('id')?> name="<?php echo $this->escapeHtml($form->getFuelType()->getName())?>" aria-controls="tgt-other-model-v" aria-expanded="false">
                        <?php foreach ($form->getFuelType()->getOptions()['value_options'] as $code => $option): ?>
                            <option <?php echo ($form->getFuelType()->getValue() == $code ? 'selected="selected"' : "") ?> value="<?php echo $this->escapeHtml($code) ?>">
                                <?php echo $this->escapeHtml($option) ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div id="tgt-div-cylinder-capacity" class="panel-indent <?php if($form->getCylinderCapacity()->getMessages()): ?>has-error<?php endif; ?> toggle-content" aria-hidden="true">
                    <label for="other-model-v">
                        <?php echo $this->formLabel($form->getCylinderCapacity()); ?>
                    </label>
                    <?php if($form->getCylinderCapacity()->getMessages()): ?>
                        <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getCylinderCapacity()->getMessages()); ?></span>
                    <?php endif; ?>
                    <?php if($form->getCylinderCapacity()->getOption('hint')): ?>
                        <p class="help-block"><?php echo $form->getCylinderCapacity()->getOption('hint'); ?></p>
                    <?php endif; ?>
                    <?php echo $this->formElement($form->getCylinderCapacity()); ?>
                </div>
            </div>

            <div class="form-group<?php if($form->getColour()->getMessages()): ?> has-error<?php endif; ?>">
                <?php echo $this->formLabel($form->getColour()); ?>
                <?php if($form->getColour()->getMessages()): ?>
                    <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getColour()->getMessages()); ?></span>
                <?php endif; ?>
                <?php echo $this->formElement($form->getColour()); ?>
            </div>
            <div class="form-group<?php if($form->getSecondaryColour()->getMessages()): ?> has-error<?php endif; ?>">
                <?php echo $this->formLabel($form->getSecondaryColour()); ?>
                <?php if($form->getSecondaryColour()->getMessages()): ?>
                    <span class="validation-message"><?php echo ArrayUtils::lastOrNull($form->getSecondaryColour()->getMessages()); ?></span>
                <?php endif; ?>
                <?php echo $this->formElement($form->getSecondaryColour()); ?>
            </div>
        </fieldset>

        <nav class="module-content-navigation">
            <?php echo $this->formElement($this->form->get('submit')); ?>
            <ul class="content-navigation_secondary">
                <li>
                    <?php echo $this->formElement($this->form->get('back')); ?>
                </li>
            </ul>
        </nav>

        <?php
        echo $this->form()->closeTag();
        ?>

    </div>
</div>

<script>
    DVSA.selectToggle.init();
</script>
