<h1>New vehicle record created</h1>

<p>
    New vehicle details have been saved.  You may now proceed to starting a

    <?php if ($this->isContingency): ?>
    <a href="<?php echo $this->basePath('/vehicle-search?contingency=1'); ?>" target="_self">Contingency Test</a>.
    <?php else: ?>
    <a href="<?php echo $this->basePath('/vehicle-search'); ?>" target="_self">MOT Test</a>.
    <?php endif; ?>
</p>