<?php

namespace DvsaCommon\Constants;

/**
 * Class with names of role
 */
class Role
{
    const ASSESSMENT = 'ASSESSMENT';
    const ASSESSMENT_LINE_MANAGER = 'ASSESSMENT-LINE-MANAGER';
    const AUTHORISED_EXAMINER = 'AUTHORISED-EXAMINER';
    const CRON = 'CRON';
    const CUSTOMER_SERVICE_CENTRE_OPERATIVE = 'CUSTOMER-SERVICE-CENTRE-OPERATIVE';
    const CUSTOMER_SERVICE_MANAGER = 'CUSTOMER-SERVICE-MANAGER';
    const DEMOTEST = 'DEMOTEST';
    const DVLA_MANAGER = 'DVLA-MANAGER';
    const DVLA_OPERATIVE = 'DVLA-OPERATIVE';
    const DVSA_AREA_OFFICE_1 = 'DVSA-AREA-OFFICE-1';
    const DVSA_AREA_OFFICE_2 = 'DVSA-AREA-OFFICE-2';
    const DVSA_SCHEME_MANAGEMENT = 'DVSA-SCHEME-MANAGEMENT';
    const DVSA_SCHEME_USER = 'DVSA-SCHEME-USER';
    const GUEST = 'GUEST';
    const SLOT_PURCHASER = 'SLOT-PURCHASER';
    const TESTER_ACTIVE = 'TESTER-ACTIVE';
    const TESTER_APPLICANT_DEMO_TEST_REQUIRED = 'TESTER-APPLICANT-DEMO-TEST-REQUIRED';
    const TESTER_APPLICANT_INITIAL_TRAINING_REQUIRED = 'TESTER-APPLICANT-INITIAL-TRAINING-REQUIRED';
    const TESTER_APPLICANT_INITIAL_TRAINING_FAILED = 'TESTER-APPLICANT-INITIAL-TRAINING-FAILED';
    const TESTER_INACTIVE = 'TESTER-INACTIVE';
    const USER = 'USER';
    const VEHICLE_EXAMINER = 'VEHICLE-EXAMINER';
    const FINANCE = 'FINANCE';
    const GVTS_TESTER = 'GVTS-TESTER';
    const CENTRAL_ADMIN_TEAM = 'CENTRAL-ADMIN-TEAM';
}
