<?php

$title = 'Test item selector';
$this->headTitle($title);
/** @var \Dvsa\Mot\ApiClient\Resource\Item\MotTest $motTestDetails */
$motTestNumber = $motTestDetails->getMotTestNumber();

$latestRfrs = $motTestDetails->getReasonsForRejection();
?>

<?php echo $this->partial(
    'motHeaderDetails',
    [
        'motTestDetails'    => $motTestDetails,
        'motTestNumber'     => $motTestNumber,
        'isMotContingency'     => $this->isMotContingency,
    ]
); ?>
<?php echo $this->partial('rfrResultsSummary', ['reasonsForRejection' => $latestRfrs, 'motTestNumber' => $motTestNumber]); ?>
<?php
/** @var \DvsaCommon\Dto\VehicleClassification\VehicleClassDto $vehicleClass */
$vehicleClass = $motTestDetails->getVehicleClass();
echo $this->partial('testItemSelectorSearch', ['motTestNumber' => $motTestNumber, 'searchString' => null, 'vehicleClass' => $vehicleClass->getCode()]); ?>
<?php echo $this->partial('rfrBreadcrumb', ['breadcrumbItemSelectors' => $breadcrumbItemSelectors, 'motTestNumber' => $motTestNumber]); ?>
<?php echo $this->partial('errorMessages', ['getFromFlash' => true]); ?>
<?php echo $this->partial('infoMessages', ['getFromFlash' => true]); ?>

<?php echo $this->partial('rfrList',
    [
        'motTestNumber' => $motTestNumber,
        'reasonsForRejection' => $reasonsForRejection,
        'vehicleClassCode' => $motTestDetails->getVehicleClass()->getCode()
    ]
); ?>

<div class="row">
    <div class="col-lg-12 btn-bar">
        <a href="<?php echo $this->url('mot-test', ['motTestNumber' => $motTestNumber]); ?>" class="btn btn-primary" id="reason-for-rejection-done">Done</a>
    </div>
</div>