<?php

$title = 'Test item selector';
$this->headTitle($title);

/** @var \Dvsa\Mot\ApiClient\Resource\Item\MotTest $motTestDetails */
$motTestNumber = $motTestDetails->getMotTestNumber();
$reasonsForRejection = $motTestDetails->getReasonsForRejection();

?>

<?php echo $this->partial(
    'motHeaderDetails',
    [
        'motTestDetails' => $motTestDetails,
        'motTestNumber' => $motTestNumber,
        'isMotContingency' => $this->isMotContingency,
    ]
); ?>

<?php echo $this->partial('rfrResultsSummary', ['reasonsForRejection' => $reasonsForRejection, 'motTestNumber' => $motTestNumber]); ?>

<?php
/** @var \DvsaCommon\Dto\VehicleClassification\VehicleClassDto $vehicleClass */
$vehicleClass = $motTestDetails->getVehicleClass();
echo $this->partial('testItemSelectorSearch', ['motTestNumber' => $motTestNumber, 'searchString' => null, 'vehicleClass' => $vehicleClass->getCode()]); ?>
<?php echo $this->partial('errorMessages', ['getFromFlash' => true]); ?>
<?php echo $this->partial('infoMessages', ['getFromFlash' => true]); ?>
<?php echo $this->partial('rfrBreadcrumb', ['breadcrumbItemSelectors' => $breadcrumbItemSelectors, 'motTestNumber' => $motTestNumber]); ?>

<section class="failure-group">
    <h2 class="visually-hidden">Reason for Rejection categories</h2>
    <?php foreach (array_chunk($testItemSelectors, 3, true) as $row):?>
        <div class="row">
            <?php foreach ($row as $element):?>
                <div class="col-xs-4">
                    <a href="<?php echo $this->url('mot-test/test-item-selector', ['tis-id' => $element['id'], 'motTestNumber' => $motTestNumber]); ?>"><?php echo $this->escapeHtml($element['name']); ?></a>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
</section>

<div class="row">
    <div class="col-xs-8">
        <div class="media">
            <div class="info-notice">
                <p>
                    All defects should be associated with an RFR item or a non-component advisory.
                    If you can't find a match, you can add a defect as a
                    <a data-toggle="modal" href="#rfr-dialog-0" id="manual-advisory"> manual advisory.</a>
                </p>
            </div>
        </div>
    </div>
</div>
<hr class="hr-thin">
<div class="row">
      <div class="col-lg-12">
        <a href="<?php echo $this->url('mot-test', ['motTestNumber' => $motTestNumber]); ?>"
        class="btn btn-primary" id="mot-header-details-rfr-done">Done</a>
    </div>
</div>
<?php
    echo $this->partial('rfrLocationModal', [
        'escRfrId' => 0,
        'motTestNumber' => $motTestNumber,
        'title' => 'Manual Advisory',
        'rfrType' => 'ADVISORY',
    ]);
?>