<?php
$this->headScript()->appendFile('/assets/javascripts/authentication.js');
?>
<div id="signIn" class="grid-row">
    <div class="column-two-thirds">
        <form id="Login" name="Login" action="<?php echo $this->url($this->loginCheckRoute); ?>" method="post">
            <div class="sign-in">
                <fieldset>
                    <legend class="form-title heading-large">Sign in</legend>
                    <div class="form-group">
                        <label  class="form-label" for="IDToken1">
                            User ID
                        </label>
                        <input class="form-control" type="text" name="IDToken1" id="IDToken1" value="" maxlength="50" tabindex="1" />
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="IDToken2">
                            Password
                        </label>
                        <input type="hidden" id="goto" name="goto" value="<?php echo $this->escapeHtmlAttr($this->gotoUrl) ?>"/>
                        <input class="form-control" type="password" name="IDToken2" id="IDToken2" value="" maxlength="100" autocomplete="off" tabindex="2" />
                        <?php echo $this->csrfToken(); ?>
                    </div>
                </fieldset>
                <nav class="module-content-navigation">
                    <input name="Login.Submit" type="submit" class="button" value="Sign in" tabindex="3" />
                    <ul class="content-navigation__secondary">
                        <li>
                            <a href="<?php echo $this->url($this->forgottenPasswordRoute); ?>" tabindex="4">Forgotten/Change password</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <input name="IDButton" type="hidden" style="display: none;">
        </form>
        <div class="message">
            <p>If you <strong>don't have</strong> an MOT testing service account you can <a href="<?php echo $this->url('account-register'); ?>">create an account</a> to register as a new user.</p>
        </div>
    </div>
    <div class="column-third">
        <img src="<?php echo $this->basePath('assets/images/icons/dvsa-org-logo2x.png'); ?>" alt="Driver and Vehicle Standards Agency" width="154">
    </div>
</div>
