<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'EquipmentApi\Controller\EquipmentModelController'          => __DIR__ . '/src/EquipmentApi/Controller/EquipmentModelController.php',
  'EquipmentApi\Factory\Service\EquipmentModelServiceFactory' => __DIR__ . '/src/EquipmentApi/Factory/Service/EquipmentModelServiceFactory.php',
  // REMOVED INVALID MAP: 'getRepository'                                             => __DIR__ . '/src/EquipmentApi/Factory/Service/EquipmentModelServiceFactory.php',
  // REMOVED INVALID MAP: 'get'                                                       => __DIR__ . '/src/EquipmentApi/Factory/Service/EquipmentModelServiceFactory.php',
  'EquipmentApi\Service\EquipmentModelService'                => __DIR__ . '/src/EquipmentApi/Service/EquipmentModelService.php',
  'EquipmentApi\Service\Mapper\EquipmentModelMapper'          => __DIR__ . '/src/EquipmentApi/Service/Mapper/EquipmentModelMapper.php',
);
