<?php

use Organisation\Form\AeCreateForm;

// Sensible defaults for the Area Office selection drop-down menu
$labelText = isset($this->label)     ? $this->label     : 'Area Office';
$labelMenu = isset($this->labelMenu) ? $this->labelMenu : 'DVSA Area Office';
$labelId   = isset($this->labelId)   ? $this->labelId   : 'legendAreaOfficeReference';
$selectId  = isset($this->id)        ? $this->id        : AeCreateForm::FIELD_AO_NR;
$showTitle = isset($this->showTitle) ? $this->showTitle : true;
?>
<fieldset>
    <?php

    if (true === $showTitle) {
        echo $this->partial(
            'partial/gds/form/control-legend',
            [
                'id' => $labelId,
                'text' => $labelText
            ]
        );
    }

    echo $this->partial(
        'partial/gds/form/control-select-group',
        [
            'id' => $selectId,
            'label' => $labelMenu,
            'errorMessage' => $this->errorMessage,
            'value' => (string)$this->value,
            'options' => $this->options,
            'inputModifier'=> '1-4',
        ]
    );
    ?>
</fieldset>
