<?php
use Core\Formatting\AddressFormatter;
/**
 * @var string $title
 * @var int[] $ids
*/
?>
<table class="table-summary">
    <thead>
    <tr>
        <th class="table-summary__heading" colspan="2">
            <?php echo $this->escapeHtml($title) ?>
        </th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th class="table-summary__key">
            Address
        </th>

        <td id="<?php echo array_key_exists("address", $ids) ? $ids["address"] : null ?>" class="table-summary__value">
            <?php
            echo !empty($contactDetail->getAddress()) ? AddressFormatter::escapedDtoToMultiLine($contactDetail->getAddress()) : 'N/A' ?>
        </td>
    </tr>
    <tr>
        <th class="table-summary__key">
            Email
        </th>

        <td id="<?php echo array_key_exists("email", $ids) ? $ids["email"] : null ?>"
            class="table-summary__value" >
            <?php $email = $contactDetail->getPrimaryEmailAddress(); ?>
            <?php if ($email): ?>
                <a href="mailto:<?php echo $this->escapeHtmlAttr($email) ?>"
                    ><?php echo $this->escapeHtml($email); ?></a>
            <?php else: ?>
                N/A
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <th class="table-summary__key">
            Telephone
        </th>

        <td id="<?php echo array_key_exists("phone", $ids) ? $ids["phone"] : null ?>"
            class="table-summary__value--tabular">
            <?php echo $this->escapeHtml(($contactDetail->getPrimaryPhoneNumber()) ?: 'N/A'); ?>
        </td>
    </tr>
    </tbody>
</table>