<?php
$urlBack = $this->urlBack;

if (empty($urlBack)) {
    return;
}

$escUrl = $urlBack['uri'];

if ($urlBack['type'] === 'home') {
    $escLabel = 'Return home';
    $escId = 'return-home';
} else {
    $escLabel = 'Search again';
    $escId = 'search-again';
}
?>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a id="<?php echo $escId ?>" href="<?php echo $escUrl; ?>"><?php echo $escLabel ?></a>
        </li>
    </ul>
</nav>