
<?php

/** @var \UserAdmin\Presenter\UserProfilePresenter $presenter */
/** @var string $userProfileUrl */
/** @var string $claimAccountUrl */
/** @var \Application\Helper\PrgHelper $prgHelper */
/** @var string $reclaimSystemMessage */

?>

<div id="reclaim-account-notification" class="text">
    <p class="lede">
        You are about to reset the security for <strong><?php echo $this->escapeHtml($presenter->displayFullName()) ?></strong>.
    </p>
    <p>
        They will be emailed at <strong><?php echo $this->escapeHtml($presenter->displayEmail()); ?></strong> with a temporary password to sign in to their account.
    </p>
    <p>
        They will then be prompted to choose a new password and security questions.
    </p>

    <?php echo $this->partial('partial/gds/general/system-message',
        [
            'messages' => [$reclaimSystemMessage],
            'type' => 'important'
        ]
    ); ?>

</div>

<form id="resetClaimAccountForm" method="POST" role="form" novalidate>
    <?php echo $this->csrfToken() ?>
    <?php echo $prgHelper->getHtml(); ?>
    <nav class="content-navigation">
        <?php echo $this->partial(
            'partial/gds/form/control-navigation',
            [
                'id'            => 'reclaim-account-submit',
                'class'         => 'button-warning',
                'value'         => 'Reset account security',
                'navigation'    => [
                    'Cancel and return to user profile' => $userProfileUrl,
                ]
            ]
        ); ?>
    </nav>
</form>

<script>
    document.onreadystatechange = function () {
        $('#resetClaimAccountForm').submit(function() {
            $('#reclaim-account-submit').attr('disabled','disabled');
        });
    };
</script>
