<?php
use Dashboard\Controller\UserHomeController;
/** @var string $userProfileUrl */
?>
<nav class="module-content-navigation">
    <ul class="content-navigation_secondary">
        <li>
            <a href="<?php echo $userProfileUrl; //VM-8519 escaped in the controller ?>" id="back_to_user_profile">Back to user profile</a>
        </li>
        <li>
            <a href="<?php echo $this->url(UserHomeController::ROUTE); ?>" id="return_to_home">Return to home</a>
        </li>
    </ul>
</nav>
