<?php
/** @var \UserAdmin\Presenter\UserProfilePresenter $presenter */
/** @var string $escUserProfileUrl */
?>
<div class="row">
    <div class="col-sm-8" id="second-time-reset-password-confirmation">
        A password reset letter has already been requested for <strong><?php echo $this->escapeHtml($presenter->displayFullName()); ?></strong> today.
    </div>
</div>
<?php echo $this->partial('user-admin/user-profile/password-reset-navigate-partial.phtml', ['userProfileUrl' => $userProfileUrl]); ?>
