<?php
/** @var \UserAdmin\Presenter\UserProfilePresenter $presenter */
/** @var string $userProfileUrl */
?>
<div class="row">
    <?php if ($this->isFailure === true): ?>
        <div class="col-sm-8" id="second-time-reset-password-confirmation">
            A password reset letter has already been requested for <strong><?php echo $this->escapeHtml($presenter->displayFullName()); ?></strong> today.
        </div>
    <?php else: ?>
        <div class="col-sm-8" id="first-time-reset-password-confirmation">
            A letter will be sent to <strong><?php echo $this->escapeHtml($presenter->displayFullName()); ?></strong> giving instructions on how to reset the password for their account.
        </div>
    <?php endif; ?>
</div>

<?php echo $this->partial(
    'partial/gds/form/control-navigation-secondary',
    [
        'navigation'    => [
            'Back to user profile' => $userProfileUrl,
            'Return to home' => '/'
        ]
    ]
); ?>
