<?php
/** @var \UserAdmin\Presenter\UserProfilePresenter $presenter */
/** @var string $userProfileUrl */
?>
<div class="row">
    <div class="col-sm-8" id="first-time-reset-password-confirmation">
        A letter will be sent to <strong><?php echo $this->escapeHtml($presenter->displayFullName()); ?></strong> giving instructions on how to reset the password for their account.
    </div>
</div>
<?php echo $this->partial('user-admin/user-profile/password-reset-navigate-partial.phtml', ['userProfileUrl' => $userProfileUrl]); ?>
