<?php
use Dashboard\Controller\UserHomeController;
use DvsaCommon\UrlBuilder\UserAdminUrlBuilderWeb;

/** @var \UserAdmin\Presenter\UserProfilePresenter $presenter */
/** @var string $searchResultsUrl */
/** @var string $passwordResetUrl */
/** @var string $usernameRecoverUrl */

$elementsSecondColumn = [
    ['id' => 'person-name', 'label' => 'Name', 'value' => $presenter->displayFullName()],
    ['id' => 'person-username', 'label' => 'Username', 'value' => $presenter->displayUserName()],
    ['id' => 'person-dob', 'label' => 'Date of birth', 'value' => $presenter->displayDateOfBirth()],
];
$elementsThirdColumn = [
    ['id' => 'person-address', 'label' => 'Address', 'value' => $presenter->displayFullAddress()],
    ['id' => 'person-email', 'label' => 'Email', 'value' => $presenter->displayEmail()],
    ['id' => 'person-telephone', 'label' => 'Telephone', 'value' => $presenter->displayTelephone()],
];

echo $this->partial(
    'partial/gds/general/system-message',
    [
        'messages' =>
            [
                [
                    'Password reset and username recovery are ',
                    'only available by post.'
                ],
            ],
        'heading'  => 'Authentication failed', 'type' => 'failure'
    ]
);
?>

<div class="grid-row">
    <div class="column-half">
        <h2 class="heading-large">Password <span class="font-large">reset</span></h2>
        <p>Send password reset instructions by:</p>
        <form action="<?php echo $this->escapeHtmlAttr($passwordResetUrl); ?>" method="POST" novalidate>
            <div class="form-group">
                <?php
                echo $this->csrfToken();
                echo $this->partial(
                    'partial/gds/form/control-submit.phtml',
                    [
                        'id'    => 'reset-password',
                        'label' => 'Reset Password',
                        'name'  => 'action',
                        'value' => 'Post',
                    ]
                );
                ?>
            </div>
        </form>
    </div>
    <div class="column-half">
        <h2 class="heading-large">Username <span class="font-large">recovery</span></h2>
        <p>Send the username by:</p>
        <form action="<?php echo $this->escapeHtmlAttr($usernameRecoverUrl); ?>" method="POST" novalidate>
            <div class="form-group">
                <?php echo $this->csrfToken() ?>
                <?php echo $this->partial(
                    'partial/gds/form/control-submit.phtml',
                    [
                        'id'    => 'recover-username',
                        'label' => 'Recover username',
                        'name'  => 'action',
                        'value' => 'Post',
                    ]
                );
                ?>
            </div>
        </form>
    </div>
</div>
<hr class="hr-thin">
<div class="present-data">
    <div class="present-data__title-container">
        <h3 class="present-data__title">Personal details</h3>
    </div>
    <?php
    echo $this->partial(
        'partial/gds/general/information-in-column',
        [
            'nbCol'     => 'third',
            'elements'  => $elementsSecondColumn,
        ]
    );

    echo $this->partial(
        'partial/gds/general/information-in-column',
        [
            'nbCol'     => 'third',
            'elements'  => $elementsThirdColumn,
        ]
    );
    ?>
</div>
<hr class="hr-thin">
<nav class="content-navigation">
    <?php echo $this->partial(
        'partial/gds/form/control-navigation-secondary',
        [
            'navigation'    => [
                'Cancel and return to search results'   => $searchResultsUrl,
                'Return to home'                        => $this->url(UserHomeController::ROUTE),
            ]
        ]
    ); ?>
</nav>

