<?php

use Dashboard\Controller\UserHomeController;
use DvsaCommon\Auth\PermissionInSystem;

/** @var \UserAdmin\Presenter\UserProfilePresenter $presenter */
/** @var string $searchResultsUrl */
/** @var string $passwordResetUrl */
/** @var string $usernameRecoverUrl */
/** @var string $resetClaimAccountUrl */
/** @var string $resetClaimAccountUrlPost */

$errorMessages      = $this->layout()->flashMessenger->getErrorMessages();
$successMessages    = $this->layout()->flashMessenger->getSuccessMessages();

echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);

$isEmail = empty(trim($presenter->displayEmail())) ? false : true;

?>

<h3 class="heading-medium">Personal details</h3>
<table class="key-value-list">
    <tbody>
    <tr>
        <th class="key-value-list__key">
            Name
        </th>
        <td id="person-name" class="key-value-list__value">
            <?php echo $this->escapeHtml($presenter->displayTitleAndFullName()); ?>
        </td>
    </tr>
    <tr>
        <th class="key-value-list__key">
            Username
        </th>
        <td id="person-username" class="key-value-list__value--numeric">
            <?php echo $this->escapeHtml($presenter->displayUsername()); ?>
        </td>
    </tr>
    <tr>
        <th class="key-value-list__key">
            Date of birth
        </th>
        <td id="person-dob" class="key-value-list__value">
            <?php echo $this->escapeHtml($presenter->displayDateOfBirth()); ?>
        </td>
    </tr>
    <?php if ($presenter->canDisplayDrivingLicence()): ?>
    <tr>
        <th class="key-value-list__key">
            Driving licence number
        </th>
        <td id="person-driving-licence" class="key-value-list__value--numeric">
            <span id="person-driving-licence-number">
                <?php if ($presenter->hasDrivingLicenceNumber()): ?>
                    <?php echo $this->escapeHtml($presenter->displayDrivingLicenceNumber()); ?>
                <?php else: ?>
                    None recorded
                <?php endif; ?>
            </span>
            <?php if ($presenter->hasDrivingLicenceNumber()): ?>
                <span id="person-driving-licence-region" class="key-value-list__meta">
                    <?php echo $this->escapeHtml($presenter->displayDrivingLicenceRegion()); ?>
                </span>
            <?php endif; ?>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($display2FAMethod): ?>
    <tr>
        <th class="key-value-list__key">
            Two-factor authentication method
        </th>
        <td id="person-2fa-method" class="key-value-list__value">
            <?php echo $this->escapeHtml($presenter->displayAuthenticationMethod()); ?>
        </td>
    </tr>
    <?php endif; ?>
    </tbody>
</table>

<h3 class="heading-medium">Contact details</h3>
<table class="key-value-list">
    <tbody>
    <tr>
        <th class="key-value-list__key">
            Address
        </th>
        <td id="person-address" class="key-value-list__value">
            <?php echo $this->escapeHtml($presenter->displayFullAddress()); ?>
        </td>
    </tr>
    <tr>
        <th class="key-value-list__key">
            Email
        </th>
        <td id="person-email" class="key-value-list__value">
            <?php echo $this->escapeHtml($presenter->displayEmail()); ?>
            <?php if ($this->authorisationHelper()->isGranted(PermissionInSystem::PROFILE_EDIT_OTHERS_EMAIL_ADDRESS)): ?>
            <a class="key-value-list__action"
               id="email-address-change"
               href="<?php echo $this->url(
                   'user_admin/user-profile/email-change', ['personId' => $presenter->getPersonId()]
               ); ?>"
               title="Amend user email">
                Change this
            </a>
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <th class="key-value-list__key">
            Telephone
        </th>
        <td id="person-telephone" class="key-value-list__value--numeric">
            <?php echo $this->escapeHtml($presenter->displayTelephone()); ?>
        </td>
    </tr>
    </tbody>
</table>

<?php echo $this->partial('user-admin/partials/roles.phtml', ['presenter' => $presenter]) ?>
<?php if ($presenter->getTesterAuthorisation()->shouldBeDisplayed()): ?>
    <?php echo $this->partial(
            'user-admin/partials/tester-qualification-status.phtml',
            [
                'viewModel' => $presenter->getTesterAuthorisation(),
                'searchQueryParams' => $searchQueryParams,
            ]
        );
    ?>
<?php endif ?>

<?php if ($presenter->canDisplayResetSection()): ?>
    <div class="grid-row">
        <div class="column-third">
            <h2 class="heading-large">Password<br /><span class="font-large">reset</span></h2>
            <p style="height: 50px">Send password reset by:</p>
            <a id="reset-password-by-post"
               class="button"
               href="<?php echo $this->escapeHtmlAttr($passwordResetUrl); ?>">
                Reset password via<br/><strong>Post</strong>
            </a>
        </div>

        <div class="column-third">
            <h2 class="heading-large">Username<br /><span class="font-large">recovery</span></h2>
            <p style="height: 50px">Send the username by:</p>
            <a id="reset-username-by-post"
               class="button"
               href="<?php echo $this->escapeHtmlAttr($usernameRecoverUrl); ?>">
                Recover username via<br/><strong>Post</strong>
            </a>
        </div>

        <div class="column-third">
            <h2 class="heading-large">Account<br /><span class="font-large">reclaim</span></h2>
            <p style="height: 50px">Send reclaim account:</p>
            <?php if ($isEmail): ?>
                <a id="reset-to-unclaim-account-by-email"
                   class="button button-warning"
                   href="<?php echo $this->escapeHtmlAttr($resetClaimAccountUrl); ?>">
                    Reclaim account via<br/><strong>Email</strong>
                </a>
                <p>
                    or
                    <a id="reset-to-unclaim-account-by-post"
                       class="button--link" href="<?php echo $this->escapeHtmlAttr($resetClaimAccountUrlPost); ?>">
                        post
                    </a>
                </p>
            <?php else: ?>
                <a id="reset-to-unclaim-account-by-email"
                   class="button button-warning"
                   href="<?php echo $this->escapeHtmlAttr($resetClaimAccountUrlPost); ?>">
                    Reclaim account via<br/><strong>Post</strong>
                </a>
            <?php endif; ?>
        </div>
    </div>
    <hr class="hr--thin">
<?php endif; ?>

<?php echo $this->partial('user-admin/partials/event-history.phtml', ['presenter' => $presenter]) ?>

<nav class="content-navigation">
    <?php echo $this->partial(
        'partial/gds/form/control-navigation-secondary',
        [
            'navigation'    => [
                'Cancel and return to search results'   => $searchResultsUrl,
                'Return to home'                        => $this->url(UserHomeController::ROUTE),
            ]
        ]
    ); ?>
</nav>
