<?php
// *** PLEASE ENSURE NO MORE THAN 72 CHARACTERS PER LINE
?>
Dear MOT Testing Service user

You recently contacted DVSA for details of your username for the MOT
Testing Service application.

Please copy and paste the link below into a web browser. You will need
to answer your security questions correctly before we can present your
recovered username.

<?php echo $this->reminderLink; ?>

If you did not request this reminder then please contact <?php echo $this->escapeHtml($this->contactLabel); ?>
 immediately on <?php echo $this->escapeHtml($this->contactNumber); ?> quoting your username.
