<?php
use Dashboard\Controller\NotificationController;
use DvsaCommon\Date\DateTimeDisplayFormat;

/** @var $notification \Dashboard\Model\Notification */

$backTo = $notification->getIsArchived()? NotificationController::BACK_TO_ARCHIVE_PARAM : null;
$notificationUrl = $this->url(NotificationController::ROUTE_NOTIFICATION, ['notificationId' => $notification->getId()], ["query" => ["backTo" => $backTo]]);
$date = DateTimeDisplayFormat::textDateShortGds($notification->getCreatedOn());
$unreadClass = $notification->getReadOn() ? '' : 'c-tab-list__row--unread';
?>

<li class="c-tab-list__row <?php echo $unreadClass; ?>">
    <div class="c-tab-list__item-left">
        <a href="<?php echo $notificationUrl; ?>"
           class="c-tab-list__item-link">
            <?php echo $this->escapeHtmlAttr($notification->getSubject()); ?>
        </a>
    </div>
    <div class="c-tab-list__item-right">
        <span class=""><?php echo $this->escapeHtml($date); ?></span>
    </div>
</li>