<?php
use DvsaCommon\Date\DateTimeDisplayFormat;
use Dashboard\Controller\UserHomeController;

/* SINGLE NOTIFICATION VIEW */

/** @var $notification \Dashboard\Model\Notification */

$fields = $notification->getFields();
$displayButton = isset($fields['buttonLink']) && isset($fields['buttonText']);

?>

<div class="text"></div>

<div class="text">
    <p class="lede" id="notification-content">
        <?php if ($notification->getTemplateId() === 24): ?>
            <?php echo $notification->getContent(); ?>
        <?php else: ?>
            <?php echo nl2br($this->escapeHtml($notification->getContent())); ?>
        <?php endif; ?>
    </p>

    <?php echo $this->notificationLink($notification); ?>
</div>
<div class="text">
    <p id="notification-sent">Notification sent <?php echo DateTimeDisplayFormat::textDateTime($notification->getCreatedOn()); ?></p>
</div>

<ul class="content-navigation__secondary">
    <li>
        <a href="<?php echo $this->url(UserHomeController::ROUTE) ?>" id="link-back-to-home">Return home</a>
    </li>
</ul>
