<?php
use DvsaCommon\Date\DateTimeDisplayFormat;
use Dashboard\Controller\NotificationController;

/* SINGLE NOTIFICATION VIEW */

/** @var $notification \Dashboard\Model\Notification */

$fields = $notification->getFields();
$backTo = ($backLinkUrl === NotificationController::ROUTE_USER_HOME)? NotificationController::BACK_TO_HOME_PARAM : null;

?>

<div class="text" xmlns="http://www.w3.org/1999/html"></div>

<?php if ($notification->isActionRequired()) : ?>
    <?php if ($notification->isDone()) : ?>
        <div class="text">
            <p class="lede" id="notification-decision">
                <?php if ($notification->isConfirmedAction()): ?>
                    You have accepted the role of <?php echo $this->escapeHtml($fields['positionName']); ?> at <?php echo $this->escapeHtml($notification->getName()); ?>.
                <?php else: ?>
                    You have rejected the role of <?php echo $this->escapeHtml($fields['positionName']); ?> at <?php echo $this->escapeHtml($notification->getName()); ?>.
                <?php endif; ?>
            </p>
            <p id="notification-decision-datetime">
                You <?php echo $this->escapeHtml($notification->getFriendlyAction()); ?> this role on  <?php echo DateTimeDisplayFormat::textDateTime($notification->getUpdatedOn()); ?>
            </p>
        </div>

        <div class="text">
            <p class="lede" id="notification-decision">
                <?php if ($notification->isConfirmedAction()): ?>
                    <p>You must sign out of your account and in again for the new role to be applied.</p>
                <?php endif; ?>
            </p>
        </div>
    <?php
        if(!$notification->getIsArchived()){
            echo $this->partial('dashboard/notification/archive-notification-button.phtml', [
                'notificationId' => $notification->getId(),
            ]);
        }
    ?>
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->url($backLinkUrl) ?>" id="link-back-to-home"><?php echo $backLinkLabel; ?></a>
            </li>
        </ul>
    <?php else: ?>
        <div class="message">
            <p id="notification-content">
                <?php echo $this->escapeHtml($notification->getContent()); ?>
            </p>
        </div>

        <form class="form-horizontal"
              action="<?php echo $this->url(NotificationController::ROUTE_NOTIFICATION_ACTION); ?>"
              method="POST">
            <nav class="content-navigation">
                <?php echo $this->csrfToken() ?>
                <?php $notificationId = intval($notification->getId()); ?>
                <?php echo $this->partial(
                    'hiddenElement',
                    [
                        'name'  => 'notificationId',
                        'value' => $notificationId
                    ]
                ); ?>
                <?php echo $this->partial(
                    'hiddenElement',
                    [
                        'name'  => 'url',
                        'value' => $this->url(
                                NotificationController::ROUTE_NOTIFICATION, ['notificationId' => $notificationId],
                                ["query" => ["backTo" => $backTo]]
                            )
                    ]
                ); ?>
                <?php foreach ($notification->getActions() as $action => $label) : ?>
                    <?php
                    $params = [
                        'value' => $action,
                        'label' => $label,
                        'name'  => 'action',
                        'id'    => 'action-' . strtolower($action)
                    ];
                    if (strrpos($action, 'REJECT') > 0) {
                        $params['cssClass'] = 'button-warning ';
                    } else {
                        $params['cssClass'] = 'button';
                    }
                    echo $this->partial('submitElement', $params); ?>
                <?php endforeach; ?>
            </nav>
        </form>
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->url($backLinkUrl) ?>" id="link-back-to-home"><?php echo $backLinkLabel; ?></a>
            </li>
        </ul>
    <?php endif; ?>
<?php endif; ?>
