<?php
use DvsaCommon\Enum\MotTestStatusName;
use DvsaCommon\Utility\ArrayUtils;

$title = 'Mot Test Search Results';

$this->headTitle($title);
$this->headScript()->appendFile('/js/dvsa-mot-enforcement/search/mot-test-search-by-vehicle.js');
$this->headLink()->appendStylesheet('/css/jquery.dataTables.css');

echo $this->partial('errorMessages', ['getFromFlash' => true]);
echo $this->partial('infoMessages', ['getFromFlash' => true]);

?>

<h1><?php echo $this->escapeHtml($this->pageTitle); ?></h1>
<hr class="hr-thick">

<div class="info-notice">
    <p>
        If these are <strong>not the right results</strong> you can
        <a href="<?php echo $this->escGoBackLink; ?>">go back</a>
    </p>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="table-responsive">
            <table class="table table-striped nowrap" id="listMOTs" style="width: 100%">
                <thead>
                <tr>
                    <th>Test date/time utc</th>
                    <th id="testDate">Test date/time</th>
                    <th id="result">Result</th>
                    <th id="summary">Summary</th>
                    <th id="test">Test</th>
                    <th id="vin">VIN/Chassis</th>
                    <th id="reg">Registration</th>
                    <th id="make">Make</th>
                    <th id="model">Model</th>
                    <th id="type">Type</th>
                    <th id="site">Site</th>
                    <th id="userId">User ID</th>
                </tr>
                </thead>
                <tbody>
                <?php
                $i = 0;
                $arrMotStatus = [
                    MotTestStatusName::FAILED,
                    MotTestStatusName::PASSED,
                    MotTestStatusName::ABORTED,
                ];
                foreach ($this->searchResults as $motTest):
                    $model = ArrayUtils::tryGet($motTest, 'model', '');
                    $testType = ArrayUtils::tryGet($motTest, 'testType', '');
                    $siteNr = ArrayUtils::tryGet($motTest, 'siteNumber');
                    $siteId = ArrayUtils::tryGet($motTest, 'siteId');

                    $canPrintTestDetails = in_array($motTest['status'], $arrMotStatus);

                    $testSummaryUrl = $motTest['link'];
                    $escClass = ($i++ % 2 == 0 ? 'even' : 'odd');
                    ?>
                    <tr class="<?php echo $escClass; ?>">
                        <td><?php echo $this->escapeHtml($motTest['test_date']); ?></td>
                        <td><?php echo $this->escapeHtml($motTest['display_date']); ?></td>

                        <td><?php echo $this->escapeHtml($motTest['display_status']); ?></td>

                        <td>
                            <?php
                            echo $this->partial(
                                'motTestSearchSummaryLink',
                                [
                                    'status' => $motTest['status'],
                                    'url' => $testSummaryUrl,
                                    'motTestNumber' => $motTest['motTestNumber']
                                ]
                            );
                            ?>
                        </td>

                        <td><?php echo $this->escapeHtml($motTest['motTestNumber']); ?></td>
                        <td><?php echo $this->escapeHtml($motTest['vin']); ?></td>
                        <td><?php echo $this->escapeHtml($motTest['registration']); ?></td>
                        <td><?php echo $this->escapeHtml($motTest['make']); ?></td>

                        <td title="<?php echo $this->escapeHtmlAttr($model); ?>" class="truncate"><?php
                            echo $this->escapeHtml($model);
                        ?></td>

                        <td title="<?php echo $this->escapeHtmlAttr($testType); ?>" class="truncate"><?php
                            echo $this->escapeHtml($testType);
                        ?></td>

                        <td>
                            <?php if (isset($siteId)): ?>
                                <a href="<?php echo $this->url('vehicle-testing-station-by-site',
                                    ['id' => $siteId]) ?>">
                                    <?php echo $this->escapeHtml($siteNr); ?>
                                </a>
                            <?php else : ?>
                                N/A
                            <?php endif; ?>
                        </td>

                        <td><?php echo $this->escapeHtml($motTest['testerUsername']); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    MotTestSeachByVehicle.isEnableExpandBtn = !!'<?php
        echo (string)(!empty ($comparedTest['motTestNumber']) && !empty ($comparedTest['motTestNumberToCompare']));
    ?>';
</script>
