<?php

use Core\Routing\MotTestRoutes;
use Core\Routing\ProfileRoutes;
use Dashboard\Controller\UserHomeController;
use Dashboard\ViewModel\UserStatsViewModel;

/**
 * @var UserStatsViewModel $viewModel
 */

$dayStats = $viewModel->getDayStats();
$monthStats = $viewModel->getMonthStats();

?>

<div class="text">
    <p class="lede">Information on tests you've done today and in the month to date.</p>
    <h2 class="heading-medium">
        Today's summary
        <span class="heading-meta"><?php echo $viewModel->getCurrentDateAsDayMonth(); ?></span>
    </h2>
</div>

<div class="grid-row">
    <?php echo $this->partial('partials/table-field', [
        'id' => 'today-total-vehicles-tested',
        'value' => $dayStats->getTotal(),
        'label' => 'tests done',
    ]);
    echo $this->partial('partials/table-field', [
        'id' => 'today-number-passed',
        'value' => $dayStats->getNumberOfPasses(),
        'label' => 'tests passed',
    ]);
    echo $this->partial('partials/table-field', [
        'id' => 'today-number-failed',
        'value' => $dayStats->getNumberOfFails(),
        'label' => 'tests failed',
    ]); ?>
</div>

<div class="text">
    <h2 class="heading-medium">
        Month to date
        <span class="heading-meta">
            <?php echo $viewModel->getFirstOfThisMonthAsDayMonth(); ?> to <?php echo $viewModel->getCurrentDateAsDayMonth(); ?>
        </span>
    </h2>
</div>

<div class="grid-row u-space-b30">
    <?php echo $this->partial('partials/table-field', [
        'id' => 'current-month-total-vehicles-tested',
        'value' => $monthStats->getTotalTestsCount(),
        'label' => 'tests done',
    ]);
    echo $this->partial('partials/table-field', [
        'id' => 'current-month-number-passed',
        'value' => $monthStats->getPassedTestsCount(),
        'label' => 'tests passed',
    ]);
    echo $this->partial('partials/table-field', [
        'id' => 'current-month-number-failed',
        'value' => $monthStats->getFailedTestsCount(),
        'label' => 'tests failed',
    ]);
    echo $this->partial('partials/table-field', [
        'id' => 'current-month-average-time',
        'value' => $viewModel->getMonthlyAverageTimeAsString() . 'm',
        'label' => 'average test time',
    ]);
    echo $this->partial('partials/table-field', [
        'id' => 'current-month-fail-rate',
        'value' => $viewModel->getAndConvertPercentFailed(),
        'label' => 'fail rate',
    ]); ?>
</div>

<div class="text">
    <p>
        <a href="<?php echo MotTestRoutes::of($this)->motTestLogs() ?>" id="test-log-link" class="big-link">Test logs</a>
    </p>
    <p>
        See information on all tests you've done, including vehicle details.
    </p>
</div>

<div class="text">
    <p>
        <a href="<?php echo ProfileRoutes::of($this)->yourProfileTqi($viewModel->getPreviousMonth(), $viewModel->getPreviousYear()) ?>" id="tqi-link" class="big-link">
            Test quality information
        </a>
    </p>
    <p>
        See more performance information on tests you've done, including your failure rate by category.
    </p>
</div>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a  id="back-to-home-link" href="<?php echo $this->url(UserHomeController::ROUTE); ?>">Back to home</a>
        </li>
    </ul>
</nav>

