<?php
use Dvsa\Mot\Frontend\PersonModule\ChangeSecurityQuestions\Controller\ChangeSecurityQuestionOneController;
use Dvsa\Mot\Frontend\PersonModule\ChangeSecurityQuestions\Controller\ChangeSecurityQuestionTwoController;
$form = $viewModel->getForm();
$this->layout('layout/layout-govuk.phtml');
?>
<?php echo $this->partial('zendFormErrorMessages', ['form' => $form]); ?>
<form method="POST" action="<?php echo $this->escapeHtml($this->url(ChangeSecurityQuestionTwoController::ROUTE)); ?>" autocomplete="off" novalidate="">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <?php
        $questions = $form->getSecurityQuestion()->getValueOptions();
        ?>
        <div class="form-group">
            <label class="form-label" for="questions">Choose a question</label>
            <select class="form-control form-control-1-2" id="questions" name="questions">
                <?php
                foreach ($questions as $key => $value) {
                    $select = $questions == $key ? 'selected' : '';
                    ?>
                    <option <?php echo $select; ?> value="<?php echo $key; ?>" <?php if($key == $viewModel->getQuestion()){echo " selected=\"selected\"";} ?>>
                        <?php echo $value; ?></option>
                    <?php
                } ?>
            </select>
        </div>

        <div class="form-group<?php if ($form->getSecurityQuestionAnswer()->getMessages()) echo ' has-error' ?>">
            <label class="form-label" for="question-answer">Enter your answer
                <span class="form-label validation-message">
                <?php
                if ($form->getSecurityQuestionAnswer()->getMessages()) {
                    foreach ($form->getSecurityQuestionAnswer()->getMessages() as $message) {
                        echo $message;
                    };
                }
                ?>
                </span>
            </label> <input class=" form-control form-control-1-2"
                            id="question-answer" name="question-answer" type="text" value="<?php echo $this->escapeHtmlAttr($viewModel->getAnswer()) ?>">
        </div>
    </fieldset>
    <nav class="content-navigation">

        <input type="submit" value="Continue" id="continue" class="button">

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtml($this->url(ChangeSecurityQuestionOneController::ROUTE)); ?>" id="back">Back</a>
            </li>
        </ul>

    </nav>
</form>