<?php
use DvsaCommon\Dto\Common\ReasonForRefusalDto;
use DvsaCommon\Dto\Vehicle\VehicleDto;

/** @var ReasonForRefusalDto[] $reasonForRefusal */
/** @var VehicleDto $vehicle */
/** @var string $backToSearchLink */
/** @var string $formAction */
/** @var bool $isDisplayRegistration */

echo $this->partial('infoMessages', ['getFromFlash' => true]);
echo $this->partial('errorMessages', ['getFromFlash' => true]);

?>
<form action="<?php echo $formAction; //escaped in controller ?>" method="POST">
    <div class="row">
        <div class="col-md-12">
            <?php echo $this->csrfToken() ?>
            <div class="form-group">
                <fieldset class="label-lg">
                    <legend class="form-label">Reason for refusing test</legend>

                    <?php
                    foreach ($reasonForRefusal as $rfr) {
                        echo $this->partial(
                            'partial/forms/radioElement.phtml',
                            [
                                'id'            => 'refusal-' . $rfr->getId(),
                                'name'          => 'refusal',
                                'value'         => $rfr->getId(),
                                'label'         => $rfr->getReason(),
                                'labelCssClass' => 'block-label label-clear',
                            ]
                        );
                    }
                    ?>
                </fieldset>
            </div>
        </div>
        <div class="col-md-6 col-md-offset-1">
            <section class="module-present-data">
                <h2>Vehicle details</h2>
                <dl class="vertical">
                    <?php if($isDisplayRegistration) : ?>
                    <dt>Registration mark</dt>
                    <dd id="registration-mark"><?php echo $this->escapeHtml($vehicle->getRegistration()); ?></dd>
                    <?php endif ?>
                    <dt>VIN/Chassis</dt>
                    <dd id="vin"><?php echo $this->escapeHtml($vehicle->getVin()); ?></dd>
                    <dt>Make and Model</dt>
                    <dd id="make-and-model"><?php echo $this->escapeHtml($vehicle->getMake() . ', ' . $vehicle->getModel()); ?></dd>
                </dl>
            </section>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <button type="submit" class="btn btn-danger" id="refuse-mot-test">Refuse MOT test</button>
        </div>
    </div>
</form>
<nav class="module-content-navigation">
    <ul class="content-navigation_secondary">
        <li>
            <a href="<?php echo $backToSearchLink; //escaped in controller ?>" id="back_to_search">Back</a>
        </li>
    </ul>
</nav>
