<?php

/**
 * @var array $reports
 */

?>

<header class="content-header">
    <h1 id="generate-survey-reports-page-title">
        <span class="content-header__title">
            Satisfaction survey data
        </span>
    </h1>
</header>

<div id="satisfaction-survey-data-container" class="text">

    <p class="lede">You can download satisfaction survey data for each month below as an Excel spreadsheet.</p>

    <?php foreach ($reports['data'] as $report) :
        $reportDate = DateTime::createFromFormat('Y-m', $report['month']);

        if (!in_array($reportDate->format('Y'), $reportYears))
            $reportYears[] = $reportDate->format('Y');
        ?>
    <?php endforeach; ?>

    <?php foreach ($reportYears as $reportYear) : ?>
        <h3 class="heading-medium"><?php echo $reportYear ?></h3>
        <ul class="list-bullet">
            <?php foreach ($reports['data'] as $report) :
                $reportDate = DateTime::createFromFormat('Y-m', $report['month']);

                if ($reportDate->format('Y') == $reportYear) : ?>
                    <?php echo '<li><a href="reports/download/' . $reportDate->format('F') . '">' ?><?php echo $reportDate->format('F') ?></a> (<?php echo round($report['size']/1024, 2) ?>KB)</li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php endforeach; ?>

    <nav class="content-navigation">
        <ul class="content-navigation__secondary">
            <li>
                <a id="back-to-home-link" href="/">Return home</a>
            </li>
        </ul>
    </nav>

</div>
