<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Event\Controller\EventController'           => __DIR__ . '/src/Event/Controller/EventController.php',
  'Event\ViewModel\Event\EventDetailViewModel' => __DIR__ . '/src/Event/ViewModel/Event/EventDetailViewModel.php',
  'Event\ViewModel\Event\EventViewModel'       => __DIR__ . '/src/Event/ViewModel/Event/EventViewModel.php',
);
