<?php

/**
 * @var \Organisation\Form\AeCreateForm            $form
 * @var string                                     $cancelRoute
 * @var \Zend\Mvc\Controller\Plugin\FlashMessenger $flashMessenger
 */

$this->inlineScript()
    ->prependFile('/js/common/email-utils.js')
    ->prependFile('/js/organisation/view/edit.js');

$flashMessenger = $this->layout()->flashMessenger;

echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'success']
);
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getSuccessMessages(), 'type' => 'failure']
);
?>

<form method="POST">
    <?php echo $this->csrfToken(); ?>
    <fieldset>
        <?php echo $this->partial('partial/gds/form/control-legend',    ['id' => 'legendEmail', 'text' => 'Email']); ?>
        <p id="textWarning">The email address should be one you have easy and regular access to and will be used to send you important
            messages that will be required outside of the MOT Testing Service application - for example, username and
            password reminders.<br>
            <strong>You could be without access for up to 5 working days</strong> if you don't supply an email address.
        </p>

        <?php echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => 'correspondenceEmail',
                'errorMessage'  => $form->getError('correspondenceEmail'),
                'inputModifier' => '1-3',
                'label'         => 'Email address',
                'value'         => $form->getCorrespondenceEmail(),
            ]
        ); ?>
        <?php echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => 'correspondenceEmailConfirmation',
                'errorMessage'  => $form->getError('correspondenceEmailConfirmation'),
                'inputModifier' => '1-3',
                'label'         => 'Confirm email address',
                'value'         => $form->getCorrespondenceEmailConfirmation(),
            ]
        ); ?>
        <?php echo $this->partial(
            'partial/gds/form/control-checkbox-group',
            [
                'label'         => '',
                'options'       => [
                    [
                        'value'         => '1',
                        'inputName'     => 'correspondenceEmailSupply',
                        'key'           => 'I don\'t want to supply an email address',
                        'checked'       => !$form->isCorrEmailSupply(),
                    ],
                ],
            ]
        ); ?>
    </fieldset>

    <fieldset>
        <?php
        echo $this->partial('partial/gds/form/control-legend', ['id' => 'legendTelephone', 'text' => 'Telephone']);
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => 'correspondencePhoneNumber',
                'name'          => 'correspondencePhoneNumber',
                'errorMessage'  => $form->getError('correspondencePhoneNumber'),
                'inputModifier' => '1-4',
                'label'         => 'Telephone number',
                'value'         => $form->getCorrespondencePhoneNumber(),
            ]
        );
        ?>
    </fieldset>
    <fieldset>
        <?php echo $this->partial(
            'partial/gds/form/control-legend', ['id' => 'legendBusiness', 'text' => 'Business address']
        ); ?>
        <p class="lede">
            <?php echo $this->partial(
                'partial/gds/general/display-address-bloc',
                [
                    'isAddress' => $form->isBusinessAddress(),
                    'address'   => $form->toArray(),
                ]
            ); ?>
            <br/>
        </p>
    </fieldset>
    <fieldset>
        <?php
        echo $this->partial(
            'partial/gds/form/control-legend', ['id' => 'legendCorrespondence', 'text' => 'Correspondence address']
        );

        echo $this->partial(
            'partial/gds/form/control-radio-group',
            [
                'inputModifier' => 'inline',
                'label'         => 'Is this the same as the business address?',
                'options'       => [
                    [
                        'value'         => '1',
                        'inputName'     => 'correspondenceContactDetailsSame',
                        'key'           => 'Yes',
                        'checked'       => $form->isCorrespondenceContactDetailsSame(),
                    ],
                    [
                        'value'         => '0',
                        'inputName'     => 'correspondenceContactDetailsSame',
                        'key'           => 'No',
                        'checked'       => !$form->isCorrespondenceContactDetailsSame(),
                        'dataTarget'    => 'addressCorrespondence',
                    ]
                ],
            ]
        );

        echo $this->partial(
            'partial/gds/form/control-address-group',
            [
                'id'        => 'addressCorrespondence',
                'type'      => 'correspondence',
                'form'      => $form,
                'address'   => $form->toArray(),
            ]
        );
        ?>
    </fieldset>
    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'            => 'submitAeEdit',
            'value'         => 'Save contact details',
            'navigation'    => [
                'Cancel and return to AE Details' => $cancelRoute,
            ]
        ]
    ); ?>
</form>

<script>
    var OrganisationEdit = {
        isCorrAddressTheSame: !!'<?php echo $form->isCorrespondenceContactDetailsSame(); ?>'
    };
</script>