Dear <?php echo $this->escapeHtml(sprintf("%s %s", $this->firstName, $this->familyName)); ?>,

<p>Please find attached your MOT Test Certificate which holds all of the result information captured during the recent MOT test that was conducted on your vehicle</p>

<p>Incorporating the Driving Standards Agency and Vehicle and Operator Services Agency.<br />Find out more about government services at <br /><a href="https://www.gov.uk/getting-an-mot">https://www.gov.uk/getting-an-mot</a></p>