<?php
// @todo: (ABN) These templates need some deep cleaning,
//        Way too much logic handled here which must to be moved elsewhere, at least to some view models

use Dvsa\Mot\ApiClient\Resource\Item\BrakeTestResultClass1And2;
use Dvsa\Mot\ApiClient\Resource\Item\BrakeTestResultClass3AndAbove;
use Dvsa\Mot\ApiClient\Resource\Item\MotTest;
use DvsaCommon\Enum\MotTestTypeCode;
use DvsaCommon\Enum\VehicleClassCode;
use DvsaMotTest\Controller\DvsaVehicleViewModel;

/** @var MotTest */
$motTest;

/** @var DvsaVehicleViewModel $vehicle */
$vehicle;

if ($motTest->getTestTypeCode() === MotTestTypeCode::RE_TEST) {
    $brakeTestResults = $motTest->getPreviousMotTest()->getBrakeTestResult();
} else {
    $brakeTestResults = $motTest->getBrakeTestResult();
}

if (in_array($vehicle->getVehicleClass()->getCode(), VehicleClassCode::getGroupAClasses())) {
    $templatePath = 'partials/brake-test-column-group-a.phtml';
    $brakeResult = new BrakeTestResultClass1And2($brakeTestResults);
} else {
    $templatePath = 'partials/brake-test-column-group-b.phtml';
    $brakeResult = new BrakeTestResultClass3AndAbove($brakeTestResults);
}

echo $this->partial(
    $templatePath,
    [
        'vehicle' => $vehicle,
        'brakeResult' => $brakeResult,
    ]
);
