<?php
use DvsaCommon\Date\DateTimeDisplayFormat;
use DvsaCommon\Enum\ColourCode;
use DvsaCommon\Dto\Common\ColourDto;
use DvsaCommon\Utility\ArrayUtils;
use DvsaMotTest\Model\VehicleClass;

/** @var \Vehicle\Helper\ColoursContainer $colours */
$colours = ArrayUtils::tryGet($this->staticData, 'colours', []);
$fuelTypes = ArrayUtils::tryGet($this->staticData, 'fuelTypes', []);

/** @var \Dvsa\Mot\ApiClient\Resource\Item\DvlaVehicle|\Dvsa\Mot\ApiClient\Resource\Item\DvsaVehicle $vehicle */
$vehicle = $this->vehicle;

$vrm = $vehicle->getRegistration();
$vin = $vehicle->getVin();
$makeAndModel = implode(
    ', ',
    array_filter(
        [
            $vehicle->getMakeName(),
            $vehicle->getModelName(),
        ]
    )
);

// The DL DT partial will only show an alternative string on a null value, not emtpy
if (empty($makeAndModel)) {
    $makeAndModel = null;
}

if ($vehicle instanceof \Dvsa\Mot\ApiClient\Resource\Item\DvsaVehicle) {
    if ((is_null($vrm) || empty($vrm)) && $vehicle->getEmptyVrmReason()) {
        $vrm = $staticData['emptyVrmReasons'][$vehicle->getEmptyVrmReason()];
    }
    if ((is_null($vin) || empty($vin)) && $vehicle->getEmptyVinReason()) {
        $vin = $staticData['emptyVinReasons'][$vehicle->getEmptyVinReason()];
    }
}

$transmissionType = $vehicle->getTransmissionType();

$expiryDate = DateTimeDisplayFormat::textDate($this->expiryDate);
?>
<div class="row">
    <div class="col-md-6">
        <?php
        echo $this->partial(
            'dldtdd', [
                'dlCssClass' => 'dl-large',
                'items'      => [
                    ['Registration number', $vrm, 'id' => 'vehicleRegistrationNumber'],
                    ['VIN/Chassis number', $vin, 'id' => 'vehicleVINnumber'],
                    ['Make', $makeAndModel, 'id' => 'vehicleMake'],
                ]
            ]
        );
        ?>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6">
                <?php
                echo $this->partial(
                    'dldtdd', [
                        'dlCssClass' => 'dl-standard',
                        'items'      => [
                            ['Cylinder capacity', $vehicle->getCylinderCapacity(), 'id' => 'vehicleCylinderCapacity'],
                            (
                                $transmissionType
                                ? ['Transmission', $transmissionType, 'id' => 'vehicleTransmission']
                                : null
                            ),
                            (
                                method_exists($vehicle, 'getWeight')
                                    ? $vehicle->getWeight() > 0
                                      ? ['Vehicle weight', $vehicle->getWeight() . ' kg', 'id' => 'vehicleWeight']
                                      : ['Vehicle weight', 'Unknown', 'id' => 'vehicleWeight']
                                    : null
                            ),
                            ($expiryDate ? ['MOT expiry date', $expiryDate, 'id' => 'motExpiryDate'] : null)
                        ]
                    ]
                );
                ?>
            </div>
            <div class="col-md-6">
                <?php
                echo $this->partial(
                    'dldtdd', [
                        'dlCssClass' => 'dl-standard',
                        'items'      => [
                            ['Body type', $vehicle->getBodyType(), 'id' => 'vehicleBodyType'],
                            [
                                'Date of first use',
                                DateTimeDisplayFormat::textDate($vehicle->getFirstUsedDate()) ?: null,
                                'id' => 'vehicleFirstUse'
                            ],
                        ]
                    ]
                );
                ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <dl class="dl-standard">
                    <dt>Vehicle class</dt>
                    <dd>
                        <div class="form-group">
                            <?php
                            $vehicleClasses = VehicleClass::getVehicleClassesCodes();

                            if (!$this->doNotShowDropDowns) {
                                echo $this->partial(
                                    'selectElement',
                                    [
                                        'id'       => 'vehicle-class-select',
                                        'name'     => 'vehicleClassId',
                                        'options'  => $vehicleClasses,
                                        'value'    => $vehicle->getVehicleClass() ? $vehicle->getVehicleClass()->getCode() : "",
                                        'required' => true,
                                    ]
                                );
                            } else {
                                echo $vehicle->getVehicleClass()->getName();
                                ?>
                                    <input type="hidden" name="vehicleClassId" value="<?php echo $vehicle->getVehicleClass() ? $vehicle->getVehicleClass()->getCode() : ""; ?>" />
                                <?php
                            }
                            ?>
                        </div>
                    </dd>
                </dl>
            </div>
            <div class="col-md-6">
                <dl class="dl-standard">
                    <dt>Fuel type</dt>
                    <dd>
                        <div class="form-group">
                            <?php
                            $fuelTypeName = $vehicle->getFuelType() ? $vehicle->getFuelType()->getName() : "";
                            if (!$this->doNotShowDropDowns) {
                                echo $this->partial(
                                    'selectElementSelectedByDisplayedValue',
                                    [
                                        'id'      => 'fuel-type-select',
                                        'name'    => 'fuelTypeId',
                                        'options' => $fuelTypes,
                                        'value'   => $fuelTypeName,
                                    ]
                                );
                            } else {
                                echo $fuelTypeName;
                                ?>
                                    <input type="hidden" name="fuelTypeId" value="<?php echo $fuelTypeName; ?>" />
                                <?php
                            }
                            ?>
                        </div>
                    </dd>
                </dl>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <dl class="dl-standard">
                    <dt>Primary colour</dt>
                    <dd>
                        <div class="form-group">
                            <?php
                            $colourName = $vehicle->getColour() ? $vehicle->getColour()->getName() : "";
                            if (!$this->doNotShowDropDowns) {
                                echo $this->partial(
                                    'selectElementSelectedByDisplayedValue',
                                    [
                                        'id'      => 'primary-colour',
                                        'name'    => 'colourId',
                                        'options' => $colours->getPrimaryColours(),
                                        'value'   => $colourName
                                    ]
                                );
                            } else {
                                echo $colourName;
                                ?>
                                    <input type="hidden" name="colourId" value="<?php echo $colourName; ?>" />
                                <?php
                            }
                            ?>
                        </div>
                    </dd>
                </dl>
            </div>
            <div class="col-md-6">
                <dl class="dl-standard">
                    <dt>Secondary colour</dt>
                    <dd>
                        <div class="form-group">
                            <?php
                            $secondaryColourName = $vehicle->getColourSecondary() ? $vehicle->getColourSecondary()->getName() : "";
                            if (!$this->doNotShowDropDowns) {
                                echo $this->partial(
                                    'selectElementSelectedByDisplayedValue',
                                    [
                                        'id'      => 'secondary-colour',
                                        'name'    => 'secondaryColourId',
                                        'options' => $colours->getSecondaryColours(),
                                        'value'   => $secondaryColourName
                                    ]
                                );
                            } else {
                                echo $secondaryColourName;
                                ?>
                                    <input type="hidden" name="secondaryColourId" value="<?php echo $secondaryColourName; ?>" />
                                <?php
                            }
                            ?>
                        </div>
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>

