<?php
use DvsaCommon\Utility\ArrayUtils;

$dlCssClass = !empty($this->dlCssClass) ? $this->dlCssClass : null;
$dlId = !empty($this->dlId) ? $this->dlId : null;

$itemId = $this->itemId;
$items = is_array($this->items) && !empty($this->items) ? $this->items : [];
?>

<dl <?php echo
    ($dlCssClass ? 'class="'.$dlCssClass.'" ' : '') .
    ($dlId ? ' id="' . $this->escapeHtmlAttr($dlId) . '"' : '')
    ?>>
    <?php foreach ($items as $idx => $item):
        if (!is_array($item) || empty($item)) {
            continue;
        }

        $isShow = (ArrayUtils::tryGet($item, 'show') !== false);
        $isNeedEscape = (ArrayUtils::tryGet($item, 'escape') !== false);

        //  --  label   --
        $label = ArrayUtils::tryGet($item, 'label');
        if (!$label) {
            $label = ArrayUtils::tryGet($item, 0);
        }

        $escLabel = (!$label ? '&nbsp;' : $this->escapeHtml($label));

        //  --  value   --
        $value = trim(ArrayUtils::tryGet($item, 'value'));
        if (!$value) {
            $value = ArrayUtils::tryGet($item, 1);
        }

        if ($value === '') {
            $value = '&nbsp;';
            $isNeedEscape = false;
        } else if ($value  === null) {
            $value = 'N/A';
        }

        $dtCssClass = ArrayUtils::tryGet($item, 'dtCssClass');
        $ddCssClass = ArrayUtils::tryGet($item, 'cssClass');

        //  --  id  --
        $ddId = ArrayUtils::tryGet($item, 'id');
        if (!$ddId && $itemId) {
            $ddId = $itemId . '-dd' . $idx;
        }

        $dtId = ArrayUtils::tryGet($item, 'dtId');
        if (!$dtId && $itemId) {
            $dtId = $itemId . '-dt' . $idx;
        }

        if ($isShow) : ?>
            <dt <?php echo
                ($dtCssClass ? ' class="' . $this->escapeHtmlAttr($dtCssClass) . '"' : '') .
                ($dtId ? ' id="' . $this->escapeHtmlAttr($dtId) . '"' : '')
            ?>><?php echo $escLabel; ?></dt>
            <dd <?php echo
                ($ddCssClass ? ' class="' . $this->escapeHtmlAttr($ddCssClass) . '"' : '') .
                ($ddId ? ' id="' . $this->escapeHtmlAttr($ddId) . '"' : '');
            ?>><?php echo $isNeedEscape ? $this->escapeHtml($value) : $value; ?></dd>
        <?php endif;
    endforeach; ?>
</dl>
