<?php
/** @var string $id */
/** @var string $name */
/** @var bool $locked */
?>

<label class="checkbox-inline" for="<?php echo $this->escapeHtml($id); ?>">
    <input type="hidden" name="<?php echo $this->escapeHtml($name); ?>" value="0">
    <input type="checkbox"
           id="<?php echo $this->escapeHtml($id); ?>"
           name="<?php echo $this->escapeHtml($name); ?>"
           value="1" <?php echo $locked ? 'checked' : ''; ?>
    > Lock
</label>