<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a id="certificates_list" href="<?php echo $this->url('mot-test-certificate-list', ['id' => $vtsId]); ?>">Back to the MOT test certificates list</a>
        </li>
    </ul>
</nav>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a id="return_home" href="/">Return Home</a>
        </li>
    </ul>
</nav>