<?php
$steps = [" Search", " Confirmation", " Results entry", " Review"];
$showTitle = $this->title ?: false;
$currentStep = $this->currentStep ?: 0;

if ($isMotContingency === true) {
    array_unshift($steps, " Contingency Test ");
    $currentStep++;
}
?>
<section>

    <?php if (false !== $showTitle) : ?>
    <div class="row">
          <div class="col-lg-12">
            <h1>
                <?php if (isset($subTitle) && !empty($subTitle)) : ?>
                    <small><?php echo $this->escapeHtml($subTitle); ?></small>
                <?php endif; ?>
                <?php echo $this->escapeHtml($title); ?>
            </h1>
        </div>
    </div>
    <?php endif; ?>
</section>