<?php
$steps = [" Search", " Confirmation", " Results entry", " Review"];
$showTitle = $this->title ?: false;
$currentStep = $this->currentStep ?: 0;

if ($isMotContingency === true) {
    array_unshift($steps, " Contingency Test ");
    $currentStep++;
}
?>
<section>
    <div class="row" id="content">
        <div class="col-lg-12 progress-tracker">
            <ul class="list-unstyled">
            <?php for ($stepNumber = 0; $stepNumber < count($steps); $stepNumber++) : ?>
                <?php
                $class = $stepNumber === $currentStep ? "active" :
                    ($stepNumber < $currentStep ? "done" : null);
                ?>
                <li <?php if (!empty($class)) { echo "class=\"$class\""; } ?>>
                    <i class="fa fa-arrow-circle-right"></i>
                    <?php echo $this->escapeHtml($steps[$stepNumber]); ?>
                </li>
            <?php endfor; ?>
            </ul>
        </div>
    </div>

    <?php if (false !== $showTitle) : ?>
    <div class="row">
          <div class="col-lg-12">
            <h1>
                <?php if (isset($subTitle) && !empty($subTitle)) : ?>
                    <small><?php echo $this->escapeHtml($subTitle); ?></small>
                <?php endif; ?>
                <?php echo $this->escapeHtml($title); ?>
            </h1>
        </div>
    </div>
    <?php endif; ?>
</section>