<?php
if (0 === count($certificates)): ?>
    <h2>
        No MOT certificates are currently available to print.
    </h2>
    <?php else: ?>
<table class="key-value-list">
    <thead>
    <tr>
        <th>
            Vehicle
        </th>
        <th>
            Registration Mark
        </th>
        <th>
            Test result
        </th>
        <th colspan="3">
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($certificates as $certificate): ?>
        <tr>
            <td>
                <span class="bold-small"><?php echo $certificate->getMake() . ' ' . $certificate->getModel(); ?></span>
            </td>
            <td>
                <?php echo $certificate->getRegistration()? :'Unknown'; ?>
            </td>
            <td>
                <?php echo $certificate->getMotTestResult(); ?>
            </td>
            <td>
                <?php if (!empty($certificate->getCertificateStorageKey())): ?>
                    <a href="<?php echo $this->url('download-certificate-pdf', [
                    'vin' =>  $certificate->getRegistration() ? $certificate->getRegistration() : $certificate->getVin(),
                    'status' =>  str_replace(" ", "", $certificate->getMotTestResult()),
                    'motRecentCertificateId' => $certificate->getId()
                ]); ?>">Download</a>
                <?php endif; ?>
            </td>
            <td>
                <?php if (!empty($certificate->getCertificateStorageKey())): ?>
                    <a href="<?php echo $this->url('mot-test-certificate-email', ['certificateId' => $certificate->getId()]); ?>">Email</a>
                <?php endif; ?>
            </td>
            <td>
                <?php if (!empty($certificate->getCertificateStorageKey())): ?>
                    <a class="button" style="margin:0" href="<?php echo $this->url('print-certificate-pdf', [
                        'vin' =>  $certificate->getRegistration() ? $certificate->getRegistration() : $certificate->getVin(),
                        'status' =>  str_replace(" ", "", $certificate->getMotTestResult()),
                        'motRecentCertificateId' => $certificate->getId()
                    ]); ?>" target="_blank">Print</a>
                <?php else: ?>
                    Certificate not ready <br/>
                    <span class="key-value-list__meta">Please try again later</span>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach;
    endif;
    ?>
    </tbody>
</table>

<?php if ($paginator->getItemsCount() && $paginator->getLastPage() !== 1): ?>
    <ul class="data-paging">
        <?php if ($paginator->getPrevPage()): ?>
            <li class="data-paging__prev">
                <a class="data-paging__link" href="<?php echo  $this->url("mot-test-certificate-list", [], ["query" => ["page" => $paginator->getPrevPage() ]]) ?>">
                    Previous
                    <span class="data-paging__page">page</span>
                    <span class="data-paging__numbers"><?php echo $paginator->getPrevPage()?> of <?php echo $paginator->getLastPage() ?></span>
                </a>
            </li>
        <?php endif; ?>
        <?php if ($paginator->getNextPage()): ?>
            <li class="data-paging__next">
                <a class="data-paging__link" href="<?php echo  $this->url("mot-test-certificate-list", [], ["query" => ["page" => $paginator->getNextPage() ]]) ?>">
                    Next
                    <span class="data-paging__page">page</span>
                    <span class="data-paging__numbers"><?php echo $paginator->getNextPage()?> of <?php echo $paginator->getLastPage() ?></span>
                </a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
