<?php
$canTestWithoutOpt = isset($canTestWithoutOpt) ? $canTestWithoutOpt : false;
$errorMessage = isset($errorMessage) ? $errorMessage : false;
$shortMessage = !empty($shortErrorMessage) ? $shortErrorMessage : $errorMessage;

?>

<?php if (!$canTestWithoutOpt): ?>

    <div class="module-second-auth">
        <img class="second-auth__logo" src="/img/mot-2.svg"
             onerror="this.src='/img/mot-2.png'; this.onerror=null;" width="55" height="52"/>
        Your MOT Testing Service PIN
    </div>
    <div class="form-group second-auth__input<?php if ($errorMessage): ?> has-error<?php endif; ?>">
        <label for="oneTimePassword">Please enter your PIN</label>
        <?php if ($shortMessage): ?>
            <span class="validation-message"><?php echo $shortMessage; //this is HTML content?></span>
        <?php endif; ?>
        <?php // Blacnk, hidden password input to prevent browser autofilling?>
        <input type="password" name="IDToken2" id="IDToken2" value="" maxlength="100"  tabindex="-1" style="width: 1px; position: absolute; left: -9999px;" aria-hidden="true"  autocomplete="off" />
        <input type="password" name="oneTimePassword" id="oneTimePassword" class="form-control" autocomplete="off" />
    </div>
    <div class="info-alert" style="border-left: 4px solid #bfc1c3;background-color: #f8f8f8;background-position:10px 10px">
        <p id="declarationStatement" style="font-weight:normal;padding-left: 15px;padding-top: 10px">
            I confirm that this MOT transaction has been conducted in accordance with the conditions of
            authorisation which includes compliance with the MOT testing guide, the requirements for
            authorisation, the appropriate MOT Inspection Manual and any other instructions issued by DVSA.
        </p>
    </div>
<?php endif; ?>
