<?php
use DvsaCommon\Constants\ReasonForRejection;

$showRfrName = true;
$descriptionValidation = '';

if (!isset($rfr)) {
    $rfr = [
        'testItemSelectorId' => 0,
        'rfrId' => 0,
        'canBeDangerous' => true,
    ];
    $showRfrName = false;
    $descriptionValidation = 'required';
}
?>

<div class="modal fade" id="rfr-edit-dialog-<?php echo $escRfrId; ?>" tabindex="-1" role="dialog"
     aria-labelledby="Enter location for fault - <?php echo $escRfrId; ?>" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title" id="modal-rfr-edit-title-<?php echo $escRfrId; ?>">
                    <?php echo $this->escapeHtml($title); ?>
                </h3>
            </div>
            <div class="modal-body">

                <form data-dialog-form
                      action="<?php echo $this->url('mot-test/rfr-edit', ['motTestNumber' => $motTestNumber, 'rfr-id' => $rfr['id']]); ?>"
                      method="POST">
                    <?php echo $this->csrfToken() ?>
                    <?php if ($showRfrName): ?>
                        <h4>
                            <?php echo !empty($rfr['name']) ? $this->escapeHtml($rfr['name']).' - ' : null;
                                echo $this->escapeHtml($rfr['failureText']); ?>
                        </h4>
                    <?php endif; ?>
                    <div data-dialog-message-pane>
                    </div>
                    <input name='searchString' type='hidden'
                           value='<?php echo isset($searchString) ? $this->escapeHtml($searchString) : null; ?>'/>

                    <div class="failure-group">
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="lateral" class="control-label">Lateral</label>
                                <?php echo $this->partial('selectElement', [
                                        'id' => 'locationLateral',
                                        'value' => $rfr['locationLateral'],
                                        'options' => [
                                            '' => 'n/a',
                                            'nearside' => 'nearside',
                                            'centre' => 'centre',
                                            'offside' => 'offside',
                                        ],
                                    ]); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="longitudinal" class=" control-label">Longitudinal</label>
                                <?php echo $this->partial('selectElement', [
                                        'id' => 'locationLongitudinal',
                                        'value' => $rfr['locationLongitudinal'],
                                        'options' => [
                                            '' => 'n/a',
                                            'front' => 'front',
                                            'rear' => 'rear',
                                        ],
                                    ]); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="vertical" class="control-label">Vertical</label>
                                <?php echo $this->partial('selectElement', [
                                        'id' => 'locationVertical',
                                        'value' => $rfr['locationVertical'],
                                        'options' => [
                                            '' => 'n/a',
                                            'upper' => 'upper',
                                            'lower' => 'lower',
                                            'inner' => 'inner',
                                            'outer' => 'outer',
                                        ],
                                    ]); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-9">
                                <label for="description" class="control-label">Description</label>
                                <textarea name="comment" class="form-control" rows="2"
                                          maxlength="<?php echo $this->escapeHtmlAttr(ReasonForRejection::MAX_DESCRIPTION_LENGTH); ?>"
                                          id="description" <?php echo $this->escapeHtmlAttr($descriptionValidation); ?>>
                                    <?php echo $this->escapeHtml($rfr['comment']) ?>
                                </textarea>
                            </div>
                        </div>
                        <?php if ($rfr['canBeDangerous']): ?>
                        <div class="row">
                            <div class="col-sm-8">
                                <label for="dangerous">
                                    <input type="checkbox" name="failureDangerous" id="dangerous" value="true" <?php if ($rfr['failureDangerous']) {
                                        echo 'checked';
                                    } ?>>
                                    Failure is dangerous
                                </label>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" id="rfr-edit-submit-<?php echo $escRfrId; ?>" name="submit" value="Save"
                               class="btn btn-primary"/>
                        <button type="button" class="btn btn-link" id="rfr-edit-cancel-<?php echo $escRfrId; ?>"
                                data-dismiss="modal">Close
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->

   <?php echo $this->partial('modalMessages'); ?>
</div><!-- /.modal -->


<script type="text/javascript">
    $(function () {
       var $modal = $("#rfr-edit-dialog-<?php echo $escRfrId; ?>");
       var $submitBtn = $modal.find('#rfr-edit-submit-<?php echo $escRfrId; ?>');
       var $closeBtn = $modal.find('#rfr-edit-cancel-<?php echo $escRfrId; ?>');
       var $messageContainer = $modal.find('[data-dialog-message-pane]');
       var actionButtons = [$submitBtn, $closeBtn];

       var updateMessagesPane = $.proxy(function($modal, $actionButtons, $messageContainer, data) {
            var source = $modal.find('[data-message-pane-tpl]').html();
            var template = Handlebars.compile(source);
            var html = template(data);
            $messageContainer.html(html);

            $.each(actionButtons, function(i, $val) {
                $val.removeProp('disabled');
            })

        }, null, $modal, actionButtons, $messageContainer);

        var $form = $modal.find('[data-dialog-form]');
        $modal.on('show.bs.modal', function (evt) {
            $form.get(0).reset();
            $messageContainer.empty();
        });

        $form.on('submit', function (evt) {

            evt.preventDefault();

            $.each(actionButtons, function(i, $val) {
                $val.prop('disabled', 'disabled');
            });

            $callPromise = $.post($form.attr('action') , $form.serializeArray())
            $callPromise.done(function (data, textStatus, jqXHR) {
                if(typeof data !== typeof {}) {
                    location.reload();
                    return;
                }
                
                if (data.redirectUrl) {
                    location.href = data.redirectUrl + '#' + '<?php echo $this->escapeJs($rfr['type'].'_'.$rfr['id']); ?>';
                    location.reload();
                } else {
                    updateMessagesPane(data.data);
                }
            }).fail(function (jqXHR, textStatus, errorThrown) {

                var errorCtx = { messages : ["Please close the form and try again"]};
                updateMessagesPane(errorCtx);
            });
        });
    });
</script>