<span id="slots" class="label
    <?php if ($slotsDetails->getSlots() > $slotsDetails->getSlotsWarning() ) : ?>
        label-success
    <?php else: ?>
        label-danger
    <?php endif ?>">
    <?php echo $this->escapeHtml($slotsDetails->getSlots()); ?> slots available
    <?php if ($slotsDetails->getSlotsInUse()>0): ?>
        (<?php echo $this->escapeHtml($slotsDetails->getSlotsInUse()) ?> in use)
    <?php endif ?>
</span>