<?php
use Dvsa\Mot\ApiClient\Resource\Item\DvsaVehicle;
use DvsaCommon\Date\DateTimeDisplayFormat;
use DvsaCommon\Dto\Vehicle\VehicleDto;

/** @var  \DvsaMotTest\Controller\DvsaVehicleViewModel $vehicle */
$vehicle = $this->vehicle;

$registration = $vehicle->getRegistration();
$vin = $vehicle->getVin();
$cylinderCapacity = $vehicle->getCylinderCapacity();
$firstUsedDate = $vehicle->getFirstUsedDate();

if ($vehicle instanceof VehicleDto) {
    $makeAndModel = $vehicle->getMakeName() . ' ' . $vehicle->getModelName();
    $transmissionType = $vehicle->getTransmissionType()->getName();
    $fuelType = $vehicle->getFuelType()->getName();
    $bodyType = $vehicle->getBodyType()->getName();
} else {
    $makeAndModel = $vehicle->getMakeAndModel();
    $transmissionType = $vehicle->getTransmissionType();
    $fuelType = $vehicle->getFuelType()->getName();
    $bodyType = $vehicle->getBodyType();
}

?>

<div class="row vehicle-summary">
    <div class="col-md-8">
        <ul class="list-unstyled">
            <li id="registrationNumber">
                <?php
                if ($registration != '') : ?>
                    <span>Registration number</span>
                    <span><?php echo $this->escapeHtml($registration); ?></span>
                <?php else: ?>
                    <span>VIN/Chassis number</span>
                    <span><?php echo $this->escapeHtml($vin); ?></span>
                <?php endif; ?>
            </li>
            <li id="make">
                <span>Make</span>
                <span><?php echo $this->escapeHtml($makeAndModel); ?></span>
                <a href="#" id="toggle-details" data-toggle="collapse" data-target="#vehicle-summary-more"
                   class="up">more <i class="fa fa-caret-down"></i></a>
            </li>
        </ul>
    </div>
</div>
<div class="row collapse" id="vehicle-summary-more">
    <div class="col-md-12">
        <?php
        echo $this->partial(
            'dldtdd', [
                'dlCssClass' => 'dl-horizontal',
                'items'      => [
                    [
                        'label' => 'VIN/Chassis',
                        'value' => $vin,
                        'id' => 'VINChassis',
                    ],
                    [
                        'label' => 'Transmission',
                        'value' => $transmissionType,
                        'id' => 'transmission',
                    ],
                    [
                        'label' => 'Fuel type',
                        'value' => $fuelType,
                        'id' => 'fuelType'
                    ],
                ],
            ]
        );

        echo $this->partial(
            'dldtdd', [
                'dlCssClass' => 'dl-horizontal',
                'items'      => [
                    [
                        'label' => 'Body type',
                        'value' => $bodyType,
                        'id' => 'bodyType'
                    ],
                    [
                        'label' => 'Cylinder capacity',
                        'value' => $cylinderCapacity,
                        'id' => 'cylinderCapacity'
                    ],
                    [
                        'label' => 'First used',
                        'value' => DateTimeDisplayFormat::textDate($firstUsedDate),
                        'id' => 'firstUsed',
                    ],
                ],
            ]
        );
        ?>
    </div>
</div>
<hr class="hr-thin">

<script type="text/javascript">
    var collapse = $('#vehicle-summary-more');

    collapse.on('shown.bs.collapse', function (e) {
        e.stopPropagation();
        $('#toggle-details').html('less <i class="fa fa-caret-up">');
    });

    collapse.on('hidden.bs.collapse', function (e) {
        e.stopPropagation();
        $('#toggle-details').html('more <i class="fa fa-caret-down">');
    });
</script>

