<?php

use DvsaMotTest\Controller\VehicleSearchController;

/** @var \DvsaMotTest\View\VehicleSearchResult\VehicleSearchResultUrlTemplateInterface $urlTemplate */
/** @var \DvsaMotTest\View\VehicleSearchResult\VehicleSearchResultMessage $searchResultMessage */

$this->layout('layout/layout-govuk.phtml');
$breadcrumbs = [
    $this->layout()->getVariable('pageSubTitle') => ''
];
$this->layout()->setVariable('breadcrumbs', ['breadcrumbs' => $breadcrumbs]);

$registrationElement = $data['registrationElement'];
$vinElement = $data['vinElement'];
$submitElement = $data['submitElement'];
$searchType = $data['searchType'];

$userSearchParams = ['searchVrm' => $registrationElement->getValue(), 'searchVin' => $vinElement->getValue()];

$noMatches = isset($noMatches) ? $noMatches : false;
$showCreateButton = isset($showCreateButton) ? $showCreateButton : false;
$results = isset($results) ? $results : null;
$tooManyMatches = isset($tooManyMatches) ? $tooManyMatches : null;
//FIXME : Update the callers for this partial to pass in the variable
$registrationNumberMaxLength = isset($registrationNumberMaxLength) ? $registrationNumberMaxLength : 13;
$hideIncognitoVehicles = isset($hideIncognitoVehicles) ? $hideIncognitoVehicles : true;

//  --  html form begin --
$this->form->setAttribute("method", "get");
echo $this->form()->openTag($this->form);

if ($this->form->has('contingency')) {
    echo $this->formInput($this->form->get('contingency'));
}
?>

<?php if ($searchResultMessage): ?>
    <h2 id="main-message" class="result__group-heading"><?php echo $searchResultMessage->getMainMessage(); ?></h2>
    <?php if ($noMatches): ?>
        <div class="text">
            <p>
                <?php echo $searchResultMessage->getAdditionalMessage(); ?>
            </p>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="text">
        <p class="lede">Enter the registration mark and Vehicle Identification Number (VIN) to search for a vehicle.</p>
    </div>
<?php endif; ?>

<?php if ($results): ?>
    <table id="results-table" class="result-table">
        <thead>
        <tr>
            <th scope="col">Vehicle</th>
            <th scope="col">Registration mark</th>
            <th scope="col">VIN</th>
            <th scope="col">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($results as $vehicle): ?>
            <tr>
                <td>
                    <?php
                    $url = $urlTemplate->getStartMotTestUrl($vehicle, $userSearchParams);
                    ?>
                    <strong>
                        <?php
                        echo ($vehicle->getMake() || $vehicle->getModel()) ?
                            $this->escapeHtml($vehicle->getMakeAndModel()) : 'N/A';
                        ?>
                    </strong>
                    <br/>
                    <?php echo $this->escapeHtml($vehicle->getModelDetail()); ?>
                    <span class="result-table__meta">
                        <?php if ((!$vehicle->isIncognito() || ($vehicle->isIncognito() && !$hideIncognitoVehicles))): ?>
                            <?php if ($vehicle->hasMotTests()): ?>
                                <?php echo $this->escapeHtml($vehicle->getMotTestCount()); ?> test<?php if ($vehicle->getMotTestCount() > 1): ?>s<?php endif; ?>,
                                last tested
                                <?php echo $this->escapeHtml($vehicle->getReadableLastMotTestDate()); ?>
                            <?php else: ?>
                                No tests
                            <?php endif; ?>
                        <?php endif; ?>
                    </span>
                </td>
                <td class="tabular"><?php echo $this->escapeHtml($vehicle->getRegistrationNumber()); ?></td>
                <td class="tabular"><?php echo $this->escapeHtml($vehicle->getVin()); ?></td>
                <td class="tabular">
                    <a href="<?php echo $url ?>">
                        Select vehicle
                    </a>
                    <?php if ($vehicle->isRetest()): ?>
                        <br/>
                        <span id="vehicle-search-retest">For retest</span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php if ($results): ?>
    <details>
    <summary role="button" aria-controls="details-content-1" tabindex="0" aria-expanded="false"><span class="summary"
                                                                                                      id="search-again">Search again</span>
    </summary>
    <div class="panel-indent" id="details-content-1" aria-hidden="true">
<?php endif; ?>

    <fieldset>
        <div class="form-group" id="registration-field">
            <label id="reg-label" for="reg-input" class="form-label">
                Registration mark
            </label>
            <?php
            $registrationElement->setAttribute('class', 'form-control is-reg');
            $registrationElement->setAttribute('id', 'reg-input');
            $registrationElement->setAttribute(
                'style',
                'width: ' . (VehicleSearchController::SEARCH_VIN_NUMBER_MAX_LENGTH) . 'ch'
            );
            $registrationElement->setAttribute('maxLength', $registrationNumberMaxLength);
            echo $this->formInput($registrationElement);
            ?>
        </div>

        <div class="form-group <?php echo($vinElement->getMessages() ? 'has-error' : ''); ?>">
            <label id="vin-label" for="vin-input" class="form-label">
                VIN
                <span class="form-hint">Enter the last 6 digits or the full VIN</span>
            </label>
            <?php
            $vinElement->setAttribute('id', 'vin-input');
            $vinElement->setAttribute('class', 'form-control is-vin');
            $vinElement->setAttribute(
                'style',
                'width: ' . (VehicleSearchController::SEARCH_VIN_NUMBER_MAX_LENGTH * 1.5) . 'ch'
            );
            $vinElement->setAttribute('maxLength', VehicleSearchController::SEARCH_VIN_NUMBER_MAX_LENGTH);
            echo $this->formInput($vinElement);
            ?>
        </div>

        <?php if (!$results): ?>
            <div class="form-group">
                <details>
                    <summary role="button" aria-controls="details-content-0" tabindex="0" aria-expanded="false"><span
                            class="summary">Can't provide the registration mark or VIN?</span></summary>
                    <div class="panel-indent" id="details-content-0" aria-hidden="true">
                        <div class="text">
                            <p>If a vehicle has a registration mark and VIN, you must enter both to find it.</p>

                            <p>However, you can look up vehicles that have just a VIN, or just a registration mark.</p>

                            <h4 class="heading-small">VIN is missing</h4>

                            <p>Search by entering the registration mark. You will see results where the vehicle has no VIN recorded.</p>

                            <h4 class="heading-small">Registration mark is missing</h4>

                            <p>Search by entering the VIN. You will see results where the vehicle has no registration mark recorded.</p>
                        </div>
                    </div>
                </details>
            </div>
        <?php endif; ?>

        <div class="form-group">
            <input type="submit" value="Search" class="button" id="vehicle-search">
        </div>
    </fieldset>

<?php if ($results): ?>
            </div>
        </div>
    </details>
<?php endif; ?>

<?php echo $this->form()->closeTag(); ?>

    <nav class="content-navigation">
        <ul class="content-navigation__secondary">
            <li>
                <a id="cancel_vehicle_search" href="<?php echo $this->url(\Dashboard\Controller\UserHomeController::ROUTE); ?>">Cancel and return home</a>
            </li>
        </ul>
    </nav>

<?php if ($showCreateButton): ?>
    <div class="message--important">
        <p id="new-vehicle-record-info">
            If you can't find a vehicle you can
            <a id="new-vehicle-record-link" href="<?php echo $this->url(
                'vehicle-step',
                [],
                ['query' => ['reg' => $registrationElement->getValue()]]
            ); ?>">create a new vehicle record</a>.
        </p>
        <p>Check that you have searched with the correct VIN and registration mark before you do this.</p>
    </div>
<?php endif; ?>