<?php
use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;

?>

<p class="lede">We'll use your security questions to identify you if you need to reset your password.</p>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $errorsSummary]); ?>

<form action="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->securityQuestionStepOne());?>"
      method="POST" autocomplete="off" novalidate="">
    <?php echo $this->csrfToken(); ?>

    <fieldset>
        <legend class="form-title heading-large" id="q-select-1">Choose a question</legend>

        <div class="form-group">
            <label class="form-label" for="question1">Select a question to answer</label>
            <select class=" form-control form-control-1-2" id="question1" name="question1">
                <?php
                foreach ($questions as $key => $value) {
                    $select = $question1 == $key? 'selected' : '';
                    ?>
                    <option <?php echo $select; ?> value="<?php echo $key; ?>">
                        <?php echo $value; ?></option>
                    <?php
                } ?>
            </select>
        </div>

        <div class="form-group<?php if ($answer1HasError) echo ' has-error' ?>">
            <label class="form-label" for="answer1">Your answer
                <?php
                if ($answer1HasError) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['answer1']]);
                }
                ?>
            </label> <input class=" form-control form-control-1-4"
                id="answer1" name="answer1" type="text" value="<?php echo $this->escapeHtmlAttr($answer1) ?>">
        </div>
    </fieldset>

    <nav class="content-navigation">

        <input type="submit" value="Continue" id="continue" class="button">

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->contactDetailsStep());?>"
                   id="back">Back</a>
            </li>
        </ul>

    </nav>
</form>