<?php
    /** @var \Vehicle\ViewModel\VehicleViewModel $viewModel */
    $this->headTitle('Vehicle Details');
    $this->layout()->setVariable('sidebar', $viewModel->getSidebar());
    $this->layout()->setVariable('breadcrumbs', $viewModel->getBreadcrumbs());
?>

<?php
    echo $this->partial('partial/gds/general/header', [
        'title' => $viewModel->getPageTitle(),
        'type' => $viewModel->getPageSecondaryTitle(),
        'tertiary' => $viewModel->getPageTertiaryTitle(),
    ]);

    echo $this->partial('partial/gds/general/system-message', [
        'messages' => $this->layout()->flashMessenger->getErrorMessages(),
        'type' => 'failure'
    ]);
?>

<h3 class="summary-heading">Vehicle specification</h3>
<?php
    echo $this->partial('partial/gds/gds-table/gds-summary-table', [
        'table' => $viewModel->getVehicleSpecificationGdsTable(),
    ]);
?>

<h3 class="summary-heading">Vehicle registration</h3>
<?php
    echo $this->partial('partial/gds/gds-table/gds-summary-table', [
        'table' => $viewModel->getVehicleRegistrationGdsTable(),
    ]);
?>
<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a href="<?php echo $viewModel->getBackUrl(); ?>"><?php echo $viewModel->getBackLinkText(); ?></a>
        </li>
    </ul>
</nav>
