<?php
    /** @var \Vehicle\ViewModel\VehicleViewModel $viewModel */
    $this->headTitle('Vehicle Details');
    $this->layout()->setVariable('sidebar', $viewModel->getSidebar());
    $this->layout()->setVariable('breadcrumbs', $viewModel->getBreadcrumbs());
?>

<?php
    echo $this->partial('partial/gds/general/header', [
        'title' => $viewModel->getPageTitle(),
        'type' => $viewModel->getPageSecondaryTitle(),
        'tertiary' => $viewModel->getPageTertiaryTitle(),
    ]);

    echo $this->partial('partial/gds/general/system-message', [
        'messages' => $this->layout()->flashMessenger->getErrorMessages(),
        'type' => 'failure'
    ]);
    echo $this->partial('partial/gds/general/system-message', [
        'messages' => $this->layout()->flashMessenger->getSuccessMessages(),
        'type' => 'success'
    ]);
?>

<?php if ($viewModel->shouldDisplayVehicleMaskedBanner()): ?>
<div class="entity-status">
    <h3 class="entity-status__title bold-xlarge">Vehicle masked</h3>
    <p>An MOT tester will see a false expiry date of tomorrow's date. This will update every day.</p>
    <p>Any tests done will not show on the vehicle's MOT history.</p>
    <a id="unmask-vehicle" class="button button--on-dark"
       href="<?php echo $this->url('vehicle/detail/unmask', ['id' => $viewModel->getObfuscatedVehicleId()]); ?>"
    >Unmask this vehicle</a>
</div>
<?php endif; ?>

<h3 class="summary-heading">Vehicle specification</h3>
<?php
    echo $this->partial('partial/gds/gds-table/gds-summary-table', [
        'table' => $viewModel->getVehicleSpecificationGdsTable(),
    ]);
?>

<h3 class="summary-heading">Vehicle registration</h3>
<?php
    echo $this->partial('partial/gds/gds-table/gds-summary-table', [
        'table' => $viewModel->getVehicleRegistrationGdsTable(),
    ]);
?>
<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a href="<?php echo $viewModel->getBackUrl(); ?>"><?php echo $viewModel->getBackLinkText(); ?></a>
        </li>
    </ul>
</nav>
