<?php

use DvsaCommon\Date\DateTimeDisplayFormat;
use DvsaCommon\Utility\ArrayUtils;
use Vehicle\Controller\VehicleController;

$title = 'Vehicle Details';
$this->headTitle($title);

echo $this->partial('partials/enforcement/title', array('title' => $title));

/** @var DvsaCommon\Dto\Vehicle\VehicleDto $vehicle */
$vehicle = $this->vehicle;
$vehicleId = $vehicle->getId();

echo $this->partial('infoMessages', ['getFromFlash' => true]);
echo $this->partial('errorMessages', array('getFromFlash' => true, 'isShowHidden' => true));

?>

<div class="row content">
    <div class="col-lg-12">

        <div class="row vehicle-summary">
            <div class="col-sm-4">
                <?php
                //  --  col 1   --
                echo $this->partial(
                    'dldtdd', [
                        'dlCssClass' => 'vertical dl-large',
                        'items'      => [
                            ['Registration number', $vehicle->getRegistration(), 'id' => 'regNr'],
                            ['VIN/Chassis number', $vehicle->getVin(), 'id' => 'vin'],
                        ],
                    ]
                );
                ?>
            </div>

            <div class="col-sm-4">
                <?php
                //  --  col 2   --
                echo $this->partial(
                    'dldtdd', [
                        'dlCssClass' => 'vertical',
                        'items'      => [
                            ['Make', $vehicle->getMakeName(), 'id' => 'make'],
                            ['Model', $vehicle->getModelName(), 'id' => 'model'],
                            ['Body Type', $vehicle->getBodyType()->getName(), 'id' => 'bodyType'],
                        ],
                    ]
                );
                ?>
            </div>

            <div class="col-sm-4">
                <?php
                //  --  col 3   --
                echo $this->partial(
                    'dldtdd', [
                        'dlCssClass' => 'vertical',
                        'items'      => [
                            ['Fuel type', $vehicle->getFuelType()->getName(), 'id' => 'fuel'],
                            ['Transmission type', $vehicle->getTransmissionType()->getName(), 'id' => 'transmission'],
                            ['Cylinder capacity', $vehicle->getCylinderCapacity(), 'id' => 'cylinder'],
                            ['Colour', $vehicle->getColoursNames(), 'id' => 'color'],
                        ],
                    ]
                );
                ?>
            </div>
        </div>

        <hr class="hr-thin">

        <div class="row vehicle-summary">
            <div class="col-sm-4">
                <?php
                //  --  col 1   --
                echo $this->partial(
                    'dldtdd', [
                        'dlCssClass' => 'vertical',
                        'items'      => [
                            [
                                'Details created',
                                DateTimeDisplayFormat::textDate($vehicle->getAmendedOn()) ?: null,
                                'id' => 'created',
                            ],
                            [
                                'Declared new',
                                $vehicle->isNewAtFirstReg() ? 'Yes' : 'No',
                                'id' => 'declaredNew',
                            ],
                            [
                                'MOT test history',
                                //  url should not be escaped, because it already escaped in controller
                                '<a href="' . ArrayUtils::tryGet($this->urls, 'history', '') . '">' .
                                    'View' .
                                '</a>',
                                'id'     => 'historyLink',
                                'escape' => false,
                            ],
                        ],
                    ]
                );
                ?>
            </div>

            <div class="col-sm-4">
                <?php
                //  --  col 2   --
                echo $this->partial(
                    'dldtdd', [
                        'dlCssClass' => 'vertical',
                        'items'      => [
                            [
                                'Manufacture date',
                                DateTimeDisplayFormat::textDate($vehicle->getManufactureDate()) ?: null,
                                'id' => 'dateOfMake'
                            ],
                            [
                                'First registration date',
                                DateTimeDisplayFormat::textDate($vehicle->getFirstRegistrationDate()) ?: null,
                                'id' => 'dateOfReg'
                            ],
                            [
                                'First use date',
                                DateTimeDisplayFormat::textDate($vehicle->getFirstUsedDate()) ?: null,
                                'id' => 'firstUseDate',
                            ],
                        ],
                    ]
                );
                ?>
            </div>

            <div class="col-sm-4">
                <?php
                //  --  col 3   --
                echo $this->partial(
                    'dldtdd', [
                        'dlCssClass' => 'vertical',
                        'items'      => [
                            ['No. of seats', $vehicle->getSeatingCapacity(), 'id' => 'noSeats'],
                            ['No. of seat belts', $vehicle->getNoOfSeatBelts(), 'id' => 'noSeatBelts'],
                            [
                                'Seat belt last checked',
                                DateTimeDisplayFormat::textDate($vehicle->getSeatBeltsLastChecked()) ?: null,
                                'id' => 'dateOfSeatBelt',
                            ],
                        ],
                    ]
                );
                ?>
            </div>
        </div>
    </div>
</div>

<hr class="hr-thin">

<div class="row form-group">
    <div class="col-lg-12 btn-bar">
        <a href="<?php echo $this->url(\Dashboard\Controller\UserHomeController::ROUTE); ?>"
           id="returnDashboard" class="btn btn-primary">
            Return to Homepage
        </a>
    </div>
</div>
<a href="<?php echo ArrayUtils::tryGet($this->urls, 'back', ''); ?>">
    Go back
</a>
