<?php
    // *** PLEASE ENSURE NO MORE THAN 72 CHARACTERS PER LINE
?>
<p>Dear <?php echo $this->escapeHtml($this->user->getFirstName()); ?></p>

<p>You requested to reset your MOT testing service password for <?php echo $this->escapeHtml($this->user->getUsername()); ?>.</p>

<p>Create a new password at:</p>

<?php echo $this->reminderLink; ?>

<p>If you didn’t ask to reset your password then contact the <?php echo $this->escapeHtml($this->contactLabel); ?> on <?php echo $this->escapeHtml($this->contactNumber); ?>.</p>

<p>Regards</p>

<p>DVSA (Driver and Vehicle Standards Agency)</p>