<?php
    // *** PLEASE ENSURE NO MORE THAN 72 CHARACTERS PER LINE
?>
Dear MOT Testing Service user

You recently contacted DVSA for a password reset for the MOT Testing
Service application.

Please copy and paste the link below into a web browser to reset your
password.

<?php echo $this->reminderLink; ?>


Once your password has been changed you will be able to sign into the MOT
Testing Service with your new password.

If you did not request this reminder then please contact <?php echo $this->escapeHtml($this->contactLabel); ?>
 immediately on <?php echo $this->escapeHtml($this->contactNumber); ?> quoting your username.
