<?php

use Application\Build\BuildConfig;
use Application\Controller\IndexController;
use Dashboard\Controller\UserHomeController;
use Dvsa\Mot\Frontend\AuthenticationModule\Controller\LogoutController;
use DvsaCommon\UrlBuilder\PersonUrlBuilderWeb;
use Core\Presenter\MastheadPresenter;

$mastheadPresenter = new MastheadPresenter;

if ($this->authorisationHelper()->hasRole(\DvsaCommon\Constants\Role::USER)) {
    /** @var $dashboard \Dashboard\Model\Dashboard */
    $dashboard = $this->dashboardDataProvider();
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php if (getenv('APPLICATION_ENV') != 'development'): ?>
    <script type="text/javascript"><?php echo $this->gtmDataLayer()->render(); ?></script>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-PS5VXQ');</script>
    <!-- End Google Tag Manager -->
    <?php endif; ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php echo $this->headTitle('MOT testing service', 'APPEND')->setSeparator(' - '); ?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="image/x-icon" rel="shortcut icon" href="/assets/images/favicon.ico">

    <?php

        echo $this->headLink()
            ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('css/font-awesome.min.css'))
            ->appendStylesheet($this->basePath('css/app.css'))
            ->appendStylesheet($this->basePath('css/refactor.css'));

    // Items must be pre-pended in reverse order so that, any items appended will get added
        // after our files. This guarantees all libraries to be enabled in all pages.
        echo $this->headScript()
            ->prependFile(
                $this->basePath('js/'.BuildConfig::getJavaScriptLessThanIe9Filename()),
                'text/javascript',
                ['conditional' => 'lt IE 9'])
            ->prependFile($this->basePath('js/'.BuildConfig::getJavaScriptEnforcementFilename()))
            ->prependFile($this->basePath('js/'.BuildConfig::getJavaScriptLibrariesFilename()))
        ;
    ?>

    <script type="text/javascript">
        var CSRF = {
            paramName : '<?php echo \Csrf\CsrfConstants::REQ_TOKEN ?>',
            token : '<?php echo $this->csrfToken(false) ?>'
        };
    </script>

</head>
<body>
<?php if (getenv('APPLICATION_ENV') != 'development'): ?>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PS5VXQ"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<?php endif; ?>

<?php echo $this->partial('partial/fragments/header-govuk',
    [
        'hideUserNav' => $this->hideUserNav,
        'isHomePage' => $this->isHomePage,
        'isYourProfile' => $this->isYourProfile
    ]); ?>

<div class="container">
    <div class="module-colour-flash">
    </div>
</div>
<div class="container">
     <p class="module-phase"><strong class="phase-name is-beta">BETA</strong>
         This is a new service - your
         <a id="feedback-link" target="_blank" href="<?php echo $this->escapeHtmlAttr($mastheadPresenter->getFeedbackUrl()) ?>">feedback</a>
         will help us to improve it.
     </p>
</div>
<?php
    if ($this->authorisationHelper()->hasRole(\DvsaCommon\Constants\Role::USER) && isset($this->home)) {
        echo $this->partial('primaryAction/' . $dashboard->getHero(), ['dashboard' => $dashboard]);
    }
?>
<div class="container page-content">

    <!-- Progress Tracker -->
    <?php if ($this->progressBar): ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="progress-tracker">
                    <ul class="list-unstyled">
                        <li class="done"><i class="fa fa-arrow-circle-right"></i>Step name</li>
                        <li class="active"><i class="fa fa-arrow-circle-right"></i>Step name</li>
                        <li><i class="fa fa-arrow-circle-right"></i>Step name</li>
                        <li><i class="fa fa-arrow-circle-right"></i>Step name</li>
                    </ul>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <!-- END -->

    <!-- Titles -->
    <?php if (isset($this->pageSubTitle) or (isset($this->pageTitle))): ?>
        <div class="row">
            <div class="col-lg-12">
                <h1>
                    <small><?php echo $this->escapeHtml($this->pageSubTitle); ?></small>
                    <?php echo $this->escapeHtml($this->pageTitle); ?>
                </h1>
                <hr class="hr-thick"/>
            </div>
        </div>
    <?php endif; ?>
    <!-- END -->

    <?php if (isset($applicationNavigator)) : ?>

        <div class="row">
            <?php echo $this->partial('applicationSteps', ['applicationNavigator' => $applicationNavigator]); ?>
            <div class="col-sm-8  col-sm-offset-1" id="content">
                <h1><?php echo $this->escapeHtml($title); ?></h1>
                <?php echo $this->content; //this is HTML page content! ?>
            </div>
        </div>

    <?php else : ?>
        <div class="row contents">
            <div class="col-lg-12">
                <?php echo $this->content; //this is HTML page content!?>
            </div>
        </div>
    <?php endif; ?>

</div>
<!-- /container -->
<footer id="footer" class="module-global-footer">
    <div class="container">
        <div class="row global-footer_links">
            <div class="col-md-8 col-sm-12">
                <div class="global-footer_resources">
                    <h2><?php echo $this->resourcesOnGovUkHelper()->getTitle(); ?></h2>
                    <nav class="global-footer_navigation-resources">
                        <ul class="list-unstyled">
                            <?php foreach ($this->resourcesOnGovUkHelper()->getDocuments() as $key => $resource) : ?>
                                <li>
                                    <a id="resources_<?php echo $key ?>" href="<?php echo $resource['url']; ?>">
                                        <?php echo $resource['name']; ?>
                                    </a>
                                    <?php echo $resource['help_text']; ?>
                                </li>
                            <?php endforeach?>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class=" col-md-4 col-sm-12">
                <div class="global-footer_resources">
                    <h2><?php echo $this->manualsHelper()->getTitle(); ?></h2>
                    <nav class="global-footer_navigation-resources">
                        <ul class="list-unstyled">
                            <?php foreach ($this->manualsHelper()->getDocuments() as $key => $resource) : ?>
                                <li>
                                    <a id="manuals_<?php echo $key ?>" href="<?php echo $resource['url']; ?>">
                                        <?php echo $resource['name']; ?>
                                    </a>
                                </li>
                            <?php endforeach?>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-md-12 col-sm-12">

                <hr class="global-footer_divider" />

            </div>

        </div>

        <div class="row">
            <div class="col-sm-9 global-footer_meta">
                <nav class="global-footer_navigation">
                    <ul>
                        <li><a href="https://www.gov.uk/help/cookies">Cookies</a></li>
                        <li>
                            Built by the Driver &amp; Vehicle Standards Agency
                            <?php
                            $releaseTagTemplate = '<span class="tt-hint">Release {release_tag_name}</span>';
                            echo $this->getReleaseTag()->renderReleaseTag($releaseTagTemplate);
                            ?>
                        </li>
                    </ul>
                </nav>
                <p class="global-footer_licence">
                    <a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2"
                       class="licence-logo">
                        Open Government Licence
                    </a>
                    All content is available under the
                    <a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2">
                        Open Government Licence v2.0
                    </a>, except where otherwise stated
                </p>
            </div>
            <div class="col-sm-3 global-footer_copyright">
                <a href="http://www.nationalarchives.gov.uk/information-management/our-services/crown-copyright.htm">
                    &copy; Crown copyright
                </a>
            </div>
        </div>
    </div>
</footer>
<?php echo $this->inlineScript(); ?>
<?php echo $this->partial('partial/fragments/google-analytics'); ?>
</body>
</html>
