<?php
    echo $this->form()->openTag($form);

    echo '<div class="module-results-search">';
// VM-8388 : CSRF token has been disabled as the current implementation does not support "GET" requests.
//    echo $this->csrfToken();
    echo $this->formRow($form->get('searchText'));
    echo '<p class="module-results-search___hint">Search by VTS number, name or postcode</p></div><!-- module-results-search -->';

    echo '<div class="module-filters">
            <h3 class="module-filters__header">Filter by</h3>';

    echo $this->partial(
        'dateRangeList',
        array(
            'dateRanges' => $dateRanges,
            'currentDateRange' => $currentDateRange,
            'currentParams' => $currentParams,
        )
    );

    echo $this->partial(
        'dateForm',
        array(
             'form' => $form,
             'currentParams' => $currentParams,
             'currentDateRange' => $currentDateRange,
             'legendFrom' => 'Start date',
             'legendTo' => 'End date',
        )
    );

    $this->form()->closeTag();

    echo '</div><!-- module-filters -->';
