<html>
    <head>
        <link href="<?php echo $escBase; ?>/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="<?php echo $escBase; ?>/css/style-guide.css" media="screen" rel="stylesheet" type="text/css">
        <link href="<?php echo $escBase; ?>/css/report.css" media="screen" rel="stylesheet" type="text/css">
    </head>
    <body>
        <?php
        if ($renderHeader) {
            ?>
        <header class="module-global-header">
            <div class="container" id="user-info">
                <a class="global-header_home-link" href="/"><img src="<?php echo $escBase; ?>/img/logo_mot2.gif" alt="MOT"></a>
            </div>
            <div class="ph-colourflash">
                <div class="container">
                </div>
            </div>
        </header>
        <?php

        }
        echo $content; // escaped in controller
        ?>
    </body>
</html>