-- update history table
ALTER TABLE `dvla_vehicle_hist`
ADD COLUMN `vin_reversed` VARCHAR(20) DEFAULT NULL AFTER `vin`;

-- update triggers for dvla_vehicle_hist
DROP TRIGGER IF EXISTS `tr_dvla_vehicle_au`;
DROP TRIGGER IF EXISTS `tr_dvla_vehicle_ad`;

CREATE TRIGGER `tr_dvla_vehicle_au` AFTER UPDATE
ON `dvla_vehicle` FOR EACH ROW
INSERT INTO  `dvla_vehicle_hist` (`hist_transaction_type`, `hist_batch_number`, `id`,
`registration`,
`registration_collapsed`,
`registration_validation_character`,
`vin`,
`vin_reversed`,
`vin_collapsed`,
`vin_collapsed_reversed`,
`model_code`,
`make_code`,
`make_in_full`,
`colour_1_code`,
`colour_2_code`,
`propulsion_code`,
`designed_gross_weight`,
`unladen_weight`,
`engine_number`,
`engine_capacity`,
`seating_capacity`,
`manufacture_date`,
`first_registration_date`,
`is_seriously_damaged`,
`recent_v5_document_number`,
`is_vehicle_new_at_first_registration`,
`body_type_code`,
`wheelplan_code`,
`sva_emission_standard`,
`ct_related_mark`,
`vehicle_id`,
`dvla_vehicle_id`,
`eu_classification`,
`mass_in_service_weight`,
`mot1_legacy_id`,
`created_by`,
`created_on`,
`last_updated_by`,
`last_updated_on`,
`version`,
`batch_number`)
VALUES ('U', COALESCE(@batch_number, CASE WHEN NEW.BATCH_NUMBER<> OLD.BATCH_NUMBER THEN NEW.BATCH_NUMBER ELSE 0 END), OLD.`id`,
OLD.`registration`,
OLD.`registration_collapsed`,
OLD.`registration_validation_character`,
OLD.`vin`,
OLD.`vin_reversed`,
OLD.`vin_collapsed`,
OLD.`vin_collapsed_reversed`,
OLD.`model_code`,
OLD.`make_code`,
OLD.`make_in_full`,
OLD.`colour_1_code`,
OLD.`colour_2_code`,
OLD.`propulsion_code`,
OLD.`designed_gross_weight`,
OLD.`unladen_weight`,
OLD.`engine_number`,
OLD.`engine_capacity`,
OLD.`seating_capacity`,
OLD.`manufacture_date`,
OLD.`first_registration_date`,
OLD.`is_seriously_damaged`,
OLD.`recent_v5_document_number`,
OLD.`is_vehicle_new_at_first_registration`,
OLD.`body_type_code`,
OLD.`wheelplan_code`,
OLD.`sva_emission_standard`,
OLD.`ct_related_mark`,
OLD.`vehicle_id`,
OLD.`dvla_vehicle_id`,
OLD.`eu_classification`,
OLD.`mass_in_service_weight`,
OLD.`mot1_legacy_id`,
OLD.`created_by`,
OLD.`created_on`,
OLD.`last_updated_by`,
OLD.`last_updated_on`,
OLD.`version`,
OLD.`batch_number`);


CREATE TRIGGER `tr_dvla_vehicle_ad` AFTER DELETE
ON `dvla_vehicle` FOR EACH ROW
INSERT INTO  `dvla_vehicle_hist` (`hist_transaction_type`, `hist_batch_number`, `id`,
`registration`,
`registration_collapsed`,
`registration_validation_character`,
`vin`,
`vin_reversed`,
`vin_collapsed`,
`vin_collapsed_reversed`,
`model_code`,
`make_code`,
`make_in_full`,
`colour_1_code`,
`colour_2_code`,
`propulsion_code`,
`designed_gross_weight`,
`unladen_weight`,
`engine_number`,
`engine_capacity`,
`seating_capacity`,
`manufacture_date`,
`first_registration_date`,
`is_seriously_damaged`,
`recent_v5_document_number`,
`is_vehicle_new_at_first_registration`,
`body_type_code`,
`wheelplan_code`,
`sva_emission_standard`,
`ct_related_mark`,
`vehicle_id`,
`dvla_vehicle_id`,
`eu_classification`,
`mass_in_service_weight`,
`mot1_legacy_id`,
`created_by`,
`created_on`,
`last_updated_by`,
`last_updated_on`,
`version`,
`batch_number`)
VALUES ('D', COALESCE(@BATCH_NUMBER,0), OLD.`id`,
OLD.`registration`,
OLD.`registration_collapsed`,
OLD.`registration_validation_character`,
OLD.`vin`,
OLD.`vin_reversed`,
OLD.`vin_collapsed`,
OLD.`vin_collapsed_reversed`,
OLD.`model_code`,
OLD.`make_code`,
OLD.`make_in_full`,
OLD.`colour_1_code`,
OLD.`colour_2_code`,
OLD.`propulsion_code`,
OLD.`designed_gross_weight`,
OLD.`unladen_weight`,
OLD.`engine_number`,
OLD.`engine_capacity`,
OLD.`seating_capacity`,
OLD.`manufacture_date`,
OLD.`first_registration_date`,
OLD.`is_seriously_damaged`,
OLD.`recent_v5_document_number`,
OLD.`is_vehicle_new_at_first_registration`,
OLD.`body_type_code`,
OLD.`wheelplan_code`,
OLD.`sva_emission_standard`,
OLD.`ct_related_mark`,
OLD.`vehicle_id`,
OLD.`dvla_vehicle_id`,
OLD.`eu_classification`,
OLD.`mass_in_service_weight`,
OLD.`mot1_legacy_id`,
OLD.`created_by`,
OLD.`created_on`,
OLD.`last_updated_by`,
OLD.`last_updated_on`,
OLD.`version`,
OLD.`batch_number`);

