<?php

use Core\Routing\AeRoutes;
use Organisation\UpdateAeProperty\UpdateAePropertyReviewViewModel;

/*
 * @var UpdateAePropertyReviewViewModel $viewModel
 */
$this->headTitle('Review address');
?>
<?php echo $this->partial('errorMessages', array('getFromFlash' => true)); ?>
<?php
echo $this->partial(
    'partial/gds/gds-table/gds-key-value-table',
    [
        'table' => $viewModel->getSummary(),
    ]
);
?>

<form novalidate="" autocomplete="off" method="POST" action="<?php echo AeRoutes::of($this)->aeReviewEditProperty($viewModel->getAeId(), $viewModel->getPropertyName(), $viewModel->getFormUuid()); ?>">
    <?php echo $this->csrfToken(); ?>

    <nav class="content-navigation">
        <input type="submit" class="button" value="<?php echo $viewModel->getSubmitButtonText() ?>" id="submitUpdate">
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo AeRoutes::of($this)->aeEditProperty($viewModel->getAeId(), $viewModel->getPropertyName(), $viewModel->getFormUuid()); ?>">Back</a>
            </li>
        </ul>
    </nav>
</form>
