<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Vehicle\Controller\VehicleController'                 => __DIR__ . '/src/Vehicle/Controller/VehicleController.php',
  'Vehicle\Factory\Service\VehicleCatalogServiceFactory' => __DIR__ . '/src/Vehicle/Factory/Service/VehicleCatalogServiceFactory.php',
  'Vehicle\Factory\VehicleControllerFactory'             => __DIR__ . '/src/Vehicle/Factory/VehicleControllerFactory.php',
  // REMOVED INVALID MAP: 'VehicleController'                                    => __DIR__ . '/src/Vehicle/Factory/VehicleControllerFactory.php',
  'Vehicle\Helper\ColoursContainer'                      => __DIR__ . '/src/Vehicle/Helper/ColoursContainer.php',
  'Vehicle\Service\VehicleCatalogService'                => __DIR__ . '/src/Vehicle/Service/VehicleCatalogService.php',
  'Vehicle\Service\VehicleSearchService'                 => __DIR__ . '/src/Vehicle/Service/VehicleSearchService.php',
  'Vehicle\Traits\VehicleServicesTrait'                  => __DIR__ . '/src/Vehicle/Traits/VehicleServicesTrait.php',
);
