<?php
$cssDlClass = isset($cssDlClass) ? trim($cssDlClass) : 'col-sm-4';
$isReinspection = isset($isReinspection) ? (true === $isReinspection) : false;
$motTestNumber = isset($motTestNumber) ? $motTestNumber : '';
?>

<dl class="<?php echo $this->escapeHtmlAttr($cssDlClass); ?>">
    <?php
    if ($isReinspection) {
        $label = 'Reinspection test number';
    } else {
        $label = 'MOT test number';
    } ?>

    <dt><?php echo $this->escapeHtml($label); ?></dt>
    <dd id="motTestNumber"><?php echo $this->escapeHtml($motTestNumber); ?></dd>
</dl>
