<?php
use DvsaCommon\Date\DateTimeDisplayFormat;
use DvsaCommon\Enum\MotTestStatusName;
use DvsaMotTest\Adapter\MotTestServiceResponseAdapter;

/* @var \Dvsa\Mot\ApiClient\Resource\Item\MotTest $motTest */
$motTest;
if (empty($motTest)) {
    return;
}

$pendingDetails = [];

$testStatus = $motTest->getStatus();
$isTestPassOrFail = ($testStatus == MotTestStatusName::PASSED || $testStatus == MotTestStatusName::FAILED);

if (!$isTestPassOrFail) {
    $pendingDetails = $motTest->getPendingDetails();
    $pendingStatus = $pendingDetails->getCurrentSubmissionStatus();
    $isTestReady = ($pendingStatus == MotTestStatusName::PASSED || $pendingStatus == MotTestStatusName::FAILED);
}

$cssDlClass = !empty(trim($this->cssDlClass)) ? $this->cssDlClass : 'col-sm-4';
?>

<dl class="<?php echo $this->escapeHtmlAttr($cssDlClass); ?>">
    <dt>Issue date</dt>
    <dd id="issueDate">
        <?php
        $issuedDate = null;

        $responseAdapter = new MotTestServiceResponseAdapter($motTest);
        $responseAdaptedIssueDate = $responseAdapter->getIssuedDate();

        if ($isTestPassOrFail && $val = $responseAdaptedIssueDate) {
            $issuedDate = $val;
        } elseif ($isTestReady && $val = $pendingDetails->getIssuedDate()) {
            $issuedDate = $val;
        }

        echo $this->escapeHtml(
            $issuedDate
            ? DateTimeDisplayFormat::textDate($issuedDate)
            : 'N/A'
        );
        ?>
    </dd>
</dl>