<?php
/** @var \DvsaCommon\Dto\Site\VehicleTestingStationDto $site */
use Core\Formatting\AddressFormatter;

$site = $this->siteData ? $this->siteData : null;

if (empty($site)) {
    return;
}

if($site instanceof \DvsaCommon\Dto\Site\VehicleTestingStationDto) {
    $siteNr = $site->getSiteNumber();
    $siteName = $site->getName();
    $tempContact = null;

    foreach($site->getContacts() as $contactDto){
        $tempContact = $contactDto;
    }

    $siteAddress = (new AddressFormatter())->escapedDtoToMultiLine($tempContact->getAddress(), true);
} else {
    $siteNr = !empty($site['siteNumber']) ? $site['siteNumber'] : '';
    $siteName = ($siteNr ? ' - ' : '') . (!empty($site['name']) ? $site['name'] : '');
    $siteAddress = !empty($site['address']) ? $site['address'] : '';
}

$cssDlClass = !empty(trim($this->cssDlClass)) ? $this->cssDlClass : 'col-sm-4';
?>

<dl class="<?php echo $this->escapeHtmlAttr($cssDlClass); ?>">
    <dt>VTS name and address</dt>
    <dd id="vtsNameAndAddress">
        <?php echo $this->escapeHtml($siteNr . ' ' . $siteName); ?>
        <br/>
        <?php echo $siteAddress; ?>
    </dd>
</dl>