<?php

use Core\Formatting\AddressFormatter;
use Dvsa\Mot\ApiClient\Resource\Item\Site;

/* @var Site $siteData */
$siteData;

if (empty($siteData->getId())) {
    return;
}

if ($siteData instanceof \Dvsa\Mot\ApiClient\Resource\Item\Site) {
    $siteNr = $siteData->getNumber();
    $siteName = $siteData->getName();
    $siteAddress = '';
    if ($address = $siteData->getFirstAddress()) {
        $siteAddress = (new AddressFormatter())->escapeAddressToMultiLine(
            $address->getLine1(),
            $address->getLine2(),
            $address->getLine3(),
            $address->getLine4(),
            null,
            $address->getTown(),
            $address->getPostcode()
        );
    }
} elseif ($siteData instanceof \DvsaCommon\Dto\Site\VehicleTestingStationDto) {
    $siteNr = $siteData->getSiteNumber();
    $siteName = $siteData->getName();
    $tempContact = null;

    foreach ($siteData->getContacts() as $contactDto) {
        $tempContact = $contactDto;
    }

    $siteAddress = (new AddressFormatter())->escapedDtoToMultiLine($tempContact->getAddress(), true);
} else {
    $siteNr = !empty($siteData['siteNumber']) ? $siteData['siteNumber'] : '';
    $siteName = !empty($siteData['name']) ? $siteData['name'] : '';
    $siteAddress = !empty($siteData['address']) ? $siteData['address'] : '';
}

$cssDlClass = !empty(trim($this->cssDlClass)) ? $this->cssDlClass : 'col-sm-4';

$siteNameAndNumber = [];
if (!empty($siteNr)) {
    $siteNameAndNumber[] = $siteNr;
}
if (!empty($siteName)) {
    $siteNameAndNumber[] = $siteName;
}
$siteNameAndNumber = implode(' - ', $siteNameAndNumber);
?>

<dl class="<?php echo $this->escapeHtmlAttr($cssDlClass); ?>">
    <dt>VTS name and address</dt>
    <dd id="vtsNameAndAddress">
        <?php echo $this->escapeHtml($siteNameAndNumber); ?>
        <br/>
        <?php echo $siteAddress; ?>
    </dd>
</dl>