<?php
$site = $this->siteData ? $this->siteData : null;

if (empty($site)) {
    return;
}

$siteNr = !empty($site['siteNumber']) ? $site['siteNumber'] : '';
$siteName = ($siteNr ? ' - ' : '') . (!empty($site['name']) ? $site['name'] : '');
$siteAddress = !empty($site['address']) ? $site['address'] : '';

$cssDlClass = !empty(trim($this->cssDlClass)) ? $this->cssDlClass : 'col-sm-4';
?>

<dl class="<?php echo $this->escapeHtmlAttr($cssDlClass); ?>">
    <dt>VTS name and address</dt>
    <dd id="vtsNameAndAddress">
        <?php echo $this->escapeHtml($siteNr . $siteName); ?>
        <br/>
        <?php echo $this->escapeHtml($siteAddress); ?>
    </dd>
</dl>