<?php
use DvsaCommon\Enum\MotTestStatusCode;
use DvsaCommon\Enum\MotTestStatusName;
use DvsaCommon\Utility\ArrayUtils;

/** @var \Dvsa\Mot\ApiClient\Resource\Item\MotTest $motTest */
$motTest;

/** @var \DvsaMotTest\Controller\DvsaVehicleViewModel $vehicle */
$vehicle;

/** @var \DvsaCommon\Dto\Site\SiteDto $siteDto */
$siteDto;

/** @var string $motTestType */
$motTestType = $motTest->getTestTypeCode();
$reasonsForRejection = $motTest->getReasonsForRejection();
$fails = $motTest->getReasonsForRejection()->FAIL;
$prses = $motTest->getReasonsForRejection()->PRS;
$advisories = $motTest->getReasonsForRejection()->ADVISORY;

$pendingStatus = null;

$isTestActive = ($motTest->getStatus() == MotTestStatusName::ACTIVE);

if($isTestActive) {
    $pendingDetails = $motTest->getPendingDetails();
    $pendingStatus = $pendingDetails->getCurrentSubmissionStatus();
    $isTestReady = ($pendingStatus != 'INCOMPLETE');
}

$isTestReadyToPass = ($pendingStatus == MotTestStatusName::PASSED);
$isTestReadyToFail = ($pendingStatus == MotTestStatusName::FAILED);

$testStatus = $motTest->getStatus();
$isTestPass = ($testStatus == MotTestStatusCode::PASSED);
$isTestFail = ($testStatus == MotTestStatusCode::FAILED);

$isReinspection = \DvsaCommon\Domain\MotTestType::isReinspection($motTestType);

if($vehicle->getVehicleClass()->getCode() >= 3) {
    $brakeResultObject = new \Dvsa\Mot\ApiClient\Resource\Item\BrakeTestResultClass3AndAbove($motTest->getBrakeTestResult());
} else {
    $brakeResultObject = new \Dvsa\Mot\ApiClient\Resource\Item\BrakeTestResultClass1And2($motTest->getBrakeTestResult());
}
?>

<div class="row" id="testInformation">
    <?php
    echo $this->partial(
        'partials/mot-test-summary/test-status',
        ['status' => $pendingStatus ? $pendingStatus : $testStatus]
    );
    ?>

    <div class="col-sm-8">
        <div class="row">
            <?php
            echo $this->partial(
                'partials/mot-test-summary/field-mot-test-number',
                [
                    'cssDlClass'      => 'col-sm-6 no-bot-marg',
                    'isReinspection'  => $isReinspection,
                    'motTestNumber'   => $motTest->getMotTestNumber(),
                ]
            );

            echo $this->partial(
                'partials/mot-test-summary/site-address',
                [
                    'cssDlClass' => 'col-sm-6 no-bot-marg',
                    'siteData'   => $siteDto,
                ]
            );
            ?>
        </div>

        <div class="row">
            <?php
            echo $this->partial(
                'partials/mot-test-summary/field-issued-date.phtml',
                [
                    'cssDlClass' => 'col-sm-6',
                    'motTest'    => $motTest,
                ]
            );

            echo $this->partial(
                'partials/mot-test-summary/field-expiry-date.phtml',
                [
                    'cssDlClass' => 'col-sm-6',
                    'motTest' => $motTest,
                    'expiryDate'    => $this->expiryDate,
                ]
            );
            ?>
        </div>
    </div>
    <span class="divider"></span>
</div>


<?php
echo $this->partial(
    'partials/mot-test-summary/vehicle-block', [
        'motTest' => $motTest,
        'vehicle' => $vehicle,
    ]
);

echo $this->partial('partials/mot-test-summary/odometer-reading-row', ['reading' => $this->odometerReading]);

//  --  brakes  --
echo $this->partial(
    'partials/mot-test-summary/brake-result-overall-block', [
        'motTest' => $motTest,
    ]
);

if (isset($isReinspection) && $isReinspection && $motTest->getBrakeTestResult() !== null) {
    echo $this->partial(
        'partials/mot-test-summary/brake-values-in-kg-block', [
            'vehicle'           => $vehicle,
            'brakeResult'       => $brakeResultObject,
            'isEnforcementUser' => false,
            'brakeTestTypeCode2Name' => $brakeTestTypeCode2Name,
        ]
    );
}

//  --  failures    --
echo $this->partial(
    'partials/mot-test-summary/rfr-block', [
        'id'    => 'fails',
        'title' => 'Fails',
        'items' => $fails,
    ]
);

echo $this->partial(
    'partials/mot-test-summary/rfr-block', [
        'id'    => 'prses',
        'title' => 'PRS',
        'items' => $prses,
    ]
);

echo $this->partial(
    'partials/mot-test-summary/rfr-block', [
        'id'    => 'advisoryText',
        'title' => 'Advisory text',
        'items' => $advisories,
    ]
);
?>
