<?php

use DvsaCommon\Date\DateTimeDisplayFormat;

/** @var \DvsaMotTest\Controller\DvsaVehicleViewModel $vehicle */
$vehicle;

?>

<div class="row vehicle-summary" id="vehicleSummary">
    <div class="col-sm-4">
        <h2>Vehicle summary</h2>
    </div>

    <div class="col-sm-4">
        <?php echo $this->partial(
            'dldtdd', [
                'cssClass' => 'dl-standard',
                'items'    => [
                    [
                        'label' => 'Registration number',
                        'value' => $vehicle->getRegistration(),
                        'id'    => 'registrationNumber',
                    ],
                    ['VIN/Chassis number', $vehicle->getVin(), 'id' => 'vinChassisNumber'],
                    ['Test class', $vehicle->getVehicleClass()->getName(), 'id' => 'testClass'],
                    [
                        'label' => 'Approximate first use',
                        'value' => !empty($vehicle->getFirstUsedDate())
                            ? DateTimeDisplayFormat::textDate($vehicle->getFirstUsedDate())
                            : null,
                        'id'    => 'aproxFirstUse',
                    ],
                ],
            ]
        );
        ?>
    </div>

    <div class="col-sm-4">
        <?php

        /** @var \Dvsa\Mot\ApiClient\Resource\Item\Colour $primaryColour */
        $primaryColour = $vehicle->getColour();
        $colour = $primaryColour->getName();

        /** @var \Dvsa\Mot\ApiClient\Resource\Item\Colour $primaryColour */
        $secondaryColour = $vehicle->getColourSecondary();
        $secondaryColourName = $secondaryColour ? $secondaryColour->getName() : NULL;

        /** @var \Dvsa\Mot\ApiClient\Resource\Item\Make $make */
        $make = $vehicle->getMake()->getName();

        /** @var \Dvsa\Mot\ApiClient\Resource\Item\Model $make */
        $model = $vehicle->getModel()->getName();

        /** @var \Dvsa\Mot\ApiClient\Resource\Item\FuelType $fuelType */
        $fuelType = $vehicle->getFuelType()->getName();

        echo $this->partial(
            'dldtdd', [
                'cssClass' => 'dl-standard',
                'items'    => [
                    ['Make', $make ? $make : '', 'id' => 'make'],
                    ['Model', $model, 'id' => 'model'],
                    ['Colour', $colour, 'id' => 'colour'],
                    [
                        'label' => 'Fuel type',
                        'value' => $fuelType,
                        'id'    => 'fuel-type',
                    ],
                ],
            ]
        );
        ?>
    </div>
    <span class="divider"></span>
</div>
