<?php
use DvsaCommon\Utility\ArrayUtils;
?>

<div class="container">
    <header class="content-header">
        <h1>
            <span class="content-header__type">MOT testing</span>
            <span class="content-header__title">Email certificate</span>
        </h1>
    </header>
    <p class="lede">
        You are about to email the certificate for the vehicle <strong><?php echo $this->escapeHtml($recentCertificateDto->getMake()) ?> <?php echo $this->escapeHtml($recentCertificateDto->getModel()) ?></strong> <br/>
        <strong><?php echo $this->escapeHtml($recentCertificateDto->getModel()) ?></strong> with registration mark <strong><?php echo $this->escapeHtml($recentCertificateDto->getRegistration()) ?></strong> to the customer.
    </p>
    <p class="lede"> <strong>Customer details</strong></p>

    <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->csrfToken() ?>

        <?php if($this->form->getMessages()): ?>
            <div class="validation-summary" id="validation-summary-id">
                <h2>There was a problem with the information you entered:</h2>
                <ol>
                    <?php foreach($form->getMessages() as $fieldName => $fieldMessages): ?>
                        <?php foreach($fieldMessages as $message): ?>
                            <li><?php echo $this->escapeHtml($message); ?></li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        <?php endif; ?>

        <fieldset>
            <?php $element = $form->get("firstName"); ?>
            <div class="form-group<?php if($element->getMessages()): ?> has-error<?php endif; ?>" id="firstname-field">
                <label id="firstname-label" for="<?php echo $element->getAttribute("id") ?>" class="form-label">
                    First Name
                </label>
                <?php if($element->getMessages()): ?>
                    <span class="validation-message"><?php echo ArrayUtils::lastOrNull($element->getMessages()); ?></span>
                <?php endif; ?>
                <?php

                $element->setAttribute('class', 'form-control');
                $element->setAttribute(
                    'style',
                    'width: 24ch'
                );
                echo $this->formElement($element);
                ?>
            </div>

            <?php $element = $form->get("familyName"); ?>
            <div class="form-group<?php if($element->getMessages()): ?> has-error<?php endif; ?>" id="familyname-field">
                <label id="lastname-label" for="<?php echo $element->getAttribute("id") ?>" class="form-label">
                    Last name
                </label>
                <?php if($element->getMessages()): ?>
                    <span class="validation-message"><?php echo ArrayUtils::lastOrNull($element->getMessages()); ?></span>
                <?php endif; ?>
                <?php

                $element->setAttribute('class', 'form-control');
                $element->setAttribute(
                    'style',
                    'width:  24ch'
                );
                echo $this->formInput($element);
                ?>
            </div>

            <?php $element = $form->get("email"); ?>
            <div class="form-group<?php if($element->getMessages()): ?> has-error<?php endif; ?>" id="email-field">
                <label id="email-label" for="<?php echo $element->getAttribute("id") ?>" class="form-label">
                    Email address
                </label>
                <?php if($element->getMessages()): ?>
                    <span class="validation-message"><?php echo ArrayUtils::lastOrNull($element->getMessages()); ?></span>
                <?php endif; ?>
                <?php
                $element->setAttribute('class', 'form-control');
                $element->setAttribute(
                    'style',
                    'width:  24ch'
                );
                echo $this->formInput($element);
                ?>
            </div>

            <?php $element = $form->get("retypeEmail"); ?>
            <div class="form-group<?php if($element->getMessages()): ?> has-error<?php endif; ?>" id="retypeEmail-field">
                <label id="retypeEmail-label" for="<?php echo $element->getAttribute("id") ?>" class="form-label">
                    Retype email address (optional)
                </label>
                <?php if($element->getMessages()): ?>
                    <span class="validation-message"><?php echo ArrayUtils::lastOrNull($element->getMessages()); ?></span>
                <?php endif; ?>
                <?php
                $element->setAttribute('class', 'form-control');
                $element->setAttribute(
                    'style',
                    'width: 24ch'
                );
                echo $this->formInput($element);
                ?>
            </div>

            <div class="form-group">
                <input type="submit" value="Email certificate" class="button" id="email-certificate">
            </div>
        </fieldset>
    <?php echo $this->form()->closeTag(); ?>

    <?php echo $this->partial('partials/mot-certificate-navigation'); ?>

</div>
