<div class="container">
    <header class="content-header">
        <h1>
            <span class="content-header__type">MOT testing</span>
            <span class="content-header__title">Certificate sent</span>
        </h1>
    </header>
    <p class="lede">
        The certificate for the vehicle <strong><?php echo $this->escapeHtml($recentCertificateDto->getMake()) ?> <?php echo $this->escapeHtml($recentCertificateDto->getModel()) ?></strong> with registration <br/>
        mark <strong><?php echo $this->escapeHtml($recentCertificateDto->getRegistration()) ?></strong> has been emailed to <strong><?php echo $this->escapeHtml($recentCertificateDto->getRecipientEmailAddress()) ?></strong>.
    </p>

    <?php echo $this->partial('partials/mot-certificate-navigation',  ['vtsId' =>$recentCertificateDto->getVtsId()]) ; ?>

</div>