<div class="container">
    <header class="content-header">
        <h1>
            <span class="content-header__type">MOT testing</span>
            <span class="content-header__title">Unable to send certificate</span>
        </h1>
    </header>
    <p class="lede">
        We are currently experiencing problems with our email <br />
        system and can't send out certificates.
    </p>
    <p>
        If you need to email a certificate urgently you should download <br />
        the certificate and use your businesses email address to send it.
    </p>
    <p>
        Alternatively you can try and use the email service later.
    </p>

    <?php echo $this->partial('partials/mot-certificate-navigation'); ?>
</div>