Dear <?php echo $firstName . ',' . PHP_EOL?>

You have successfully created your MOT testing service account.

Your User ID is <?php echo $userName ?>

Your User ID is used to sign in to the service.

We recommend that you save this email in case you forget your User ID.
To sign in to the MOT testing service you will to use your User ID and the password you entered when you created your account.

Sign in to the MOT testing service using the following link <?php echo $signInUrl . PHP_EOL ?>

Driver and Vehicle Standards Agency
