<footer class="group js-footer" id="footer">
    <div class="footer-wrapper">

        <div class="footer-categories">
            <div class="footer-resources--two-thirds">
                <h2 class="footer-resources__header"><?php echo $this->resourcesOnGovUkHelper()->getTitle(); ?></h2>
                <ul>
                    <?php foreach ($this->resourcesOnGovUkHelper()->getDocuments() as $key => $resource) : ?>
                        <li>
                            <a id="resources_<?php echo $key ?>" href="<?php echo $resource['url']; ?>">
                                <?php echo $resource['name']; ?>
                            </a>
                            <?php echo $resource['help_text']; ?>
                        </li>
                    <?php endforeach?>
                </ul>
            </div>
            <div class="footer-resources--one-third">
                <h2 class="footer-resources__header"><?php echo $this->manualsHelper()->getTitle(); ?></h2>
                <ul>
                    <?php foreach ($this->manualsHelper()->getDocuments() as $key => $resource) : ?>
                        <li>
                            <a id="manuals_<?php echo $key ?>" href="<?php echo $resource['url']; ?>">
                                <?php echo $resource['name']; ?>
                            </a>
                        </li>
                    <?php endforeach?>
                </ul>
            </div>
            <hr>
        </div>

        <div class="footer-meta">
            <div class="footer-meta-inner">
                <h2 class="visuallyhidden">Support links</h2>
                <ul>
                    <li><a href="https://www.gov.uk/help/cookies">Cookies</a></li>
                    <li>
                        Built by the <a href="https://www.gov.uk/government/organisations/driver-and-vehicle-standards-agency">Driver &amp; Vehicle Standards Agency</a>
                        <?php if ($this->identity()):
                            $releaseTagTemplate = '<span class="tt-hint">Release {release_tag_name}</span>';
                            echo $this->getReleaseTag()->renderReleaseTag($releaseTagTemplate);
                        endif; ?>
                    </li>
                </ul>
                <div class="open-government-licence">
                    <p class="logo"><a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence</a></p>
                    <p>All content is available under the <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated</p>
                </div>
            </div>
            <div class="copyright">
                <a href="https://www.nationalarchives.gov.uk/information-management/our-services/crown-copyright.htm">© Crown copyright</a>
            </div>
        </div>
    </div>
</footer>
