<?php

use Core\Presenter\MastheadPresenter;

$mastheadPresenter = new MastheadPresenter();

?>

<div class="o-wrapper phase-banner">
    <p>
      <strong class="phase-tag">BETA</strong>
      <span>
          This is a new service – your
          <a id="feedback-link" target="_blank" href="<?php echo $this->escapeHtmlAttr($mastheadPresenter->getFeedbackUrl()) ?>">feedback</a>
          will help us to improve it.
      </span>
    </p>
</div>
