<?php
use Dashboard\Controller\UserHomeController;
use Dvsa\Mot\Frontend\AuthenticationModule\Controller\LogoutController;
use DvsaCommon\Constants\Role;
use DvsaCommon\UrlBuilder\PersonUrlBuilderWeb;

if ($this->authorisationHelper()->hasRole(Role::USER)):
?>
<ul class="header-user__menu">
    <li>
        <a href="<?php echo $this->url(UserHomeController::ROUTE); ?>"
           class="selected" id="homepage">
            Home
        </a>
    </li>
    <li>
        <a href="<?php echo $this->isFeatureEnabled('new_person_profile')
            ? $this->url('newProfile',
                [], []
            )
            : PersonUrlBuilderWeb::profile(); ?>" id="user-profile">Your profile</a>
    </li>
    <li>
        <a href="<?php echo $this->url(LogoutController::ROUTE_LOGOUT); ?>" id="logout">
            Sign out
        </a>
    </li>
</ul>
<?php endif;

