<?php
use DvsaCommon\UrlBuilder\UserAdminUrlBuilderWeb;

/**
 * @var \UserAdmin\ViewModel\SecurityQuestionViewModel  $viewModel
 * @var string $numberOfAttemptMessage
 * @var \Application\Helper\PrgHelper $prgHelper
 */

$question = $viewModel->getQuestion();
$questionNumber = $viewModel->getQuestionNumber();
$personId = $viewModel->getUserId();

$formAction         = UserAdminUrlBuilderWeb::userProfileSecurityQuestion($personId, $questionNumber)->toString();
$legendTitle        = 'Security question ' . ($questionNumber == 1 ? 'one' : 'two');
$labelText          = $question->getText();
$inputId            = 'question' . $questionNumber;
$inputName          = 'question' . $questionNumber;
$errorMessages      = $this->layout()->flashMessenger->getErrorMessages();
$successMessages    = $this->layout()->flashMessenger->getSuccessMessages();

echo $this->partial('partial/gds/general/system-message', ['messages' => $successMessages, 'type' => 'success']);
echo $this->partial('partial/gds/general/system-message', ['messages' => $errorMessages, 'type' => 'failure']);
?>

<form id="securityQuestionForm" action="<?php echo $this->escapeHtmlAttr($formAction); ?>" method="POST">
    <?php echo $this->csrfToken(); ?>
    <?php echo $prgHelper->getHtml(); ?>
    <fieldset>
        <?php
        echo $this->partial('partial/gds/form/control-legend', ['id' => 'legendQuestion', 'text' => $legendTitle]);

        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => $inputId,
                'name'          => $inputName,
                'errorMessage'  => $numberOfAttemptMessage,
                'label'         => $labelText,
                'value'         => '',
            ]
        );
        ?>
    </fieldset>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'            => 'submitSecurityQuestion',
            'value'         => 'Submit answer',
            'message'       => 'You can %sskip this question%s but it will be treated as an incorrect answer.',
            'linkMessage'   => $viewModel->getNextPageLink($this->layout()->flashMessenger),
            'navigation'    => [
                'Cancel and return to search results' => UserAdminUrlBuilderWeb::of()->userResults() . '?' . $viewModel->getSearchParams(),
            ]
        ]
    ); ?>
</form>

<script>
    document.onreadystatechange = function () {
        $('#securityQuestionForm').submit(function() {
            $('#submitSecurityQuestion').attr('disabled','disabled');
        });
    };
</script>
