<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
  'TestSupport\Module'                                   => __DIR__ . '/Module.php',
  'TestSupport\Service\AccountService'                   => __DIR__ . '/src/TestSupport/Service/AccountService.php',
  'TestSupport\Controller\AeDataController'              => __DIR__ . '/src/TestSupport/Controller/AeDataController.php',
  'TestSupport\Controller\AedDataController'             => __DIR__ . '/src/TestSupport/Controller/AedDataController.php',
  'TestSupport\Controller\AedmDataController'            => __DIR__ . '/src/TestSupport/Controller/AedmDataController.php',
  'TestSupport\Controller\AreaAdminDataController'       => __DIR__ . '/src/TestSupport/Controller/AreaAdminDataController.php',
  'TestSupport\Controller\AssessorDataController'        => __DIR__ . '/src/TestSupport/Controller/AssessorDataController.php',
  'TestSupport\Controller\CacheController'               => __DIR__ . '/src/TestSupport/Controller/CacheController.php',
  'TestSupport\Controller\ResetController'               => __DIR__ . '/src/TestSupport/Controller/ResetController.php',
  'TestSupport\Controller\RouteDumpController'           => __DIR__ . '/src/TestSupport/Controller/RouteDumpController.php',
  'TestSupport\Controller\SchemeMgtUserDataController'   => __DIR__ . '/src/TestSupport/Controller/SchemeMgtUserDataController.php',
  'TestSupport\Controller\SiteUserDataHelper'            => __DIR__ . '/src/TestSupport/Helper/SiteUserDataHelper.php',
  'TestSupport\Controller\SiteManagerDataController'     => __DIR__ . '/src/TestSupport/Controller/SiteManagerDataController.php',
  'TestSupport\Controller\SiteAdminDataController'       => __DIR__ . '/src/TestSupport/Controller/SiteAdminDataController.php',
  'TestSupport\Controller\TesterDataController'          => __DIR__ . '/src/TestSupport/Controller/TesterDataController.php',
  'TestSupport\Controller\UserDataController'            => __DIR__ . '/src/TestSupport/Controller/UserDataController.php',
  'TestSupport\Controller\VehicleExaminerDataController' => __DIR__ . '/src/TestSupport/Controller/VehicleExaminerDataController.php',
  'TestSupport\Controller\VtsDataController'             => __DIR__ . '/src/TestSupport/Controller/VtsDataController.php',
  'TestSupport\Helper\DataGenSupport'                    => __DIR__ . '/src/TestSupport/Helper/DataGenSupport.php',
  'TestSupport\TestIdentitySetter'                       => __DIR__ . '/src/TestSupport/TestIdentitySetter.php',
];
