<?php
//  --  init values and passed parameters   --
use DvsaCommon\Enum\MotTestTypeCode;
use DvsaCommon\Enum\ReasonForRejectionTypeName;
use DvsaCommon\UrlBuilder\MotTestUrlBuilderWeb;
use DvsaCommon\Utility\ArrayUtils;
use DvsaMotTest\Controller\AbstractDvsaMotTestController;

/** @var boolean  $isDemo */
/** @var \DvsaCommon\Dto\Common\MotTestDto $motTest */
$motTest = $this->motTest;
$motTestNumber = $motTest->getMotTestNumber();
/** @var \DvsaMotTest\Model\OdometerReadingViewObject $odometerReading */
$odometerReading = $this->odometerReading;
$submissionStatus = isset($motTest->getPendingDetails()['currentSubmissionStatus']) ? $motTest->getPendingDetails()['currentSubmissionStatus'] : null;
/** @var \DvsaCommon\Dto\Vehicle\VehicleDto $vehicle */
$vehicle = $motTest->getVehicle();
$brakeResult = $motTest->getBrakeTestResult();
/** @var \DvsaCommon\Dto\Common\MotTestTypeDto $testType */
$testType = $motTest->getTestType();
/** @var string $motTestType */
$motTestType = $testType->getCode();

$brakeTestRecorded = $brakeResult ? true : false;
if ($motTestType === MotTestTypeCode::RE_TEST && $brakeResult === null) {
    $brakeResult = $motTest->getMotTestOriginal()->getBrakeTestResult();
}
$pendingDetails = $motTest->getPendingDetails();
$testActive = isset($pendingDetails);

$rfrsGroupedByType = $motTest->getReasonsForRejection();
$rfrTypesCount = count($motTest->getReasonsForRejection());
$testerBrakePerformanceNotTested = $motTest->getTesterBrakePerformanceNotTested();

//  --  title and header    --
$testName = AbstractDvsaMotTestController::getTestName($motTestType);

$title = $testName;
$header = $testName . ' results entry';

$this->headTitle($title);
$this->layout()->setVariable('pageSubTitle', 'MOT testing');
$this->layout()->setVariable('pageTitle', $header);

//  --  js  --
$this->headScript()->appendFile('/js/dvsa-mot-test/index.js');

//  --  progress bar    --
$this->placeholder('progressBar')->captureStart();
echo $this->partial(
    'motTestProgress',
    [
        'currentStep' => 2,
        'motTestNumber' => $motTestNumber,
        'isMotContingency' => $this->isMotContingency
    ]
);
$this->placeholder('progressBar')->captureEnd();

//  --  error & msg panels    --
echo $this->partial('errorMessages', ['getFromFlash' => true]);
echo $this->partial('infoMessages', ['getFromFlash' => true]);
?>

<?php echo $this->partial('vehicleSummary', ['vehicle' => $vehicle]); ?>

    <div class="results-entry">
        <div class="row">
            <div class="results-entry-item clearfix">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-sm-6">
                            <h3>Odometer reading</h3>
                        </div>
                        <div id="odometerReading" class="col-sm-4">
                            <<?php echo $odometerReading->isNotRecorded() ? 'p' : 'h3'; ?> class="result-summary-info">
                            <?php echo $this->escapeHtml($odometerReading->getDisplayValue()) ?>
                        </<?php echo $odometerReading->isNotRecorded() ? 'p' : 'h3' ?>>

                        <?php if ($odometerReading->hasNotice()): ?>
                            <h6 id="odometerReadingNotice" style="white-space: nowrap; overflow:visible">
                                <?php echo $this->escapeHtml($odometerReading->getNotice()) ?>
                            </h6>
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div id="showHideOdometerResults" class="show-hide-container">
                <div class="row">
                    <div class="col-sm-8">
                        <form id="odometerResults" class="form-inline" action="<?php echo $this->url('mot-test/odometer-update', ['motTestNumber' => $motTestNumber]); ?>"
                              method="POST">
                            <?php echo $this->csrfToken() ?>
                            <fieldset>
                                <ul class="odometer-list">
                                    <li>
                                        <div class="radio">
                                            <label class="form-group" for="odometerValue">
                                                <input id="odometerValue" type="radio" name="resultType" class="radio"
                                                       value="OK" checked required="">
                                            </label>

                                            <div class="form-group">
                                                <label class="sr-only" for="odometer">Odometer</label>
                                                <input type="text" class="form-control" id="odometer" name="odometer"
                                                       value="<?php echo $this->escapeHtml(
                                                           $odometerReading->getValue()
                                                       ); ?>" maxlength="6">
                                            </div>
                                            <div class="form-group">
                                                <label class="sr-only" for="unit">Unit</label>
                                                <select class="form-control" id="unit" name="unit">
                                                    <option value="mi" <?php if (null === $odometerReading->getUnit() || $odometerReading->isInMiles()) :?>
                                                            selected
                                                    <?php endif; ?>>
                                                    Miles
                                                    </option>
                                                    <option value="km" <?php if ($odometerReading->isInKilometers()) :?>
                                                        selected
                                                    <?php endif; ?>>Kilometres
                                                    </option>
                                                </select>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="radio">
                                            <label for="notReadable">
                                                <input id="notReadable" type="radio" name="resultType" class="radio"
                                                       value="NOT_READ" required>
                                                Odometer is not readable
                                            </label>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="radio">
                                            <label for="noOdometer">
                                                <input id="noOdometer" type="radio" name="resultType" class="radio"
                                                       value="NO_METER" required>
                                                There is no odometer
                                            </label>
                                        </div>
                                    </li>
                                    <li>
                                        <input type="submit" id="odometer_submit" name="submit" value="Submit"
                                               class="btn btn-primary"/>
                                    </li>
                                </ul>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8"><span class="divider"></span></div>
    </div>

    <?php $isBrakePass = ArrayUtils::tryGet($brakeResult, 'generalPass'); ?>
    <div class="row">
        <div class="results-entry-item clearfix">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>Brake test results</h3>
                    </div>
                    <div id="brakeTestResultsNotice" class="col-sm-4">
                        <?php if ($brakeResult) : ?>
                            <h3 class=" <?php echo $isBrakePass ? 'pass' : 'fail'; ?> result-summary-info">
                                <?php
                                if ($brakeTestRecorded) {
                                    echo $isBrakePass ? 'Passed' : 'Failed';
                                } else {
                                    echo $isBrakePass ? 'Initial test passed' : 'Initial test failed';
                                }
                                ?>
                            </h3>
                            <?php if ($brakeTestRecorded || !$isBrakePass) : ?>
                                <a href="<?php echo $this->url('mot-test/brake-test-summary', ['motTestNumber' => $motTestNumber]); ?>"
                                   id="viewBrakeTestResults">View results</a>
                            <?php endif ; ?>
                        <?php elseif($testerBrakePerformanceNotTested) : ?>
                            <h3 class="fail">Not tested</h3>
                        <?php else : ?>
                            <p>Not recorded</p>
                        <?php endif; ?>
                    </div>
                    <div class="col-sm-2">
                        <?php if ($brakeTestRecorded || !$isBrakePass) : ?>
                            <a href="<?php echo $this->url(
                                'mot-test/brake-test-configuration', ['tis-id' => null, 'motTestNumber' => $motTestNumber]
                            ); ?>" class="btn btn-primary pull-right" id="addBrakeTestResults"
                                <?php echo ($testerBrakePerformanceNotTested ? ' disabled' : ''); ?>>
                                <span>
                                    <?php echo $brakeTestRecorded ? 'Edit' : 'Add'; ?>
                                    <span class="fa fa-chevron-right"></span>
                                </span>
                            </a>
                        <?php else : ?>
                            <a href="<?php echo $this->url('mot-test/brake-test-summary', ['motTestNumber' => $motTestNumber]); ?>"
                               class="btn btn-primary pull-right" id="addBrakeTestResults">
                                <span>
                                    View
                                    <span class="fa fa-chevron-right"></span>
                                </span>
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8"><span class="divider"></span></div>
    </div>
    <div class="row">
        <div class="results-entry-item clearfix">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-sm-8">
                        <h3>Failures, PRS and advisories</h3>
                    </div>
                    <div class="col-sm-4">
                        <a class="btn btn-primary pull-right" id="add_rfr_button"
                           href="<?php echo $this->url(
                               'mot-test/test-item-selector',
                               [
                                   'tis-id' => null,
                                   'motTestNumber' => $motTestNumber,
                               ]
                           ); ?>"><span>Add<span class="fa fa-chevron-right"></span></span></a>
                    </div>
                </div>
                <?php if ($rfrTypesCount): ?>
                    <div class="row">
                        <div class="col-sm-12">
                            There are
                            <?php echo $this->partial('rfrResults', ['reasonsForRejection' => $rfrsGroupedByType, 'motTestNumber' => $motTestNumber, 'testerBrakePerformanceNotTested' => $testerBrakePerformanceNotTested]); ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8"><span class="divider"></span></div>
    </div>
    </div>
    <div class="row">
        <div class="col-lg-12 btn-bar">
            <div class="form-group">
                <nav class="module-content-navigation">
                    <ul class="content-navigation_secondary">
                        <li>
                            <a id="createCertificate"
                               href="<?php echo MotTestUrlBuilderWeb::summary($motTestNumber); ?>"
                               class="btn btn-primary"
                               <?php if ($submissionStatus == "INCOMPLETE") : ?>disabled<?php endif; ?>
                                >Review test</a>
                        </li>
                        <?php if(false === $isDemo) : ?>
                        <li>
                            <a id="cancelMotTest" class="btn-link"
                               href="<?php echo MotTestUrlBuilderWeb::cancel($motTestNumber); ?>"
                                >Cancel test</a>
                        </li>
                        <?php endif ?>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

<script type="text/javascript">
    var MotTestIndex = {
        FAIL_REGEX: new RegExp("#<?php echo ReasonForRejectionTypeName::FAIL ?>"),
        ADVISORY_REGEX: new RegExp("#<?php echo ReasonForRejectionTypeName::ADVISORY ?>"),
        PRS_REGEX: new RegExp("#<?php echo ReasonForRejectionTypeName::PRS ?>"),

        IS_RETEST: !!"<?php echo $motTestType === MotTestTypeCode::RE_TEST ?>"
    };
</script>
