<?php
use Dashboard\Controller\UserHomeController;
use DvsaAuthentication\Controller\AuthenticationController;
/** @var \DvsaMotTest\Presenter\MotTestOptionsPresenter $presenter */
?>
<h2>MOT test successfully started</h2>
<p>You have successfully started an MOT test for a <strong><?php echo $this->escapeHtml($presenter->displayVehicleMakeAndModel()); ?></strong>, registration mark <strong><?php echo $this->escapeHtml($presenter->displayVehicleRegistrationNumber()); ?></strong></p>
<p>Test started <strong><?php echo $this->escapeHtml($presenter->displayMotTestStartedDate()); ?></strong></p>
<p>You should now sign out and inspect the vehicle</p>
<form action="<?php echo $this->url(AuthenticationController::ROUTE_LOGOUT); ?>" method="GET" role="form" novalidate>
    <div class="form-group">
        <?php echo $this->partial('partial/forms/submitElement.phtml', ['id' => 'sign-out', 'label' => 'Sign out']); ?>
    </div>
</form>
<nav class="module-content-navigation">
    <ul class="content-navigation_secondary">
        <li>
            <a href="<?php echo $this->url(UserHomeController::ROUTE); ?>" id="return_to_home">Return to home</a>
        </li>
    </ul>
</nav>
