<?php
use Dvsa\Mot\ApiClient\Resource\Item\MotTest;
use DvsaCommon\UrlBuilder\UrlBuilderWeb;
use DvsaMotTest\ViewModel\DvsaVehicleViewModel;

/**
 * @var MotTest
 * @var DvsaVehicleViewModel $vehicleViewModel
 * @var int                  $draftId
 * @var bool                 $isOriginalTester
 * @var bool                 $isAdmin
 * @var array                $differentTesterReasons
 */
$motTest = $this->motTest;
$vehicleViewModel = $this->vehicleViewModel;
$siteDto = $this->siteDto;
$draftId = $this->draftId;
$isOriginalTester = (bool) $this->isOriginalTester;
$isAdmin = (bool) $this->isAdmin;
$differentTesterReasons = $this->differentTesterReasons ?: [];

$title = 'Replacement certificate review';
$this->headTitle($title);

$this->headScript()->appendFile('/js/dvsa-mot-test/display-test-summary.js');

?>

<div class="row">
    <div class="col-lg-12">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>

<div class="row" id="content">
    <div class="col-lg-12 progress-tracker">
        <div>
            <a href="<?php echo $this->url('replacement-certificate-vehicle-search'); ?>" class="btn btn-primary"
               id="cancelMotTest">Cancel and return to vehicle</a>
        </div>
    </div>
</div>

<?php
echo $this->partial('infoMessages', ['getFromFlash' => true]);
echo $this->partial('errorMessages', ['getFromFlash' => true]);

if ($motTest instanceof MotTest) :
    echo $this->partial(
        'partials/mot-test-summary/test-summary',
        [
            'motTest' => $motTest,
            'siteDto' => $siteDto,
            'vehicle' => $vehicleViewModel,
            'odometerReading' => $odometerReading,
            'expiryDate' => $expiryDate,
        ]
    );
    ?>

    <form action="<?php echo UrlBuilderWeb::replacementCertificateSummary($draftId, $motTest->getMotTestNumber()); ?>" method="POST">
        <?php
        echo $this->csrfToken();
        echo $this->prgHelper->getHtml();

        if (!$isOriginalTester && !$isAdmin): ?>
            <div class="row">
                <div class="col-sm-12">
                    <p>Why was the original tester unable to update this document?</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <?php
                    echo $this->partial(
                        'selectElement',
                        [
                            'id' => 'reasonForDifferentTester',
                            'options' => $differentTesterReasons,
                            'required' => true,
                        ]
                    );
                    ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-sm-8">
                <?php
                echo $this->partial(
                    'otpInput',
                    [
                        'canTestWithoutOpt' => $this->canTestWithoutOtp(),
                        'errorMessage' => $this->otpErrorMessage,
                        'shortErrorMessage' => $this->otpErrorShortMessage,
                    ]
                );

                if ($this->canTestWithoutOtp()) {
                    echo $this->partial(
                        '2faDeclaration',
                        [
                            'declarationMessage' => 'By saving this replacement certificate you confirm that the changes you have made are in line with DVSA conditions for MOT testing.',
                        ]
                    );
                }
                ?>

                <nav class="module-content-navigation">
                    <input type="submit" class="button" value="Finish changes and print certificate"
                           id="confirm_and_print">
                </nav>
            </div>
        </div>
    </form>
<?php endif; ?>
