<?php $this->gtmDataLayer(['event' => 'user-locked-out']); ?>
<div class="text">

    <div class="banner--error">
        <span class="banner__heading-large"> Your account is locked </span>
        <span> You can try to sign in again after 30 minutes </span>
    </div>

    <p class="lede">
        You have tried to sign in too many times. Try again in 30 min or reset your password.
    </p>

    <nav class="content-navigation">
        <a href="<?php echo $this->url('forgotten-password') ?>" type="submit" class="button" name="reset_password"> Reset your password </a>
    </nav>

    <p>
        <a href="<?php echo $this->url($this->loginRoute); ?>">Return to sign in</a>
    </p>
</div>