<?php $this->gtmDataLayer(['event' => 'user-lockout-warning']); ?>
<div></div>
<div class="banner--error column-two-thirds">
    <span class="banner__heading-large">You have tried to sign in 4 times</span>
    <span>If you enter the wrong password one more time your account will be locked for 30 minutes</span>
</div>
<div class="text">

    <div class="row">
        <nav class="module-content-navigation">
            <a href="<?php echo $this->url('forgotten-password'); ?>" class="button" id="go-to-password-reset">
                Reset your password
            </a>
        </nav>
    </div>

    <p>
        <a href="<?php echo $this->url($this->loginRoute); ?>">Back to sign in</a>
    </p>

</div>
