<?php
use Vehicle\UpdateVehicleProperty\Form\ModelForm;
use Vehicle\UpdateVehicleProperty\ViewModel\UpdateVehiclePropertyViewModel;

/**
 * @var UpdateVehiclePropertyViewModel $viewModel
 */

/** @var ModelForm $form */
$form = $viewModel->getForm();
?>
<fieldset>
    <?php
        echo $this->partial(
            'partial/gds/form/control',
            [
                'element' => $form->getModelElement()
            ]
        );
    ?>

    <div id="<?php echo ModelForm::DATA_TARGET_ID ?>" class="panel-indent" aria-hidden="false">
        <label for="<?php echo $form->getOtherModelElement()->getAttribute("id") ?>" class="form-label">
            <?php echo ModelForm::FIELD_OTHER_MODEL_LABEL ?>
        </label>

        <?php echo $this->partial(
            'partial/gds/form/control',
            [
                'element' => $form->getOtherModelElement()
            ]
        );?>
    </div>
</fieldset>

<?php echo $this->headScript()->appendFile('/assets/javascripts/vendor/jquery-1.11.0.min.js'); ?>
<?php echo $this->headScript()->appendFile('/assets/javascripts/dvsa-2100.js'); ?>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        DVSASelectToggle.init();
    });
</script>