<?php
use Vehicle\UpdateVehicleProperty\Form\CountryOfRegistrationForm;
use Vehicle\UpdateVehicleProperty\ViewModel\UpdateVehiclePropertyViewModel;

/**
 * @var UpdateVehiclePropertyViewModel
 */

/** @var CountryOfRegistrationForm $form */
$form = $viewModel->getForm();
?>

<div class="text">
    <p class="lede">This should be the country where the car is registered, not the country of origin.</p>
</div>

<fieldset>
    <?php echo $this->partial(
        'partial/gds/form/control',
        [
            'element' => $form->getCountryOfRegistrationElement(),
        ]
    ); ?>
</fieldset>