<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MailerApi\Controller\MailerController'  => __DIR__ . '/src/MailerApi/Controller/MailerController.php',
  // REMOVED INVALID MAP: 'getServiceLocator'                      => __DIR__ . '/src/MailerApi/Controller/MailerController.php',
  // REMOVED INVALID MAP: 'true'                                   => __DIR__ . '/src/MailerApi/Controller/MailerController.php',
  'MailerApi\Factory\MailerServiceFactory' => __DIR__ . '/src/MailerApi/Factory/MailerServiceFactory.php',
  'MailerApi\Logic\ClaimAccountReminder'   => __DIR__ . '/src/MailerApi/Logic/ClaimAccountReminder.php',
  'MailerApi\Logic\PasswordReminder'       => __DIR__ . '/src/MailerApi/Logic/PasswordReminder.php',
  'MailerApi\Logic\Reminder'               => __DIR__ . '/src/MailerApi/Logic/Reminder.php',
  'MailerApi\Logic\UsernameReminder'       => __DIR__ . '/src/MailerApi/Logic/UsernameReminder.php',
  'MailerApi\Service\MailerService'        => __DIR__ . '/src/MailerApi/Service/MailerService.php',
  // REMOVED INVALID MAP: 'null'                                   => __DIR__ . '/src/MailerApi/Service/MailerService.php',
  'MailerApi\Validator\MailerValidator'    => __DIR__ . '/src/MailerApi/Validator/MailerValidator.php',
);
