<div class="column-two-thirds">
    <p class="lede" id="order-message">You need a security card to access the full MOT testing service and to make your account more secure.</p>
    <p>You can order a security card now or do it later from your profile.</p>
    <p>You must activate your card as soon as you have it.</p>
    <a class="button" href="<?php echo $this->url('security-card-order/new'); ?>">Order a security card</a>
    <p><a id="continue-to-home" href="<?php echo $this->url('user-home'); ?>">Continue to home</a></p>
</div>
