<div class="column-two-thirds">
    <p class="lede" id="activate-message">You can only access the full MOT testing service with an activated security card.</p>
    <h3 class="heading-small">Received your card?</h3>
    <p><a id="register-card-link" href="<?php echo $this->url('register-card')?>">Activate your security card</a>
    or do it later from your profile.</p>
    <h3 class="heading-small">Don't have your card yet?</h3>
    <p><a id="continue-to-home" href="<?php echo $this->url('user-home'); ?>">Continue to home</a>
    - you will be able to access a limited amount of the service.</p>
</div>
