<div class="column-two-thirds">
    <p class="lede">We’re making your account more secure with a new security card and PIN system.</p>
    <p>In the next couple of weeks you’ll receive a new security card to your work address. You’ll use the card whenever you sign in. </p>
    <p>Once you’ve received your card you must activate it, then you’ll use it whenever you sign in.</p>
    <p>You must activate your card as soon as you have it.</p>
    <h3 class="heading-small">Received your card?</h3>
    <p><a id="register-card-link" href="<?php echo $this->url('register-card')?>">Activate your security card now</a></p>
    <h3 class="heading-small">Don't have your card yet?</h3>
    <p><a id="continue-to-home" href="<?php echo $this->url('user-home'); ?>">Continue to home</a></p>
</div>