<?php

use Dvsa\Mot\Frontend\SecurityCardModule\CardActivation\ViewModel\RegisterCardViewModel;

/**
 * @var RegisterCardViewModel $viewModel
 */

$this->layout('layout/layout-govuk.phtml');
$this->layout()->setVariable('pageTitle', 'Activate your security card');
$this->headTitle('Activate your security card');

$gtmData = $viewModel->getGtmData();
if (!empty($gtmData)) {
    foreach ($gtmData as $gtmDatum) {
        $this->gtmDataLayer($gtmDatum);
    }
}

$gtmTitle = 'User - Activate Security Card';

if ($viewModel->isInvalidSerialNumber()) {
    $this->gtmDataLayer(['event' => 'activate-card-fail', 'reason' => 'invalid-serial-number', 'title' => $gtmTitle]);
}

if ($viewModel->isPinMismatch()) {
    $this->gtmDataLayer(['event' => 'activate-card-fail', 'reason' => 'wrong-serial-number-or-pin', 'title' => $gtmTitle]);
}

if ($viewModel->isCardAlreadyRegistered()) {
    $this->gtmDataLayer(['event' => 'activate-card-fail', 'reason' => 'already-activated-serial-number', 'title' => $gtmTitle]);
}

?>

<div class="grid-row">
    <div class="column-two-thirds">
        <p class="lede">Activate your new card using its serial number and a new PIN. This will take 2 minutes.</p>
        <p>
        </p>
        <details role="group">
            <summary role="button" aria-controls="details-content-0" aria-expanded="false" tabindex="0">
                <span class="summary">Where to find the serial number and PIN</span>
            </summary>
            <div class="panel panel-indent" id="details-content-0" aria-hidden="true">
                <p>The serial number is on the back of the card, in the upper right-hand corner.</p>
                <img src="/assets/images/register-new-card-serial.png" class="u-full-width" alt="The serial number is in the top-right corner on the back of the security card and has 12 or 16 digits">
                <p>Generate a new 6-digit PIN by pressing on the button on the front of the card. You can generate a new PIN every 30 seconds.</p>
                <img src="/assets/images/register-new-card-pin.png" class="u-full-width" alt="The PIN will show in the top-right corner of the security card and has 6 digits">
            </div>
        </details>
        <p></p>

        <div class="">
            <?php echo $this->partial('zendFormErrorMessages', ['form' => $viewModel->getForm()]); ?>
            <?php
            if ($viewModel->isPinMismatch() || $viewModel->isCardAlreadyRegistered()) :?>
                <div class="message--failure">
                    <p>The was a problem with your serial number or PIN.</p>

                    <p>Try the following. Check your serial number is correct. Generate and enter a new PIN.</p>
                </div>
            <?php endif; ?>

            <form action="<?php echo $this->url('register-card') ?>" method="POST" autocomplete="off">
                <?php echo $this->csrfToken(); ?>
                <fieldset>
                    <?php
                    echo $this->partial(
                        'partial/gds/form/control',
                        [
                            'element' => $viewModel->getForm()->getSerialNumberField()
                        ]
                    );
                    echo $this->partial(
                        'partial/gds/form/control',
                        [
                            'element' => $viewModel->getForm()->getPinField()
                        ]
                    );
                    ?>
                </fieldset>
                <nav class="content-navigation">
                    <input id="activate_cta" type="submit" value="Activate your security card" class="button">
                    <ul class="content-navigation__secondary">
                        <li><?php echo $this->partial($viewModel->getSkipCtaTemplate()); ?></li>
                    </ul>
                </nav>
            </form>
        </div>
    </div>
