<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'NonWorkingDaysApi\Constants\CountryCode'                      => __DIR__ . '/src/NonWorkingDaysApi/Constants/CountryCode.php',
  'NonWorkingDaysApi\Factory\NonWorkingDaysHelperFactory'        => __DIR__ . '/src/NonWorkingDaysApi/Factory/NonWorkingDaysHelperFactory.php',
  'NonWorkingDaysApi\Factory\NonWorkingDaysLookupManagerFactory' => __DIR__ . '/src/NonWorkingDaysApi/Factory/NonWorkingDaysLookupManagerFactory.php',
  'NonWorkingDaysApi\Factory\NonWorkingDaysProviderFactory'      => __DIR__ . '/src/NonWorkingDaysApi/Factory/NonWorkingDaysProviderFactory.php',
  // REMOVED INVALID MAP: 'HolidaysProvider'                                             => __DIR__ . '/src/NonWorkingDaysApi/Factory/NonWorkingDaysProviderFactory.php',
  'NonWorkingDaysApi\NonWorkingDaysHelper'                       => __DIR__ . '/src/NonWorkingDaysApi/NonWorkingDaysHelper.php',
  'NonWorkingDaysApi\NonWorkingDaysLookupManager'                => __DIR__ . '/src/NonWorkingDaysApi/NonWorkingDaysLookupManager.php',
  'NonWorkingDaysApi\Provider\HolidaysProvider'                  => __DIR__ . '/src/NonWorkingDaysApi/Provider/HolidaysProvider.php',
  'NonWorkingDaysApi\Provider\NonWorkingDaysProvider'            => __DIR__ . '/src/NonWorkingDaysApi/Provider/NonWorkingDaysProvider.php',
);
