<?php
use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;
?>

<div class="text">
    <p class="banner--error" id="failBanner">
        <span class="banner__heading-large">The service was not able to create your account at this time</span>
    </p>

    <h2 class="heading-medium">What happens next?</h2>

    <p>Please go back and try to
        <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->summaryStep());?>">create your account</a>
        again.
    </p>

    <h2 class="heading-small">If the problem persists</h2>
    <?php echo $this->partial('partial/gds/general/contactHelpdesk', ['config' => $this->helpdesk]) ?>
</div>

