<?php
    $emailAddress = isset($email) ? $email : 'undefined';
?>

<div class="text">
    <p id="successBanner" class="banner--confirmation">
        <span class="banner__heading-large">Now check your email</span>
        <span>Your User ID has been sent to
        <strong><?php echo $this->escapeHtmlAttr($emailAddress) ?></strong>
        </span>
    </p>

    <h2 class="heading-medium">What happens next?</h2>

    <p>Check your email for your new user ID</p>
    <p>You can now <a id="sign-in-link" href="<?php echo $this->url('login') ?>">sign in</a>
        to the MOT testing service using your user ID and password.</p>
    <h2 class="heading-small">If you haven't received an email</h2>
    <p>It can take 15 minutes to arrive. Check your spam folder if you still don't see it after this time.</p>

    <h2 class="heading-small">If you're still having problems</h2>
    <?php echo $this->partial('partial/gds/general/contactHelpdesk', ['config' => $this->helpdesk]) ?>
</div>