<?php
use Dashboard\Controller\NotificationController;
use Dashboard\Model\Notification;
use DvsaCommon\Date\DateTimeDisplayFormat;

/** @var Notification[] $notifications */
/** @var int $count */
$count = count($notifications);
/** @var int $unread */
/** @var int $limit */
$limit = 5;
?>

<section class="module-pivot-panel" id="notification-list">
    <header class="pivot-panel_header">
        <h2 class="pivot-panel_title">
            <?php if ($unread > $limit) : ?>
                <a id="action-view-all-notifications"
                   href="<?php echo $this->url(NotificationController::ROUTE_NOTIFICATION_LIST); ?>">
                    Notifications
                </a>
            <?php else: ?>
                Notifications    
            <?php endif; ?>
        </h2>
    </header>
    <?php if ($unread > 0) : ?>
        <a href="<?php echo $this->url(NotificationController::ROUTE_NOTIFICATION_LIST); ?>"
           class="mailbox-status" id="unread-notification-count">
            <span class="mega-number">
                <strong class="number"><?php echo intval($unread); ?></strong>
                <span class="super-text">unread</span>
            </span>
        </a>
    <?php else: ?>
        <span class="mega-number" id="unread-notification-count">
            <strong class="number"><?php echo intval($unread); ?></strong>
            <span class="super-text">unread</span>
        </span>
    <?php endif ?>

    <?php
    foreach ($notifications as $notification) :
        $escUrl = $this->url(NotificationController::ROUTE_NOTIFICATION, ['notificationId' => $notification->getId()], ["query" => ["backTo" => NotificationController::BACK_TO_HOME_PARAM]]);
        $date = DateTimeDisplayFormat::textDateTime($notification->getCreatedOn());
        $cssClass = (null === $notification->getReadOn()) ? "is-unread" : "is-read";
        if ($notification->isActionRequired()) {
            $cssClass .= ' is-nomination';
        }

        ?>
        <article id="notifications" class="module-notification <?php echo $this->escapeHtmlAttr($cssClass); ?>">
            <header>
                <p class="notification_subject">
                    <a href="<?php echo $escUrl; ?>" class="notification_link" title="<?php echo $this->escapeHtmlAttr($notification->getSubject()); ?>">
                        <?php echo $this->escapeHtml($notification->getSubject()); ?>
                    </a>
                </p>

                <p>
                    <time pubdate class="notification_time"><?php echo $this->escapeHtml($date); ?></time>
                </p>
            </header>
        </article>

        <?php endforeach; ?>
</section>
