<?php
use Dashboard\Controller\NotificationController;
use Dashboard\Controller\UserHomeController;
use DvsaCommon\Date\DateTimeDisplayFormat;

$notifications = (isset($notifications)) ? $notifications : [];
$limit = (isset($limit)) ? $limit : -1;
$unread = 0;
$count = 0;

foreach ($notifications as $notification) {
    if (null === $notification->getReadOn()) {
        $unread++;
    }
}
?>

<section class="module-pivot-panel" id="notification-list">

    <header class="pivot-panel_header">
        <h2 class="pivot-panel_title">
            <?php if ($limit > 0 && count($notifications) > $limit) : ?>
                <a id="action-view-all-notifications"
                   href="<?php echo $this->url(NotificationController::ROUTE_NOTIFICATION_LIST); ?>">
                    Notifications
                </a>
            <?php else: ?>
                Notifications    
            <?php endif; ?>
        </h2>
    </header>
    <?php if ($limit > 0 && count($notifications) > 0) : ?>
        <a href="<?php echo $this->url(NotificationController::ROUTE_NOTIFICATION_LIST); ?>"
           class="mailbox-status" id="unread-notification-count">
            <span class="mega-number">
                <strong class="number"><?php echo intval($unread); ?></strong>
                <span class="super-text">unread</span>
            </span>
        </a>
    <?php else: ?>
        <span class="mega-number" id="unread-notification-count">
            <strong class="number"><?php echo intval($unread); ?></strong>
            <span class="super-text">unread</span>
        </span>
    <?php endif ?>

    <?php
    /** @var $notification \Dashboard\Model\Notification */
    foreach ($notifications as $notification) :

        $escUrl = $this->url(NotificationController::ROUTE_NOTIFICATION, ['notificationId' => $notification->getId()]);
        $date = DateTimeDisplayFormat::textDateTime($notification->getCreatedOn());
        $cssclass = (null === $notification->getReadOn()) ? "is-unread" : "is-read";
        if ($notification->isActionRequired()) {
            $cssclass .= ' is-nomination';
        }

        ?>
        <article class="module-notification <?php echo $this->escapeHtmlAttr($cssclass); ?>">
            <header>
                <p class="notification_subject">
                    <a href="<?php echo $escUrl; ?>" class="notification_link" title="<?php echo $this->escapeHtmlAttr($notification->getSubject()); ?>">
                        <?php echo $this->escapeHtml($notification->getSubject()); ?>
                    </a>
                </p>

                <p>
                    <time pubdate class="notification_time"><?php echo $this->escapeHtml($date); ?></time>
                </p>
            </header>
        </article>

        <?php
        $count++;

        if ($limit === $count) {
            break;
        }

    endforeach;
    ?>

    <?php if ($limit === -1): ?>

        <!--   FULL VIEW    -->
        <footer>
            <a id="link-back-to-home" href="<?php echo $this->url(UserHomeController::ROUTE); ?>">
                Back to your home
            </a>
        </footer>

    <?php endif; ?>
</section>