<?php
/** @var AddressFormModel $form */
use DvsaClient\ViewModel\AddressFormModel;

$form = $this->form;
$group = $this->group ?: '';
$countryRadio = $this->countryRadio ?: '';

$tmplFieldName = (!empty($group) ? '%1$s[%2$s]' : '%2$s');
?>

<div class="panel-indent" id="<?php echo $this->escapeHtmlAttr($this->id); ?>">
    <?php
    echo $this->partial(
        'partial/gds/form/control-text-group',
        [
            'id'           => $group . AddressFormModel::FIELD_LINE1,
            'name'         => sprintf($tmplFieldName, $group, AddressFormModel::FIELD_LINE1),
            'errorMessage' => $form->getError(sprintf($tmplFieldName, $group, AddressFormModel::FIELD_LINE1)),
            'divModifier'  => 'form-group-compound',
            'label'        => 'Address line',
            'value'        => $form->getAddressLine1(),
            'maxLength'    => 50,
        ]
    );

    echo $this->partial(
        'partial/gds/form/control-text-group',
        [
            'id'           => $group . AddressFormModel::FIELD_LINE2,
            'name'         => sprintf($tmplFieldName, $group, AddressFormModel::FIELD_LINE2),
            'errorMessage' => $form->getError(sprintf($tmplFieldName, $group, AddressFormModel::FIELD_LINE2)),
            'divModifier'  => 'form-group-compound',
            'value'        => $form->getAddressLine2(),
            'maxLength'    => 50,
        ]
    );

    echo $this->partial(
        'partial/gds/form/control-text-group',
        [
            'id'           => $group . AddressFormModel::FIELD_LINE3,
            'name'         => sprintf($tmplFieldName, $group, AddressFormModel::FIELD_LINE3),
            'errorMessage' => $form->getError(sprintf($tmplFieldName, $group, AddressFormModel::FIELD_LINE3)),
            'divModifier'  => 'form-group-compound',
            'value'        => $form->getAddressLine3(),
            'maxLength'    => 50,
        ]
    );

    echo $this->partial(
        'partial/gds/form/control-text-group',
        [
            'id'           => $group . AddressFormModel::FIELD_TOWN,
            'name'         => sprintf($tmplFieldName, $group, AddressFormModel::FIELD_TOWN),
            'errorMessage' => $form->getError(sprintf($tmplFieldName, $group, AddressFormModel::FIELD_TOWN)),
            'divModifier'  => 'form-group-compound',
            'label'        => 'Town or city',
            'value'        => $form->getTown(),
            'maxLength'    => 50,
        ]
    );

    echo $this->partial(
        'partial/gds/form/control-text-group',
        [
            'id'            => $group . AddressFormModel::FIELD_POSTCODE,
            'name'          => sprintf($tmplFieldName, $group, AddressFormModel::FIELD_POSTCODE),
            'errorMessage'  => $form->getError(sprintf($tmplFieldName, $group, AddressFormModel::FIELD_POSTCODE)),
            'divModifier'   => 'form-group-compound',
            'inputModifier' => '1-8',
            'label'         => 'Postcode',
            'value'         => $form->getPostCode(),
            'maxLength'     => 10,
        ]
    );

    if (!empty($countryRadio)) {
        echo $this->partial(
            'partial/gds/form/control-radio-group',
            [
                'divModifier' => 'inline',
                'label' => 'Country',
                'options' => $countryRadio,
            ]
        );
    }
    ?>
</div>
