<?php
$id = $this->id;
$name = (!empty($this->name) ? $this->name : $id);
$label = $this->label ?: '';
$value = $this->value;
$type = (empty($this->type) ? 'text' : $this->type);
$help = $this->help;

$tabIndex  = $this->tabIndex;

$inputModifier  = isset($this->inputModifier) ? $this->inputModifier : '';
$divModifier    = isset($this->divModifier) ? $this->divModifier : '';

$cssClass = join(
    ' ', array_filter(
        [
            (isset($this->errorMessage) ? 'has-error' : null),
            (!empty($this->divModifier) ? $this->divModifier : null),
        ]
    )
);

?>
<div class="form-group <?php echo $this->escapeHtmlAttr($cssClass); ?>">
    <label for="<?php echo $this->escapeHtmlAttr($id); ?>"
           class="form-label">

        <?php if (!empty($label)) :
            echo $this->escapeHtml($label);
        endif; ?>

        <?php if (!empty($help)): ?>
            <span class="form-hint"><?php echo $this->escapeHtml($help); ?></span>
        <?php endif; ?>

        <?php if (!empty($errorMessage)): ?>
            <span class="validation-message"><?php echo $this->escapeHtml($errorMessage); ?></span>
        <?php endif; ?>
    </label>

    <?php echo $this->partial(
        'partial/gds/form/control-text',
        [
            'id'            => $id,
            'name'          => $name,
            'value'         => $value,
            'inputModifier' => $inputModifier,
            'type'          => $type,
            'maxLength'     => isset($maxLength) ? $maxLength : '',
            'tabIndex'      => $tabIndex,
            'autofocus'     => $this->autofocus,
            'pattern'       => $this->pattern,
            'patternErrorMsg' => $this->patternErrorMsg
        ]
    ); ?>
</div>