<?php
$value = $this->value;
$escElmId = $this->escapeHtmlAttr($this->inputName.$value);
?>

<label
    class="block-label"
    for="<?php echo $escElmId; ?>"
    <?php if (!empty($dataTarget)): ?>
        data-target="<?php echo $this->escapeHtmlAttr($dataTarget); ?>"
    <?php endif; ?>
    >
    <input type="checkbox"
           value="<?php echo $this->escapeHtmlAttr($value); ?>"
           name="<?php echo $this->escapeHtmlAttr($inputName); ?>"
           id="<?php echo $escElmId ?>"
        <?php if ($checked === true): ?>
            checked="true"
        <?php endif; ?>
        />
    <?php echo $this->escapeHtml($key); ?>
</label>
