<div class="form-group <?php echo !empty($errorMessage) ? 'has-error' : ''; ?> <?php echo !empty($divModifier) ? $this->escapeHtmlAttr($divModifier) : ''; ?>">
    <fieldset class="<?php echo (!empty($inputModifier) ? $this->escapeHtmlAttr($inputModifier) : ''); ?>">
        <legend class="form-label<?php echo (!empty($labelModifier) ? $this->escapeHtmlAttr($labelModifier) : ''); ?>">
            <?php echo $this->escapeHtml($label); ?>
        </legend>

        <?php foreach ($options as $option): ?>
            <?php echo $this->partial(
                'partial/gds/form/control-radio',
                $option
            ); ?>
        <?php endforeach; ?>
    </fieldset>
</div>
