<?php

$type = (empty($this->type) ? 'text' : $this->type);

$id = $this->id ?: false;
$name=  isset($this->name) ? $this->name : $id;
$tabIdx = (int) $this->tabIndex;
?>

<input
    type="<?php echo $this->escapeHtmlAttr($type); ?>"
    <?php
    echo $id ? ' id="'. $this->escapeHtmlAttr($id) . '"' : '';
    echo $name ? ' name="'. $this->escapeHtmlAttr($name) .'"' : '';
    echo $this->autofocus === true ? ' autofocus' : '';
    echo $tabIdx > 0 ? ' tabindex="'. $this->escapeHtmlAttr($tabIdx) .'"' : '';
    echo !empty($maxLength) ? ' maxlength="'.$this->escapeHtmlAttr($maxLength).'"' : '';
    echo ($type == 'password') ? ' autocomplete="off"' : '';
    ?>
    value="<?php echo $this->escapeHtmlAttr($this->value); ?>"
    class="form-control
        <?php echo !empty($inputModifier) ? 'form-control-' . $this->escapeHtmlAttr($inputModifier) : ''; ?>"
/>
