<?php

use \DvsaCommon\Utility\ArrayUtils;
$errorMessages = $element->getMessages();
$errorMessage = ArrayUtils::lastOrNull($errorMessages);
$params = ["name" => $element->getName(),"label" => $element->getLabel(), "value" => $element->getValue(), "errorMessage" => $errorMessage];
$params = array_merge($params, $element->getAttributes());
if ($element->hasAttribute("group") && $element->getAttribute("group") === true):
    $partial = 'partial/gds/form/control-' . $element->getAttribute('type') . '-group';
else:
    $partial = 'partial/gds/form/control-' . $element->getAttribute('type');
endif;

echo $this->partial(
    $partial,
    $params
);
?>