<div class="form-group <?php echo !empty($errorMessage) ? 'has-error' : ''; ?> <?php echo !empty($divModifier) ? $this->escapeHtmlAttr($divModifier) : ''; ?>">
    <fieldset class="<?php echo !empty($inputModifier) ? $this->escapeHtmlAttr($inputModifier) : ''; ?>">
        <legend class="form-label<?php echo !empty($labelModifier) ? $this->escapeHtmlAttr($labelModifier) : ''; ?>">
            <?php echo $this->escapeHtml($label); ?>
            <?php if (!empty($errorMessage)): ?>
                <span class="validation-message"><?php echo $this->escapeHtml($errorMessage); ?></span>
            <?php endif; ?>
            <?php if (!empty($labelHint)): ?>
                <span class="form-hint"><?php echo $this->escapeHtmlAttr($labelHint); ?></span>
            <?php endif; ?>
        </legend>

        <?php $lastOption = count($options) - 1 ?>

        <?php if (!empty($newStyle) && $newStyle === true): ?>

            <?php foreach ($options as $option): ?>
                <div class="multiple-choice">
                    <input type="radio"
                           value="<?php echo $this->escapeHtmlAttr($option['value']); ?>"
                           name="<?php echo $this->escapeHtmlAttr($option['inputName']); ?>"
                           id="<?php echo $this->escapeHtmlAttr($option['attributes']['id']); ?>"
                        <?php echo ($option['checked'] === true) ? ' checked="checked"' : '' ?>>
                    <label
                        for="<?php echo $this->escapeHtmlAttr($option['attributes']['id']); ?>"
                        <?php if (!empty($dataTarget)): ?>
                            data-target="<?php echo $this->escapeHtmlAttr($dataTarget); ?>"
                        <?php endif; ?>>

                        <?php echo $this->escapeHtml($option['key']); ?>

                    </label>
                </div>
            <?php endforeach; ?>

        <?php else : ?>

            <?php foreach ($options as $k => $option): ?>
                <?php if ($k == $lastOption && isset($splitLastOption) && $splitLastOption): ?>
                    <p class="form-block">or</p>
                <?php endif; ?>
                <?php echo $this->partial(
                    'partial/gds/form/control-radio',
                    $option
                ); ?>
            <?php endforeach; ?>

        <?php endif; ?>
    </fieldset>
</div>
