<?php

$type = (empty($this->type) ? 'text' : $this->type);

$id = $this->id ?: false;
$name=  isset($this->name) ? $this->name : $id;
$tabIdx = (int) $this->tabIndex;

$pattern = !empty($this->pattern) ? $this->pattern : '';
$patternError = !empty($this->patternErrorMsg) ? $this->patternErrorMsg : '';
$autoCompleteOff = !empty($autoCompleteOff) ? $autoCompleteOff : '';
?>

<input
    type="<?php echo $this->escapeHtmlAttr($type); ?>"
    <?php
    echo $id ? ' id="'. $this->escapeHtmlAttr($id) . '"' : '';
    echo $name ? ' name="'. $this->escapeHtmlAttr($name) .'"' : '';
    echo $this->autofocus === true ? ' autofocus' : '';
    echo $tabIdx > 0 ? ' tabindex="'. $this->escapeHtmlAttr($tabIdx) .'"' : '';
    echo !empty($maxLength) ? ' maxlength="'.$this->escapeHtmlAttr($maxLength).'"' : '';
    echo !empty($pattern) ? ' pattern="'. $this->escapeHtmlAttr($pattern).'"' : '';
    echo !empty($pattern) && !empty($patternError) ? 'title="'. $this->escapeHtmlAttr($patternError).'"' : '';
    echo ($type == 'password' || $autoCompleteOff) ? ' autocomplete="off"' : '';
    ?>
    value="<?php echo $this->escapeHtmlAttr($this->value); ?>"
    class="form-control
        <?php echo !empty($inputModifier) ? 'form-control-' . $this->escapeHtmlAttr($inputModifier) : ''; ?>"
/>
