
<select
    id="<?php echo $this->escapeHtmlAttr($this->id); ?>"
    name="<?php echo $this->escapeHtmlAttr($this->name); ?>"
    class="form-control
        <?php echo !empty($inputModifier) ? 'form-control-' . $this->escapeHtmlAttr($inputModifier) : ''; ?>">

    <option value="">
        <?php echo $this->escapeHtml('Please select'); ?>
    </option>

    <?php foreach($options as $key => $value): ?>
        <option value="<?php echo $this->escapeHtmlAttr($key); ?>"
            <?php echo ((string) $key === $this->value ? 'selected' : ''); ?>
            ><?php echo $this->escapeHtml($value); ?>
        </option>
    <?php endforeach; ?>
</select>