<?php
echo $this->partial(
    'partial/gds/form/control-text-group',
    [
        'id'            => $id,
        'errorMessage'  => $errorMessage,
        'label'         => $label,
        'value'         => $value,
        'type'          => $type,
        'name'          => $name,
        'inputModifier' => isset($inputModifier) ? $inputModifier : null,
        'divModifier'   => isset($divModifier) ? $divModifier : null
    ]
);