<?php
$label = $this->withDefault('')->getValue($label);
$day = $this->withDefault('')->getValue($day);
$month = $this->withDefault('')->getValue($month);
$year = $this->withDefault('')->getValue($year);
$required = $this->withDefault(true)->getValue($required);
$optional = $this->withDefault(true)->getValue($optional);
/** @var \DateTime $value */
$value = $this->withDefault(false)->getValue($value);
$help = $this->withDefault(false)->getValue($help);

if (!$value instanceof DateTime) {
    $value = DateTime::createFromFormat('Y-m-d', $value);
}
if ($value instanceof DateTime) {
    $day = $value->format('d');
    $month = $value->format('m');
    $year = $value->format('Y');
}

$cssClass = implode(
    ' ', array_filter(
        [
            (isset($this->errorMessage) ? 'has-error' : null),
            (!empty($this->divModifier) ? $this->divModifier : null),
        ]
    )
);
?>

<div class="form-group <?php echo $this->escapeHtmlAttr($cssClass); ?>">
    <fieldset>
        <legend class="form-label">
            <?php echo $this->escapeHtml($label); ?>
            <?php if ($help): ?>
                <span class="form-hint"><?php echo $this->escapeHtml($help) ?></span>
            <?php endif ?>
            <?php if (!empty($errorMessage)): ?>
                <span class="validation-message"><?php echo $this->escapeHtml($errorMessage); ?></span>
            <?php endif; ?>
        </legend>
        <div class="form-date">

            <?php echo $this->partial(
                'partial/forms/inputBox.phtml',
                [
                    'id' => 'date1-day',
                    'label' => 'Day',
                    'name' => 'dobDay',
                    'classFormGroup' => 'form-group-day',
                    'value' => $day,
                    'required' => $required,
                    'optional' => $optional,
                    'maxLength' => 2,
                ]
            );
            ?>
            <?php echo $this->partial(
                'partial/forms/inputBox.phtml',
                [
                    'id' => 'date1-month',
                    'label' => 'Month',
                    'name' => 'dobMonth',
                    'classFormGroup' => 'form-group-month',
                    'value' => $month,
                    'required' => $required,
                    'optional' => $optional,
                    'maxLength' => 2,
                ]
            );
            ?>
            <?php echo $this->partial(
                'partial/forms/inputBox.phtml',
                [
                    'id' => 'date1-year',
                    'label' => 'Year',
                    'name' => 'dobYear',
                    'classFormGroup' => 'form-group-year',
                    'value' => $year,
                    'required' => $required,
                    'optional' => $optional,
                    'maxLength' => 4,
                ]
            );
            ?>
        </div>
    </fieldset>
</div>
