<?php
use DvsaCommon\UrlBuilder\RegistrationUrlBuilderWeb;

?>
<div class="text">
    <p class="lede">Your address is used to identify you if you contact the help desk.</p>
</div>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $errorsSummary]); ?>


<form action="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->addressStep());?>"
      method="post" autocomplete="off" novalidate="">
    <?php echo $this->csrfToken(); ?>

    <fieldset>
        <legend class="form-title heading-large" id="newUserAddress">Your address</legend>

        <div class="form-group form-group-compound<?php if ($address1HasError) echo ' has-error' ?>">
            <label class="form-label" for="address1">
                Home address
                <?php
                if ($address1HasError) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['address1']]);
                }
                ?>
            </label>
            <input class=" form-control" id="address1" name="address1" type="text" value="<?php echo $this->escapeHtmlAttr($address1) ?>">
        </div>

        <div class="form-group form-group-compound">
            <label class="form-label- visuallyhidden" for="address2">Address line 2</label>
            <input class=" form-control" id="address2" name="address2" type="text" value="<?php echo $this->escapeHtmlAttr($address2) ?>">
        </div>

        <div class="form-group form-group-compound">
            <label class="form-label- visuallyhidden" for="address3">Address line 3</label>
            <input class=" form-control" id="address3" name="address3" type="text"
                   value="<?php echo $this->escapeHtmlAttr($address3) ?>">
        </div>

        <div class="form-group form-group-compound<?php if ($townOrCityHasError) echo ' has-error' ?>">
            <label class="form-label" for="townOrCity">Town or city
                <?php
                if ($townOrCityHasError) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['townOrCity']]);
                }
                ?>
            </label> <input class=" form-control form-control-1-4"
                id="townOrCity" name="townOrCity" type="text" value="<?php echo $this->escapeHtmlAttr($townOrCity) ?>">
        </div>

        <div class="form-group form-group-compound<?php if ($postcodeHasError) echo ' has-error' ?>">
            <label class="form-label" for="postcode">Postcode
                <?php
                if ($postcodeHasError) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $errors['postcode']]);
                }
                ?>
            </label> <input class="form-control form-control-1-8"
                id="postcode" name="postcode" type="text" value="<?php echo $this->escapeHtmlAttr($postcode) ?>">
        </div>
    </fieldset>

    <nav class="content-navigation">
        <input type="submit" value="Continue" id="continue" class="button">

        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->escapeHtmlAttr(RegistrationUrlBuilderWeb::of()->detailsStep());?>"
                   id="back">Back
                </a>
            </li>
        </ul>
    </nav>
</form>