<div class="text">
    <p>The MOT testing service puts small files (known as 'cookies') onto your computer to collect information about how you browse the site.</p>
    <p>Cookies are used to:</p>
    <ul class="list-bullet">
        <li>measure how you use the website so it can be updated and improved based on your needs</li>
        <li>remember the notifications you've seen so that we don't show them to you again</li>
        <li>direct you down certain journeys to improve your experience</li>
    </ul>
    <div role="note" aria-label="Information" class="panel-indent">
        <p>MOT testing service cookies aren’t used to identify you personally.</p>
    </div>
    <p>You’ll normally see a message on the site before we store a cookie on your computer.</p>
    <p>Find out more about <a rel="external" href="http://www.aboutcookies.org/">how to manage cookies.</a></p>
    <h2 class="heading-medium">How cookies are used on MOT testing service</h2>
    <p>There are a number of different types of cookie used in the MOT testing service which allow the system to work securely and consistently. These are:</p>
    <ul class="list-bullet">
        <li>Google Analytics cookies</li>
        <li>MOT testing service application cookies</li>
        <li>third party cookies</li>
        <li>Imperva Incapsula cookies</li>
    </ul>
    <h3 class="heading-small">Google Analytics cookies</h3>
    <p>We use Google Analytics software to collect information about how you use MOT testing service. We do this to help make sure the site is meeting the needs of its users and to help us make improvements, eg
        <a rel="external" href="https://mattersoftesting.blog.gov.uk/improving-how-you-enter-test-results/">improving how you enter test results.</a>
    </p>
    <p>Google Analytics stores information about:</p>
    <ul class="list-bullet">
        <li>the pages you visit on the MOT testing service</li>
        <li>how long you spend on each page</li>
        <li>how you got to the site</li>
        <li>what you click on while you're visiting the site</li>
    </ul>
    <p>Google do not collect or store your personal information (eg your name or address) so this information can't be used to identify who you are. We don't allow Google to use or share our analytics data.</p>
    <p>Google Analytics sets the following cookies:</p>
    <h4 class="heading-small">Universal Analytics</h4>
</div>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Purpose</th>
        <th>Expires</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>_ga</td>
        <td>This helps us count how many people visit MOT testing service by tracking if you've visited before</td>
        <td>2 years</td>
    </tr>
    <tr>
        <td>_gat</td>
        <td>Used to manage the rate at which page view requests are made</td>
        <td>10 minutes</td>
    </tr>
    </tbody>
</table>
<h4 class="heading-small">Google Analytics</h4>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Purpose</th>
        <th>Expires</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>_utma</td>
        <td>Like _ga, this lets us know if you've visited before, so we can count how many of our visitors are new to MOT testing service or to a certain page</td>
        <td>2 years</td>
    </tr>
    <tr>
        <td>_utmb</td>
        <td>This works with _utmc to calculate the average length of time you spend on MOT testing service</td>
        <td>30 minutes</td>
    </tr>
    <tr>
        <td>_utmc</td>
        <td>This works with _utmb to calculate when you close your browser</td>
        <td>when you close your browser</td>
    </tr>
    <tr>
        <td>_utmz</td>
        <td>This tells us how you reached MOT testing service (eg from another website or a search engine)</td>
        <td>6 months</td>
    </tr>
    </tbody>
</table>
<div class="text">
    <p>You can <a rel="external" href="https://tools.google.com/dlpage/gaoptout">opt out of Google Analytics cookies.</a></p>
    <h2 class="heading-medium">MOT testing service application cookies</h2>
    <p>The MOT testing service sets a number of cookies to remember what you have done on the site and what messages you have seen.</p>
    <h3 class="heading-small">Our cookies message</h3>
    <p>You may see a pop-up cookies message when you first visit the MOT testing service. We'll store a cookie so that your computer knows you've seen it and knows not to show it again.</p>
</div>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Purpose</th>
        <th>Expires</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>seen_cookie_message</td>
        <td>Saves a message to let us know that you've seen our cookie message</td>
        <td>1 month</td>
    </tr>
    </tbody>
</table>
<div class="text">
    <h3 class="heading-small">Security cards (two-factor authentication)</h3>
    <p>You may see a message when you log in informing you of changes to our security policy and the introduction of security cards. We use a cookie to indicate that you have seen that message so we do not show it to you again that day. We will also use cookies to remember if you have used security questions to login that day or that you have a security card on order so that we do not ask you for your security card PIN for the rest of the day.</p>
</div>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Purpose</th>
        <th>Expires</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>hasSeenCardInformation</td>
        <td>Set to remember that you have seen the "Changes to security" information message</td>
        <td>Midnight</td>
    </tr>
    <tr>
        <td>_hasLoggedInWithLostForgottenCardJourney</td>
        <td>Set to remember that you have logged in using security questions today</td>
        <td>Midnight</td>
    </tr>
    <tr>
        <td>_hasSeenOrderedCardLandingPage</td>
        <td>Set to remember that you have seen the "Card on order" landing page</td>
        <td>Midnight</td>
    </tr>
    </tbody>
</table>
<div class="text">
    <h3 class="heading-small">Session management and security</h3>
    <p>MOT testing service uses cookies for session management and security. No personal identification data will be stored in any browsers. Once the browser is closed those cookies will be removed.</p>
</div>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Purpose</th>
        <th>Expires</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>PHPSESSID</td>
        <td>Stores a Session identifier between pages to speed up browsing. It only used as a key to small amounts of non-persistent data such as search criteria.</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>iPlanetDirectoryPro</td>
        <td>Session-Cookie containing the SSO token and Session Key for your visit</td>
        <td>When you close your browser</td>
    </tr>
    </tbody>
</table>
<div class="text">
    <h2 class="heading-medium">Third-party cookies</h2>
    <h3 class="heading-small">Our feedback survey</h3>
    <p>We use <a rel="external" href="http://www.smartsurvey.co.uk/">SmartSurvey</a> to collect responses to the survey. If you take part, SurveyMonkey will save extra cookies to your computer to track your progress through it. For more information, please see <a rel="external" href="https://www.smartsurvey.co.uk/privacy-policy">Smart Survey privacy information.</a></p>
</div>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Purpose</th>
        <th>Expires</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>ASP.Net_SessionId</td>
        <td>ASP.NET uses to store a unique identifier for your session</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>_ga</td>
        <td>This helps us count how many people visit MOT testing service by tracking if you’ve visited before</td>
        <td>2 years</td>
    </tr>
    <tr>
        <td>_gat</td>
        <td>Used to manage the rate at which page view requests are made</td>
        <td>10 minutes</td>
    </tr>
    </tbody>
</table>
<div class="text">
    <h3 class="heading-small">Imperva Incapsula cookies</h3>
    <p>Imperva Incapsula cookies help the Imperva Incapsula service identify malicious activity.</p>
    <p>The cookies collect information in an anonymous form - they don't collect or store any personal information (eg names or addresses) so this information can’t easily be used to identify who the user is.</p>
    <p>The only constant cookie is the Visitor ID (see visid_incap_{ID} below) - the other Imperva Incapsula cookies are removed within 15 minutes or once the browser is closed.</p>
</div>
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Purpose</th>
        <th>Expires</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>incap_ses_{ID}</td>
        <td>Session-Cookie containing an encrypted Session id. Used to relate HTTP requests to a particular visit.</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>nlbi_{ID}</td>
        <td>A network load balancer cookie used by the Incapsula application delivery platform.</td>
        <td>When you close your browser</td>
    </tr>
    <tr>
        <td>visid_incap_{ID}</td>
        <td>Visitor-Cookie containing Visitor id. This cookie is used to relate sessions to a specific visitor's device.</td>
        <td>One Year</td>
    </tr>
    </tbody>
</table>
<div class="text">
    <h3 class="heading-small">Government services</h3>
    <p>Most services we link to are run by different government departments, eg HM Revenue and Customs (HMRC) or the Home Office.</p>
    <p>These services may set additional cookies and, if so, will have their own cookies policy.</p>
</div>