
<h2 class="heading-medium">Inspection checklists</h2>

<ul class="list-bullet">
    <li><a href="https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/212494/Plain_Paper_MOT_Inspection_Checklist_for_Motorcycles__VT_29M_.pdf" rel="external" target="_blank">Motorcycle inspection checklist for class 1 and 2 (VT29M)</a> <span class="text-secondary font-xsmall">(PDF, 653 KB)</span></li>
    <li><a href="https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/212475/Plain_Paper_MOT_Inspection_Checklist__VT_29_.pdf" rel="external" target="_blank">Vehicle inspection checklist for class 3, 4, 5 and 7 (VT29)</a> <span class="text-secondary font-xsmall">(PDF, 645 KB)</span></li>
</ul>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a id="back-to-home-link" href="<?php echo $this->url(\Dashboard\Controller\UserHomeController::ROUTE); ?>">Return to home</a>
        </li>
    </ul>
</nav>
