<?php
// VM-4217: Role based solution done for this sprint. A permissions based solution
// will need to be implemented when Rbca et al. is completely stable and ready.
$isVE = $this->isVE;
?>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>MOT Forms</h1>
        </div>
    </div>

    <?php if (!$isVE): ?>
    <div class="row">
        <div class="col-lg-12">
            <h2>Vehicle checklists</h2>
        </div>
    </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-lg-12">
            <ul>
                <li><a href="https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/212475/Plain_Paper_MOT_Inspection_Checklist__VT_29_.pdf" target="_blank">VT29 Inspection Checklist - class 3, 4, 5 and 7</a></li>
                <li><a href="https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/212494/Plain_Paper_MOT_Inspection_Checklist_for_Motorcycles__VT_29M_.pdf" target="_blank">VT29M Inspection Checklist - class 1 and 2</a></li>
            </ul>
        </div>
    </div>

    <nav class="module-content-navigation">
        <ul class="content-navigation_secondary">
            <li>
                <a href="<?php echo $this->url(\Dashboard\Controller\UserHomeController::ROUTE); ?>">Back to user home</a>
            </li>
        </ul>
    </nav>
</div>

