<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>MOT Forms</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <ul>
                <li><a href="https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/212475/Plain_Paper_MOT_Inspection_Checklist__VT_29_.pdf" target="_blank">VT29 Vehicle inspection checklist - class 3, 4, 5 and 7</a></li>
                <li><a href="https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/212494/Plain_Paper_MOT_Inspection_Checklist_for_Motorcycles__VT_29M_.pdf" target="_blank">VT29M Motorcycle inspection checklist - class 1 and 2</a></li>
            </ul>
        </div>
    </div>

    <nav class="module-content-navigation">
        <ul class="content-navigation_secondary">
            <li>
                <a id="back-to-home-link" href="<?php echo $this->url(\Dashboard\Controller\UserHomeController::ROUTE); ?>">Return to home</a>
            </li>
        </ul>
    </nav>
</div>

