<?php

use Dashboard\Form\ChangePasswordForm as Form;

$this->headScript()->appendFile('/js/dvsa.js');

?>
    <form method="POST">
        <?php
        echo $this->csrfToken();

        if($form->getMessages()): ?>
            <div class="validation-summary" id="validation-summary-id">
                <h2>There was a problem with the information you entered:</h2>
                <ol>
                    <?php foreach($form->getElements() as $element): ?>
                        <?php foreach($element->getMessages() as $message): ?>
                            <li>
                                <?php echo $this->escapeHtml($element->getLabel()); ?> -
                                <?php echo $this->escapeHtml($message); ?>
                            </li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        <?php endif;

        echo $this->partial(
            'partial/gds/general/password-criteria',
            [
                'username' => $username
            ]
        );
        ?>

        <fieldset>
            <?php

            echo $this->partial(
                'partial/gds/form/control',
                [
                    'element' => $form->get(Form::FIELD_OLD_PASSWORD)
                ]
            );

            echo $this->partial(
                'partial/gds/form/control',
                [
                    'element' => $form->get(Form::FIELD_PASSWORD)
                ]
            );

            echo $this->partial(
                'partial/gds/form/control',
                [
                    'element' => $form->get(Form::FIELD_RETYPE_PASSWORD)
                ]
            );
            ?>
        </fieldset>

        <?php echo $this->partial(
            'partial/gds/form/control-navigation',
            [
                'id'    => 'submitPass',
                'value' => 'Reset password',
            ]
        ); ?>
    </form>

    <nav class="content-navigation">
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->url("logout"); ?>">Cancel</a>
            </li>
        </ul>
    </nav>

