<?php

use Dashboard\Form\ChangePasswordForm as Form;

/** @var Form $form */
/** @var string $username */
/** @var string $cancelRoute */
/** @var string $cancelText */
/**
 */

$this->headScript()->appendFile('/js/dvsa.js');

?>
    <form method="POST">
        <?php echo $this->csrfToken(); ?>
        <?php echo $this->partial('zendFormErrorMessages', ['form' => $form ]); ?>

        <fieldset>
            <legend id="" class="form-title heading-large">Current password</legend>

            <input type="password" value="" style="width: 1px; position: absolute; left: -9999px;">
            <?php echo $this->partial(
                'partial/gds/form/control',
                [
                    'element' => $form->getOldPasswordElement(),
                ]
            ); ?>
        </fieldset>
        <fieldset>
            <legend class="form-title heading-large">New password</legend>
            <?php echo $this->partial(
                'partial/gds/general/password-criteria',
                [
                    'username' => $username
                ]
            ); ?>
            <?php  echo $this->partial(
                'partial/gds/form/control',
                [
                    'element' => $form->get(Form::FIELD_PASSWORD)
                ]
            );

            echo $this->partial(
                'partial/gds/form/control',
                [
                    'element' => $form->get(Form::FIELD_RETYPE_PASSWORD)
                ]
            ); ?>
        </fieldset>

        <?php echo $this->partial(
            'partial/gds/form/control-navigation',
            [
                'id'    => 'submitPass',
                'value' => 'Change password',
            ]
        ); ?>
    </form>

    <nav class="content-navigation">
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->url($cancelRoute); ?>" id='cancelLink'><?php echo $cancelText ?></a>
            </li>
        </ul>
    </nav>

