<header class="transaction-header">
    <h1 id="reset-confirmation-title" class="transaction-header__title">You have reset your account security</h1>
    <p class="transaction-header__next-step">Keep your new password and security questions hidden</p>
</header>

<div class="text">
    <h2 class="heading-medium">What happens next?</h2>
    <p>Sign in with your user ID and new password.</p>
    <p>You can reset your password and security questions at any time from your profile.</p>
</div>

<nav class="content-navigation">
    <ul class="content-navigation__secondary">
        <li>
            <a href="<?php echo $this->url('logout'); ?>" id="go-to-sign-in">
                Sign In
            </a>
        </li>
    </ul>
</nav>