<?php

use DvsaCommon\Utility\ArrayUtils;

$this->headScript()->appendFile('/js/dvsa.js'); ?>

<div class="row">
    <div class="col-lg-12">
        <header class="module-content-header">
            <h1>
                <span class="content-header_title">Claim your account</span>
                <span class="content-header_progress">Step 1 of 3</span>
            </h1>
        </header>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <h2>Welcome to your account</h2>
        <p class="lead">
            Before you start using <?php echo $this->escapeHtml($serviceName); ?> you need to complete some security questions.
        </p>
        <p class="lead">
            Make sure no one can read your screen while you answer these questions.
        </p>
    </div>
</div>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $summaryMessages]); ?>

<div class="row">
    <div class="col-md-8">
        <form role="form" novalidate method="post" id="frmMain" autocomplete="off">
            <!--
            TC.
            NB the "novalidate" attribute used to disable client-side browser validation
            on HTML5 inputs as we can't style or control content
            -->
            <?php
            $msgEmail = ArrayUtils::tryGet($messages, 'email', false);
            $msgEmailConfirm = ArrayUtils::tryGet($messages, 'confirm_email', false);
            $msgEmailOptOut = ArrayUtils::tryGet($messages, 'email_opt_out', false);
            ?>
            <fieldset>
                <legend>Your email address</legend>
                <p>
                    Email is only used to help you recover your account if you have problems signing in.<br >
                    We will never send you SPAM.
                </p>
                <div class="form-group<?php if ($msgEmail|| $msgEmailOptOut) echo ' has-error' ?>">
                    <label for="email">Email address
                        <?php
                        if ($msgEmail) {
                            echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $msgEmail]);
                        }
                        ?>
                    </label>
                    <input type="email" class="form-control" name="email" id="email"
                           value="<?php if (isset($email)) echo $this->escapeHtmlAttr($email) ?>" >
                </div>
                <div class="form-group<?php if ($msgEmailConfirm || $msgEmailOptOut) echo ' has-error' ?>">
                    <label for="confirm_email">Confirm email address
                        <?php
                        if ($msgEmailConfirm) {
                            echo $this->partial(
                                'partial/forms/errorMessageInline.phtml', ['messages' => $messages['confirm_email']]
                            );
                        }
                        ?>
                    </label>
                    <input type="email" class="form-control" name="confirm_email" id="confirm_email"
                           value="<?php if (isset($confirm_email)) echo $this->escapeHtmlAttr($confirm_email)?>">
                    <label class="checkbox-inline">
                        <?php
                        if ($msgEmailOptOut) {
                            echo $this->partial(
                                'partial/forms/errorMessageInline.phtml', ['messages' => $msgEmailOptOut]
                            );
                        }
                        ?>
                        <input id="emailOptOut" name="email_opt_out" value="email_opt_out" type="checkbox"
                            <?php if (isset($email_opt_out)) echo 'checked'; ?>>
                        I don't want to supply an email address
                    </label>
                </div>
                <div class="form-group">
                    <div id="emailWarning" class="panel-indent">
                        <strong>You could be without access for up to 5 working days</strong> if you don't supply an
                        email address.<br>
                        If you need to recover your account we will have to send your replacement password in the post.
                    </div>
                </div>
            </fieldset>

            <?php
            $msgPass = ArrayUtils::tryGet($messages, 'password', false);
            $msgPassConf = ArrayUtils::tryGet($messages, 'confirm_password', false);
            ?>
            <fieldset>
                <legend>Your new password</legend>
                <div class="form-group<?php if ($msgPass) echo ' has-error' ?>">
                    <label style="display: block;">
                        Your password is used to sign in to <?php echo $this->escapeHtml($serviceName); ?>.<br />
                    </label>

                    <?php echo $this->partial('partial/gds/general/password-criteria'); ?>

                    <label for="password" style="display: block;">
                        Password
                        <?php
                        if ($msgPass) {
                            echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $msgPass]);
                        }
                        ?>
                    </label>
                    <input type="password" id="password" name="password" class="form-control "
                           value="<?php if (isset($password)) echo $this->escapeHtmlAttr($password)?>"/>
                </div>
                <div class="form-group<?php if ($msgPassConf) echo ' has-error' ?>">
                    <label for="confirm_password">Confirm password
                        <?php
                        if ($msgPassConf) {
                            echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $msgPassConf]);
                        }
                        ?>
                    </label>
                    <input type="password" id="confirm_password" name="confirm_password" class="form-control " title=""
                           value="<?php if (isset($confirm_password)) echo $this->escapeHtmlAttr($confirm_password)?>"/>
                </div>
            </fieldset>

            <?php echo $this->csrfToken(); ?>
            <input type="hidden" name="submitted_step" value="<?php echo $this->escapeHtmlAttr($stepName); ?>" >


                <nav class="module-content-navigation col-sm-12-broken">
                    <?php echo $this->partial('submitElement', ['id'=>'btSubmitForm','label'=>'Continue', 'cssClass'=>'button']); ?>
                </nav>


        </form>
    </div>
</div>


<script type="text/javascript">
    var emailOptOut = new DVSA.toggle({
        trigger: document.querySelector("#emailOptOut"),
        target: document.querySelector('#emailWarning')
    });

    emailOptOut.checkState();
</script>
