<?php
use DvsaCommon\Utility\ArrayUtils;
$this->headScript()->appendFile('/js/dvsa.js');
?>

<header class="content-header">
    <h1>
        <span class="content-header__title">
            Reset your account security
        </span>
    </h1>
</header>

<div class="text">
    <p class="lede">Create a new password and choose new security questions for your account.</p>
    <h2 class="heading-large">Create a new password</h2>
    <p>You need to create a memorable password for your account.</p>
</div>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $summaryMessages]); ?>

<form action="#" method="post" id="frmMain" autocomplete="off" novalidate>
    <!--
    TC.
    NB the "novalidate" attribute used to disable client-side browser validation
    on HTML5 inputs as we can't style or control content
    -->
    <?php
    $msgPass = ArrayUtils::tryGet($messages, 'password', false);
    $msgPassConf = ArrayUtils::tryGet($messages, 'confirm_password', false);
    ?>
    <fieldset>
        <?php echo $this->partial('partial/gds/general/password-criteria'); ?>

        <div class="form-group<?php if ($msgPass !== false) echo ' has-error' ?>">
            <label for="password" class="form-label">
                New password
                <?php
                if ($msgPass !== false) {
                    $msgPass = str_replace('New password – ', '', $msgPass);
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $msgPass]);
                }
                ?>
            </label>
            <input type="password" name="password" id="password" class="form-control"
                   value="<?php if (isset($password)) echo $this->escapeHtmlAttr($password)?>"/>
        </div>

        <div class="form-group<?php if ($msgPassConf !== false) echo ' has-error' ?>">
            <label for="confirm_password" class="form-label">
                Re-type your new password
                <?php
                if ($msgPassConf !== false) {
                    echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $msgPassConf]);
                }
                ?>
            </label>
            <input type="password" name="confirm_password" id="confirm_password" class="form-control"
                   value="<?php if (isset($confirm_password)) echo $this->escapeHtmlAttr($confirm_password)?>"/>
        </div>
    </fieldset>

    <?php echo $this->csrfToken(); ?>
    <input type="hidden" name="submitted_step" value="<?php echo $this->escapeHtmlAttr($stepName); ?>" >

    <nav class="content-navigation">
        <?php echo $this->partial('submitElement', ['id'=>'btSubmitForm','label'=>'Continue', 'cssClass'=>'button']); ?>
    </nav>
</form>


