<?php

use DvsaCommon\Utility\ArrayUtils;

$this->headScript()->appendFile('/js/dvsa.js'); ?>

<div class="row">
    <div class="col-lg-12">
        <header class="module-content-header">
            <h1>
                <span class="content-header_title">Reset your account security</span>
                <span class="content-header_progress">Step 1 of 3</span>
            </h1>
        </header>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <p class="lead">
            Create a new password and choose new security questions for your account.
        </p>
    </div>
</div>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $summaryMessages]); ?>

<div class="row">
    <div class="col-md-8">
        <form role="form" novalidate method="post" id="frmMain" autocomplete="off">
            <!--
            TC.
            NB the "novalidate" attribute used to disable client-side browser validation
            on HTML5 inputs as we can't style or control content
            -->
            <?php
            $msgPass = ArrayUtils::tryGet($messages, 'password', false);
            $msgPassConf = ArrayUtils::tryGet($messages, 'confirm_password', false);
            ?>
            <fieldset>
                <legend>Create a new password</legend>
                <div class="form-group<?php if ($msgPass) echo ' has-error' ?>">
                    <label style="display: block;">
                        You need to create a memorable password for your account.
                    </label>
                    <br />
                    <?php echo $this->partial('partial/gds/general/password-criteria'); ?>

                    <label for="password" style="display: block;">
                        Password
                        <?php
                        if ($msgPass) {
                            echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $msgPass]);
                        }
                        ?>
                    </label>
                    <input type="password" id="password" name="password" class="form-control "
                           value="<?php if (isset($password)) echo $this->escapeHtmlAttr($password)?>"/>
                </div>
                <div class="form-group<?php if ($msgPassConf) echo ' has-error' ?>">
                    <label for="confirm_password">Confirm password
                        <?php
                        if ($msgPassConf) {
                            echo $this->partial('partial/forms/errorMessageInline.phtml', ['messages' => $msgPassConf]);
                        }
                        ?>
                    </label>
                    <input type="password" id="confirm_password" name="confirm_password" class="form-control " title=""
                           value="<?php if (isset($confirm_password)) echo $this->escapeHtmlAttr($confirm_password)?>"/>
                </div>
            </fieldset>

            <?php echo $this->csrfToken(); ?>
            <input type="hidden" name="submitted_step" value="<?php echo $this->escapeHtmlAttr($stepName); ?>" >


                <nav class="module-content-navigation col-sm-12-broken">
                    <?php echo $this->partial('submitElement', ['id'=>'btSubmitForm','label'=>'Continue', 'cssClass'=>'button']); ?>
                </nav>

        </form>
    </div>
</div>


