<?php
/**
 * @var string $helpdeskName
 */
$helpdeskName = (isset($this->helpdeskCfg['name']) ? $this->helpdeskCfg['name'] : null);
?>
<style>

.banner--confirmation {
    background: #28a197;
    color: #FFFFFF;
    text-align: center;
    padding: 15px;
    margin-top: 0; 
    margin-bottom: 30px;
    
}

.banner__heading {
    font-weight: bold;
    font-size: 24px;
    margin-bottom: 0;
}

.banner__heading-large {
    font-size: 36px;
    font-weight: bold;
    display: block;
}


</style>
<div class="row">
    <div class="col-lg-12">
        <header class="module-content-header">
            <h1>
                <span class="content-header_title">Claim account confirmation</span>
            </h1>
        </header>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="text">
            <p class="lead">Your <?php echo $this->escapeHtml($serviceName); ?> account has been claimed.</p>
            
            <div class="banner--confirmation">
                <span class="banner__heading">
                    Your <?php echo $this->escapeHtml($serviceName); ?> PIN is
                </span>
                <span class="banner__heading-large" id="claim-account-pin"><?php echo $this->escapeHtml($pin); ?></span>
            </div>

            <h4>What happens next?</h4>
            <p>When you sign in again you should use the details you have just provided.</p>
            <p><strong>Memorise your PIN</strong>, you will need it to perform key actions like performing an MOT test.</p>
            <p>You can reset this at any time in the 'Your account' page.</p>
        </div>

    </div>
</div>
<div class="row">
    <nav class="module-content-navigation col-sm-12">
        <a href="<?php echo $this->url('user-home'); ?>" class="button" id="go-to-home">
            Continue to the <?php echo $this->escapeHtml($serviceName); ?>
        </a>
    </nav>
</div>
