<?php
/**
 * @var string $helpdeskName
 */
$helpdeskName = (isset($this->helpdeskCfg['name']) ? $this->helpdeskCfg['name'] : null);
?>

<form role="form" novalidate method="post">
    <div class="row">
        <div class="col-lg-12">
            <header class="module-content-header">
                <h1>
                    <span class="content-header_type">Sign in</span>
                    <span class="content-header_title">Claim account</span>
                    <span class="content-header_progress">Step 3 of 3</span>
                </h1>
            </header>
        </div>
    </div>

    <?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $messages]); ?>

    <?php if ($this->isStepOneInvalid) : ?>
        <a href="<?php echo $this->url('account/claim/confirmEmailAndPassword'); ?>">Correct invalid entry on step 1</a>
    <?php endif; ?>

    <br>

    <?php if ($this->isStepTwoInvalid) :?>
        <a href="<?php echo $this->url('account/claim/setSecurityQuestion'); ?>">Correct invalid entry on step 2</a>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-8">
            <h3>Your 6 digit PIN</h3>

            <p class="lead" id="lead-paragraph">
                Your PIN will be used to confirm your identity once you are signed into
                the <?php echo $this->escapeHtml($serviceName); ?>
                and when calling the <?php echo $this->escapeHtml($helpdeskName); ?>.</p>

            <?php if ($is_tester) : ?>
                <p id="tester-paragraph">Your PIN replaces your smart card and will be required during MOT testing.</p>
            <?php endif; ?>

            <p id="worn-paragraph">Don't tell anyone your PIN.</p>

            <p class="module-second-auth">
                <img class="second-auth__logo" src="/img/mot-2.svg"
                     onerror="this.src='/img/mot-2.png'; this.onerror=null;" width="55" height="52"/>
                Your <?php echo $this->escapeHtml($serviceName); ?> PIN:
                <strong class="second-auth__pin" id="claim-account-pin"><?php echo $this->escapeHtml($pin); ?></strong>
            </p>

        </div>
    </div>
    <div class="row">
        <nav class="module-content-navigation col-sm-12">
            <?php echo $this->csrfToken(); ?>
            <input type="hidden" name="submitted_step" value="<?php echo $this->escapeHtmlAttr($stepName); ?>">
            <?php echo $this->partial(
                'submitElement',
                ['id' => 'btSubmitForm', 'label' => 'Save and continue', 'cssClass' => 'button']
            ); ?>
            <ul class="content-navigation_secondary">
                <li>
                    <a href="<?php echo $this->url('account/claim/setSecurityQuestion'); ?>" id="go-to-previous-page" >Back</a>
                </li>
            </ul>
        </nav>
    </div>
</form>