<?php
use Account\ViewModel\ReviewViewModel;

/**
 * @var string $helpdeskName
 */
$helpdeskName = (isset($this->helpdeskCfg['name']) ? $this->helpdeskCfg['name'] : null);

/** @var $reviewViewModel ReviewViewModel */
?>

<form role="form" novalidate method="post">
    <div class="row">
        <div class="col-lg-12">
            <header class="module-content-header">
                <h1>
                    <span class="content-header_type">Claim your account</span>
                    <span class="content-header_title">Review account details</span>
                    <span class="content-header_progress">Step 3 of 3</span>
                </h1>
            </header>
        </div>
    </div>

    <?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $messages]); ?>

    <?php if ($this->isStepOneInvalid) : ?>
        <a href="<?php echo $this->url('account/claim/confirmEmailAndPassword'); ?>">Correct invalid entry on step 1</a>
    <?php endif; ?>

    <br>

    <?php if ($this->isStepTwoInvalid) :?>
        <a href="<?php echo $this->url('account/claim/setSecurityQuestion'); ?>">Correct invalid entry on step 2</a>
    <?php endif; ?>
    <style>
        table {
            width: 100%;
        }

        table tr {
            border-bottom: 1px solid #bfc1c3;
        }
        table tr:first-child {
            border-top: 1px solid #bfc1c3;
        }
        table td {
            padding: 15px 15px 15px 0; 
            font-size: 19px;
            width: 50%;
        }
        .text-obscured {
            font-size: 1.5em;
            line-height: .75em;
        }
    </style>
    <div class="row">
        <div class="col-md-8">
            <p class="lead">
                Check the details you have provided before you claim your account.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2>Summary details</h2>
            <table>
                <tr>
                    <td>Email address</td>
                    <td><?php echo $this->escapeHtml($reviewViewModel->getEmail()); ?></td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td><strong class="text-obscured"><?php echo $reviewViewModel->getHiddenPassword(); ?></strong></td>
                </tr>
                <tr>
                    <td><?php echo $reviewViewModel->getSecurityQuestionGroupAText(); ?></td>
                    <td><strong class="text-obscured"><?php echo $reviewViewModel->getHiddenAnswerA(); ?></strong></td>
                </tr>
                <tr>
                    <td><?php echo $reviewViewModel->getSecurityQuestionGroupBText(); ?></td>
                    <td><strong class="text-obscured"><?php echo $reviewViewModel->getHiddenAnswerB(); ?></strong></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="row">
        <nav class="module-content-navigation col-sm-12">
            <?php echo $this->csrfToken(); ?>
            <input type="hidden" name="submitted_step" value="<?php echo $this->escapeHtmlAttr($stepName); ?>">
            <?php echo $this->partial(
                'submitElement',
                ['id' => 'btSubmitForm', 'label' => 'Claim your account', 'cssClass' => 'button']
            ); ?>
            <ul class="content-navigation_secondary">
                <li>
                    <a href="<?php echo $this->url('account/claim/setSecurityQuestion'); ?>" id="go-to-previous-page" >Back</a>
                </li>
            </ul>
        </nav>
    </div>
</form>