<header class="content-header">
    <h1>
        <span class="content-header__type">
            Reset your account security
        </span>

        <span class="content-header__title">
            Review your new account security
        </span>
    </h1>
</header>

<div class="text">
    <p class="lede">Check the information you have given before you reset your password and security questions.</p>
</div>

<h2 class="heading-medium">Your account security</h2>

<table class="key-value-list">
    <caption class="visuallyhidden">Summary of your details</caption>
    <tbody>
    <tr>
        <th scope="col" class="key-value-list__key">
            Password
        </th>
        <td class="key-value-list__value">
            <span class="masked-text"><?php echo $reviewViewModel->getHiddenPassword(); ?></span>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            First security question
        </th>
        <td class="key-value-list__value">
            <?php echo $reviewViewModel->getSecurityQuestionGroupAText(); ?><br>
            <span class="font-small"><?php echo $this->escapeHtmlAttr($reviewViewModel->getAnswerA()); ?></span>
        </td>
    </tr>
    <tr>
        <th scope="col" class="key-value-list__key">
            Second security question
        </th>
        <td class="key-value-list__value">
            <?php echo $reviewViewModel->getSecurityQuestionGroupBText(); ?><br>
            <span class="font-small"><?php echo $this->escapeHtmlAttr($reviewViewModel->getAnswerB()); ?></span>
        </td>
    </tr>
    </tbody>
</table>

<form action="#" method="post">
    <nav class="content-navigation">
        <?php echo $this->csrfToken(); ?>
        <input type="hidden" name="submitted_step" value="<?php echo $this->escapeHtmlAttr($stepName); ?>">
        <?php echo $this->partial(
            'submitElement',
            ['id' => 'btSubmitForm', 'label' => 'Reset your account security', 'cssClass' => 'button']
        ); ?>
        <ul class="content-navigation__secondary">
            <li>
                <a href="<?php echo $this->url('account/claim/setSecurityQuestion'); ?>"
                   id="go-to-previous-page" >Back</a>
            </li>
        </ul>
    </nav>
</form>