<?php
/**
 * @var string $helpdeskName
 */
$helpdeskName = (isset($this->helpdeskCfg['name']) ? $this->helpdeskCfg['name'] : null);
?>

<div class="row">
    <div class="col-lg-12">
        <header class="module-content-header">
            <h1>
                <span class="content-header_type">Claim your account</span>
                <span class="content-header_title">Security questions</span>
                <span class="content-header_progress">Step 2 of 3</span>
            </h1>
        </header>
    </div>
</div>

<?php echo $this->partial('partial/forms/errorMessagePageHeader.phtml',['messages' => $messages]); ?>

<div class="row">
    <div class="col-md-8">
        <p class="font-core19z lead">Your security questions will be used to recover your account if you forget
            your password and when calling the <?php echo $this->escapeHtml($helpdeskName);?>.</p>

        <p>Please complete this section carefully as you'll be asked to remember the answers exactly as answered.</p>
        <form role="form" novalidate method="post" autocomplete="off">
            <fieldset>
                <legend>Security question one</legend>
                <div class="form-group<?php if (array_key_exists('question_a',$messages)) echo ' has-error' ?>">
                    <label for="question_a">Choose a question
                        <?php if (array_key_exists('question_a',$messages)) : ?>
                            <?php echo $this->partial('partial/forms/errorMessageInline.phtml',['messages' => $messages['question_a']]) ?>
                        <?php endif ?>
                    </label>
                    <select name="question_a" class="form-control form-control-xl" id="question_a">
                        <option value="">Please select</option>
                        <?php
                        foreach ($this->questions['groupA'] as $value => $question):
                            $selected = (isset($question_a) && $question_a == $value) ? 'selected' : '';
                            ?>
                            <option value="<?php echo $this->escapeHtmlAttr($value); ?>"
                                <?php echo $this->escapeHtml($selected); ?>
                                ><?php echo $this->escapeHtml($question); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group<?php if (array_key_exists('answer_a',$messages)) echo ' has-error' ?>">
                    <label for="answer_a">Memorable answer
                        <?php if (array_key_exists('answer_a',$messages)) : ?>
                            <?php echo $this->partial('partial/forms/errorMessageInline.phtml',['messages' => $messages['answer_a']]) ?>
                        <?php endif ?>
                    </label>
                    <input type="text" class="form-control form-control-sm" name="answer_a" id="answer_a" value="<?php if (isset($answer_a)) echo $this->escapeHtmlAttr($answer_a) ; ?>" autocomplete="off">
                </div>
            </fieldset>
            <fieldset>
                <legend>Security question two</legend>
                <div class="form-group<?php if (array_key_exists('question_b',$messages)) echo ' has-error' ?>">
                    <label for="question_b">Choose a question
                        <?php if (array_key_exists('question_b',$messages)) : ?>
                            <?php echo $this->partial('partial/forms/errorMessageInline.phtml',['messages' => $messages['question_b']]) ?>
                        <?php endif ?>
                    </label>
                    <select name="question_b" class="form-control form-control-xl" id="question_b">
                        <option value="">Please select</option>
                        <?php
                        foreach ($this->questions['groupB'] as $value => $question):
                            $selected = isset($question_b) && $question_b == $value ? 'selected' : '';
                            ?>
                            <option value="<?php echo $this->escapeHtmlAttr($value); ?>" <?php echo $this->escapeHtml($selected); ?>><?php echo $this->escapeHtml($question); ?></option>
                        <?php
                        endforeach;
                        ?>
                    </select>
                </div>
                <div class="form-group<?php if (array_key_exists('answer_b',$messages)) echo ' has-error' ?>">
                    <label for="answer_b">Memorable answer
                        <?php if (array_key_exists('answer_b',$messages)) : ?>
                            <?php echo $this->partial('partial/forms/errorMessageInline.phtml',['messages' => $messages['answer_b']]) ?>
                        <?php endif ?>
                    </label>
                    <input type="text" class="form-control form-control-sm" name="answer_b" id="answer_b" value="<?php if (isset($answer_b)) echo $this->escapeHtmlAttr($answer_b) ; ?>" >
                </div>
            </fieldset>


            <nav class="module-content-navigation col-sm-12-broken">
                <?php echo $this->partial('submitElement', ['id'=>'btSubmitForm','label'=>'Continue', 'cssClass'=>'button']); ?>
                <ul class="content-navigation_secondary">
                    <li>
                        <a href="<?php echo $this->url('account/claim/confirmEmailAndPassword'); ?>" id="go-to-previous-page" >Back</a>
                    </li>
                </ul>
            </nav>

            <?php echo $this->csrfToken(); ?>
            <input type="hidden" name="submitted_step" value="<?php echo $this->escapeHtmlAttr($stepName); ?>" >
        </form>
    </div>
</div>




