<?php

use DvsaClient\ViewModel\EmailFormModel;
use DvsaCommon\Enum\SiteContactTypeCode;

/**
 * @var \Zend\Mvc\Controller\Plugin\FlashMessenger    $flashMessenger
 * @var \Site\Form\VtsContactDetailsUpdateForm        $form
 * @var string                                        $cancelUrl
 * @var \DvsaCommon\Dto\Site\VehicleTestingStationDto $dto
 */

$this->inlineScript()->prependFile('/js/common/email-utils.js');

$flashMessenger = $this->layout()->flashMessenger;

echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getErrorMessages(), 'type' => 'success']
);
echo $this->partial(
    'partial/gds/general/system-message',
    ['messages' => $flashMessenger->getSuccessMessages(), 'type' => 'failure']
);

$dto = $form->getDto();
$busContact = $dto->getContactByType(SiteContactTypeCode::BUSINESS);
?>

<form method="POST">
    <?php echo $this->csrfToken() ?>

    <?php if($busContact): ?>
        <fieldset>
            <p class="lede">
                <?php echo $this->escapeHtml($busContact->getAddress()->getFullAddressString()) ?><br/>
            </p>
        <fieldset>
    <?php endif; ?>

    <fieldset>
        <?php echo $this->partial('partial/gds/form/control-legend', ['id' => 'legendEmail', 'text' => 'Email']); ?>
        <p id="textWarning">The email address should be one you have easy and regular access to and will be used to send you important
            messages that will be required outside of the MOT Testing Service application - for example, username and
            password reminders.<br>
            <strong>You could be without access for up to 5 working days</strong> if you don't supply an email address.
        </p>

        <?php
        $emailFieldName = $form->getBusEmail()->getFieldName(EmailFormModel::$FIELD_EMAIL);
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => $emailFieldName,
                'errorMessage'  => $form->getError($emailFieldName),
                'inputModifier' => '1-3',
                'label'         => 'Email address',
                'value'         => $form->getBusEmail()->getEmail(),
            ]
        );

        $emailConfFieldName = $form->getBusEmail()->getFieldName(EmailFormModel::$FIELD_EMAIL_CONFIRM);
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => $emailConfFieldName,
                'errorMessage'  => $form->getError($emailConfFieldName),
                'inputModifier' => '1-3',
                'label'         => 'Confirm email address',
                'value'         => $form->getBusEmail()->getEmailConfirm(),
            ]
        );

        $isSupplyEmailFieldName = $form->getBusEmail()->getFieldName(EmailFormModel::$FIELD_IS_SUPPLY);
        echo $this->partial(
            'partial/gds/form/control-checkbox-group',
            [
                'label'         => '',
                'options'       => [
                    [
                        'value'         => '1',
                        'inputName'     => $isSupplyEmailFieldName,
                        'key'           => 'I don\'t want to supply an email address',
                        'checked'       => !$form->getBusEmail()->isSupply(),
                    ],
                ],
            ]
        );
        ?>
    </fieldset>

    <fieldset>
        <?php
        echo $this->partial('partial/gds/form/control-legend', ['id' => 'legendTelephone', 'text' => 'Telephone']);
        echo $this->partial(
            'partial/gds/form/control-text-group',
            [
                'id'            => SiteContactTypeCode::BUSINESS. 'PhoneNumber',
                'errorMessage'  => $form->getError(SiteContactTypeCode::BUSINESS. 'PhoneNumber'),
                'inputModifier' => '1-4',
                'label'         => 'Telephone number',
                'value'         => $form->getBusPhone()->getNumber(),
            ]
        );
        ?>
    </fieldset>

    <?php echo $this->partial(
        'partial/gds/form/control-navigation',
        [
            'id'            => 'submitAeEdit',
            'value'         => 'Save contact details',
            'navigation'    => [
                'Cancel and return to Site Details' => $this->cancelUrl,
            ]
        ]
    ); ?>
</form>

<?php $this->inlineScript()->captureStart(); ?>
    $(function() {
        var $eIsEmailSupply = $('input[name="<?php echo $this->escapeJs($isSupplyEmailFieldName); ?>"]'),
            $eCorrEmail = $('#<?php echo $this->escapeJs($emailFieldName); ?>'),
            $eCorrEmailConf = $('#<?php echo $this->escapeJs($emailConfFieldName); ?>');

        EmailUtils.cleanIfNotSupply($eCorrEmail, $eCorrEmailConf, $eIsEmailSupply);
    });
<?php $this->inlineScript()->captureEnd(); ?>
