<?php
/**
 * @var \Site\Form\VehicleTestingStationForm $form
 * @var array                     $vtsData
 * @var string                    $formAction
 * @var string                    $cancelUrl
 */
?>

<?php if ($vtsData): ?>
    <h1>
        <small>
            <span id="site-name-heading"><?php echo $this->escapeHtml($vtsData['name']); ?></span> -
            <span id="site-number-heading"><?php echo $this->escapeHtml($vtsData['siteNumber']); ?></span>
        </small>
        Edit vehicle testing station
    </h1>
<?php else: ?>
    <h1>Create vehicle testing station</h1>
<?php endif ?>

<?php echo $this->partial('errorMessages', ['getFromFlash' => true]); ?>

<form action="<?php echo $formAction ?>" method="post">
    <?php echo $this->csrfToken() ?>

    <fieldset>
        <?php
        echo $this->partial(
            'partial/forms/inputBox.phtml',
            [
                'id'        => 'name',
                'name'      => 'name',
                'label'     => 'VTS name',
                'title'     => 'Enter the name of the vehicle testing station',
                'maxLength' => 255,
                'value'     => $form->getName(),
            ]
        );
        ?>
    </fieldset>
    <fieldset>
        <legend>Business contact details</legend>
        <?php if ($form->canEditBusinessContact()): ?>
            <?php
            echo $this->partial(
                'partial/fragments/address-and-contact-details',
                [
                    'values'  => $form->toArray(),
                    'showFax' => true
                ],
                'Core'
            );
            ?>
        <?php else: ?>
            <dl class="vertical col-sm-12">
                <dt><?php echo $this->translate('Address'); ?></dt>
                <dd><?php echo $this->escapeHtml($form->getAddressLine1()); ?></dd>
                <dd><?php echo $this->escapeHtml($form->getAddressLine2()); ?></dd>
                <dd><?php echo $this->escapeHtml($form->getAddressLine3()); ?></dd>

                <dt><?php echo $this->translate('City or Town'); ?></dt>
                <dd><?php echo $this->escapeHtml($form->getTown()); ?></dd>

                <dt><?php echo $this->translate('Postcode'); ?></dt>
                <dd><?php echo $this->escapeHtml($form->getPostcode()); ?></dd>

                <dt><?php echo $this->translate('Email address'); ?></dt>
                <dd><?php echo $this->escapeHtml($form->getEmail()); ?></dd>

                <dt><?php echo $this->translate('Telephone number'); ?></dt>
                <dd><?php echo $this->escapeHtml($form->getPhoneNumber()); ?></dd>

                <dt><?php echo $this->translate('Fax number'); ?></dt>
                <dd><?php echo $this->escapeHtml($form->getFaxNumber()); ?></dd>
            </dl>
        <?php endif ?>
    </fieldset>


    <fieldset>
        <legend>Correspondence contact details</legend>
        <?php if ($form->canEditCorrespondenceContact()): ?>
            <?php
            echo $this->partial(
                'partial/forms/checkbox-box',
                [
                    'id'        => 'correspondenceContactSame',
                    'label'     => 'Same as business contact details',
                    'value'     => 1,
                    'isChecked' => $form->getCorrespondenceContactSame(),
                ],
                'Core'
            );
            ?>
            <div id="addressAndContactDetailsFragmentDiv">
                <?php
                echo $this->partial(
                    'partial/fragments/address-and-contact-details',
                    [
                        'values'   => $form->toArray(),
                        'idPrefix' => 'correspondence',
                        'showFax'  => true
                    ],
                    'Core'
                ); ?>
            </div>
        <?php else: ?>
            <?php if ($form->getCorrespondenceContactSame()): ?>
                Same as business contact details
            <?php else: ?>
                <dl class="vertical col-sm-12">
                    <dt><?php echo $this->translate('Address'); ?></dt>
                    <dd><?php echo $this->escapeHtml($form->getCorrespondenceAddressLine1()); ?></dd>
                    <dd><?php echo $this->escapeHtml($form->getCorrespondenceAddressLine2()); ?></dd>
                    <dd><?php echo $this->escapeHtml($form->getCorrespondenceAddressLine3()); ?></dd>

                    <dt><?php echo $this->translate('City or Town'); ?></dt>
                    <dd><?php echo $this->escapeHtml($form->getCorrespondenceTown()); ?></dd>

                    <dt><?php echo $this->translate('Postcode'); ?></dt>
                    <dd><?php echo $this->escapeHtml($form->getCorrespondencePostcode()); ?></dd>

                    <dt><?php echo $this->translate('Email address'); ?></dt>
                    <dd><?php echo $this->escapeHtml($form->getCorrespondenceEmail()); ?></dd>

                    <dt><?php echo $this->translate('Telephone number'); ?></dt>
                    <dd><?php echo $this->escapeHtml($form->getCorrespondencePhoneNumber()); ?></dd>

                    <dt><?php echo $this->translate('Fax number'); ?></dt>
                    <dd><?php echo $this->escapeHtml($form->getCorrespondenceFaxNumber()); ?></dd>
                </dl>
            <?php endif ?>

        <?php endif ?>
    </fieldset>
    <div class="form-group">
        <?php
        echo $this->partial(
            'partial/forms/submitElement',
            [
                'label' => 'Save',
                'value' => 'save',
                'id'    => 'save'
            ],
            'Core'
        ); ?>
    </div>

    <a id="cancel-link" href="<?php echo $cancelUrl ?>" class="btn btn-link">Cancel</a>

</form>

<script type="text/javascript">
    function render() {
        if ($("#correspondenceContactSame").is(":checked")) {
            var $addressAndContactDetailsFragmentDiv = $("#addressAndContactDetailsFragmentDiv");

            $("input[type='text'], input[type='email']", $addressAndContactDetailsFragmentDiv).each(function () {
                $(this).val("");
                $(this).removeAttr('required');
            });

            $addressAndContactDetailsFragmentDiv.slideUp();
        } else {
            $("#addressAndContactDetailsFragmentDiv").slideDown();

            $("#correspondenceAddressLine1").prop('required', true);
            $("#correspondenceTown").prop('required', true);
            $("#correspondencePostcode").prop('required', true);
            $("#correspondenceEmail").prop('required', true);
            $("#correspondenceEmailConfirmation").prop('required', true);
            $("#correspondencePhoneNumber").prop('required', true);
        }
    }

    $(document).ready(render);
    $("#correspondenceContactSame").change(render);
</script>
